### ISSUE TITLE
E-commerce : refreshing index structure don't change varchar to longtext for instance

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5250] opened 2019-11-13 16:18 UTC
Using `php bin/console ecommerce:indexservice:bootstrap --create-or-update-index-structure`,

if i had in ecommerce.yml `description: varchar(255)` previously and changing it to `description: longtext`, and after run again update index structure, on the `ecommerceframework_productindex`, the field `description` stay as `varchar`.
It should be updated to `longtext`.

Actually we had to uncomment it in the ecommerce.yml, update structure, and after add it with new type and update structure.

Thanks.

**Comment by markus-moser** [comment] 2019-11-20 22:07
duplicate of #2886 - would be really nice if we could fix this

**Closed** 2019-11-25 12:58 UTC
