### ISSUE TITLE
[Bug] Icon Library Problems

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#17395] opened 2024-07-24 13:40 UTC
### Pimcore version

2024.2

### Steps to reproduce

open icon library 

### Actual Behavior

- [ ] JS errors when opening
![image](https://github.com/user-attachments/assets/d4d8bf84-42d5-4528-b8fa-015c3f15be98)

- [ ] click on icons with green border has no effect
![image](https://github.com/user-attachments/assets/a0796410-3a74-4082-9809-77896c8be770)

- [ ] click on icon does not copy path to clipboard

### Expected Behavior

no errors...

**Comment by kingjia90** [comment] 2024-07-25 07:17
Update: Hiding this misleading comment, in the demo it worked because another bundle added jquery to csp allowed list


mhh, weird, all the listed problems are originated by `jQuery` being somehow blocked by `buttons.github.io/buttons.js`. 

So it is only broken on `debug` mode as per
https://github.com/pimcore/admin-ui-classic-bundle/blob/fa2d03aaeb4787e1813f71f6a7ec58b28cd820cb/templates/admin/login/layout.html.twig#L45-L50

On demo seems working fine
![image](https://github.com/user-attachments/assets/1493a559-e238-4be4-975f-8fd4a3d6f28e)
(by opening `icon library` when editing a data object class) and even locally on `dev` mode

**Comment by kingjia90** [comment] 2024-07-25 07:33
But the mentioned github button is appearing only on login page, not sure how it can be reproduced, looks like it is logging out/expiring session somehow on some icon and it's in-lining the login page content instead of the image or things like that.

I see a `i am content script` in the console log, is it part of some front end tests?

**Comment by fashxp** [comment] 2024-07-25 11:38
Hmm problem appreared in fresh installation of skeleton in prod env

**Comment by podarcis** [comment] 2024-07-26 07:01
The error output regarding GitHub buttons JavaScript is misleading - it's just the CSP header's value.

I think the reason for this error is that the `icon-list` template includes the jQuery lib from external source, but the URL is not listed in CSP allow list:

```html
<script
    src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
    crossorigin="anonymous"></script>
```

https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.5.1/templates/admin/misc/icon_list.html.twig#L127

```php
        self::SCRIPT_OPT => [
            'https://buttons.github.io/buttons.js', // GitHub star button on login page
        ],
```
https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.5.1/src/Security/ContentSecurityPolicyHandler.php#L57

So a quick fix could be to include the jQuery CDN as well in the CSP.

**Comment by kingjia90** [comment] 2024-11-15 11:03
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/749

Thank you @podarcis for suggesting the right fix

**Closed as completed by kingjia90** 2024-11-15 11:03 UTC
Labels: Bug, Pimcore:Priority
