### ISSUE TITLE
Invalid Composer Autoload Classmap breaks Updater

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1972] opened 2017-09-14 15:27 UTC
using the command- or web-updater:

- update to a build
- [invalidateComposerAutoloadClassmap](https://github.com/pimcore/pimcore/blob/e81ebbd29bb5f258f5776229a9bb32407958030f/pimcore/lib/Pimcore/Update.php#L481) removes all pimcore namespaces
- [bootstrap.php](https://github.com/pimcore/pimcore/blob/1c4518fa13a6254b060881fd72cd164f84c6c077/pimcore/config/bootstrap.php#L18) requires the `Pimcore` Namespace
- fatal error: `Uncaught Error: Class 'Pimcore' not found in /var/www/public/vendor/pimcore/pimcore/pimcore/config/bootstrap.php:18 `

**Comment by dpfaffenbauer** [comment] 2017-09-14 15:29
Ha, just had the same issue, just replaced the pimcore folder with the one from github, there aren't any migrations since build 100 anyway.

But that's not a proper solution

**Comment by solverat** [comment] 2017-09-14 15:41
adding 
`require_once PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/pimcore/lib/Pimcore.php';` to the bootstrap.php worked for me

**Comment by brusch** [comment] 2017-09-14 15:43
@solverat that was a timing, just 20secs apart ;)

**Comment by solverat** [comment] 2017-09-14 15:44
@brusch! Ha! :) perfekt - thanks!

**Comment by brusch** [comment] 2017-09-14 15:49
The issue is caused by our Composer autoloading config, because we're using `Pimcore\\` instead of `Pimcore` (with out the trailing `\\`) which is the recommended way (less error prone). Using `Pimcore` in the config would fix it, but since we're just talking about 1 single class which is essentially anyway for Pimcore to work properly, I guess including it directly instead of using the autoloader is much better in this case.

**Comment by brusch** [comment] 2017-09-14 15:52
7e22b412c3e490bca9d3a3f34d6488be7dc76945 - missed to reference the issue number for that one.

**Comment by solverat** [comment] 2017-09-14 15:54
ah true. we already removed this namespace in our composer.json - sorry, forgot to tell.

**Comment by fashxp** [comment] 2017-09-14 18:04
hmm, now our tests are failing

**Comment by brusch** [comment] 2017-09-15 07:21
Fixed already :) 
I think it's better to keep the composer autoloader config, it's making things easier for tools around Pimcore, eg. tests, et cetera.

**Comment by fashxp** [comment] 2017-09-15 08:41
just updated a pimcore to latest build ... still broken

**Comment by fashxp** [comment] 2017-09-15 09:01
only appeared when system was already at build 117. should be fixed now.

**Comment by brusch** [comment] 2017-09-15 09:02
updated `boostrap.php` is now also distributed with updates to build 117 & 118.

**Closed by fashxp** 2017-09-15 09:02 UTC
Labels: Bug
