### ISSUE TITLE
Calculated fields - Missing table column when used in bricks

### ISSUE THREAD

**Issue by dkorbginski** [pimcore/pimcore#727] opened 2016-07-06 18:27 UTC
When adding a calculated field to a brick, the according table column will be added to the "object_brick_query_Mybrick_2" tables, but not to the "object_brick_store_Mybrick_2" table, which leads to an "unknown column" error when saving an object with this brick attached.

Using Version: 4.1.3, Build: 3858

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mycalculatedfield' in 'field list'' in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace:
#0 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT o_id AS ...', 134830)
#4 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Zend_Db_Adapter_Pdo_Abstract- in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235`

**Comment by weisswurstkanone** [comment] 2016-07-08 10:38
Unable to reproduce this error. Concerning the tables. It is intentional that there is no column in the store table as this datatype computes its value on the value on the fly. The query table is solely used for filtering purposes in the object grid. Otherwise this wouldn't be possible.

**Comment by dkorbginski** [comment] 2016-07-19 11:06
After some more reasearch i found that this problem only occures when the class containing the brick has inheritance enabled. I'll attach the callstack here: [brick error callstack.txt](https://github.com/pimcore/pimcore/files/371273/brick.error.callstack.txt)
If it is of any help, i could also provide a pimcore backup of a demo setup where this error occures.

**Comment by weisswurstkanone** [comment] 2016-07-19 12:20
thx. fixed in build 3902

**Closed by weisswurstkanone** 2016-07-19 12:20 UTC
Labels: Bug
