### ISSUE TITLE
[Bug]: Shortcut 'Save' does not work for Asset Custom meta data

### ISSUE THREAD

**Issue by LarissaBl** [pimcore/pimcore#10008] opened 2021-08-12 06:46 UTC
### Expected behavior

If you add a line to the meta data of the assets, it should not make any difference if you save with the button "Save and Publish" or with the shortcut "CTRL + S". The metadata should be saved in both cases. 

### Actual behavior

If you save with the key combination "CTRL + S", the message "saved successfully" appears, but the next time you open the program, the last line that was added is gone. With the button save everything works. 

### Steps to reproduce

1. Add a line in Assets Custom Meta Data 
2. Save with CTRL + S 
3. Close the Asset
4. Open the Asset again 
5. The line is gone 
6. Add the line again 
7. Save with Button "Save and Publish"
8. Close the Asset
9. Open Asset again 
10. Line is still here 
![metadata](https://user-images.githubusercontent.com/88819616/129150360-b7c04677-ec67-4855-91f1-49448c84ef80.jpg)

**Comment by matthiashamacher** [comment] 2021-10-06 17:38
@LarissaBl I cannot reproduce the issue in the demo. Does the issue still exist in the newest version?

**Comment by fashxp** [comment] 2023-12-20 10:29
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed as not planned by fashxp** 2023-12-20 10:29 UTC
Labels: Bug, PR Welcome
