### ISSUE TITLE
[Bug]: & sign is displayed as &amp;

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#16790] opened 2024-03-14 13:50 UTC
### Pimcore version

11.1.5 and newer

### Steps to reproduce

Sample Code:

```twig
{% set headline = pimcore_input('headline') %}
{% if editmode %}
{{ headline|raw }}
{% else %}
{{ headline }}
{% endif %}
```

Put the following text in Backend:
Marketing & Entwicklung

Will appear as Marketing &amp; Entwicklung in frontend (non editmode)

### Actual Behavior

`Display Marketing &amp; Entwicklung`

### Expected Behavior

`Display Marketing & Entwicklung`

**Comment by Cruiser13** [comment] 2024-03-14 13:50
Follow up to https://github.com/pimcore/admin-ui-classic-bundle/issues/234
Does also affect special chars like '

**Comment by kingjia90** [comment] 2024-03-22 09:20
Thank you for your report.
I've just took a deeper look, however, it seems that it is actually unrelated to that mentioned issue, because we are dealing with input fields here, while the other were covering the wysiwyg editable.

By digging into the code stumbled upon a [parameter](https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/models/Document/Editable/Input.php#L54-L56) that needs to be set to use `&` as is, instead of the encoded one.
The [htmlspecialchars param](https://pimcore.com/docs/platform/Pimcore/Documents/Editables/Input/#configuration) hints that your mentioned case is actually an intended behaviour.

So to "fix" the reproduceable example, it should be changed to 
`{% set headline = pimcore_input('headline', {'htmlspecialchars': false}) %}`

On my end, this is considered as resolved and closing for the moment, if there's anything else, feel free to re-open or open a new one

**Closed as not planned by kingjia90** 2024-03-22 09:20 UTC
Labels: Bug, Pimcore:ToDo
