### ISSUE TITLE
[Bug]: [Document] Inherited video-editable (iframe/youtube) can't be overwritten

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#10569] opened 2021-10-12 13:06 UTC
### Expected behavior

- Inherited document with video-editable (filled with youtube-id) on it
- option to overwrite the video editable

### Actual behavior

- Inherited document with video-editable (filled with youtube-id) on it
- no interaction with video-editable possible, due to div-overlay with class "pimcore_iframe_mask"

### Steps to reproduce

- Create a template with a video-editable
- fill in a youtube video (no asset, it has to be a iframe)
- copy the document and paste it with inheritance
- close all documents and open only the inherited, so the overlay is on it

I think the intention is, to not be able to interact with a e.g. implemented youtube video, but this also applies to the inherited editable.

Other importand bug: if you open the content-master document, THEN open the inherited document, the iframe-mask div will additionally be applied to the content-master editable (not the inherited one). Then you could interact with the inherited editable 😄

**Comment by dvesh3** [comment] 2021-10-12 15:51
> Other importand bug: if you open the content-master document, THEN open the inherited document, the iframe-mask div will additionally be applied to the content-master editable (not the inherited one). Then you could interact with the inherited editable

sorry, not able to reproduce the other issue.

**Comment by dvesh3** [comment] 2021-10-13 10:16
Fixed by #10572

**Closed as completed by dvesh3** 2021-10-13 10:16 UTC
Labels: Bug
