### ISSUE TITLE
XLIFF Import broken - Call to a member function children() on bool

### ISSUE THREAD

**Issue by ghettopro** [pimcore/pimcore#6887] opened 2020-08-04 09:32 UTC
# Bug Report

When I try to import an XLIFF file, the following error message appears:

Status: 500 | 
URL: /admin/translation/xliff-import-element
Method: POST
Message: Call to a member function children() on bool

I tested it also in the testsystem https://demo.pimcore.fun/admin.

A few weeks ago, it worked fine.

Thanks in advance - Robert

# Feature Request

**Comment by weisswurstkanone** [comment] 2020-08-04 11:00
Could you please provide a sample xliff. thx

**Comment by ghettopro** [comment] 2020-08-04 11:23
Hey - i directly exported it from the demo system - but I think i found the problem!

If there is something selected in the "Elements to Export" section and you try to import the XLIFF file, the error above occurs.

So it´s hopefully a simple bug.

**Comment by weisswurstkanone** [comment] 2020-08-04 11:27
Please explain _what_ you exported.

**Comment by ghettopro** [comment] 2020-08-04 11:37
![image](https://user-images.githubusercontent.com/5647857/89289097-fa1da600-d656-11ea-8922-76e2b7de477a.png)

Here the screenshot - i´ve taken a page (e.g. Lifestyle) from the demosystem (same Issue at customer project).

Process:
a) Export the XLIFF
b) Translate the XLIFF
**c) Didn´t change anything in the settings**
d) Import the XLIFF
--> Error as described

BUT - Next try was:
a) Export the XLIFF
b) Translate the XLIFF
**c) Remove the "Lifestyle" page from the Multihref "Elements to Export"**
d) Import the XLIFF
--> works

**Comment by weisswurstkanone** [comment] 2020-08-04 12:36
Please attach the translated xliff

**Comment by ghettopro** [comment] 2020-08-04 14:56
[lifestyle-modified.txt](https://github.com/pimcore/pimcore/files/5022794/lifestyle-modified.txt)
[lifestyle-unmodified.txt](https://github.com/pimcore/pimcore/files/5022795/lifestyle-unmodified.txt)

Here the files - but you don´t need them anymore. The problem is not the XLIFF file, it´s the reason that there´s an element in the multihref.

**Comment by ghettopro** [comment] 2020-08-05 08:59
Have you already fixed something?

Next problem, when i upload the xliff file as attached, everywhere <?xml version="1.0"?>is added.

![grafik](https://user-images.githubusercontent.com/5647857/89393092-a2d90d80-d70a-11ea-89d0-9a6fbed1f25f.png)

[5f2a73afa0249.txt](https://github.com/pimcore/pimcore/files/5027271/5f2a73afa0249.txt)

**Comment by weisswurstkanone** [comment] 2020-08-05 09:21
Duplicate of https://github.com/pimcore/pimcore/pull/6795

**Closed by weisswurstkanone** 2020-08-05 09:21 UTC
