### ISSUE TITLE
[Bug]: assets versionning doesn't work 

### ISSUE THREAD

**Issue by jerem-eng** [pimcore/pimcore#10534] opened 2021-10-08 08:30 UTC
### Expected behavior

Hello, 

i'm on pimcore version 10.1.4 and i have some trouble with the assets versionning.

i upload an asset picture. 

then i draw on this image and save. 

this will be create a new version of the assets and i will be able to navigate between my two versions of assets
 one is the original asset and the second is the original with a draw.

then i will be able to publish an old assets. 

### Actual behavior

i upload an asset picture. 

then i draw on this image and save. 

the new version of the asset is created and i can navigate between my two versions of assets. But my drawing assets erase the originale assets in all version of this assets.

then when i want to publish and old version i get a 500 

Timestamp: Fri Oct 08 2021 10:16:15 GMT+0200 (heure d’été d’Europe centrale)
Status: 500 | Internal Server Error
URL: /admin/asset/publish-version
Method: post
Message: stream_get_meta_data(): Argument #1 ($stream) must be of type resource, null given

### Steps to reproduce

1 - go on the DAM demo, 

2 - upload a picture
<img width="995" alt="Capture d’écran 2021-10-08 à 10 19 21" src="https://user-images.githubusercontent.com/85865177/136523436-56bf5182-d883-41f6-9504-bb5ac61f10a7.png">
3 - modify this picture with the draw tools
<img width="998" alt="Capture d’écran 2021-10-08 à 10 20 04" src="https://user-images.githubusercontent.com/85865177/136523449-4ef58ccf-d4fb-4c48-9b1c-7cd319de130a.png">
4 -  save 
5 - go to the version tab 
6 - all versions are modified  by the new draw, and i cant get the original picture
<img width="994" alt="Capture d’écran 2021-10-08 à 10 20 54" src="https://user-images.githubusercontent.com/85865177/136523451-0498dfe5-295c-4bec-9023-c45b9bdcd8e8.png">
7 - rigth click on an old version and click to publish and got a 500 
"Timestamp: Fri Oct 08 2021 10:16:15 GMT+0200 (heure d’été d’Europe centrale)
Status: 500 | Internal Server Error
URL: /admin/asset/publish-version
Method: post
Message: stream_get_meta_data(): Argument #1 ($stream) must be of type resource, null given"

**Comment by dvesh3** [comment] 2021-10-08 08:43
duplicate of #10477

**Closed as completed by dvesh3** 2021-10-08 08:43 UTC
Labels: Bug
