### ISSUE TITLE
[Bug]: „&“ character in shared translations gets converted to „&amp;“ in templates

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#15827] opened 2023-08-28 09:48 UTC
### Pimcore version

11.0.7

### Steps to reproduce

1. Create a translation with the key „foo.bar“ and the value „Foo & Bar“ for your language.
2. use it in your code: `{{ 'foo.bar'|trans }}`

### Actual Behavior

The website shows `Foo &amp; Bar`.

### Expected Behavior

The website shows `Foo & Bar` as it was the case in Pimcore 10.6.9. Otherwise I would be forced to use the `|raw` filter for all translations in all templates as in every translation the „and“ symbol could potentially be used. That would reduce the security level of the application.

**Comment by dvesh3** [comment] 2023-08-28 10:16
duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/234

**Closed as completed by dvesh3** 2023-08-28 10:16 UTC
Labels: Bug
