### ISSUE TITLE
Weird behavior when deploying Pimcore application - Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception                           

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2543] opened 2018-02-02 09:36 UTC
Following situation: 
Deployed an application via git. did an composer install ... as usual. 
Following error: `script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception `     
( system.php and so on .. everything configured and working ) 

I spent hours trying to debug this exception. nothing really worked out.   
Now i just tried to exec `bin/console deployment:classes-rebuild -c --env=dev` and `bin/console list --env=dev`.
The result of both: 
`Fatal error: Class 'Pimcore\Model\DataObject\Customer' not found in /var/www/bts-platform/dev/releases/1/src/AppBundle/Model/DataObject/Customer.php on line 9`

Tried with Pimcore v5.1.2 and after downgrade with v5.1.0.

**Comment by brusch** [comment] 2018-02-02 10:31
Te definition file (php) for class `Customer` is in place right? 
Was the PHP class `Pimcore\Model\DataObject\Customer` generated correctly and located in `var/classes/DataObject` ? 

Stack trace?

**Comment by davidhoeck** [comment] 2018-02-02 15:08
@brusch yes the defintion files are under var/classes .. this is the first time I encountered that error ... 
I deploying by via Deployer PHP by default. First I run `composer install` and then `deployment:classes-rebuild -c`

**Comment by ruudNoBears** [comment] 2018-02-22 09:45
@brush @davidhoeck We have exactly the same problem when deploying a new project in Pimcore 5.

Models that we create extend the DataObject class created by Pimcore. When the first deployment is done the DataObject folder including it's classes does not exists since this directory is in the .gitignore. 

As soon as we try to rebuild the classes, the models try to extend a DataObject class that does not exists which results in the above error (or a ReflectionException).

Removing the extends in the models on a first deployment makes it possible to rebuild the DataObject classes.

Since we haven't found a decent solution for this yet  (except for removing DataObject from gitignore), i wanted to share this with you.

**Comment by davidhoeck** [comment] 2018-02-22 09:51
@ruudNoBears yeah I also just added the DataObject folder to my git repo, but it is not the best strategy. I'm deploying via Deployer PHP so my models are automatically rebuilt on every deployment. 
Maybe they find a fix for that.

**Comment by brusch** [comment] 2019-02-05 16:39
@davidhoeck @RuudvdvNB do you have a stack trace for the error?

**Comment by davidhoeck** [comment] 2019-02-06 16:48
@brusch I completely removed all class overrides from our projects and we are working with parent classes now.
class overrides also have a really big impact on the performance - especially in local deployment. I think in one project we got a local-development performance ("page speed") improvement of about 400-500%, by just removing all class overrides and working with the parent classes.

**Comment by RuudvdvNB** [comment] 2019-02-07 08:17
@brusch i have been testing some projects at this moment but unable to reproduce this problem. Close the issue, when i run in this problem again i'll post a stack trace.

**Closed** 2019-02-07 08:37 UTC

**Comment by brusch** [comment] 2019-02-07 10:32
@davidhoeck that sounds strange, because there's not really a difference if you're using a class-mapping or not.

**Comment by dpfaffenbauer** [comment] 2019-02-07 12:12
it does sound indeed odd. But I can imagine that overriding needs more resources, but not that much. But: As of now, everybody should now my opinion on overrides: Don't use them, they're evil ;)

**Comment by romainbessugesmeusy** [comment] 2020-04-24 12:16
Hey we have this exact problem right now. Has anyone managed to solve it in the past?
