### ISSUE TITLE
[Bug]: XLIFF Import issues

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#13332] opened 2022-10-07 08:24 UTC
### Expected behavior

I noticed several bugs when importing the xliff files.

### Actual behavior

The xliff export has been created using source language DE and target language ES. The DE tree has been cloned using "Paste language recursive, updating references".

- When importing the documents, the source documents will also get replaced with the translated contents
- This happens also for data objects
- In some cases the $blockData (blocks inside translatedfields) is an array, not an object. Therefore an error is thrown when cloning the object. Have there been any changes? https://github.com/pimcore/pimcore/blob/11.x/lib/Translation/ImporterService/Importer/DataObjectImporter.php#L72
![image](https://user-images.githubusercontent.com/90033/194505479-0fa2a880-7beb-4f32-b3c0-6c2928a5b8da.png)

- When handling data objects while importing documents, $request in the Symfony LogoutUrlGenerator.php#104 is empty.
![image](https://user-images.githubusercontent.com/90033/194506028-a55864cb-ddeb-4feb-a34b-879ea4baf5f7.png)
I have no clue why this is happening.

The export was created using Pimcore 10.4, I tried importing the data using Pimcore 10.4 and 10.5.7.

### Steps to reproduce

- Create a xliff export of documents/objects
- Change contents
- Run import

**Comment by simonkey** [comment] 2022-10-28 10:05
Update about the problem:

The `__clone method called on non-object` error occurs for data objects which have the following setup:
* localizedfields -> Block -> Input Field
* 
![image](https://user-images.githubusercontent.com/1583145/198561455-4208785e-bc81-48c2-891b-31b6e1e77a8d.png)

Here the export and a translated export: [xliff-files.zip](https://github.com/pimcore/pimcore/files/9887297/xliff-files.zip)

The `getBaseUrl() on null` error  in  LogoutUrlGenerator.php occurs only in debug mode. It is already fixed in symfony (https://github.com/symfony/security-http/blob/5.4/Logout/LogoutUrlGenerator.php#L104), but the version tag is still missing. **Update 31.10.2022**: Version 5.4.15 Released and fixed

Tested pimcore version: 10.5.9

**Comment by aryaantony92** [comment] 2022-10-31 08:16
@valentin- I just tried to reproduce the issue where source document gets replaced with the translated contents.

As per the above mentioned steps, I tried the following in 10.5.7

-> Copied a folder tree (inside the 'de' folder) and pasted it as a new folder outside the 'de' folder using the option 'Paste language (recursive), updating references'.
-> Then, exported the copied document using Xliff export (de to en) and then edited the xliff file.
-> And then, imported the edited xliff file. 
The contents of the document in the copied folder (which is outside the 'de' folder') got translated with the edited Xliff translations. But contents of the document in the 'de' folder remains the same.
 
It works fine. So, could you please check and confirm if the issue (source documents get replaced with the translated content) still exists or Should I need to consider some extra points to test this ?

**Comment by valentin-** [comment] 2022-11-02 08:04
@aryaantony92 thanks for you response. I checked the xliff file again. Turned out there are mixed IDs in the translation file, I think this causes the issue.

DE document IDs starting with 6
ES document IDs starting with 642

In the original translated file, the IDs seem to be mixed up:
![image](https://user-images.githubusercontent.com/90033/199432189-b3385961-678e-4706-b245-017dc7b07bb0.png)

Unfortunately I can't reproduce a file with wrong export IDs anymore. Was there any earlier fix for the export behaviour?

Export from DE tree:
![image](https://user-images.githubusercontent.com/90033/199432605-bd5ff95d-746b-4792-90ac-1516eebd2283.png)

Export from ES tree:
![image](https://user-images.githubusercontent.com/90033/199432640-882971ba-72fb-47e6-865d-a8e32c673a9e.png)

We'll have to fix this on our side. Any information on the other issues? 

Thanks in advance!

**Comment by aryaantony92** [comment] 2022-11-04 13:06
@valentin- Thanks for the reply. I have tested the translation issue in case of DataObjects (source also gets translated) and was unable to reproduce the issue. And regarding the error " __clone method called on non-object" in case of data objects, I have tested it with the data objects with block data type. But I didn't get the error. But, it can throw error if we try to clone null value. Since $blockData and $originalBlockItem can have null values, the error could be possible. 
https://github.com/pimcore/pimcore/blob/6851acd093a0d1b7ea9ef053cd47c004dc004e44/lib/Translation/ImporterService/Importer/DataObjectImporter.php#L67
https://github.com/pimcore/pimcore/blob/6851acd093a0d1b7ea9ef053cd47c004dc004e44/lib/Translation/ImporterService/Importer/DataObjectImporter.php#L72
Will handle the error using exception.

**Comment by simonkey** [comment] 2022-11-04 14:23
@aryaantony92 

I've tested the issue in your live demo (https://demo.pimcore.com/admin/?perspective=default) and it's quite easy to reproduce with a simple dataobject as described bevore. Here the class definition.
[class_TranslationTest_export.zip](https://github.com/pimcore/pimcore/files/9939071/class_TranslationTest_export.zip).

Fill in some data (only in EN!)
![image](https://user-images.githubusercontent.com/1583145/199996579-e33f8b52-f785-4654-9e76-ba5ebdfcc466.png)
![image](https://user-images.githubusercontent.com/1583145/199996657-306f98b4-74c2-4b5e-a35e-4692c939b0ed.png)

Export the XLIFF:
![image](https://user-images.githubusercontent.com/1583145/199996879-392fbb09-d90e-4428-9568-50e1f89137d0.png)

Translate e.g. at https://xliff.brightec.co.uk/. It's important to add some translation, otherwise no error will be thrown.

Trying to import the translation -> error occurs:
![image](https://user-images.githubusercontent.com/1583145/199997390-d1ed7f17-f56f-4dfe-8a6f-e2502ea9439e.png)

I've debugged the import and `$originalBlockItem` is in that case not `null`. It's some property of the object which cannot be cloned. I know that there is a deep copy mechanism for the versioning of the dataobjects maybe this will to the trick to avoid the error.

If the null-case happens, there should be either a silent fail or better a new empty block should be created and filled with the data.

**Comment by aryaantony92** [comment] 2022-11-04 14:47
Thank you for the update, I will check then

**Comment by simonkey** [comment] 2022-11-11 08:08
@aryaantony92 
I've an update about the target-language export/import issue. The issue can be found here https://github.com/pimcore/pimcore/issues/13557.

**Comment by aryaantony92** [comment] 2022-11-23 12:19
@simonkey @valentin Thanks! Closing the issue as https://github.com/pimcore/pimcore/pull/13659 fixes the XLIFF import with the dataobjects and will create a different PR to fix the issue (https://github.com/pimcore/pimcore/issues/13557) with the documents

**Closed as completed by aryaantony92** 2022-11-23 12:19 UTC
Labels: Bug
