### ISSUE TITLE
Classification store inheritance causes JS issue

### ISSUE THREAD

**Issue by msoroka** [pimcore/pimcore#9906] opened 2021-07-30 06:38 UTC
Pimcore version: 10.0.8

### Expected behavior

Data object which has inheritance enabled and field with type "Classification Store" open correctly, both parent and its children.

### Actual behavior

While open child data object which has field with type "Classification Store" cause Javascript issue and backend panel stops working.
Parent:
![image](https://user-images.githubusercontent.com/25011263/127610934-79417ff1-c9c3-4bcf-abfb-2618e4369bc4.png)
Child:
![image](https://user-images.githubusercontent.com/25011263/127611301-c4ebf093-0526-479b-99dd-cb9eae928912.png)
![image](https://user-images.githubusercontent.com/25011263/127610971-b23e06ef-1363-4ab1-8f8a-e585a0602baf.png)

### Steps to reproduce

1. Create classification store definition.
2. Create data object class with inheritance enabled and create field with type "classification store", as store select created one from first step.
3. Create parent object.
4. Create child object. During opening for edit this object error is supposed to happen.  

Disabling inheritance fix the issue but it's not a solution.

**Comment by weisswurstkanone** [comment] 2021-07-30 07:31
Not able to reproduce. Maybe I missed a step. Could you please add the unminfied_js parameter and post the stack trace again. 
See https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Magic_Parameters.html

**Comment by dvesh3** [comment] 2021-08-02 08:48
Fixed by #9908

**Closed as completed by dvesh3** 2021-08-02 08:49 UTC
Labels: Bug
