### ISSUE TITLE
[Bug]: Unable to generate thumbnail in ORIGINAL format

### ISSUE THREAD

**Issue by limenet** [pimcore/pimcore#17051] opened 2024-05-15 09:27 UTC
### Pimcore version

11.2.3.2

### Steps to reproduce

1. Create a thumbnail definition
2. Set "Format" to `ORIGINAL` (and, for easier reproduction, enable "List as option in download section on image detail view")
3. Upload a JPG image
4. Generate a thumbnail e.g. by selecting that definition in the asset module and clicking "Download"

Note: `pimcore.assets.thumbnails.allowed_formats` as described at https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/#pimcore-1124--11231--11165 is left untouched i.e. `JPG` (or any variations thereof) should work.

### Actual Behavior

1. HTTP 500

Please note: this is currently only reproducible on the Enterprise demo which uses v11.2.3.2 and not on the Community demo which is on v11.2.3 as the corresponding change introduced in a6821a16ea38086bf6012e682e1743488244bd85 is not yet tagged as a non-Enterprise version (see also https://github.com/pimcore/pimcore/compare/v11.2.3...11.x).

### Expected Behavior

1. Thumbnail is downloaded in the original format

The bug is due to https://github.com/pimcore/pimcore/commit/a6821a16ea38086bf6012e682e1743488244bd85#diff-b48489e5be12fb4a4ec4f716c03e4690a799c39a87430cbb1a435d7badebf97cR433-R449 not checking whether the original format is requested and checking that value against the `allowed_formats` in the `in_array` call.

If desired, I can submit a pull request with a fix.

**Comment by limenet** [comment] 2024-06-05 06:53
Can confirm this bug can be reproduced on 11.2.4 on both the Community and the Enterprise demo.

**Comment by mattamon** [comment] 2024-06-05 10:18
@limenet I created a PR https://github.com/pimcore/pimcore/pull/17129
Could you please check if that fixes it for you. For me it now works as intended with these changes.

**Comment by limenet** [comment] 2024-06-05 14:07
@mattamon appreciate the PR and can confirm it now works as expected

**Comment by mattamon** [comment] 2024-06-05 14:13
@limenet Thank you for your quick feedback! I am waiting for feedback in another issue, but as soon as I have it, I will merge this PR

**Comment by mattamon** [comment] 2024-06-06 14:09
Closed by #17129 

@limenet new version was released today https://github.com/pimcore/pimcore/releases/tag/v11.2.5

**Closed as completed by mattamon** 2024-06-06 14:09 UTC
Labels: Bug, Pimcore:Priority
