### ISSUE TITLE
[Bug]: Entries in documents_translations are not referencing each other correclty

### ISSUE THREAD

**Issue by Butterd** [pimcore/pimcore#15125] opened 2023-05-05 09:28 UTC
### Pimcore version

10.5.8

### Steps to reproduce

- Have at least 3 different locales and/or languages configured (as per my case the languages are "de, de_at, de_be, nl")
- Link Documents to each other using the Translation-Menuitem and selecting "Link existing document"
- The source language using this method has always been the same ("de" in my case)
- In some cases - seemingly when trying to link entire subtrees - some links between the languages are missing

### Expected / actual behavior

**Expected behaviour**
You should be able to get to every document no matter your source language.

**Actual behaviour**
Some connections are missing. 
i.e.: You can get to every document from the de language, however the de_at language isn't connected to anyhing according to the documents_translations table.

<details><summary>de</summary>
Here are the entries using the "de" document's Id as sourceId (note the missing ids 3028 and 4645 in this table)  

![image](https://user-images.githubusercontent.com/9197082/236421780-14dffd43-abe5-4e6c-bbe0-5c9c2db3e8b9.png)</details>

<details><summary>de_at</summary>
These are the entries using the "de_at" document's Id as sourceId   

![image](https://user-images.githubusercontent.com/9197082/236421954-158435bc-6152-4388-9a58-78f90e5cf3c8.png)
</details>

Is there a possibility to clean up the table or is this a wider-spread issue?

**Comment by dvesh3** [comment] 2023-05-31 10:09
@Butterd sorry, not able to reproduce the issue on latest v10.5.23. The translations are loaded from the source id so it loads all translations except the current. 

_"In some cases - seemingly when trying to link entire subtrees - some links between the languages are missing"_ ~ do you mean when using "Paste as New Language Variant (recursive)"? If so, it works too.

**Comment by dvesh3** [comment] 2023-06-12 07:54
@Butterd 🏓

**Comment by Butterd** [comment] 2023-06-13 13:47
> _"In some cases - seemingly when trying to link entire subtrees - some links between the languages are missing"_ ~ do you mean when using "Paste as New Language Variant (recursive)"? If so, it works too.  

Hi @dvesh3 , apologies for the delay.
Sadly "Paste as New Language Variant" wasn't possible as all possible tranlsations for each document were already in the system.

How this came about, I assume, was as follows:

- You have 2 Trees _de\_de_ and _de\_at_ which have all documents linked as translations.
- You create 2 new Trees that represent the new root of each tree respectively. Let's call them _de\_de\_new_ and _de/_at\_new_
- Then you move the all documents from one root to another. i.e. _de\_de_ to _de\_de\_new_
- Then we try to remap the translations by linking the new roots as translations.

I hope this helps you find the issue. Thanks

**Comment by dvesh3** [comment] 2023-06-16 13:28
still works for me:

`de (id: 136)` is linked to `en (id: 3)` with 
<img width="400" alt="image" src="https://github.com/pimcore/pimcore/assets/5137917/d14f1acf-42b3-434e-87fa-9bbaf97184a3">

and `en (id: 3)` linked to `fr (id: 215)`
<img width="400" alt="image" src="https://github.com/pimcore/pimcore/assets/5137917/ea65594b-ef04-4db4-9efc-51464a302be7">

then you see transitive link between `fr (id: 215)` & `de (id: 136)`:
<img width="440" alt="image" src="https://github.com/pimcore/pimcore/assets/5137917/2566c306-261c-4eea-9d45-f02cb3431215">

**Comment by dvesh3** [comment] 2023-06-26 07:40
Closed as not reproducible. Please feel free to continue the discussion.

**Closed as completed by dvesh3** 2023-06-26 07:40 UTC
Labels: Bug
