### ISSUE TITLE
Debug email information not displayed in email / backoffice

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9177] opened 2021-05-20 19:37 UTC
Hello,

When using email features with debug mode activated and debut email address filed, the debug information is not displayed nor in the email received on the debug address, neither in the back-office.
Tested with the pimcore/demo install of Pimcore X last stable version, dev env and debug activated, debug email address filled in System -> Settings.

![image](https://user-images.githubusercontent.com/9025839/119038320-4736f280-b9b3-11eb-9cf5-73571e57c71c.png)

On the back-office:

- In the data information, there is no more information (in Pimcore 6 we can get the real receiver if debug mode was not active):

![image](https://user-images.githubusercontent.com/9025839/119036497-13f36400-b9b1-11eb-8e62-d646c32f2f46.png)

In the mailbox:

- There is no more the debug information in the footer (the real receiver if debug mode was not active), neither in the email client software where the email was received, neither in the email html preview in the BO:

![image](https://user-images.githubusercontent.com/9025839/119036714-587eff80-b9b1-11eb-9dbe-12ae45436c03.png)

Do I miss something or is there a problem/bug ? It is like all debug information are lost.

Thanks!
Best regards.

**Comment by dvesh3** [comment] 2021-05-25 14:42
@Yivan debug params in email logs are fixed in #9222

- Debug info is not logged in email logs.
- not able to reproduce debug info missing issue (if you are using send test mail functionality that ignores the debug info https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Controller/Admin/EmailController.php#L401)

Received debug info in email client:
![image](https://user-images.githubusercontent.com/5137917/119517745-2b976780-bd78-11eb-9624-b38d4b4e8a92.png)

**Comment by brusch** [comment] 2021-05-26 08:04
Fixed by #9222

**Closed as completed by brusch** 2021-05-26 08:04 UTC
Labels: Bug
