### ISSUE TITLE
[Bug, EC]: Custom OptionsProvider getOptions() has no 'object' in $context

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [pimcore/pimcore#17571] opened 2024-09-05 14:04 UTC
### Pimcore version

11

### Steps to reproduce

1. Add custom OptionsProvider
The custom OptionsProvider `getOptions()` method rely on `$context['object']->getProperty('foo')`
Return different content in options array depending on property 'foo' of data object.
Return empty array `[]` if `!array_key_exists('object', $context)`.
2. Add new select field to data model using the custom OptionsProvider from previous step
3. Open data object in admin backend

### Actual Behavior

In Pimcore v11.1.5.2 / 11.1.6 / 11.2.2 the `$context` parameter (array) does not always contain the `'object'`.

In the Pimcore admin backend the Dropdown has NO option.
If the field have a valid value before introducing this OptionsProvider (e.g. direct select options from class definition) then an alert is shown "invalid_option".

### Expected Behavior

The `getOptions()` method of a custom OptionsProvider should always have `$context['object']`. Then the options can be build as required -- depending on property 'foo' of the data object. 

In the Pimcore admin backend the Dropdown has all necessary options depending on property 'foo' of the data object.

In some older Pimcore versions it works as expected, e.g. v11.0.12.

/PIS

**Comment by kingjia90** [comment] 2024-09-26 10:50
Thank you for reporting!

I've tried to debug this but couldn't totally get what's going on under the hood.

This point caught my attention
> Return empty array [] if !array_key_exists('object', $context).

It seems that object can be nullable when it comes from field definition.
https://github.com/pimcore/pimcore/blob/8e6ceb61ca02f47e40e8077482a89818881dd47e/models/DataObject/ClassDefinition/Data/Multiselect.php#L510-L513
https://github.com/pimcore/pimcore/blob/8e6ceb61ca02f47e40e8077482a89818881dd47e/models/DataObject/ClassDefinition/Data/Multiselect.php#L518-L521
and by also noting this fallback
https://github.com/pimcore/pimcore/blob/e4fea5a022c1ecfbb2b07ae2409ad476bc6da9e1/models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectionProviderTrait.php#L38

looks as intended.

Can we go a step back to see what are you trying to achieve and see if there's another way?

**Comment by studio1gmbh-pimcore** [comment] 2024-09-26 13:21
Hello @kingjia90 ,

we try to offer different select options depending on property of the data object itself (see steps to reproduce). The custom options provider evaluates the property and depending on the result different options should be provided. 

To detect the property value of the data object we rely on the `$context['object']`:
* As a fallback we `return []` in the custom options provider `getOptions()` method If `array_key_exists('object', $context) != true`. 
* The expected case was that `array_key_exists('object', $context) == true`. Then we can return different content in custom options provider `getOptions()` method based on `$context['object']->getProperty('foo')`. E.g. something like the following
  ```php
  if ($context['object']->getProperty('foo') == 'bar') {
      return [[
          'value' => 'foobar-1',
          'key' => 'Foobar 1',
      ], [
          'value' => 'foobar-2',
          'key' => 'Foobar 2',
      ]];
  } else {
      return [[
          'value' => 'lorem-1',
          'key' => 'Lorem 1',
      ], [
          'value' => 'lorem-2',
          'key' => 'Lorem 2',
      ], [
          'value' => 'lorem-3',
          'key' => 'Lorem 3',
      ]];
  }
  ```

Maybe together we can figure out a solution?

/PIS

**Comment by kingjia90** [comment] 2024-09-26 14:38
Mhhh, but doesn't it without `array_key_exists('object', $context) != true` and by changing to
```
if ($context['object']?->getProperty('foo') == 'bar') {
...
}else{
...
}
```
(NB: the question mark as coalescing on the undefined `object` key)
just work fine? On my end, looks fine, at least. 

Could it be fixed in 11.3?

**Comment by studio1gmbh-pimcore** [comment] 2024-09-27 06:10
To provide a non-cluttered easy-to-read example we stumbled up on the method `\Pimcore\Model\DataObject\ClassDefinition\DynamicOptionsProvider\SelectOptionsProviderInterface::hasStaticOptions()`. The doc-block of this method was a bit confusing, because it describes the dynamic part but should return `false` for it. After fixing this / changing the return value, our custom options provider works as expected.
 
For us this issue can be closed. Maybe an optimization of the doc-block helps other users?!

/PIS

**Comment by kingjia90** [comment] 2024-09-27 07:27
Thank you for the follow-up!
It's great to hear you have figured out how to make it work

Closing the issue, for the doc block optimization would you be able to provide a quick PR for it since you are more aware of how it should have been phrased to be more clear? TIA

**Closed as completed by kingjia90** 2024-09-27 07:27 UTC
Labels: Bug
