### ISSUE TITLE
[Bug]: Filter by relation doesn't work in grid view

### ISSUE THREAD

**Issue by mladenmakso** [pimcore/pimcore#17811] opened 2024-11-08 09:00 UTC
### Pimcore version

v11.4.1.2

### Steps to reproduce

1. Click on object folder
![Image](https://github.com/user-attachments/assets/74016441-8a52-4671-b7d5-caa1db84cb72)

2. Filter by relation
![Image](https://github.com/user-attachments/assets/63cf8d4e-30b4-4deb-a90f-43611d6f454a)

### Actual Behavior

Error popup:

1. Layout breaks:
![Image](https://github.com/user-attachments/assets/fdfe079a-b720-48a6-8d39-e7a707589f0a)

2. Error in console
![Image](https://github.com/user-attachments/assets/788814f9-444d-411c-aadf-394b351ea3aa)

### Expected Behavior

Filter by relation should work

**Comment by blankse** [comment] 2024-11-08 09:20
@mladenmakso Duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/720
Already fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/741

**Comment by mattamon** [comment] 2024-11-11 10:05
Closing of duplication and wrong repository https://github.com/pimcore/admin-ui-classic-bundle/issues/720

**Closed as completed by mattamon** 2024-11-11 10:05 UTC
Labels: Bug
