### ISSUE TITLE
Error when saving object with calculated fields because bad column type.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2440] opened 2018-01-11 17:01 UTC
Calculated fields can make problem when saving object (SQL error) because of the getQueryColumnType wich send back varchar(190) but in fact there is not column in database.
Is it wanted ?

Here https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/ClassDefinition/Data/CalculatedValue.php#L280
`return $this->queryColumnType . '(' . $this->getColumnLength() . ')';`
should be replaced by
`return null;`

Same should be applied for Pimcore 4:
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Object/ClassDefinition/Data/CalculatedValue.php#L265

Thanks.

**Comment by weisswurstkanone** [comment] 2018-01-12 06:56
Actually there should be a column in the query table (but not in the store table). Can you find out why it doesn't exist. Cannot reproduce this on my side, at least with a simple setup (not contained in localized field, brick or whatever)

**Comment by weisswurstkanone** [comment] 2018-01-16 09:29
@Yivan , any updates on this ?

**Comment by Yivan** [comment] 2018-01-16 10:28
I will try to reproduce a use case and come back soon on this.

**Comment by weisswurstkanone** [comment] 2018-01-22 08:57
Closing this one for now ...

**Closed by weisswurstkanone** 2018-01-22 08:57 UTC

**Comment by Yivan** [comment] 2018-01-22 11:20
I cannot provide details to reproduce it for now (we changed many code in this project from the time this bug appeared). So yes can be closed. If it reproduce on another project i will post more details to recreate it.
Thanks.
