### ISSUE TITLE
[Bug]: pimcore:build:classes requires DB (and other services) for multiple class definitions

### ISSUE THREAD

**Issue by juckerf** [pimcore/pimcore#15520] opened 2023-07-12 09:30 UTC
### Pimcore version

10.6

### Steps to reproduce

* Shutdown database (or execute the following command during build-time)
* Run `bin/console pimcore:build:classes`

### Expected / actual behavior

* Actual behavior:
  * running `bin/console pimcore:build:classes` results in an error:
    ```
    Next Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused in /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112
    Stack trace:
    #0 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDO\Exception))
    #1 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'An exception oc...')
    #2 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(31): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception))
    #3 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(412): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, '', '', Array)
    #4 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1952): Doctrine\DBAL\Connection->connect()
    #5 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1290): Doctrine\DBAL\Connection->getWrappedConnection()
    #6 /var/www/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(92): Doctrine\DBAL\Connection->executeQuery('SELECT id FROM ...', Array, Array, NULL)
    #7 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1119): Pimcore\Db\Connection->executeQuery('SELECT id FROM ...', Array, Array)
    #8 /var/www/pimcore/vendor/pimcore/pimcore/models/Tool/Targeting/TargetGroup/Listing/Dao.php(33): Doctrine\DBAL\Connection->fetchFirstColumn('SELECT id FROM ...', Array)
    #9 [internal function]: Pimcore\Model\Tool\Targeting\TargetGroup\Listing\Dao->load()
    #10 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(246): call_user_func_array(Array, Array)
    #11 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/TargetGroup.php(87): Pimcore\Model\AbstractModel->__call('load', Array)
    #12 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/TargetGroup.php(128): Pimcore\Model\DataObject\ClassDefinition\Data\TargetGroup->configureOptions()
    #13 /var/www/pimcore/var/classes/definition_CustomerSegment.php(255): Pimcore\Model\DataObject\ClassDefinition\Data\TargetGroup::__set_state(Array)
    #14 /var/www/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/Command/ClassesDefinitionsBuildCommand.php(63): include('/var/www/pimcor...')
    #15 /var/www/pimcore/vendor/symfony/console/Command/Command.php(298): Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #16 /var/www/pimcore/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #17 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #18 /var/www/pimcore/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #19 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #20 /var/www/pimcore/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #21 /var/www/pimcore/bin/console(48): Symfony\Component\Console\Application->run()
    #22 {main}
    ```
  * Affected after a quick scan (probably even more ClassDefinitions affected)
    * `models/DataObject/ClassDefinition/Data/TargetGroup.php`
    * `models/DataObject/ClassDefinition/Data/QuantityValue.php`

* Expected behavior:
  * building php classes should not rely on any external services (db, cache) etc.
  * `bin/console pimcore:build:classes` should be executable during build-time

**Comment by jdreesen** [comment] 2023-08-02 09:18
If this is true, it must be fixed before the EOL of Pimcore 10.6!

**Comment by dvesh3** [comment] 2023-08-16 09:52
Fixed by #15726

**Closed as completed by dvesh3** 2023-08-16 09:52 UTC
Labels: Bug, Backlog

**Comment by saitho** [comment] 2024-10-05 18:14
@dvesh3 I'm just wondering: I can reproduce this with the latest Pimcore version.
Is that supposed to be the case with Pimcore 11, that database is required to generate classes?
Or is that a regression? If so, I can open a separate issue for that.

EDIT: No worries. Seems to be related to the CMF bundle. If I take out my Customer classes, it works.

**Comment by fashxp** [comment] 2024-10-07 06:20
Please create a separate issue for it with detail information (respective which data type requires DB). If you have already a solution, a PR would be even better ;-)

**Comment by jdreesen** [comment] 2024-10-07 06:59
The separate issue is probably this one: https://github.com/pimcore/personalization-bundle/issues/70 ;)
