### ISSUE TITLE
[Bug]: Pimcore installation process failing v10.6+

### ISSUE THREAD

**Issue by MajorKuprich** [pimcore/pimcore#15460] opened 2023-07-02 16:46 UTC
### Pimcore version

10.6+

### Steps to reproduce

Hello,

Install Pimcore with below commands:

```bash
COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/demo my-project
cd ./my-project
./vendor/bin/pimcore-install
```

### Expected / actual behavior

Pimcore installation process fails after run `./vendor/bin/pimcore-install`.

Logs:

```bash
[2023-07-02T07:51:50.680588+00:00] pimcore.WARNING: Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "pimcore.config". in /var/www/html/var/installer/cache/ContainerXskAEuz/Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer.php:782 Stack trace: #0 /var/www/html/vendor/pimcore/pimcore/lib/Config.php(157): ContainerXskAEuz\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer->getParameter('pimcore.config') #1 /var/www/html/vendor/pimcore/pimcore/lib/Tool/Console.php(81): Pimcore\Config::getSystemConfiguration('general') #2 /var/www/html/vendor/pimcore/pimcore/lib/Tool/Requirements.php(610): Pimcore\Tool\Console::getExecutable('convert') #3 /var/www/html/vendor/pimcore/pimcore/bundles/InstallBundle/src/Installer.php(220): Pimcore\Tool\Requirements::checkPhp() #4 /var/www/html/vendor/pimcore/pimcore/bundles/InstallBundle/src/Command/InstallCommand.php(351): Pimcore\Bundle\InstallBundle\Installer->checkPrerequisites() #5 /var/www/html/vendor/symfony/console/Command/Command.php(326): Pimcore\Bundle\InstallBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/www/html/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(91): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /var/www/html/vendor/pimcore/pimcore/bin/pimcore-install(106): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #12 /var/www/html/vendor/bin/pimcore-install(120): include('/var/www/html/v...') #13 {main} [] []
[2023-07-02T07:51:50.712834+00:00] console.DEBUG: Command "pimcore:install" exited with code "2" {"command":"pimcore:install","code":2} []
```

There is no problem with versions until 10.6.
I've tried different ways to fixing it:
- [add preconfig](https://pimcore.com/docs/platform/Pimcore/Getting_Started/Advanced_Installation_Topics#preconfiguring-the-installer)
- [update bundles priority](https://github.com/pimcore/pimcore/issues/14929)

Similar issue fixed by adding **mysql_host_socket** config: https://github.com/pimcore/pimcore/issues/13287

**Comment by dvesh3** [comment] 2023-08-09 07:29
Closing as not reproducible on our end. It seems to be a problem with installation setup.

**Closed as completed by dvesh3** 2023-08-09 07:29 UTC
Labels: Bug, PR Welcome
