### ISSUE TITLE
[Bug]: AssetDocumentConversionTask deleted

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10841] opened 2021-11-16 15:42 UTC
### Expected behavior

[According to the documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Working_with_Thumbnails/Document_Thumbnails.html) PDF:s and other files should have thumbnails being generated though the maintenance tasks.

### Actual behavior

It appears it is a regression of #10425 and #10390

### Steps to reproduce

1. Upload a PDF file
2. Wait for the thumbnail to generate
3. No thumbnail ever gets generated

**Comment by mcop1** [comment] 2021-11-29 09:46
Hello,

since the thumbnail conversion is now handled by the symfony messenger queue, the AssetDocumentConversionTask isn´t needed anymore. The new AssetUpdateTasksMessage gets added to the messenger queue and the maintenance task consumes the queue. 
If you are interested, you can find some more informations in the upgrade notes [here](https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/index.html)

Regarding your problem, unfortunately, I can´t reproduce the issue on my side. 

Could you please try and 

1.) Create a new Asset 
2.) Check log file in var/log
3.) Check if you can find an entry similiar to

`messenger.INFO: Sending message Pimcore\Messenger\AssetUpdateTasksMessage with pimcore_core sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Pimcore\\Messenger\\AssetUpdateTasksMessage":[]},"class":"Pimcore\\Messenger\\AssetUpdateTasksMessage","alias":"pimcore_core","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []`

Does the problem occur with every (pdf) file or with some specific files?

Best regards

**Comment by NiklasBr** [comment] 2021-11-29 10:28
Neither `AssetDocumentConversionTask` nor `AssetDocumentConversionTask` is not mentioned in the upgrade log. Which code is responsible for generating the Asset Documents thumbnails today @mcop1?

We have loads and loads of error messages like these in the log: https://github.com/pimcore/pimcore/issues/10714#issuecomment-953709325 when running this command: `bin/console maintenance --excludedJobs=logmaintenance,cleanuplogfiles,imageoptimize`

Looking at the database we have thousands of rows in the `messenger_messages` table like these:

![image](https://user-images.githubusercontent.com/279826/143850678-9f4be85f-9972-4270-afec-d80819ea9799.png)
The above date coincides with the installation of 10.2 on the server. It appears the messenger queue is never consumed. Why? What documentation is available here?
![image](https://user-images.githubusercontent.com/279826/143852240-80e0ac2c-cc19-4700-8b2c-2f112c4a3996.png)


When can these be expected to execute? We run cron with the following schedule:
```*/5 * * * *                  www-data /bin/bash -c '/usr/local/bin/php $PIMCORE_ROOT/bin/console maintenance --async --excludedJobs=logmaintenance,cleanuplogfiles,imageoptimize >>$PIMCORE_ROOT/var/log/cron.log```

**Comment by mcop1** [comment] 2021-11-30 10:51
@NiklasBR

The code responsible for generating the (document) thumbnails can be found here

https://github.com/pimcore/pimcore/blob/777984e9d301bc1df1dbbe2cdbda04d27e74b750/models/Asset/Document.php#L89

and here

https://github.com/pimcore/pimcore/blob/96dfb78d70ff6a3868e863246a913fd26d2145bb/lib/Messenger/Handler/AssetUpdateTasksHandler.php#L33

The upgrade notes mention the maintenance task and the async argument. That´s what I meant, sorry, if I wasn´t clear enough about that.
That means, as long as you are using the --async argument for the maintenance task your queues won´t be consumed. 
Removing the --async argument would work, but then the command would run for 300 seconds every time. 
Therefore it is recommended to setup an additional worker process to consume the queues.

You can also try and run the messenger:consume command manually like this: 

`php bin/console messenger:consume --limit=10 pimcore_core pimcore_maintenance -vv`

This should consume 10 messages from the queues and print some details about that to the commandline. 

Best regards

**Comment by NiklasBr** [comment] 2021-11-30 14:19
> `php bin/console messenger:consume --limit=10 pimcore_core pimcore_maintenance -vv`

Is that supposed to generate the thumbnails? I cannot make that command create any thumbnails from Asset Documents on 10.2.5

**Comment by NiklasBr** [comment] 2021-12-01 08:45
> [...] as long as you are using the --async argument for the maintenance task your queues won´t be consumed.

But then it says:

> Running Maintenance Command without --async and not having the messenger consume message yourself is deprecated and will be removed from Pimcore in 11.

@mcop1 can you provide some documentation about the *intended* usage here?

**Comment by mcop1** [comment] 2021-12-01 09:01
@NiklasBr 
> > `php bin/console messenger:consume --limit=10 pimcore_core pimcore_maintenance -vv`
> 
> Is that supposed to generate the thumbnails? I cannot make that command create any thumbnails from Asset Documents on 10.2.5

This command consumes 10 messages from the pimcore_core and pimcore_maintenance queue. But not only AssetUpdateTasksMessage are queued there. It is a way to check if the queues get consumed in general. 

> > [...] as long as you are using the --async argument for the maintenance task your queues won´t be consumed.
> 
> But then it says:
> 
> > Running Maintenance Command without --async and not having the messenger consume message yourself is deprecated and will be removed from Pimcore in 11.
> 
> @mcop1 can you provide some documentation about the _intended_ usage here?

For Pimcore 10 the --async argument is still supported. But it will be dropped with Pimcore 11, the job will always be async then.

The recommended/intended use: 

* Run maintenance job in one process (with async argument for Pimcore 10)
* Consume symfony messenger queues in another,  additional worker process

Just as it is mentioned in the upgrade notes:

> [Maintenance] Maintenance tasks are now handled with Symfony Messenger. The pimcore:maintenance command will add the maintenance messages to the bus and runs them afterwards immediately from the queue. **However it's recommended** to setup **independent workers that process the queues**, by running **bin/console messenger:consume pimcore_core pimcore_maintenance** (using e.g. Supervisor) and adding --async option to the pimcore:maintenance command that stops the maintenance command to process the queue directly. Details about setting it up for production environments, please check Symfony Messenger Component docs.

Best regards

**Comment by fashxp** [comment] 2021-12-01 10:34
maybe also related: #10928

**Comment by NiklasBr** [comment] 2021-12-01 10:58
> That means, as long as you are using the --async argument for the maintenance task your queues won´t be consumed.

> For Pimcore 10 the --async argument is still supported. But it will be dropped with Pimcore 11, the job will always be async then.

This part is unclear. So to consume the queue in Pimcore 11 we have to run a second command in addition to `pimcore:maintenance`?

Also take a look at issue #10714 which causes issues with the queue.

Running your suggested command `messenger:consume pimcore_core pimcore_maintenance -vv` as well as `maintenance --excludedJobs=logmaintenance,cleanuplogfiles,imageoptimize` does not appear to create any thumbnails for Document Assets such as uploaded PDF files. How do I run that command to create the thumbnails? How do I run that command as cron to automatically create thumbnails the way the documentation *says* it should work?

There are no errors, nothing interesting in the logs, it just simply does not process any thumbnails, setting a breakpoint in the AssetUpdateTasksHandler.php never breaks.

**Comment by mcop1** [comment] 2021-12-02 08:05
> This part is unclear. So to consume the queue in Pimcore 11 we have to run a second command in addition to pimcore:maintenance?

Exactly. The plan for Pimcore 11 is to run a second command. 
In Pimcore X you only have to run the second command if you are using async argument.

There is no dedicated command for creating thumbnails, since they are stored in the same queue as other messages. 
As I said, the command

`messenger:consume pimcore_core pimcore_maintenance -vv` 

consumes the queue, but there are all kinds of different messages in the queue- including, but not limited to AssetUpdateTaskMessage. Since you already mentioned, that there a lot of entries in your queue, it will take some time to process the whole queue. Once the queue is empty, we can safely say that all AssetUpdateTaskMessages were handled and thus thumbnails should be created.

While running this command, does it output anything to the command line? 
And while running this command, please check your queue (messenger_messages table in db). The entries in the table should become fewer. 

Best regards

**Comment by NiklasBr** [comment] 2021-12-02 08:28
> Exactly. The plan for Pimcore 11 is to run a second command.

Then why are you deprecating when there is no replacement available. That is incompatible with the Symfony way.

> There is no dedicated command for creating thumbnails, since they are stored in the same queue as other messages.

Why?

> Since you already mentioned, that there a lot of entries in your queue, it will take some time to process the whole queue

It never gets consumed when the command is completed even following your instructions to the tee.

> While running this command, does it output anything to the command line?

Once again, see #10714

> Once the queue is empty [...]

The command completes (takes about 7 hours to run through with millions of lines in the log, see #10714), but the queue remains in the table. 

>  And while running this command, please check your queue (messenger_messages table in db). The entries in the table should become fewer.

It does not.

**Comment by mcop1** [comment] 2021-12-09 07:23
Good morning,

sorry for the late repsonse, but since I can´t reproduce the problem and @brusch did the PR, I assigned him to this issue. 

Best regards

**Comment by NiklasBr** [comment] 2021-12-09 12:32
@brusch looking deeper into the logs I wonder if these messages are related:

```log
10:31:06 ERROR     [messenger] Error thrown while handling message Pimcore\Messenger\AssetUpdateTasksMessage. Sending for retry #1 using 1000 ms delay. Error: "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization" ["message" => Pimcore\Messenger\AssetUpdateTasksMessage { …},"class" => "Pimcore\Messenger\AssetUpdateTasksMessage","retryCount" => 1,"delay" => 1000,"error" => "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]
10:31:07 ERROR     [messenger] Error thrown while handling message Pimcore\Messenger\AssetUpdateTasksMessage. Sending for retry #2 using 2000 ms delay. Error: "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization" ["message" => Pimcore\Messenger\AssetUpdateTasksMessage { …},"class" => "Pimcore\Messenger\AssetUpdateTasksMessage","retryCount" => 2,"delay" => 2000,"error" => "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]
10:31:10 ERROR     [messenger] Error thrown while handling message Pimcore\Messenger\AssetUpdateTasksMessage. Sending for retry #3 using 4000 ms delay. Error: "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization" ["message" => Pimcore\Messenger\AssetUpdateTasksMessage { …},"class" => "Pimcore\Messenger\AssetUpdateTasksMessage","retryCount" => 3,"delay" => 4000,"error" => "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]
10:31:14 CRITICAL  [messenger] Error thrown while handling message Pimcore\Messenger\AssetUpdateTasksMessage. Removing from transport after 3 retries. Error: "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization" ["message" => Pimcore\Messenger\AssetUpdateTasksMessage { …},"class" => "Pimcore\Messenger\AssetUpdateTasksMessage","retryCount" => 3,"error" => "Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]

```

**Comment by brusch** [comment] 2022-01-03 14:36
@NiklasBr yes, this seems to be related, because the message cannot be processed. But I'm wondering how this could happen... because there's no such code in Pimcore that would trigger the error `Handling "Pimcore\Messenger\AssetUpdateTasksMessage" failed: Typed static property Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail must not be accessed before initialization`  is it maybe somewhere in your custom code or bundle?

**Comment by NiklasBr** [comment] 2022-01-05 10:14
We have no code adding to or consuming messages from the queue.

**Comment by brusch** [comment] 2022-01-05 10:25
Probably not directly to the queue, maybe in an event handler or so? 
Like I said, there is no such code in `pimcore/pimcore` that accesses `Pimcore\Model\Asset\Image\Thumbnail\Config::$previewThumbnail` and it's not reproducible on our end. 

I'll close this here for now, if there are any new findings, please come back on this issue.

**Closed as completed by brusch** 2022-01-05 10:25 UTC
Labels: Bug
