### ISSUE TITLE
Unable to filter grid by objectbrick field

### ISSUE THREAD

**Issue by brainsbucket** [pimcore/pimcore#2103] opened 2017-10-12 08:13 UTC
Unable to filter grid by objectbrick field.

Pimcore version : 
Version: 5.0.0-RC
Build: 124 (2017-09-22T09:45:49+00:00)

To reproduce this, simply create a class with an objectbrick, then add the object brick field in a grid view.
Try to apply a filter on this column, then the server throw an exception : 
_

> Server threw exception - could not perform action. Please reload the admin interface and try again.
> 
> Timestamp: Thu Oct 12 2017 10:07:35 GMT+0200 (CEST)
> Status: 500 | Internal Server Error
> URL: /admin/object/grid-proxy?classId=2&folderId=2448&xaction=read&_dc=1507795655401
> Method: POST
> Message: An exception occurred while executing 'SELECT object_2.o_id as o_id, `object_2`.`o_type` FROM `object_2`
>  LEFT JOIN `object_brick_query_eleve_2` AS `eleve` ON 1
> AND `eleve`.o_id = `object_2`.o_id WHERE ((o_path = '/personnes/eleves' OR o_path LIKE '/personnes/eleves/%') AND (`eleve`.IFNULL(`is_eleve`, 0) = '0'  AND `eleve`.`id_cf` LIKE '%D52%' ) AND  object_2.o_type IN ('object','folder')) ORDER BY `is_eleve` DESC LIMIT 25':
> 
> SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION eleve.IFNULL does not exist

_

**Comment by weisswurstkanone** [comment] 2017-10-16 11:21
Unable to reproduce this using  a textfield + build 139. Is there anything special about the datatype?

**Comment by weisswurstkanone** [comment] 2017-10-16 12:55
Assuming that we are talking about a checkbox column ...

Fixed in build 140

**Closed by weisswurstkanone** 2017-10-16 12:55 UTC
Labels: Bug
