### ISSUE TITLE
The route "pimcore_admin_asset_getimagethumbnail" does not exist

### ISSUE THREAD

**Issue by mc-supply** [pimcore/pimcore#6533] opened 2020-06-04 22:38 UTC
# Bug Report

Since updating to 6.6.5, images using image editable no longer display in editmode.  Instead, an error 'Uncaught Error: The route to "pimcore_admin_asset_getimagethumbnail" does not exist.' is thrown in the Javascript console.  This even appears on demo.pimcore.fun.

Steps to reproduce: Add any image editable and add an image.

![image](https://user-images.githubusercontent.com/54868988/83819102-40ba4880-a686-11ea-9067-8dd96837dc7e.png)

![image](https://user-images.githubusercontent.com/54868988/83817917-2e8adb00-a683-11ea-9a73-1857d7fbb355.png)

**Comment by jdreesen** [comment] 2020-06-04 22:47
That's strange, because the route is defined here: 
https://github.com/pimcore/pimcore/blob/v6.6.5/bundles/AdminBundle/Controller/Admin/AssetController.php#L1251

**Comment by mc-supply** [comment] 2020-06-04 22:53
Not entirely sure?  It occurs both when adding a new image as well as when displaying existing content within the admin interface.

**Comment by tevesh** [comment] 2020-06-05 07:03
Hi there,
i've encountered the same issue with complex template.
The fix for now is to inject the following lines of code into project's main template (file **.html.php**).
Otherwise i'm not be able to correctly save the page during editing inside backend.
```php
<?php if ($this->editmode) { ?>
        <script src="<?php echo $view->router()->path('fos_js_routing_js', array('callback' => 'fos.Router.setData')) ?>"></script>
<?php
} ?>
```

**Comment by dvesh3** [comment] 2020-06-05 08:03
regression of https://github.com/pimcore/pimcore/pull/6146

**Comment by dvesh3** [comment] 2020-06-05 08:06
@mc-supply can you please confirm if https://github.com/pimcore/pimcore/pull/6534 fixes your issue? thanks!

**Comment by mc-supply** [comment] 2020-06-05 14:45
@dvesh3, I can confirm that fixes it.  Thank you for the quick reply!

**Comment by weisswurstkanone** [comment] 2020-06-05 14:47
PR needs to be merged first

**Comment by mc-supply** [comment] 2020-06-05 14:58
Sounds good.  Thank you for reopening it.

**Comment by dvesh3** [comment] 2020-06-05 16:04
resolved by #6534

**Closed by dvesh3** 2020-06-05 16:04 UTC
Labels: Bug

**Comment by alex-jungwirth** [comment] 2020-06-09 10:17
Is there a workaround for twig atm?
