### ISSUE TITLE
[Bug]: Unable to open the Preview video

### ISSUE THREAD

**Issue by vignesh-happiestminds** [pimcore/pimcore#12833] opened 2022-08-05 13:17 UTC
### Expected behavior

Upload any videos (MP4) under assets.
On click of uploaded video should able to play on the video.

### Actual behavior

> Upload any videos (MP4) under assets.
> On click of uploaded video should able to play on the video. As of now through error.
> 
> "Pimcore\Model\Asset\Video\ImageThumbnail::__toString(): Return value must be of type string, null returned"

All the extension are enabled related on view. 
FFMPEG,imagick,ImageMagick LCMS delegate,WebP

### Steps to reproduce

1.Login as admin
2.Open the assets
3.Upload the videos into assets
4.Click on the video file to preview video

**Comment by kingjia90** [comment] 2022-08-05 18:19
Closing as it seems the same as #12740.
Please let us know and reopen, if it is not the same and/or not fixed by #12697 and happening in Pimcore > 10.4.6

**Comment by birgerstoeckelmann** [comment] 2022-08-09 07:48
This is still an issue in 10.5.2. See above for steps to reproduce.
![Bildschirmfoto 2022-08-09 um 09 46 23](https://user-images.githubusercontent.com/10415259/183594423-805d9a59-a5fb-4f90-b751-23de51c68f82.png)

**Comment by blankse** [comment] 2022-08-09 08:18
@birgerstoeckelmann I created a PR https://github.com/pimcore/pimcore/pull/12849
Can you test it with this changes?

**Comment by birgerstoeckelmann** [comment] 2022-08-09 10:12
> @birgerstoeckelmann I created a PR #12849 Can you test it with this changes?

Thank you @blankse for your quick response - I installed Pimcore from your repo/branch and the exception is gone. But there is another issue coming as response to the thumbnail request /admin/asset/get-video-thumbnail?id=65007&width=265&aspectratio=true&_dc=1660038809153

![Bildschirmfoto 2022-08-09 um 11 54 48](https://user-images.githubusercontent.com/10415259/183621156-655c34b4-18a2-4811-89d4-3c4af74cbbd1.png)

The video preview is generated if the messenger is running (messenger:consume pimcore_core), but is generated several times in the tmp folder. Every video (e.g. temp-file-62f230d9e80d8-18f81ef323ed236c3cbb098fa70674.mp4) has the same size as the original video.

I wonder why Pimcore needs to create a video preview. Why isn't it simply embedded as a HTML5 video tag?

**Comment by blankse** [comment] 2022-08-09 10:41
@birgerstoeckelmann I added a commit which should catch this error. Pimcore should only generate an preview image for the video poster attribute, for the preview in the tree. I don't know why you have this temp files. Do you see something in the log files? (/var/log)

**Comment by birgerstoeckelmann** [comment] 2022-08-09 11:07
@blankse - the exception is gone too, thanks! We use S3 buckets to store the assets. There seems to be an issue with S3 integration (and video previews) here: https://github.com/pimcore/pimcore/issues/5007

When using the default config for pimcore.asset.storage and not S3 the temp files (mp4 and jpg) are all gone after processing the video thumbnail. So I guess it's a problem with Pimcore and S3.

Thank you very much for your support. I hope your work gets merged soon ;-)

**Comment by kingjia90** [comment] 2022-08-17 13:46
Fixed by #12849

**Closed as completed by kingjia90** 2022-08-17 13:46 UTC
Labels: Bug
