### ISSUE TITLE
[Task]: Add more php doc annotations 

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#13577] opened 2022-11-14 17:41 UTC
### Improvement description

Add/change common php doc annotations, see comment https://github.com/pimcore/pimcore/pull/13474#discussion_r1011343631

**Comment by fashxp** [comment] 2022-12-05 10:02
duplicate of https://github.com/pimcore/pimcore/issues/13627

**Closed as completed by fashxp** 2022-12-05 10:02 UTC
Labels: Improvement
