### ISSUE TITLE
[Bug]:  db.inc.php:89 - Warning: Cannot modify header information - headers already sent by 

### ISSUE THREAD

**Issue by leitge** [pimcore/pimcore#11304] opened 2022-01-30 12:51 UTC
### Expected behavior

Trouble-free connection with database

### Actual behavior

In every installation of Pimcore, the following error occurs in the UI under "Database Administration":

Warning: Cannot modify header information - headers already sent by (output started at /opt/bitnami/pimcore/vendor/vrana/adminer/adminer/db.inc.php:89)

The problem exists both in the pimcore/pimcore version and in the Bitnami AWS package (pimcore/admin)

### Steps to reproduce

- Install Bitnami AWS Package by default or install clean (pimcore/pimcore) version manually.
-

**Comment by leitge** [comment] 2022-01-30 12:52
![Bildschirmfoto 2022-01-30 um 01 00 32](https://user-images.githubusercontent.com/98694299/151700444-6d94c979-4a39-4bbf-8004-b60fdc9f9545.png)

**Comment by brusch** [comment] 2022-01-31 14:30
I can't reproduce this on `demo.pimcore.org` - can you please provide more information on that? 
Thanks - closing for now ...

**Comment by leitge** [comment] 2022-01-31 15:03
you can simply install the Bitnami Standard image in the latest version in an AWS environment. 
Without any further configuration.

If needed, I can provide access to an example instance.

**Comment by markvomark** [comment] 2022-02-01 07:17
> I can't reproduce this on `demo.pimcore.org` - can you please provide more information on that? Thanks - closing for now ...

Hi Bernhard, I can reproduce the error/warning with a fresh pimcore project (10.2.8 and 10.2.9). The error is only displayed in the dev environment (on the bottom of the adminer view) , I guess demo.pimcore.com runs in prod.

**Comment by NiklasBr** [comment] 2022-02-07 10:33
We can also reproduce this issue in 10.2.10

**Comment by podarcis** [comment] 2022-02-07 13:55
Can confirm this behavior with Pimcore 10.3.0 (migrated from 10.0.3) with `dev` environment within Pimcore Docker env and `vrana/adminer:v4.8.1`. However, first output happening in different file, but that might not matter.

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/vrana/adminer/adminer/include/design.inc.php:19)
```

**Comment by brusch** [comment] 2022-02-07 15:35
Guys, can you please confirm #11388 fixes the issue for you? Thanks!

**Comment by podarcis** [comment] 2022-02-07 15:42
@brusch Thanks for investigating! The error is gone. However, history of Adminer queries are not recorded (so it seems there is still a problem with the session).

**Comment by brusch** [comment] 2022-02-08 08:13
@podarcis Thanks for your feedback! At least it makes it already better 😉 Maybe someone else could investigate why the history doesn't work. Thanks 😊

**Comment by podarcis** [comment] 2022-02-08 11:57
Seems to be a session related change (HttpFoundation/ HttpKernel) in Symfony as it first appears with 5.4.0-BETA1.

**Comment by podarcis** [comment] 2022-02-08 12:57
I just realized that - despite no error message - Adminer doesn't record my query history even in Pimcore 10.0.3 (and Symfony 5.3.0) in my local dev env (earlier Pimcore Docker image w/ Apache). However, on the production machine (even with an environment inheriting dev) it works fine. So maybe it's an issue with my env.

@NiklasBr @markvomark Can you confirm similar behavior? Does your history (e.g. `SELECT 1` and another `SELECT 2`) work?

**Comment by brusch** [comment] 2022-02-08 12:59
Mine didn't work - also auth failed after wiping cookies, that's the reason for #11398

**Comment by markvomark** [comment] 2022-02-08 14:16
@podarcis: yeah, same behaviour here after the fix. The query history is gone after page reload.  I did some debugging but couldn't find the spot where in adminer the "queries" part of the session got wiped.

Just a guess: the "symfony/http-kernel" had some rather "interesting" changes going from 5.3 to 5.4, regarding the session handling, and there were a couple of fixes with v5.4.2 & .3. I just bumped my local http-kernel version up to 5.4.4 (running on Pimcore 10.2.8) but there's no difference with or without the now reverted fix.

**Comment by neha04** [comment] 2022-02-18 07:18
just updated  instance from 10.2 to 10.3 and getting this error

**Comment by BentBr** [comment] 2022-10-21 16:38
We are having this issue since quite a while now.
So I decided on investigating a bit.

I just installed a brand new (and empty) instance of pimcore skeleton and I do get this error as well.
The only changes I did to this particular installation:

- using docker-compose with mutagen (mutagen-compose)
- using a custom domain (instead of a local port) locally
- no changes to config or src folder

My Version with this issue: **10.5.8**

As far as I understand the error:
May it be caused by the adminer doing some stuff with page's header and AFTER that symfony's session handling kicks in?
So to say the problem is caused by the way how the page is rendered inside pimcore's iframe. Not?

Just as @podarcis  suggests.
> Seems to be a session related change (HttpFoundation/ HttpKernel) in Symfony as it first appears with 5.4.0-BETA1.

Best,
Bent

**Comment by podarcis** [comment] 2022-10-24 09:53
@BentBr Adminer will be moved to a bundle (see #12520) with Pimcore 11 and maybe is even replaced by another database explorer, as Adminer seems to be not maintained anymore, as @NiklasBr mentioned. So maybe it's not worth putting any more effort into the investigation and instead find a better replacement.

**Comment by BentBr** [comment] 2022-10-24 09:57
@podarcis thx for the hint!
In that case I'd suggest to remove the **PR Welcome** tag and add a **Known Issue** one. Or **Won't be solved**.

Best,
Bent

**Comment by brusch** [comment] 2023-05-30 12:37
Obsolete, see #13921

**Closed as completed by brusch** 2023-05-30 12:37 UTC
Labels: Bug, PR Welcome
