### ISSUE TITLE
[Bug]: Error when saving after deleting a fieldcollection in an object

### ISSUE THREAD

**Issue by lisaPolena** [pimcore/pimcore#10926] opened 2021-11-30 09:11 UTC
### Expected behavior

- Delete Fieldcollection in object
- Save and publish object 

### Actual behavior

If you delete a fieldcollection (not the one at the bottom) and then try to click "Save and Publish", an error message comes up.

![image](https://user-images.githubusercontent.com/88780000/144016086-3c1eb603-e3af-4123-be00-e0ca0a4afe29.png)
![image](https://user-images.githubusercontent.com/88780000/144016141-de8aa6a8-6d92-41f8-910f-4aeac2912408.png)
![image](https://user-images.githubusercontent.com/88780000/144016925-bd4d30b5-9d2b-4a87-b97a-ca40873f3223.png)

**The error message does not come if you are fast enough for the object not to be saved automatically.** 
![image](https://user-images.githubusercontent.com/88780000/144017017-1296091c-3fc1-4b48-acde-13368861b419.png)

### Steps to reproduce

**If the problem is recreated in the demo version, all existing fieldcollections must be deleted beforehand, because otherwise another error message comes up, which I have already temporarily solved in my project.**

- Open an object with fieldcollections --> [News Object in Demo Version](https://demo.pimcore.fun/admin/login/deeplink?object_773_object)
- (delete all existing fieldcollections and save the object)
- add some new fieldcollection 
- save the object 
- delete one fieldcollection (not at the bottom) 
- try to save the object
- now you should see the error message 

**The error message does not come if you are fast enough for the object not to be saved automatically.** 
![image](https://user-images.githubusercontent.com/88780000/144017041-e4a082f7-8a3b-4004-b15d-3705c9ec870b.png)
VS.
![image](https://user-images.githubusercontent.com/88780000/144016925-bd4d30b5-9d2b-4a87-b97a-ca40873f3223.png)

**Comment by kingjia90** [comment] 2024-07-04 09:54
Thank you for reporting and your patience

I cannot reproduce it anymore, It seems to me that it was indirectly fixed by https://github.com/pimcore/pimcore/issues/14090 and all related PRs.
Closing, but please re-open if it still occurs.

**Closed as completed by kingjia90** 2024-07-04 09:54 UTC
Labels: Bug, Pimcore:Priority
