### ISSUE TITLE
[Bug]: [Data Objects] ReverseManyToManyObjectRelation no longer supports reverse relations from ManyToOneRelation field

### ISSUE THREAD

**Issue by pimcore-galilee** [pimcore/pimcore#12073] opened 2022-05-09 15:21 UTC
### Expected behavior

[Data Objects] ReverseManyToManyObjectRelation supports reverse relations from ManyToOneRelation field

### Actual behavior

When saving an object which contains a reverse relation to a field which is a ManyToOne Relation, we get the following error message : Validation failed: Invalid non owner object relation to object [1167] :
Timestamp: Mon May 09 2022 17:17:49 GMT+0200 (heure d’été d’Europe centrale)
Status: 422 | Unprocessable Content
URL: /admin/object/save?task=publish
Method: PUT
Message: Validation failed: Invalid non owner object relation to object [4565]
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php:183
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(735): Pimcore\Model\DataObject\Concrete->update(true, Array)
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(711): Pimcore\Model\DataObject\AbstractObject->save(Array)
#2 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1353): Pimcore\Model\DataObject\Concrete->save()
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}

### Steps to reproduce

create a class TEST1
create a class TEST2 with a field myRel of type ManyToOne relation authorizing objects of type TEST1
update class TEST1 and add a reverseManyToManyRelation for class : TEST2 field myRel

Create an instance of TEST1 object.
Create an instance of TEST2 object and put TEST1 object instance in the relation.
Go back to TEST1, reload, and press save and publish

You will get the error message.

**Comment by fashxp** [comment] 2022-05-09 15:50
probably related? https://github.com/pimcore/pimcore/issues/12007

**Comment by pimcore-galilee** [comment] 2022-05-09 16:04
Dear Fashxp, I am not sure at all since class creation works fine 100%.
This is a server response that is throwing the exception.
    protected function allowObjectRelation($object)
    {
        //only relations of owner type are allowed
        $ownerClass = DataObject\ClassDefinition::getByName($this->getOwnerClassName());
        if ($ownerClass instanceof DataObject\ClassDefinition && $object instanceof DataObject\Concrete && $ownerClass->getId() == $object->getClassId()) {
            $fd = $ownerClass->getFieldDefinition($this->getOwnerFieldName());
            if ($fd instanceof DataObject\ClassDefinition\Data\ManyToManyObjectRelation) {
                return true;
            }
        }

        return false;
    }

However, this was actually working previously and I cannot identify why since here ManyToManyObjectRelation is hardcoded and ManyToOne relation is not in this part of the code.
Arnaud.

**Comment by kingjia90** [comment] 2022-05-10 20:43
Narrowed down a little bit, it seems caused by this [load()](https://github.com/pimcore/pimcore/pull/10242/files#diff-2b30de942edd58bfcbda8ca04a54619d65bcb861da86cfe7cd22699570bee8d3R192-R212) in this PR #10242. 
By commeting it out or rename the method, it doesn't throw the error anymore.

**Comment by dvesh3** [comment] 2022-05-24 14:34
Fixed by #12144

**Closed as completed by dvesh3** 2022-05-24 14:34 UTC
Labels: Bug
