### ISSUE TITLE
[Bug]: Having a pretty URL, that matches the key of a document link leads to infinite redirects on multisite environments

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#16420] opened 2024-01-04 18:18 UTC
### Pimcore version

11.1.4

### Steps to reproduce

Create a subsite. Create a link document with the key "test". Create a directory or a page and nest another page with the key "test" below it. Give the nested "test" document the pretty URL "/test".

### Actual Behavior

I am caught in an infinite redirect loop.

### Expected Behavior

Navigating to /test should show the page with the internal path /subsite/subfolderOrPage/test.

**Comment by ghost** [comment] 2024-01-08 08:54
@alexej-d  Thanks for reporting this issue. Does this also occur without subsites?

**Comment by alexej-d** [comment] 2024-01-08 09:20
@wisconaut yeah, the same error occurs without sites. If the resolved page of type link with the key test links to /subsite/subfolderOrPage/test an infinite loop is started. If /test just links to a direct URL or another document, the link is resolved but shouldn't be (calling /test should open /subsite/subfolderOrPage/test not the link in /test).

**Comment by ghost** [comment] 2024-01-08 10:14
@alexej-d Thanks for clarifying. We will have a look at it then.

**Comment by alexej-d** [comment] 2024-01-12 15:08
BTW @wisconaut: I believe [this line](https://github.com/pimcore/pimcore/blob/2b3bb4d10f4c32270589bb37557b932ca38d2a7e/lib/Routing/Dynamic/DocumentRouteHandler.php#L105) needs to be changed.

At the moment, it takes pretty URLs into account too late. Before matching by the system path (like now), the code needs to check if a document with the pretty URL exists first.

**Comment by kingjia90** [comment] 2024-02-26 11:31
Thank you for reporting and  the PR!


Not sure if i did it right, maybe a few screenshot would help to visualize the tree

Do you also have the ⚠️  icon on the Pretty URL? 
![image](https://github.com/pimcore/pimcore/assets/6014195/6ab6493a-896b-4e2e-b7d4-3f3c33e54950)

Is it possible that you missed the warning alert?
![image](https://github.com/pimcore/pimcore/assets/6014195/932dc674-573b-44d0-9f45-d4ebf1837e31)

If a link `/test` exists and set your pretty url as `/test` it will be conflicting 🤔 
The check if is there a pretty url indeed is a little later in the code, i am wondering if there was any known issue/limitation to led to this and the warning https://github.com/pimcore/pimcore/blob/29f878e043048d7b014845f1f400cc8b625732eb/lib/Routing/Dynamic/DocumentRouteHandler.php#L118
I see instead a problem that the pretty url for a multi-site page is absolute and not relative to the sub-site domain itself, that might be the "bug"

**Comment by alexej-d** [comment] 2024-02-26 12:55
@kingjia90 what I mean is that link documents should not be considered in the process of creating pretty URLs. Check the attached video. I should be able to create a correctly functioning pretty URL even if a document of the type link exists with the same key. Apart from that, I also think document folders and snippets are also considered when creating a pretty URL which is wrong as only page documents can have pretty URL…

https://github.com/pimcore/pimcore/assets/3934198/3eb2ae2f-86be-40e4-8a77-734c0d9508b6

**Comment by kingjia90** [comment] 2024-02-26 13:30
Thank you for the videoscreenshot!

I see, there is an alert on `0:27`, there is clearly something unsupported/unwanted on the table 😄 

AFAIK it is/was always prioritizing the document full path over PrettyUrls here
https://github.com/pimcore/pimcore/blob/2ad37be5b110a980418efaebd33b60a9998da7e5/models/Document/Dao.php#L62-L70

**Comment by alexej-d** [comment] 2024-02-26 13:33
@kingjia90 yeah, that alert should not have popped up as the duplicate URL is in fact just an internal path of a link document

**Comment by kingjia90** [comment] 2024-02-26 13:46
Link are not internal though, the right path is `https://demo.pimcore.com/en/Find-and-Buy` and in the video you were typing without `/en` but the error should appear with  `/en/`, at least [here](https://github.com/pimcore/pimcore/blob/2ad37be5b110a980418efaebd33b60a9998da7e5/models/Document/Dao.php#L62) doesn't find as `/Find-and-Buy`

**Comment by alexej-d** [comment] 2024-03-13 07:24
So my PR has been closed @kingjia90 – I take it you are working on this issue instead? :)

**Comment by kingjia90** [comment] 2024-03-13 07:26
Sorry for that, it was unintentional, as soon as i have deleted 11.1, it automatically closed all the open PRs based off that. Fixing these right now

**Comment by kingjia90** [comment] 2024-03-13 07:35
In  your case, you have already deleted the branch though and i can't manually fix the base anymore, could you please recreate the branch and open a new PR? Thank you in advance

**Comment by alexej-d** [comment] 2024-03-13 08:08
@kingjia90 I have reopened my PR here #16776

**Comment by alexej-d** [comment] 2024-07-18 12:31
@kingjia90 anything I can do to help? 😄

**Comment by kingjia90** [comment] 2024-07-18 12:50
Sorry for the wait, this issue went under my radar unfortunately. Thank you for you reminder.

There was something wrong in the PR and conceptually not used as intended as seen in the videoscreenshot (the warning shouldn't be ignored), we should continue from https://github.com/pimcore/pimcore/issues/16420#issuecomment-1964185148

**Comment by mattamon** [comment] 2024-09-02 09:49
@alexej-d 

I checked the issue and the PR now.

Tbh I am not really sure, what you are trying to achieve here and why this is a BUG.

The document link is an element to LINK to a different page, meaning the key of the link is already your pretty URL right?
If you are now taking that exact key to be a pretty URL from a different document, I would expect and endless redirect.
So for me this is even the expected behavior in this case as show in the video. 

This is in general a routing issue, that is not caused by the system, but rather a misunderstanding of Pretty URL and document links.

You should actually never mix up document keys and pretty URLs.

If it is okay for you I would close the issue and the PR since it is more of a wrong usage than a bug.

**Comment by alexej-d** [comment] 2024-09-02 10:14
@mattamon so you are saying that it is by design, that one may load a document of the type "link" or "snippet" when trying to actually load a page by a pretty url?

**Comment by mattamon** [comment] 2024-09-02 12:06
@alexej-d My best guess is that it is intentional yes since the class itself is called DocumentRouteHandler.

Unfortunately we cannot simply change the actual behavior in a bug fix branch anyways because of unknown side-effects. 

If we want to do this, we would need either a minor or a major version and document it properly with the changed behavior.

But my main point was the following: Don't use existing keys as pretty URLs especially if the key is from a document link.

**Comment by alexej-d** [comment] 2024-09-02 15:01
> @alexej-d My best guess is that it is intentional yes since the class itself is called DocumentRouteHandler.
> 
> Unfortunately we cannot simply change the actual behavior in a bug fix branch anyways because of unknown side-effects.
> 
> If we want to do this, we would need either a minor or a major version and document it properly with the changed behavior.
> 
> But my main point was the following: Don't use existing keys as pretty URLs especially if the key is from a document link.

All fair points @mattamon and I agree, that this change should not be made in a bugfix version. It is still pretty unintuitive , as a common user would suspect that pretty urls only affect pages and objects. Links, directories, snippets do not have a way of defining pretty urls (and should not have their own public routes).

Maybe pretty URLs should take precedence before internal keys when resolving public URLs? At least a notice should be added to the documentation, that pretty URLs are affected by internal keys, event when they do not belong to pages or objects.

What do you think?


BTW: My PR seemed to not change anything else but the pretty URL resolution – in my tests everything else still continues to work.

**Comment by mattamon** [comment] 2024-09-03 08:57
@alexej-d 

Since such changes would affect a lot of user, how about starting a discussion here https://github.com/orgs/pimcore/discussions and see what other community members think of that changes?

I will rise this topic internally to get more opinions.

@brusch what's your thoughts on this?

**Comment by alexej-d** [comment] 2024-09-04 08:34
Here is [the discussion](https://github.com/orgs/pimcore/discussions/17561).

**Comment by brusch** [comment] 2024-11-04 08:53
Currently it's intentional and therefore by design that links and snippets have a public route / URI. 
However ... this is just the default behavior, that you can change by config: 

```yaml
pimcore:
    documents:
        type_definitions:
            map:
                snippet:
                    direct_route: false
```

Imho, it always depends on the use-case whether this makes sense or not - therefore we can change that in the config. In general I think we're anyway talking about an edge-case here 😉 

I agree that we could improve error handling 😊 But again, there was a reason for showing only a warning and not stopping the user from doing such things, one I can remember are migration scenarios (moving from one to another path, ...). 

I'm closing this issue for now, we can continue the discussion over there https://github.com/orgs/pimcore/discussions/17561 or even in this thread if it makes sense 😉

**Closed as completed by brusch** 2024-11-04 08:53 UTC
Labels: Bug, Pimcore:ToDo
