### ISSUE TITLE
block inside localized field

### ISSUE THREAD

**Issue by Meni899** [pimcore/pimcore#6976] opened 2020-08-24 09:17 UTC
# Bug Report
I am currently having troubles when I try to use a block inside a localized field. You can see the class structure in the attached 
image 
![Class](https://user-images.githubusercontent.com/66207443/91026417-0021f980-e5fb-11ea-986e-8bff7d34b2e7.PNG)

### Actual behavior
If I am creating a new blockitem inside the localized field and save it everything seems to work but as soon as I reload pimcore and try to save the Object again the backend instantly goes into maintenance mode.

### Steps to reproduce
create class -> create object -> add block item -> save -> reload pimcore -> try to save again

**Comment by MercuryKojo** [comment] 2020-08-25 07:53
After some testing it happens with links inside of blocks inside of localized fields

important step in reproduction is to fill the link with some dummy data -> then save -> then reload the complete pimcore interface -> then hit save again

class Definition:
`{
    "id": "Test",
    "description": "",
    "parentClass": "",
    "implementsInterfaces": "",
    "listingParentClass": "",
    "useTraits": "",
    "listingUseTraits": "",
    "allowInherit": false,
    "allowVariants": null,
    "showVariants": false,
    "layoutDefinitions": {
        "fieldtype": "panel",
        "labelWidth": 100,
        "layout": null,
        "border": false,
        "name": "pimcore_root",
        "type": null,
        "region": null,
        "title": null,
        "width": null,
        "height": null,
        "collapsible": false,
        "collapsed": false,
        "bodyStyle": null,
        "datatype": "layout",
        "permissions": null,
        "childs": [
            {
                "fieldtype": "panel",
                "labelWidth": 100,
                "layout": null,
                "border": false,
                "name": "Navigation",
                "type": null,
                "region": null,
                "title": "Navigation",
                "width": null,
                "height": null,
                "collapsible": false,
                "collapsed": false,
                "bodyStyle": "",
                "datatype": "layout",
                "permissions": null,
                "childs": [
                    {
                        "fieldtype": "localizedfields",
                        "phpdocType": "\\Pimcore\\Model\\DataObject\\Localizedfield",
                        "childs": [
                            {
                                "fieldtype": "block",
                                "lazyLoading": false,
                                "disallowAddRemove": false,
                                "disallowReorder": false,
                                "collapsible": false,
                                "collapsed": false,
                                "maxItems": null,
                                "columnType": "longtext",
                                "styleElement": "",
                                "phpdocType": "\\Pimcore\\Model\\DataObject\\Data\\BlockElement[][]",
                                "childs": [
                                    {
                                        "fieldtype": "link",
                                        "queryColumnType": "text",
                                        "columnType": "text",
                                        "phpdocType": "\\Pimcore\\Model\\DataObject\\Data\\Link",
                                        "name": "metaNavigationLink",
                                        "title": "metaNavigationLink",
                                        "tooltip": "",
                                        "mandatory": false,
                                        "noteditable": false,
                                        "index": false,
                                        "locked": false,
                                        "style": "",
                                        "permissions": null,
                                        "datatype": "data",
                                        "relationType": false,
                                        "invisible": false,
                                        "visibleGridView": false,
                                        "visibleSearch": false
                                    }
                                ],
                                "layout": null,
                                "fieldDefinitionsCache": null,
                                "name": "metaNavigation",
                                "title": "metaNavigation",
                                "tooltip": "",
                                "mandatory": false,
                                "noteditable": false,
                                "index": false,
                                "locked": false,
                                "style": "",
                                "permissions": null,
                                "datatype": "data",
                                "relationType": false,
                                "invisible": false,
                                "visibleGridView": false,
                                "visibleSearch": false
                            }
                        ],
                        "name": "localizedfields",
                        "region": null,
                        "layout": null,
                        "title": "",
                        "width": "",
                        "height": "",
                        "maxTabs": null,
                        "labelWidth": null,
                        "border": false,
                        "provideSplitView": false,
                        "tabPosition": null,
                        "hideLabelsWhenTabsReached": null,
                        "fieldDefinitionsCache": null,
                        "tooltip": "",
                        "mandatory": false,
                        "noteditable": false,
                        "index": null,
                        "locked": false,
                        "style": "",
                        "permissions": null,
                        "datatype": "data",
                        "relationType": false,
                        "invisible": false,
                        "visibleGridView": true,
                        "visibleSearch": true
                    }
                ],
                "locked": false,
                "icon": ""
            }
        ],
        "locked": false,
        "icon": null
    },
    "icon": "",
    "previewUrl": "",
    "group": "",
    "showAppLoggerTab": false,
    "linkGeneratorReference": "",
    "compositeIndices": [],
    "generateTypeDeclarations": false,
    "showFieldLookup": false,
    "propertyVisibility": {
        "grid": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        },
        "search": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        }
    },
    "enableGridLocking": false
}`

**Comment by weisswurstkanone** [comment] 2020-08-28 08:16
We will come up with a generic approach.

Discussion points:
* https://github.com/pimcore/pimcore/pull/5799
* https://github.com/pimcore/pimcore/pull/6236

**Comment by palazzetti** [comment] 2020-09-02 16:02
Hi, this issue is blocking for our usage of the PIM. There is an estimated release date for this fix? We tried to checkout branch "6.1" where PR were merged but unfortunatly the patch were not applied.

**Comment by brusch** [comment] 2020-09-02 18:23
Not really, we're kind of a in a deadlock with this issue, so do not expect a fix before 6.8, because we cannot fix it without breaking with BC.

**Comment by palazzetti** [comment] 2020-09-03 08:52
> Not really, we're kind of a in a deadlock with this issue, so do not expect a fix before 6.8, because we cannot fix it without breaking with BC.

Is there anything we could do to mitigate the problem? like falling back to a specific version of the PIM or, in extremis, modify ourself the code.

**Comment by weisswurstkanone** [comment] 2020-09-03 14:30
https://github.com/pimcore/pimcore/pull/7051 may resolve this

**Closed** 2020-09-14 07:54 UTC
Labels: Bug
