### ISSUE TITLE
[Bug]: Many-To-One Relation long label breaks layout

### ISSUE THREAD

**Issue by kaurov** [pimcore/pimcore#11790] opened 2022-03-28 15:41 UTC
### Expected behavior

DataObject field of type Many-To-One Relation would be limited to the width from its configuration

### Actual behavior

If user puts the long name in field of Many-To-One Relation type, then the input folm length is increased to fit the name length and design is broken

### Steps to reproduce

1. create a field of Many-To-One Relation type in any class.
2. set the field with = 200 in its settings, save the class
3. create an data object of this class
4. grag-n-drop the object with the long name like '/Print/2022//some/long/name/located/deaplyintree/hereSomeGoodNameMasterProduct_copy_1' to created Many-To-One Relation field

**Comment by mattamon** [comment] 2024-09-17 07:10
@kaurov thanks for the ticket and sorry for the late reply. Currently on Pimcore 11.x I cannot reproduce it anymore.
Probably should also be in the admin-classic-ui. Closing the ticket.

**Closed as completed by mattamon** 2024-09-17 07:10 UTC
Labels: Bug, PR Welcome
