### ISSUE TITLE
[Bug]: Object with special character as first letter can't be found via "Show in tree". Object is not listed in the created directory.

### ISSUE THREAD

**Issue by eciosk** [pimcore/pimcore#12051] opened 2022-05-06 11:05 UTC
### Expected behavior

1. When clicking "Show in tree" button the current object is highlighted in the tree.
2. Opening directory with objects show object on list.

### Actual behavior

1. After clicking "Show in tree" the object is not found and view shows the last page of all objects in the tree.
2. Missing object in the list of all objects from particular directory.

### Steps to reproduce

1. It is required to have at least two pages of objects.
2. Create object with any of the following first letter 'Ć', 'Ź', 'Ż', 'Ó', 'Ł' e.g. 'Ćtest object'. Save object. Refresh page. Object has to be located in directory.
3. Click "Show in tree" button.
4. Open the directory and try to find created object on the list.

**Comment by kingjia90** [comment] 2022-05-10 15:02
May i ask you which version of Pimcore are you using? I am unable to reproduce it on the latest.
I guess it is more related to permissions (that got recently fixed), it doesn't seem caused by the special characters.

Just to double-check:
- could you manually navigate to the location of that file in the folder tree view? 
- are the `list` permission enabled (for that file or any parent folder)? it could be that the file only has `view` permission

**Comment by eciosk** [comment] 2022-05-12 18:43
@kingjia90 
I use version 10.3.2.

Before I created the ticked I also tried to duplicate this behaviour on official Pimcore demo (https://demo.pimcore.com/admin/login?perspective=PIM) on the latest version but there was another problem. I can't even  show the list of objects from any directory. Tried this on many different browsers (also on private cart). On Pimcore demo "Show in tree" also doesn't work properly. Answering your question:
    - yes I can
    - I use admin user so I got list permission. Without  list permission it's not possible to show any object in the tree.
    
Alternatively, may I ask you to fix the demo? Then I can try to duplicate the behaviour and confirm if it still occur.

Thanks in advance.

**Comment by kingjia90** [comment] 2022-05-13 08:44
@eciosk Thank you for the info! Knowing that, then I would say that is not directly related to the changes that i am aware of.

The demo problem(#12134) you mention is known and will be fixed ASAP. 
In the meantime, it should work with the [Default ](https://demo.pimcore.com/admin/login?perspective=default)perspective, as the demo problem is only affecting the custom view in custom perspectives.  Please give it a try and let us know.

In the meantime, i will also try locally to see if i can reproduce it in 10.3.2.

**Comment by kingjia90** [comment] 2022-05-16 11:29
I've tried on 10.3.2 and still cannot reproduce it. 

Could you please click on the `Info` button (near Show in tree) and check the `path` there actually exists and is valid?

**Comment by kingjia90** [comment] 2022-05-23 15:14
@eciosk Just a kind reminder, do you have any updates on this? In case, you can also use the [demo.pimcore.fun ](https://demo.pimcore.fun/admin) (user/pass are ~both `admin`~  `admin` /`demo`), it's working there as the problem you also mentioned in the custom views is in progress and affects only `.com` Enterprise one.

**Comment by kingjia90** [comment] 2022-05-30 13:07
@eciosk Do you have any update?

**Comment by eciosk** [comment] 2022-05-31 09:20
@kingjia90 Sorry that I didn't answer.
I tried once more to duplicate the problem on the demo and amazingly everything works properly. In a few days I am going to update Pimcore in my project to the 10.4.2 version, so after the update I will check if it resolve the problem and then give you some feedback.

BTW. I tried to log in demo.pimcore.fun with _admin_ and it doesn't work.

**Comment by kingjia90** [comment] 2022-05-31 09:28
No problem, i am glad that it all works. I am closing the issue for the moment, if there's anything related, feel free to re-open or open a new one by referencing this.

I am sorry, my bad, the demo.pimcore.fun admin's password is `demo` and not `admin` as i previously commented.

**Closed as completed by kingjia90** 2022-05-31 09:28 UTC
Labels: Bug
