### ISSUE TITLE
Option to grant notification sending right not visible for admins in Pimcore 6.6.10

### ISSUE THREAD

**Issue by ascheererEberbach** [pimcore/pimcore#6979] opened 2020-08-24 10:00 UTC
**Bug Report**
Admins in Pimcore 6.6.10 (PHP Version 7.4.9) have no option to grant the right to send notifications to normal users, despite of release notes stating the opposite. Every project memeber with admin rights is experiencing this issue, despite of having this right in other projects with the same pimcore version. 

**Expected behavior**
When I log in with admin rights, I should be able to grant the right to send notifications to other, normal users. 
There should be a checkbox to grant the right to send notifications in the user-permissions and in the role-permissions, or at least in one of them. In other projects with the same version, the checkbox is there.

**Actual behavior**
In one particular project, there is not checkbox to grant notification rights. But there are checkboxes created by (non-custom) bundles that are used in this project, not in the others (at least CMF isn't used there). Perhaps a bundle is causing the issue.

Here yo can see an (edited) screenshot of the rights I can grant as admin. I edited the image because I couldn't get the checkboxes on one page.. I didn't cut any parts away.
![Screenshot Adminrightst](https://user-images.githubusercontent.com/51356005/91030440-77f22300-e5ff-11ea-9dab-f22ee7133037.png)

**Steps to reproduce**
Install the following (non-custom) bundles and try to grant admin rights. Is the checkbox visble?

- AdvancedObjectSearchBundle 3.1.5
- CustomerManagementFramework 2.5.6
- EcommerceFrameworkBundle 6.6.10
- NumberSequenceGenerator
- ObjectMergerBundle 2.4.4 

Thanks in advance
Alice

**Comment by dvesh3** [comment] 2020-09-23 07:55
Sorry, not able to reproduce on latest version 6.7.2 with following bundles:
- AdvancedObjectSearchBundle 3.1.7
- CustomerManagementFramework 2.5.7
- EcommerceFrameworkBundle
- NumberSequenceGenerator 1.0.3
- ObjectMergerBundle 2.4.5

It could be something went wrong with auto migrations(responsible for adding notification entries to `users_permission_definitions ` table) during update. you can try to execute this migration manually https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Migrations/Version20181214145532.php#L41

**Comment by ascheererEberbach** [comment] 2020-09-29 07:28
@dvesh3 Thanks a lot for the hints and the link to the migration code. All migrations where up-to-date ('No migrations to execute'), but after executing the SQL-code you linked, we had the possibility to add notification-rights in the backend. 
I left the category empty, as using a category leads to a new area in the user-options:

 "INSERT IGNORE INTO users_permission_definitions VALUES ('notifications'), **('')**;"

**Comment by dvesh3** [comment] 2020-09-29 08:52
> I left the category empty, as using a category leads to a new area in the user-options:

> "INSERT` IGNORE INTO users_permission_definitions VALUES ('notifications'), ('');"

@ascheererEberbach Ohh wait! this is a bug: We added a category column to `users_permission_definitions` https://github.com/pimcore/pimcore/blob/f5b02e99a581eaeef90b4122de94357a5d873d18/bundles/CoreBundle/Migrations/Version20190729085052.php#L19 and didn't adapt older migrations so when i manually tried to downgrade -> upgrade the migration for notifications, it failed with error message:
![image](https://user-images.githubusercontent.com/5137917/94533962-26f9ce00-0240-11eb-82db-21520ae23e2d.png)

So we need a fix for all  `users_permission_definitions` migrations. Thanks a lot for your findings :)

**Comment by brusch** [comment] 2020-09-29 12:13
Fixed by #7190

**Closed by brusch** 2020-09-29 12:13 UTC
Labels: Bug
