### ISSUE TITLE
Custom reports small problems

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#587] opened 2016-05-11 19:16 UTC
We noticed some small problems on custom reports on Chrome (last version on Windows 8) with the last nighlty build (11 may 2016):
- The pie chart when renderer display a small scrollbar under the legend (see image below please)
- When editing a custom reports, on the list (dynamicaly actualised depending the request parameters) there is an ordering up/down button. They seems not to be saved/used in the rendered reports (orde of the FROM elements seems to be taken). Maybe those up/down arrow should be removed or be corrected to work as intented ?
- When assigning a custom report in the main menu, clicking on it open the Marketing Reports tab as espected but don't open directly the custom reports after (so we need to select it again...)

Appart from this it seems to work very well, Thanks a lot for having corrected other problems of custom reports wich was on the RC2.
![scrollbar_should_not_be_here](https://cloud.githubusercontent.com/assets/9025839/15193308/708e79e8-17bd-11e6-9975-664e75e36756.png)

**Comment by weisswurstkanone** [comment] 2016-05-12 08:16
#2 and #3 fixed in build 3776, unable to reproduce #1 

![image](https://cloud.githubusercontent.com/assets/6142086/15208215/99765624-182a-11e6-912a-e3e096edfab7.png)

**Comment by Yivan** [comment] 2016-05-12 20:34
It is only on Chrome (not Firefox). Windows 8. Browsers last version.
I manage to recreate the problem on the online demo instance of Pimcore.
I have keep my try on the demo, but maybe it will be reseted the time you check it.
So fast test is:

Create a new custom report (whatever name)
SELECT: count(*), date
FROM: object_2
WHERE: (empty)
GROUPBY: date

And chose "Pie Chart":
Label: date
Data: count(*)

Hope it helps! Thanks.

**Comment by Yivan** [comment] 2016-05-12 20:34
I forgot the screenshot from the online demo:
![website_demo](https://cloud.githubusercontent.com/assets/9025839/15229527/bd24387c-1891-11e6-8db1-d84b155a6662.png)

**Comment by weisswurstkanone** [comment] 2016-05-13 06:25
Weird, this is what I see with Chrome Version 50.0.2661.94 m

![image](https://cloud.githubusercontent.com/assets/6142086/15239604/37fa07c8-18e4-11e6-92f2-c56a0d2c2c9b.png)

**Comment by Yivan** [comment] 2016-05-13 11:02
Yes, i think this is just some display bug from browsers maybe.
If it can help, my setup is:

- Chrome Version 50.0.2661.102 m
- Windows 8.1
- Résolution: 1920x1080 (but when changing resolution problem is always present, resizing browser problem is always present)
- Installed extension (only Google extension are activated, so problem don't come from here i think)

![extensions](https://cloud.githubusercontent.com/assets/9025839/15245986/1d06e988-190a-11e6-8890-c5af7e00829b.png)

Here is a copy of debug chrome:
![debug_console](https://cloud.githubusercontent.com/assets/9025839/15246129/d9c439d6-190a-11e6-9e0a-640f8dffd2da.png)

Ask me if you need more informations, thanks.

**Comment by fashxp** [comment] 2018-03-13 19:48
if this problem still occurs, please create a new issue

**Closed by fashxp** 2018-03-13 19:48 UTC
