### ISSUE TITLE
Option "Open in new tab" for object folders

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#3581] opened 2018-11-07 16:15 UTC
One use case for this is analysis productivity. When I have a folder with a lot of objects and filters I may wish to open more than one time the folder and apply different filters in order to see different lists of object and do any conclusion or analysis. It's like in any IDE. Same folder may be opened from multiple windows because it is practical.

How I like it implemented: on folder click in the objects tree it opens in a new tab the folder, if clicked again the opened tab is focused (as is now). With right click on the folder I am given option "Open in new tab" - opens the folder in new tab. If now i switch to any other object tab and then I click the folder from the tree again, than it shows the tab for that folder, which I was lastly looking.

Consider implementing it for all/other types of folders or even other entities I am doing request for the objects folders as my personal most practical need.

**Comment by kanevbg** [comment] 2018-11-17 14:35
Today I experienced the need for multi tab future for the "application logger". It makes sense to be abstract algorithm having allowed by default all things to be opened many times, than with simple number field a count limit may be implemented, used mostly to limit to one tab if needed for something.

**Comment by dpfaffenbauer** [comment] 2018-11-18 15:16
I am not really sure about that, a lot of my customers don't use the tab-bar much, they open everything thru the tree or the menu, having the ability to open the same thing multiple times will end them up having thousands of tabs open

**Comment by brusch** [comment] 2019-02-06 16:11
Let's see if others would like to see this feature as well - please vote! 
However I'm closing this issue for now as I currently don't see the need for this or better to say I see more risks like browser crashes caused by to many open tabs, outdated content, ...

**Closed by brusch** 2019-02-06 16:11 UTC
