### ISSUE TITLE
[Bug]: versions 500 error when field collection is removed

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#13749] opened 2022-12-06 15:06 UTC
### Expected behavior

After removing a field collection it should still be possible to view the versions of a data object.

### Actual behavior

A 500 internal server error is thrown.
![Versions_500_internal_server_error](https://user-images.githubusercontent.com/24292941/205946954-98411493-02a2-4ffb-b2c3-2ac119020660.png)

### Steps to reproduce

- Create two field collections.
  - Add a text input field to each of them.
- Create a class definition.
  - Add a field collection field and link the created field collections.
- Create a new data object of the new class definition type.
  - Add at least one of each field collection and enter a value in the text input field.
  - Save the data object.
- Remove one of the field collections from the field collection field in the class definition.
- Remove the field collection itself via the field collection editor.
- Open the latest version of the data object.

**Comment by robertSt7** [comment] 2022-12-22 16:12
@kjkooistra-youwe Thanks for reporting the bug. Unfortunately i can't reproduce it. Could you please provide more information, like which Pimcore version are you using? Thanks

**Comment by kjkooistra-youwe** [comment] 2022-12-23 07:47
@robertSt7 I reproduced this on the demo environment.

I actually forgot one possible step, which is to remove the field collection from the data object itself. Then the latest version works, but the one before doesn't, since it still contains the field collection which no longer exists. Might that be why you couldn't reproduce it?

https://user-images.githubusercontent.com/24292941/209297324-a781609f-7810-4947-a56d-faaa5add82f0.mov

**Comment by robertSt7** [comment] 2023-01-03 14:48
fixed by https://github.com/pimcore/pimcore/pull/13957

**Closed as completed by robertSt7** 2023-01-03 14:48 UTC
Labels: Bug
