### ISSUE TITLE
Upload asset error

### ISSUE THREAD

**Issue by danielczestki** [pimcore/pimcore#9272] opened 2021-05-28 16:36 UTC
I’m uploading my assets and this error keeps appearing every bulk upload.

Transaction commit failed because the transaction has been marked for rollback only.

I have a choice of Details and OK.

When I checked details, it said this.

{“success”:false,“message”:“Transaction commit failed because the transaction has been marked for rollback only.”}

Sometimes, not all assets are uploaded so have to redo them again.

**Comment by brusch** [comment] 2021-05-31 08:18
@danielczestki 
Can you reproduce this here as well? 
Admin-URL (dev): https://x.pimcore.fun/admin/
Username: admin
Password: demo

**Comment by brusch** [comment] 2021-06-04 09:26
@danielczestki 🏓

**Comment by fashxp** [comment] 2023-12-20 10:10
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed as not planned by fashxp** 2023-12-20 10:10 UTC
Labels: PR Welcome
