### ISSUE TITLE
[Bug]: The row of a data component type "table" is shorter then the table width

### ISSUE THREAD

**Issue by Geni2** [pimcore/pimcore#17710] opened 2024-10-10 12:56 UTC
### Pimcore version

11.3.0

### Steps to reproduce

Open classes from the Data Object and in an existing layout panel create a data component>Structured>Table you can specify a width of 800 for example. See the image below.
![create a table](https://github.com/user-attachments/assets/56a967cc-b52d-4936-8fe6-3b5e5e0311e8)

### Actual Behavior

The row doesn't get the table width in this case 800px but gets a width of 40px. See the image.
![dataComponent Table](https://github.com/user-attachments/assets/e8c0e9e0-0a2c-4f09-9da4-af4b632c6156)

### Expected Behavior

In the previous version 10.6.9 this wasn't the case. The raw was as long as the table was 
![table pimcore 10 6 9](https://github.com/user-attachments/assets/4ae67a2f-3f94-42c9-8aa4-36a4b3b3a082)

**Comment by blankse** [comment] 2024-10-14 12:56
@Geni2 Duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/688 ?

**Comment by Geni2** [comment] 2024-10-14 13:01
Thanks @blankse for letting me know, we can close it then.

**Closed as completed** 2024-10-14 13:01 UTC
Labels: Bug
