### ISSUE TITLE
[Bug]: Data-importer: Import many-to-many relations not possible.

### ISSUE THREAD

**Issue by Timonwatteny** [pimcore/pimcore#9939] opened 2021-08-04 09:58 UTC
### Expected behavior

Import an array of dataobjects on a many-to-many field via the data-importer creates the relation for every element provided. 

Transformation result is of type dataObjectArray and there is no option to iterate over the array so I expect the load dataobject to do this. 
![Screenshot 2021-08-04 at 11 52 48](https://user-images.githubusercontent.com/31765954/128161488-327ee7fb-719e-4bad-b4ca-17f28020ea92.png)

### Actual behavior

Nothing happens, no relations are added to the dataobject. 

Values with only one dataobject are accepted: 
![Screenshot 2021-08-04 at 12 00 15](https://user-images.githubusercontent.com/31765954/128162404-8118df72-774c-44d4-a302-66979603c876.png)

### Steps to reproduce

- Create a class with a many-to-many relation to another class 
- Create a data objects importer configuration in data hub. 
- Explode a value on a delimiter (; in this case) to have an array of dataobjects in the transformation pipeline
- Load dataobject in the next step of the transformation pipeline (type = dataObjectArray)
- In the data target add the many-to-many field. 
- Run the import.

**Comment by dvesh3** [comment] 2021-08-05 08:07
duplicate of https://github.com/pimcore/data-importer/issues/80

**Closed as completed by dvesh3** 2021-08-05 08:07 UTC
Labels: Bug
