### ISSUE TITLE
Custom Login Background Image is not saved

### ISSUE THREAD

**Issue by mittererr** [pimcore/pimcore#9125] opened 2021-05-15 13:46 UTC
The Custom Login Background Image is not saved when clicking to save button in system setting. 
There was a pretty similar issue in 6.9.2 -> see #8848

**Comment by dvesh3** [comment] 2021-05-17 08:01
@mittererr you mean using svg file as background image on Pimcore X? sorry, it works for me as mime type is detected correctly. 
Could you please share more information or exacts steps to reproduce the issue? thanks!

**Comment by mittererr** [comment] 2021-05-17 08:53
I'm talking about JPG background image:

<img width="1277" alt="grafik" src="https://user-images.githubusercontent.com/23724310/118461383-ea5ee200-b6fd-11eb-97eb-1645f4e3b11d.png">

When I click to save, everything seems to be OK. Next time visiting System settings the field is empty again. 

Tested on Pimcore X, Chrome and FireFox, Mac iOS

**Comment by dvesh3** [comment] 2021-05-19 08:58
Fixed by #9130

**Closed as completed by dvesh3** 2021-05-19 08:58 UTC
Labels: Bug
