### ISSUE TITLE
[Custom Views] Errors are thrown if user logs in with insufficient rights

### ISSUE THREAD

**Issue by cmaerz** [pimcore/pimcore#4881] opened 2019-08-22 14:28 UTC
# Bug Report
I got about 10 custom views in a project. Since a recent update users that do not have the rights to view a custom view get an error popup. 

### Expected behavior
No Error Popup.

### Actual behavior
One Error Popup for each custom view with no rights.

**Comment by dvesh3** [comment] 2019-09-10 09:35
Cannot Reproduce!!....could you please try to reproduce it on demo? https://demo-basic.pimcore.org/admin

**Comment by cmaerz** [comment] 2019-09-10 09:40
Pretty sure it's not possible to reproduce on Demo as I can't edit the `var/config/customviews.php` file.

**Comment by dvesh3** [comment] 2019-09-10 09:42
you are right! It would be great if you can share steps to reproduce it.

**Comment by cmaerz** [comment] 2019-09-10 09:48
Just give me a few minutes but I narrowed it down to this commits:
https://github.com/pimcore/pimcore/commit/6d3b819f53d9261a010887d1b5ade2c44477956c
https://github.com/pimcore/pimcore/commit/8fd4bc3b82b8147687c67b16278229a4809c5023

I don't have that problems on 6.1.1 but when it update to 6.1.2 the errors come up.


I got a few customs views like this:
```<?php 

return [
    "views" => [
        [
            "name" => "Neuigkeiten",
            "condition" => "",
            "icon" => "/bundles/pimcoreadmin/img/flat-white-icons/news.svg",
            "id" => "1",
            "rootfolder" => "/neuigkeiten",
            "showroot" => "1",
            "classes" => "1"
        ],
        [
            "name" => "Bekanntmachungen",
            "condition" => "",
            "icon" => "/bundles/pimcoreadmin/img/flat-white-icons/globe.svg",
            "id" => "20",
            "rootfolder" => "/bekanntmachungen",
            "showroot" => "1",
            "classes" => "18"
        ]
]
?>
```

But if a user doesn't have access to `/neuigkeiten` or `/bekanntmachungen` a error popup gots thrown that he has no access. Even it shouldn't even matter to him.

**Comment by dvesh3** [comment] 2019-09-10 10:01
Sorry, works for me. let's wait for others to report it :)

**Comment by cmaerz** [comment] 2019-09-10 10:15
What Version you are on? I guess I only tested it on 6.1.2 - Will test on the newest one too

**Comment by dvesh3** [comment] 2019-09-10 11:14
Yes, please try on latest version. I'm on dev-master!

**Comment by fashxp** [comment] 2023-12-19 14:05
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed by fashxp** 2023-12-19 14:05 UTC
Labels: PR Welcome
