### ISSUE TITLE
"Call to undefined method getInherited" when saving a document a second time

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#7760] opened 2020-12-15 14:38 UTC
I have the following error in multiple projects with Pimcore 6.8.5.

### Steps to reproduce

1. open a document
2. save the document
3. repeat step 2

### Expected behavior

The document is saved after step 2 and after step 3.

### Actual behavior

The document is saved after step 2 but after step 3 an error message appears. I have to close the document and open it again, then saving the document works again but don't work after a second attempt to save.

```
Status: 500 | Internal Server Error
URL: /admin/page/save?task=publish
Method: PUT
Message: Call to undefined method getInherited in class Pimcore\Model\DataObject\ConfigWebsite
Trace: 
in /web/web12545/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:251
#0 /web/web12545/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(1338): Pimcore\Model\AbstractModel->__call('getInherited', Array)
#1 /web/web12545/vendor/pimcore/pimcore/models/Document/PageSnippet.php(128): Pimcore\Model\DataObject\AbstractObject->__call('getInherited', Array)
#2 /web/web12545/vendor/pimcore/pimcore/models/Document.php(424): Pimcore\Model\Document\PageSnippet->update(Array)
#3 /web/web12545/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php(184): Pimcore\Model\Document->save()
#4 /web/web12545/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#5 /web/web12545/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /web/web12545/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /web/web12545/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
```
I want to note that `ConfigWebsite` represents a data object in our projects which is used fairly a lot within these projects. This makes it probably a bit difficult for you to reproduce the issue. What I found out:

In /vendor/pimcore/pimcore/models/Document/PageSnippet.php there is a method `update($params = [])`. In this method you can find the following block:

```
      if (is_array($this->getEditables()) and count($this->getEditables()) > 0) {
            foreach ($this->getEditables() as $name => $editable) {
                if (!$editable->getInherited()) {
                    $editable->setDao(null);
                    $editable->setDocumentId($this->getId());
                    $editable->save();
                }
            }
        }
```

If I change the following line:

`if (!$editable->getInherited()) {`

to:

`if (method_exists($editable, 'getInherited') && !$editable->getInherited()) {`

… the problem does no longer exist. But I don't know if this change has some other unwanted consequences.

So the main question is: Should it be possible at all that there is a $editable within the foreach loop without a getInherited method? If no, then there is probably a bug somewhere because it happens that the getInherited method does not exist for every $editable. But I really have no idea what exactly in our project is triggering this. Please let me know if I can somehow help to find the culprit.

**Comment by dvesh3** [comment] 2020-12-18 11:22
Hi @cadeyrn yes, all document editables should be able to call `getInherited()`, as it is defined in base class Pimcore\Model\Document\Editable. It seems completely wrong that it is called on your DataObject instance. Please check your logs or perform debugging on PageSnippet::update(). thanks!

**Comment by cadeyrn** [comment] 2021-01-07 15:12
I did some further investigation.

Most $editables are of the expected type, for example:

```
$name: string(24) "content:1.mediaTextRatio"
get_class(): string(38) "Pimcore\Model\Document\Editable\Select"
```

… other classes from Pimcore\Model\Document\Editable.

But some $editables are unexpected:

```
$name: string(16) "content:1.layout"
get_class(): string(38) "Pimcore\Model\DataObject\ConfigWebsite"

$name: string(19) "content:1.mediaType"
get_class(): string(36) "Pimcore\Model\DataObject\ConfigHotel"

$name: string(30) "content:1.mediaBackgroundColor"
get_class(): string(36) "Pimcore\Model\DataObject\ConfigHotel"

$name: string(17) "content:1.overlay"
get_class(): string(38) "Pimcore\Model\DataObject\ConfigWebsite"
```

The documents have the following areablock defined:

```
{{ pimcore_areablock('content', {
  'globalParams': {
    'website': website,
    'hotel': hotel,
    'language': language
  }
}) }}
```

Once I remove `website` and `hotel` from the `globalParams` the error disappears.

`website` and `hotel` are defined in the `FrontendController`:

```
$websiteConfig = Config::getWebsiteConfig();
$this->params['website'] = DataObject\ConfigWebsite::getById($websiteConfig->get('website')->getId());
$this->params['hotel'] = DataObject\ConfigHotel::getById($websiteConfig->get('hotel')->getId());
```

($this->params contains the parameters for the view, it's returned in the actions of every controller)

Can someone reproduce this issue when using `globalParams`? Or does anyone has an idea why the first save always works and it's only a problem from the second save of the document?

**Comment by MosiiAUT** [comment] 2021-01-11 12:58
Hello! I'm having the exact same problem (quite same scenario with a config for the site).
But as @cadeyrn mentioned, it is quite hard to reproduce. I thought it had something to do with my project related `templateVars` but i also had the Config-Object in the `globalParams `of my editables.

 After i removed the config from my `templateVars `and `globalParams `i used your little hack `if (method_exists($editable, 'getInherited') && !$editable->getInherited()) {` so i could save my documents again.

**Comment by blankse** [comment] 2021-03-08 15:39
@dvesh3 I have the same problem with an email editable. Before the save its an \Pimcore\Model\Document\Editable\Input. After the save its an \Pimcore\Model\Element\ElementDescriptor object. So the second save has this error.

I debugged it. It came from the Version::marshalData() method. This line also change the source $data object:
```
$newData = $copier->copy($data);
```

**Comment by blankse** [comment] 2021-03-08 17:47
@dvesh3 @MosiiAUT @cadeyrn I digged further and found the bug in the DeepCopy dependency. I created an PR there:
https://github.com/myclabs/DeepCopy/pull/164
Could you test the new approach?

**Comment by blankse** [comment] 2021-03-09 07:06
Ok I think its the wrong approach. We should look why the original editable object get lost, so deep copy find other object with this hashes.

**Comment by blankse** [comment] 2021-03-09 09:31
@dvesh3 @MosiiAUT @cadeyrn I created a PR https://github.com/pimcore/pimcore/pull/8363
This should fix it now.

**Comment by brusch** [comment] 2021-03-09 11:17
Fixed by #8363

**Comment by blankse** [comment] 2021-03-11 10:07
@brusch Can you open this again? I will look again if I had time.

**Comment by brusch** [comment] 2021-03-11 10:13
@blankse sure, thanks!

**Comment by dvesh3** [comment] 2021-03-11 10:51
possibly fixed by https://github.com/pimcore/pimcore/pull/7706 on 6.9. @blankse could you please give it a try? thanks!

**Comment by blankse** [comment] 2021-03-11 11:15
@dvesh3 Yes this looks good. I will test it.

**Comment by blankse** [comment] 2021-03-12 06:59
@dvesh3 I can no longer reproduce the error. I saved the same documents twice, but now it works. I guess it's a lottery.

But I'm sure #7706 should fix the error, since there are no more references between editable / elements.

**Comment by brusch** [comment] 2021-03-12 08:12
@blankse thanks a lot for your feedback - I'll close this issue then for now. 
`6.9` will be released latest mid of next week, if the issue still persists we can reopen this ticket any time 😊

**Closed by brusch** 2021-03-12 08:12 UTC
