### ISSUE TITLE
[Bug][DataObjects]: Adding Media -> Video type is not working anymore

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#12979] opened 2022-08-25 11:25 UTC
### Expected behavior

Add video type without problems in the class editor for data objects

### Actual behavior

Doesn´t work, configuration page stays blank

### Steps to reproduce

Add Media -> Video type

**Comment by dvesh3** [comment] 2022-08-25 16:10
Duplicate of #12832

**Closed as completed by dvesh3** 2022-08-25 16:10 UTC
Labels: Bug
