### ISSUE TITLE
[Bug]: Return type incompatibility in \Pimcore\Model\DataObject\ClassDefinition\Data\Date

### ISSUE THREAD

**Issue by drs-anton** [pimcore/pimcore#15296] opened 2023-05-31 09:37 UTC
### Pimcore version

11.0.0

### Steps to reproduce
We are migrating from pimcore 10.6 to 11.0.0 at the moment and stumbled across the following behaviour
Return types between 
\Pimcore\Model\DataObject\ClassDefinition\Data\Date::getDataForResource (int|string|null)
and
\Pimcore\Model\DataObject\ClassDefinition\Data\Date::getDataForQueryResource (int|null)
are not compatible.

For example if there is an object field from type Date with the datatype DATE, getDataForResource() returns a date string.
But getDataForQueryResource only allows int or null as return type and in the example above getDataForQueryResource throws a PHP-Error because getDataForQueryResource returns the return value from getDataForResource

### Expected / actual behavior

getDataForQueryResource should also be able to return a string

**Comment by mcop1** [comment] 2023-05-31 10:19
Duplicate of https://github.com/pimcore/pimcore/issues/15292?

**Comment by drs-anton** [comment] 2023-05-31 10:21
> Duplicate of #15292?

Absolutely!

**Comment by mcop1** [comment] 2023-05-31 10:27
Ok, then I will close this issue and we will take a look at the problem in https://github.com/pimcore/pimcore/issues/15292. 

Thanks for reporting the problem.

**Closed as completed by mcop1** 2023-05-31 10:27 UTC
Labels: Bug
