### ISSUE TITLE
[Bug]: Missing pimcore context resolver. Is the listener properly configured?

### ISSUE THREAD

**Issue by jhonbaudin** [pimcore/pimcore#12886] opened 2022-08-13 03:25 UTC
### Expected behavior

i was hoping to see the main page

### Actual behavior

i made an skeleton pimcore installation, and i receive this message

![image](https://user-images.githubusercontent.com/47991218/184466358-fb1069f3-ab7b-479b-99c4-6c0347a93825.png)

### Steps to reproduce

just a new pimcore 10.5 installation on docs
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html

PHP 8.1.9
nginx version: nginx/1.22.0
composer version 2.3.10
Mysql  Ver 8.0.29
Rocky Linux 8.6 (Green Obsidian)

**Comment by kingjia90** [comment] 2022-08-16 12:01
@jhonbaudin i gave it a try but it works fine on my end, can you please retry and let us know if it's happening again and further details to reproduce it?

**Comment by dvesh3** [comment] 2022-08-23 07:55
🏓 @jhonbaudin

**Comment by kingjia90** [comment] 2022-08-30 11:39
@jhonbaudin I'm closing the issue for the moment, as it have been more than 2 weeks without further feedback. 
Let us know if the problem is still occuring.

**Closed as completed by kingjia90** 2022-08-30 11:39 UTC
Labels: Bug
