### ISSUE TITLE
[Bug]: Installer should use the PHP binary that was used to run the installer

### ISSUE THREAD

**Issue by GaneshKandu** [pimcore/pimcore#10913] opened 2021-11-27 11:56 UTC
### Expected behavior

pimcore-install should use php binary that was used for its exicution but after run pimcore-install uses default php binary.

### Actual behavior

I am using server with multiphp, i am trying to run ```./vendor/bin/pimcore-install``` with php 8.0 that is ```ea-php80 ./vendor/bin/pimcore-install```

but after starting command ```./vendor/bin/pimcore-install``` uses default php that is ```/usr/local/bin/php```

i think it should keep using binary which is passed in command because as user my expectation was it will use passed binary only
because of this behavior  i am getting this error
```
  /usr/local/bin/php /home/user/public_html/bin/console doctrine:migrations:sync-metadata-storage -q
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.3.32.Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.3.32.

 ! [NOTE] Marking all migrations as done failed. Please run the following
 !        command manually:

  /usr/local/bin/php /home/user/public_html/bin/console doctrine:migrations:version --all --add --prefix=Pimcore\Bundle\CoreBundle -n -q
```

### Steps to reproduce

Install pimcore with non default php version on multi-php installed server
``ea-php80 ./vendor/bin/pimcore-install``

**Comment by brusch** [comment] 2021-11-29 08:43
@GaneshKandu can you please check if Symfony's `PhpExecutableFinder` is resolving the right binary? We could then switch to that. If so can you please create a PR for that? 
Thanks in advance!

**Comment by GaneshKandu** [comment] 2021-12-24 11:35
I am not able to do that because i don't have knowledge about Symfony.

**Comment by brusch** [comment] 2021-12-27 14:15
@GaneshKandu just run the following code in your project directory: 
https://symfony.com/doc/current/components/process.html#finding-the-executable-php-binary
Should be easy without Symfony knowledge - thanks in advance.

**Comment by GaneshKandu** [comment] 2021-12-29 04:18
@brusch yes, its working
i am getting correct binary path

**Comment by brusch** [comment] 2022-01-03 14:22
Unfortunately I don't think we can change that without possibly breaking existing installations, so I'm afraid we need to change that for Pimcore XI.

**Comment by dvesh3** [comment] 2023-04-05 08:45
You can define php executable path in your [config ](https://github.com/pimcore/demo/blob/61375b3a88449b37d80add359f486e3848d1e295/config/services.yaml#L28)which is then used by Installer [here](https://github.com/pimcore/pimcore/blob/23d5456a6d58d4b5ec0f7a3872ab9a4359f2c495/bundles/InstallBundle/src/Installer.php#L449). please see https://github.com/pimcore/pimcore/blob/81276d6d5af6f6533f98e1a4a42761cc57f6cff0/lib/Tool/Console.php#L148

If we switch to Symfony's `PhpExecutableFinder` then we loose the ability to use custom php executable. I don't know if i'm missing a point here. 

@brusch could you please confirm? thanks!

**Comment by brusch** [comment] 2023-04-05 09:25
@dvesh3
We could extract this part
https://github.com/pimcore/pimcore/blob/81276d6d5af6f6533f98e1a4a42761cc57f6cff0/lib/Tool/Console.php#L75-L89
into it's own method and then use a custom fallback mechanism in `\Pimcore\Tool\Console::getPhpCli()` where we check for a config first, if not available we use the `PhpExecutableFinder` and last but not least `\Pimcore\Tool\Console::getExecutable()`. 

WDYT?

**Comment by dvesh3** [comment] 2023-04-05 09:35
@brusch 
To sum-up, the new priorities are:
 1. Check config for executable
 2. Use PhpExecutableFinder
 3. Use `getExecutable` (we still have to check config again here as it used for other libs)

Just to confirm, we are only changing priorities for `getPhpCli()` not for other binaries. right?

**Comment by dvesh3** [comment] 2023-04-05 09:44
But wait, Isn't that `getExecutable` is already doing? checking for parameter `pimcore_executable_php` first and then system.yaml `path_variable`. If not found in both then use `PhpExecutableFinder` at last.

**Comment by brusch** [comment] 2023-04-05 09:57
Yes an now 😅 
The problem is that it could find the wrong binary, in case you don't have it configured with `pimcore_executable_php`. 
As explained above, if you have installed multiple versions of PHP and you run e.g. the installer using a non-default PHP version, eg. `php-82 ./vendor/bin/pimcore-install` it would find the default PHP version (`/usr/bin/php`). 

When using the `PhpExecutableFinder` it would find the correct `php-82` binary. 

So the correct order would be: 
1. `pimcore_executable_php`
2.  `PhpExecutableFinder`
3. `\Pimcore\Tool\Console::getExecutable('php')` 

That should solve the issue 😊

**Closed as completed** 2023-04-06 10:10 UTC
Labels: Bug, Priority
