### ISSUE TITLE
sample code with "< (&lt;)" not shown in WYSIWYG [Bug]: 

### ISSUE THREAD

**Issue by capitalfuse** [pimcore/pimcore#15740] opened 2023-08-12 01:41 UTC
### Pimcore version

11.0.6

### Steps to reproduce

When I will show the code sample like the below in WYSIWYG text area (ex. NewsText on pimcore demo site )
all "<(\&lt;)" will be not shown at all after reloading the page.

before the page reloaded,
```
<script src="prism.js" data-manual></script>
<script src="tinymce.js"></script>
```
after the page reloaded, 
```
script src="prism.js" data-manual>/script>
script src="tinymce.js">/script>
```

### Actual Behavior

It seems that all "< (\&lt;)" will be sanitized in WYSIWYG Text Area.

```
script src="prism.js" data-manual>/script>
script src="tinymce.js">/script>
```

### Expected Behavior

Could I write the program code sample with "< (\&lt;)" in WYSIWYG Text Area?

```
<script src="prism.js" data-manual></script>
<script src="tinymce.js"></script>
```

**Comment by GeorgII-web** [comment] 2023-08-16 12:40
After upgrading to a Pimcore 11

[[Security] :](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/#security-)
- Implemented Symfony HTML sanitizer for WYSIWYG editors.

I'm facing the same issue - more than 4k products have now corrupted description.

Simple example: `delay < 2 min` became `delay  2 min`

In a code, `$product->setDescription("delay < 2 min")` works fine, in a DB the value is correct.
But `$product->getDescription()` returns sanitized (corrupted) value without `<` sign.
In UI the same behavior on read\open correctly saved object, sanitized value shown.

Any place to change sanitizer settings?
Like in https://symfony.com/doc/current/html_sanitizer.html

**Comment by fracsi** [comment] 2023-08-24 07:16
The error is caused by the Wysiwyg editable class. It decodes the HTML entities created by TinyMCE.
See:

https://github.com/pimcore/pimcore/blob/f6436cac11dadd6ccb568ea9b4474ce3d144b16e/models/Document/Editable/Wysiwyg.php#L78-L92

If you remove the `html_entity_decode` function, the result contains the `&lt;` entity.

**Comment by aryaantony92** [comment] 2023-08-24 08:05
@fracsi Thank you for the suggestion. Created a PR https://github.com/pimcore/pimcore/pull/15811

**Comment by aryaantony92** [comment] 2023-08-24 13:47
Fixed by https://github.com/pimcore/pimcore/pull/15811

**Comment by dvesh3** [comment] 2023-09-27 09:10
Also revert disabled tests from https://github.com/pimcore/pimcore/pull/15960

**Comment by mhgtlc** [comment] 2023-10-02 09:08
@aryaantony92 @dvesh3 I have tested it with the latest code and the issue is there
Indeed it was fixed, but broken once again as I mentioned in the description
if you look here:
https://github.com/pimcore/pimcore/blob/11.0/models/DataObject/ClassDefinition/Data/Wysiwyg.php#L117
and here
https://github.com/pimcore/pimcore/blob/11.0/models/Document/Editable/Wysiwyg.php#L104
there is html_entity_decode

**Comment by dvesh3** [comment] 2023-10-02 09:12
@mhgtlc thanks! we are aware of it. The fix was reverted (please see https://github.com/pimcore/pimcore/pull/15960) as it was leading to regression of broken anchor links. This needs to be fixed properly so re-opened this issue in next bugfix release.

**Comment by dvesh3** [comment] 2023-10-11 08:45
@capitalfuse the script tag is stripped off as it is not allowed in the config https://pimcore.com/docs/platform/Pimcore/Documents/Editables/WYSIWYG#extending-symfony-html-sanitizer-configuration.

Regarding the scenarios about `<` removal, this is by design as the html sanitizer strips it considering incomplete tag.

At the moment, we are in discussion to kick the html sanitizer executing on runtime and provide a command to sanitize and persist the wysiwyg data.

**Comment by aryaantony92** [comment] 2023-10-11 09:05
Also, you can see here in the tests, https://github.com/symfony/html-sanitizer/blob/947492c7351d6b01a7b38e515c98fb1107dc357d/Tests/HtmlSanitizerAllTest.php#L87-L88 `<` is stripped off intentionally from the symfony sanitizer.

**Comment by aryaantony92** [comment] 2023-10-16 11:52
Fixed by https://github.com/pimcore/pimcore/pull/16086

**Closed as completed by aryaantony92** 2023-10-16 11:52 UTC
Labels: Bug
