### ISSUE TITLE
[Bug]: pimcore-install process is failing

### ISSUE THREAD

**Issue by Eviradnus** [pimcore/pimcore#13287] opened 2022-09-30 16:22 UTC
### Expected behavior

In a  `pimcore/pimcore:PHP8.1-fpm` docker image,
on a freshly composer-generated Pimcore skeleton,
given the appropriate configuration (either `PIMCORE_INSTALL_*` env variables or `--mysql-*` options),
I can install Pimcore using `pimcore-install`.

### Actual behavior

It fails:
```
# vendor/bin/pimcore-install --ignore-existing-config --no-interaction

Running installation. You can find a detailed install log in var/log/preprod.log

Running database setup...

  6/11 [===============>------------]  54%


                                                                                                                        
 [ERROR] The following errors were encountered during installation                                                      
                                                                                                                        

 * An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
```

Logs extract:
```
 [...]
[2022-09-30T13:22:16.294876+02:00] pimcore.WARNING: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "pimcore.config" must be defined. in /var/www/pimcore/var/installer/cac
he/ContainerKeMckWU/Pimcore_Bundle_InstallBundle_InstallerKernelPreprodDebugContainer.php:610 Stack trace: #0 /var/www/pimcore/vendor/pimcore/pimcore/lib/Config.php(159): ContainerKeMckWU\Pimcore_Bundle_InstallB
undle_InstallerKernelPreprodDebugContainer->getParameter('pimcore.config') #1 /var/www/pimcore/vendor/pimcore/pimcore/lib/Tool/Console.php(102): Pimcore\Config::getSystemConfiguration('general') #2 /var/www/pimc
ore/vendor/pimcore/pimcore/lib/Tool/Requirements.php(620): Pimcore\Tool\Console::getExecutable('convert') #3 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(177): Pimcore\Tool\Require
ments::checkPhp() #4 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Command/InstallCommand.php(349): Pimcore\Bundle\InstallBundle\Installer->checkPrerequisites() #5 /var/www/pimcore/vendor/symfony
/console/Command/Command.php(298): Pimcore\Bundle\InstallBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/
www/pimcore/vendor/symfony/console/Application.php(1046): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #7 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\C
omponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /var/www/pimcore/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doR
unCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /var/www/pimcore/vendor/symfon
y/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /var/ww
w/pimcore/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console
Output)) #11 /var/www/pimcore/vendor/pimcore/pimcore/bin/pimcore-install(106): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #12 /var/www/pimcore/vendor/bin/pimcor
e-install(120): include('/var/www/pimcor...') #13 {main} [] []
[...]
[2022-09-30T13:22:18.299274+02:00] app.ERROR: PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40 Stack trace: #0
 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(40): PDO->__construct('mysql:host=loca...', 'root', '', Array) #1 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/
PDOMySql/Driver.php(25): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'root', NULL, Array) #2 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(412): Doctrine\DBAL\D
river\PDOMySql\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1952): Doctrine\DBAL\Connection->connect() #4 /var/www/pimcore/vendor/doctrine
/dbal/lib/Doctrine/DBAL/Connection.php(1290): Doctrine\DBAL\Connection->getWrappedConnection() #5 /var/www/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(92): Doctrine\DBAL\Connection->executeQ
uery('SET FOREIGN_KEY...', Array, Array, NULL) #6 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(584): Pimcore\Db\Connection->executeQuery('SET FOREIGN_KEY...') #7 /var/www/pimcore/v
endor/pimcore/pimcore/bundles/InstallBundle/Installer.php(394): Pimcore\Bundle\InstallBundle\Installer->setupDatabase(Array, Array) #8 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(
285): Pimcore\Bundle\InstallBundle\Installer->runInstall(Array, Array) #9 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Command/InstallCommand.php(388): Pimcore\Bundle\InstallBundle\Installer->in
stall(Array) #10 /var/www/pimcore/vendor/symfony/console/Command/Command.php(298): Pimcore\Bundle\InstallBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\C
omponent\Console\Output\ConsoleOutput)) #11 /var/www/pimcore/vendor/symfony/console/Application.php(1046): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object
(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\Insta
llBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/pimcore/vendor/symfony/console/Application.php(299): Symf
ony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outpu
t\ConsoleOutput)) #14 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\
Component\Console\Output\ConsoleOutput)) #15 /var/www/pimcore/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInp
ut), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/pimcore/vendor/pimcore/pimcore/bin/pimcore-install(106): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Inpu
t\ArgvInput)) #17 /var/www/pimcore/vendor/bin/pimcore-install(120): include('/var/www/pimcor...') #18 {main}  Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000] [2002] No such file or directory in /var/www
/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18 Stack trace: #0 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(44): Doctrine\DBAL\Driver\PDO\Exceptio
n::new(Object(PDOException)) #1 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(25): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'root', NULL, Array) 
#2 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(412): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBA
L/Connection.php(1952): Doctrine\DBAL\Connection->connect() #4 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1290): Doctrine\DBAL\Connection->getWrappedConnection() #5 /var/www/pimcore/v
endor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(92): Doctrine\DBAL\Connection->executeQuery('SET FOREIGN_KEY...', Array, Array, NULL) #6 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Inst
aller.php(584): Pimcore\Db\Connection->executeQuery('SET FOREIGN_KEY...') #7 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(394): Pimcore\Bundle\InstallBundle\Installer->setupDatabas
e(Array, Array) #8 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(285): Pimcore\Bundle\InstallBundle\Installer->runInstall(Array, Array) #9 /var/www/pimcore/vendor/pimcore/pimcore/bu
ndles/InstallBundle/Command/InstallCommand.php(388): Pimcore\Bundle\InstallBundle\Installer->install(Array) #10 /var/www/pimcore/vendor/symfony/console/Command/Command.php(298): Pimcore\Bundle\InstallBundle\Comm
and\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /var/www/pimcore/vendor/symfony/console/Application.php(1046): Symfony\C
omponent\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Appli
cation.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Consol
e\Output\ConsoleOutput)) #13 /var/www/pimcore/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallComm
and), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Componen
t\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/pimcore/vendor/symfony/console/Application.php(171): Symfony\B
undle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/pimcore/vendor/pimcore/pimcore/bin/pimcore
-install(106): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #17 /var/www/pimcore/vendor/bin/pimcore-install(120): include('/var/www/pimcor...') #18 {main}  Next D
octrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver
.php:112 Stack trace: #0 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driv
er\PDO\Exception)) #1 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBA
L\Driver\PDO\Exception), 'An exception oc...') #2 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(31): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\
PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception)) #3 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(412): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', NULL, A
rray) #4 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1952): Doctrine\DBAL\Connection->connect() #5 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1290): Doctrin
e\DBAL\Connection->getWrappedConnection() #6 /var/www/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(92): Doctrine\DBAL\Connection->executeQuery('SET FOREIGN_KEY...', Array, Array, NULL) #7 /va
r/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(584): Pimcore\Db\Connection->executeQuery('SET FOREIGN_KEY...') #8 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer
.php(394): Pimcore\Bundle\InstallBundle\Installer->setupDatabase(Array, Array) #9 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php(285): Pimcore\Bundle\InstallBundle\Installer->runInst
all(Array, Array) #10 /var/www/pimcore/vendor/pimcore/pimcore/bundles/InstallBundle/Command/InstallCommand.php(388): Pimcore\Bundle\InstallBundle\Installer->install(Array) #11 /var/www/pimcore/vendor/symfony/con
sole/Command/Command.php(298): Pimcore\Bundle\InstallBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www
/pimcore/vendor/symfony/console/Application.php(1046): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #1
3 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Com
ponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/pimcore/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRu
nCommand(Object(Pimcore\Bundle\InstallBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/pimcore/vendor/symfon
y/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/ww
w/pimcore/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console
Output)) #17 /var/www/pimcore/vendor/pimcore/pimcore/bin/pimcore-install(106): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #18 /var/www/pimcore/vendor/bin/pimcor
e-install(120): include('/var/www/pimcor...') #19 {main} [] []
[2022-09-30T13:22:18.300565+02:00] console.DEBUG: Command "pimcore:install --ignore-existing-config --no-interaction" exited with code "2" {"command":"pimcore:install --ignore-existing-config --no-interaction","
code":2} []
```

Note: when editing `pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php` to add an `echo` statement with DB connection args, it shows a 1st call is going OK with expected DB credentials, then the failing `Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'root', NULL, Array)` call is given `mysql:host=localhost`, `root`, and `NULL` args, as if no config was given.

### Steps to reproduce

```
export PIMCORE_INSTALL_ADMIN_PASSWORD=somePassword \
  PIMCORE_INSTALL_ADMIN_USERNAME=admin \
  PIMCORE_INSTALL_MYSQL_DATABASE=pimcore \
  PIMCORE_INSTALL_MYSQL_HOST_SOCKET=pimcore-mariadb \
  PIMCORE_INSTALL_MYSQL_PASSWORD=somePassword \
  PIMCORE_INSTALL_MYSQL_PORT=3306 \
  PIMCORE_INSTALL_MYSQL_USERNAME=pimcore
composer create-project pimcore/skeleton pimcore
cd pimcore
vendor/bin/pimcore-install --ignore-existing-config --no-interaction
```

**Comment by scrummer** [comment] 2022-10-05 20:14
Can confirm - exactly same behaviour. Also with using the interactive setup without setting the constants.

**Comment by scrummer** [comment] 2022-10-05 20:31
Okay after some debugging: As most times - my bad!
The host was configured wrong and with setting the `PIMCORE_INSTALL_MYSQL_HOST_SOCKET` variable it all worked well.

**Comment by aashan10** [comment] 2022-10-06 08:32
@Eviradnus Could you please check that the environment variables you are setting are correct? I was not able to reproduce this issue in the given environment with the mentioned steps.

**Comment by dvesh3** [comment] 2022-10-10 07:12
> Okay after some debugging: As most times - my bad! The host was configured wrong and with setting the `PIMCORE_INSTALL_MYSQL_HOST_SOCKET` variable it all worked well.

Closing as the problem was fixed with host configuration.

**Closed as completed by dvesh3** 2022-10-10 07:12 UTC
Labels: Bug
