### ISSUE TITLE
[Bug]: Image Drag and Drop Safari not working

### ISSUE THREAD

**Issue by TobiSW** [pimcore/pimcore#16654] opened 2024-02-22 13:49 UTC
### Pimcore version

11.1.5

## Safari

1. Open any backend with pimcore between 10.6.9 and 11.1.5, for example demo.pimcore.com with latest Safari (17.3.1).
2. Open a document, e.g. /de
3. Create a Image brick
4. Try to drag and drop an image from the asset panel into the image brick.

## Chrome, Firefox
1. Repeat the same steps from above. The image drag and drop is working here.

## More informations
Please see attached screen recording on Mac with Safari where the drag and drop is not working and one screen recording on Mac with Chrome where it is working.

https://github.com/pimcore/pimcore/assets/6861689/0d2dbad0-b75f-4ed3-ac82-24f37935225d
https://github.com/pimcore/pimcore/assets/6861689/4a927d27-dde5-4745-b135-186cb77c9e53

### Actual Behavior

Its not possible to add the image via drag and drop.

### Expected Behavior

The image drag and drop is working in Safari.

**Comment by MeinTollerUsername** [comment] 2024-02-22 13:55
Same problem here with Safari

**Comment by kingjia90** [comment] 2024-02-22 14:02
Thank you for reporting, but closing as duplicate of https://github.com/pimcore/pimcore/issues/16540

**Closed as not planned by kingjia90** 2024-02-22 14:02 UTC
Labels: Bug
