### ISSUE TITLE
[Bug]: key for Advanced Many-To-Many Object is allowed in any case but works only in lowercase

### ISSUE THREAD

**Issue by jakesde** [pimcore/pimcore#11746] opened 2022-03-23 14:55 UTC
### Expected behavior

Since magic `__call` for `Pimcore\Model\DataObject\Data\ElementMetadata` supports any case for `set*`/`get*` I would expect that also the column key is also handled as case insensitive. E.g. you set key as `myColumn`, then you create logic that updates that column like `$elData->setMyColumn(42)` and save the parent object with it. Afterwards, when you fetch the parent object again (new request, new fetch from database) you get the proper `myColumn` value 42.

### Actual behavior

When saved object is fetched the column that has defined non-all-lowercase key is fetched as empty (null)

### Steps to reproduce

1. Create new Class in Settings => Data Objects => Classes, let's say `MMTestClass`
2. In the newly created class add Panel to General Settings - Add Layout Component => Panel
3. Create Advanced Many-To-Many Object Relation (name e.g. `MySubObjects`) - Add Data Component => Relation => Advanced Many-To-Many Object Relation
4. Setup the relation
5. Add column to Columns in this relation with a name `myColumn`, optionally, a label `My Column`, for type choose Text or Number
6. Create a PHP logic setting that column:
7. Prepare a new array `$mySubObjects`
8. Create new `Pimcore\Model\DataObject\Data\ElementMetadata` (`$newEl`), use `$newEl->setMyColumn(42)` or `$newEl->setmyColumn(42)` to set the data and push it to the `$mySubObjects` array
9. Create logic in PHP that creates a new MMTestClass instance `$mmtest`, set all required fields and use `$mmtest->setMySubObjects($mySubObjects)` to set the element set
10. Call `$mmtest->save()`
11. Go to pimcore admin and open the newly created object in Data Objects and go to the panel created in step 2
12. You will see the newly created sub object element, but the column "My Column" will be empty

**Comment by kingjia90** [comment] 2024-07-04 12:09
~Could it be fixed by https://github.com/pimcore/pimcore/pull/5967 ? Do you remember which pimcore/pimcore version was affected?~
~Update: nevermind, it wasn't related  to that, i got it right and was able to reproduce it, investigating...~
Update: opened a PR

**Comment by kingjia90** [comment] 2024-07-04 12:40
For me seems working fine, i couldn't reproduce it, guessing you were using `pimcore\pimcore` < `6.6.0`, could it be? 
Closing for the moment, if it occurs again, please re-open a new issue.
Thank you again for reporting

**Comment by kingjia90** [comment] 2024-07-12 07:14
Fixed by https://github.com/pimcore/pimcore/pull/17272

**Closed as completed by kingjia90** 2024-07-12 07:14 UTC
Labels: Bug, Pimcore:Priority
