### ISSUE TITLE
Anchor links disappear when wysiwyg element is focused

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#945] opened 2016-10-14 13:03 UTC
When you enter a wysiwyg field with an anchor link - the anchor disappears. It shows fine again when you reload the document.
Reproducible on the pimcore demo. 

Not sure if this is a CKEditor problem. It works on their demo: http://ckeditor.com/demo

**Comment by brusch** [comment] 2016-10-18 07:52
@ultramegatom unfortunately I was not able to reproduce the problem (tried it on a document page). 
May you have more details on that, to make it easier for me to reproduce? 

Thanks!

**Comment by brusch** [comment] 2016-10-18 07:59
@ultramegatom with the help of @mrudnicki I was able to reproduce it - thanks :)

**Comment by ultramegatom** [comment] 2016-11-30 11:23
I took a quick look at this:

It seems to be happening here: https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/document/tags/wysiwyg.js#L117

```javascript
Ext.get(this.textarea).removeCls("pimcore_wysiwyg_inactive");
```
also removes all CKEditor related style classes like ''cke_editable" from the element.

However i cant find any usefull usages of the 'pimcore_wysiwyg_inactive' except for adding and removing the styleclass. So... is this even needed?

**Comment by brusch** [comment] 2017-01-12 12:19
@ultramegatom you're absolutely right, this code isn't needed anymore - just removed it. 
But interesting though that `removeCls()` removed also other classes ... anyway, should be fixed :)

**Closed** 2017-01-12 12:20 UTC
Labels: Bug
