### ISSUE TITLE
Remove Pimcore\Log\Simple from docs

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#12115] opened 2022-05-13 07:16 UTC
### Improvement description

`Pimcore\Log\Simple` is marked as `@internal`, yet the documentation states that [one can use it for logging](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Logging.html#page_Writing-your-own-log-files):

![image](https://user-images.githubusercontent.com/57256630/168231096-cc8db225-4c68-438b-bb50-a2f0cdba2e19.png)

> Note that this might be resolved when implementing the request feature https://github.com/pimcore/pimcore/issues/11877 - provided that the documentation is updated accordingly.

**Comment by brusch** [comment] 2022-12-30 08:54
We just remove that from the docs for now.

**Comment by dvesh3** [comment] 2023-01-02 08:38
Duplicate of https://github.com/pimcore/pimcore/pull/13446. already covered in https://github.com/pimcore/pimcore/pull/13607

**Closed as completed by dvesh3** 2023-01-02 08:38 UTC
Labels: Improvement, Backlog
