### ISSUE TITLE
Missing Newline in CSV-Export more than 20 items

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#6815] opened 2020-07-21 13:27 UTC
# Bug Report

If a CSV export is processed from the GridView with more than 20 lines, a line break is missing every 20 lines.
### Steps to reproduce
* Click on the home object folder in the pimcore demo
* Select "Cars"
* Export the date vie CSV-Export-Button
* Result:
`...
"31";"/Product Data/Cars/alfa romeo/Giulietta/white";"1";"Giulietta";"object:/Product Data/Body-Styles/2-door coupé";"white""32";"/Product Data/Cars/alfa romeo/Spider";"1";"Spider";"object:/Product Data/Body-Styles/2-door roadster";""
...`
**Notice the missing line break before the ID field of ID "32"**

### Code example

https://github.com/pimcore/pimcore/blob/7afd7f1b1f521b8e5b70bc462768b3adb0b054f2/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php#L1884-L1886

**Comment by weisswurstkanone** [comment] 2020-07-21 13:58
duplicate of https://github.com/pimcore/pimcore/pull/6744

**Closed by weisswurstkanone** 2020-07-21 13:58 UTC
