### ISSUE TITLE
User permissions are not applied correctly

### ISSUE THREAD

**Issue by kkarkus** [pimcore/pimcore#6761] opened 2020-07-09 14:57 UTC
# Bug Report
User permissions are not applied correctly.
When we have role A and role B, these roles have the same object path added to workspace, but different permissions, 
then in the result, user permissions are taken from one role only, not summed up. 
Example reproduced on demo.pimcore.fun instance (and in ^5.8 and ^6.0 versions):
Role A: [https://i.imgur.com/yiHmdkK.png](https://i.imgur.com/yiHmdkK.png)
Role B: [https://imgur.com/YhKN10s.png](https://imgur.com/YhKN10s.png)
User: [https://imgur.com/ynE2tSN.png](https://imgur.com/ynE2tSN.png)

### Actual behavior
Permissions analyzer result: [https://imgur.com/KYWyBf4.png](https://imgur.com/KYWyBf4.png)
Got only list and view permission.

### Expected behavior
Available permissions should be list, view, save, and publish. 

I suppose that this query is wrong and that's why permission are dependent on order of roles.  
```php
$permissionsParent = $this->db->fetchOne('SELECT `' . $type . '` FROM users_workspaces_object WHERE cid IN (' . implode(',', $parentIds) . ') AND userId IN (' . implode(',', $userIds) . ') ORDER BY LENGTH(cpath) DESC, ABS(userId-' . $user->getId() . ') ASC LIMIT 1');
```
Perhaps this query can be replaced by something like this
```php
$permissionsParent = $this->db->fetchOne('SELECT MAX(`' . $type . '`) FROM users_workspaces_object WHERE cid IN (' . implode(',', $parentIds) . ') AND userId IN (' . implode(',', $userIds) . ') ORDER BY LENGTH(cpath) DESC, ABS(userId-' . $user->getId() . ') ASC LIMIT 1');
```

**Comment by dvesh3** [comment] 2020-07-09 15:16
duplicate of https://github.com/pimcore/pimcore/issues/6654. please see https://github.com/pimcore/pimcore/pull/6670

**Closed by dvesh3** 2020-07-09 15:16 UTC
