### ISSUE TITLE
Checkbox value when object is being updated/saved

### ISSUE THREAD

**Issue by lige-development** [pimcore/pimcore#840] opened 2016-09-01 15:15 UTC
**Scenario**
Object (call it for example Product) has multiple grouped parameters, where each group of parameters consists of input (any type - numeric, string, whatever) and checkbox. 

**Required behaviour**
On object save all data are transmitted to DB and saved as required - including correct state of checkbox.

**Actual behaviour**
Only first changed checkbox is transmitted with correct (means changed) value, the rest is being ignored. When user/admin wants to change multiple checkboxes with one save action, it fails and save just and only the first one. Remaining ones are kept in original state.

**Reproducible**
Always

**Comment by mrudnicki** [comment] 2016-09-01 19:25
Hi @lige-development 
Thanks for the request, could you send the class definition which you've used? 
I can't reproduce the issue.

**Comment by lige-development** [comment] 2016-09-02 07:01
Hi @mrudnicki 
I did some investigation on this matter yesterday. Actually, all system function work as expected, nevertheless object form render logic makes a bit stupid mistake (from our point of view). I'll try to explain why:

We use Classification store for parameters definitions. We have there simple inputs (input fields, sliders, checkboxes), Groups (where we make complex groups or just simple pairs - very often input field and checkbox) and Group Collections (where we create complex parameter groups). Above mentioned checkbox is crucial for the active project - with it we define paired input box as filterable on frontend. 

And here the issue comes - checkbox is, logically, defined just once ("Filter"), but in Group Collection used multiple times. Unfortunately the same logic is then used in backend, where checkbox is rendered everytime with the same name parameter (name="Filter") and therefore only one value is being handed over.

Although it's not a bug in a typical way, I think lots of other user might become the same problem when trying to spare some key definitions...

**Comment by mrudnicki** [comment] 2016-09-02 07:38
Hi @lige-development,
Thank you for the description.

If you're using the same checkbox (for example with "filter" name attribute), in many groups, with your group collection in an object, it shouldn't cause described behavior by you. 

Every input parameter in groups (even if has the same name) is transferred to the ObjectController in a different row and is handled by the action as a different value. 
I've revised it and still, I can't reproduce. 
At the moment I close the task but if you want, you can send the class definition to check it in your specific case.

**Closed by mrudnicki** 2016-09-02 07:38 UTC

**Comment by lige-development** [comment] 2016-09-02 09:04
Hi @mrudnicki,
That's strange because according to classificationstore.js, object gertValue() definition (L273):

`localizedData[currentLanguage][this.languageElements[currentLanguage][s].getName()] = value;`

my proposal:

`if (localizedData[currentLanguage][this.languageElements[currentLanguage][s].getName()]) {
     localizedData[currentLanguage][this.languageElements[currentLanguage][s].getName()].push(value);
} else {
     localizedData[currentLanguage][this.languageElements[currentLanguage][s].getName()] = [];
     localizedData[currentLanguage][this.languageElements[currentLanguage][s].getName()].push(value);
}`

you always overwrite the defined parameter. In case of multiple params with same name this should return array of objects, not a simple object. I did a quickfix which solves this matter on both sides (js/php), in case you'd like to create pull request, feel free to let me know. Otherwise thank you for you comments above!
