### ISSUE TITLE
[Bug]: Not editable fields writeable without permission

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#12574] opened 2022-07-04 09:36 UTC
### Expected behavior

Not editable fields of DataObjects cannot be written without permission.

### Actual behavior

Not editable fields in DataObjects can be written i.e. by Browser plugins like Password Managers, Autofill form tools

### Steps to reproduce

Use plugin to fill a not editable field in a Pimcore DataObject

**Comment by robertSt7** [comment] 2022-07-14 07:05
@jremmurd Thanks for reporting the bug, but I couldn't reproduce it. Could you please specify which pimcore version, plugin and browser you are using? Thank you

**Comment by jremmurd** [comment] 2022-07-18 10:03
@robertSt7 Pimcore Version was 10.3.5 I do not know the exact plugin, one of our client had the error. I will have to research.

**Comment by jremmurd** [comment] 2022-07-18 11:01
> @robertSt7 Pimcore Version was 10.3.5 I do not know the exact plugin, one of our client had the error. I will have to research.

additional info:

* Chrome (100.0.4896.127 (Offizieller Build) (64-Bit)
* KeePassXC-Browser-Version: 1.8.1
* KeePassXC-Version: 2.7.1

**Comment by robertSt7** [comment] 2022-07-19 11:06
@jremmurd Sorry, but I can't reproduce the bug. Could you please try to reproduce it in the demo (https://demo.pimcore.fun/) and descripe your steps in detail. Thanks

**Comment by NiklasBr** [comment] 2022-07-19 12:16
This sounds like a browser autocomplete function or extension of some sort. ExtJS/Pimcore marks the input fields as `readonly="readonly"`, but that still means they [can be edited and submitted](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly) by anything which changes the DOM:

> [...] read-only controls can still function and are still focusable, whereas disabled controls can not receive focus and are not submitted with the form and generally do not function as controls until they are enabled.

**Comment by fashxp** [comment] 2023-12-21 09:33
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed as not planned by fashxp** 2023-12-21 09:33 UTC
Labels: Bug, PR Welcome

**Comment by byfareska** [comment] 2024-04-16 11:34
that's unauthorized modyfing of data and you are closing it? how about companies which are paying for this software, are they paying for dead software?
