### ISSUE TITLE
[Bug]: prettyUrl handling in multi sites

### ISSUE THREAD

**Issue by TobiSW** [pimcore/pimcore#13501] opened 2022-11-02 15:19 UTC
### Expected behavior

Pretty Url should be only unique inside a site

### Actual behavior

Its not possible to set the same prettyUrl inside different sites. When you have already defined a pretty url you will get a warning that this URL already exist. In any case it will be saved. 

### Steps to reproduce

Create the same prettyUrl inside different site documents

**Comment by dvesh3** [comment] 2022-11-07 11:04
Duplicate of #7219

**Closed as completed by dvesh3** 2022-11-07 11:04 UTC
Labels: Bug
