### ISSUE TITLE
[Objects] Localized Fields in Fieldcollections do not work when Object itself has no Localized Fields and Inheritance is activated

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2810] opened 2018-04-30 07:13 UTC
Steps to reproduce: 
- Create FieldCollection with Localized Fields
- Create Class, activate Inheritance and add FieldCollection (but no localized fields)

- Create object of created class, create sub object of created class , add empty field collection entry
- Save, close and reopen subobject in Pimcore backend

```
in pimcore/lib/Pimcore/Model/AbstractModel.php (line 262)

AbstractModel->__call('getLocalizedFields', array())
in pimcore/models/DataObject/AbstractObject.php (line 1272)

AbstractObject->__call('getLocalizedFields', array())
in pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php (line 203)

Localizedfields->doGetDataForEditMode(object(Localizedfield), object(Test), array('de_AT' => array('test' => null), 'en_GB' => array('test' => null), 'fr_FR' => array('test' => null)), array('en_GB' => array('test' => array('inherited' => true, 'objectid' => 12467)), 'de_AT' => array('test' => array('inherited' => true, 'objectid' => 12467)), 'fr_FR' => array('test' => array('inherited' => true, 'objectid' => 12467))), 1, false)
in pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php (line 123)

Localizedfields->getDataForEditmode(object(Localizedfield), object(Test), false)
in pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php (line 128)

Fieldcollections->getDataForEditmode(object(Fieldcollection), object(Test), false)
in pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php (line 540)

DataObjectController->getDataForField(object(Test), 'test', object(Fieldcollections), false)
in pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php (line 467)

DataObjectController->getDataForObject(object(Test), false)
in pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php (line 355)
```

**Comment by fashxp** [comment] 2018-04-30 07:13
might be connected to #2809

**Comment by weisswurstkanone** [comment] 2018-04-30 07:57
unable to reproduce. maybe an important aspect to reproduce this is missing ?

**Comment by weisswurstkanone** [comment] 2018-05-24 10:17
should be fixed via https://github.com/pimcore/pimcore/pull/2813

**Closed** 2018-05-25 08:34 UTC
Labels: Bug
