### ISSUE TITLE
[Bug]: URL Slug cannot store fallback for multiple languages

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11697] opened 2022-03-17 12:51 UTC
### Expected behavior

Every language for a localized URL Slug inside a localizedfield should be able to have a fallback slug.

### Actual behavior

It is only possible to have one language have a fallback slug.

### Steps to reproduce

1. Add a URL Slug to a localized field
2. Fill in the "fallback" field in one language.
3. Save object.
4. Fill in the "fallback" field in another language.

Result is an error with: `Duplicate entry '/product/22964-0' for key 'object_url_slugs.PRIMARY'`

**Comment by kingjia90** [comment] 2022-04-04 18:10
@NiklasBr i was unable to reproduce the same exact error, could you please provide more info to reproduce the error? 

Is this the same circumstances as [`Unique constraint violated. Slug alreay used by object urlSlug, fieldname: urlSlug` ](https://github.com/pimcore/pimcore/issues/10604#issuecomment-1073701197) where the same slug is used in multiple places?

**Comment by NiklasBr** [comment] 2022-04-11 08:47
The above description works on demo.pimcore.fun, so I am not sure what else to provide. You can *also* confirm the error by simply running these two SQL statements.

First for e.g. `en`:
```sql
INSERT INTO `object_url_slugs` (`objectId`, `classId`, `fieldname`, `index`, `ownertype`, `ownername`, `position`, `slug`, `siteId`)
VALUES ('22950', 'product', 'urlSlug', '0', 3, 'localizedfield', 'en', '/fallback', '0');
```
and then for another language in the localized field e.g. `nb`:
```sql
INSERT INTO `object_url_slugs` (`objectId`, `classId`, `fieldname`, `index`, `ownertype`, `ownername`, `position`, `slug`, `siteId`)
VALUES ('22950', 'product', 'urlSlug', '0', 3, 'localizedfield', 'nb', '/fallback', '0');
```

It gives the very same error as doing it in the frontend UI.

**Comment by kingjia90** [comment] 2022-04-11 09:35
Thank you for providing more details. 
By looking at the queries, we would be in the same case of `unique constraint violated`.

But this makes me wonder, why would anyone be using the same fallback slug for different localized fields? 
let's say it is now allowed to have same slugs for different languages, save and type `demo.pimcore.fun/fallback`, what language would it be expected (`en` or `nb`) in the frontend? Doesn't it confuse the routing and cause sort of infinite redirections?

As far as i know, most of the multi-language websites either would be slug `/en/fallback` and `/nb/fallback`, or in domain approach as `en.pimcore.fun/fallback` and `nb.pimcore.fun/fallback` and both these cases work fine at the moment.

**Comment by NiklasBr** [comment] 2022-04-11 09:51
> But this makes me wonder, why would anyone be using the same fallback slug for different localized fields?

So that the UK site can have the same URL fallback as the Swedish site.

**Comment by kingjia90** [comment] 2022-04-11 10:47
maybe i got it

![image](https://user-images.githubusercontent.com/6014195/162721791-79a6a614-1f35-4db0-8e3f-9d48595bf060.png)
the term `fallback` is misleading here.
The fallback actually only happens "vertically": when one slug in the site(siteId > 0) doesn't exists, it takes the slug for siteId=0 as valid, when set.
There is no "horizontal" fallback between languages, like it would happens, for example for translations.

If i didn't misunderstood and to my limited knowledge of Pimcore, what you want to achieve should be something done at a redirection/routing level, not on the slug of the dataobject (which just "assigns" the slug value).

**Comment by kingjia90** [comment] 2022-04-11 10:56
in other words, when dataobject slug (priority 4) is not found, the `fallback` is the [priority 5](https://pimcore.com/docs/pimcore/current/Development_Documentation/MVC/Routing_and_URLs/index.html#page_5-Static-Routes-Custom-Routes) rule. 
This is not managed here inside the slug data type and there are no any other priorities rules in between.

**Comment by NiklasBr** [comment] 2022-04-11 11:06
I'm not sure I understand your explanation, but considering that:

1. There is only one site/domain available per language in the localizedfield:
   ![image](https://user-images.githubusercontent.com/279826/162727271-15c7de45-b9ba-413a-8077-5b019ec35a33.png)
3. URL Slugs are tied to languages

What should "fallback" be called? How should it be used according to you? Why is it not possible to have a proper fallback slug which is the same on different sites/domains?

**Comment by kingjia90** [comment] 2022-04-11 13:51
`Fallback` should be called `Default` and only makes sense when there are more than 1 subsite. 
It is the value taken when the Site specific slug is not defined.

Let's say we have `pimcore.com` which has subsites `academy.pimcore.com` and `demo.pimcore.com`.

If you only have Default slug `/fallback` and the other subsites' slug are empty, then `demo.pimcore.com/fallback` works because of the default value defined. Same goes for `academy.pimcore.com/fallback`. That's the purpose of `fallback` here, if the  slug part is the same, you don't need to write it for each subsite, you need only once and it's valid across each multisite.

You can see better in the code, this part `(siteId = %d OR siteId = 0)`.
https://github.com/pimcore/pimcore/blob/90a603647ae074be3b99b545b8246a4a59244fdd/models/DataObject/Data/UrlSlug.php#L343-L354

It has nothing to do with redirects fallbacks and language fallbacks, which should be managed elsewhere (eg. static routing or at least priority > 4).

You cannot have the same slug, for the reason that if you type that slug, the routing won't be able to know which language to load and potetially cause other problems.

**Comment by NiklasBr** [comment] 2022-04-11 14:05
It reads to me like the design of URLSlugs is inherently incompatible with localizedfields, is that it? Shouldn't slugs then be prevented from being added to localizedfields?

Why is this idiosyncrasy not explained to the end user who clicks save on the object and then wonders why it does not work as expected? They do expect `site1.com/fallback` and `site2.se/fallback` to both work.

**Comment by kingjia90** [comment] 2022-04-11 14:20
Why incompatible with localizefields? `/en/fallback` and `/se/fallback` can both work under the same dataobject in their respective language/flag tab. Just not the same exact slug, due its nature of being unique across the same domain.

For example you could have another dataobject, with empty default and site `academy.pimcore.com` have again `/en/fallback` and `/se/fallback` specified, it doesn't conflict with `pimcore.com/en/fallback` from dataobject1. As soon as you type the same slug across the same domain, then the duplicate slug triggers.

**Comment by NiklasBr** [comment] 2022-04-11 14:31
> Why incompatible with localizefields? /en/fallback and /se/fallback can both work under the same dataobject in their respective language/flag tab. 

But they don't work today, for multiple reasons: 1. they cause an error, 2. they do not fill, 3. they do not redirect on the fronted, and from my understanding of your description it is not intended, but maybe I am misunderstanding something?

**Comment by kingjia90** [comment] 2022-04-11 15:07
mhhh 🤔 , then i will double-check that and open an issue/PR if i find something, but if you don't mind, i will close this issue for the moment: we made sure why having duplicate slugs is not possibile and that the `fallback` here is just the default value for all sub-sites. 
I kindly invite you to do the same if you also find any helpful clues or have more details about what's not working.

FYI: If you use the demo to reproduce it, there would be an underlying problem that i also stumbled upon myself: the routing is going to be faulty because of the `current` here, it won't return the right slug
https://github.com/pimcore/demo/blob/5aa7546cdae998a07475312d6b5b5fbf8e0a74bf/src/Website/LinkGenerator/ProductLinkGenerator.php#L69
I would fix that as well and eventually implement better examples in the live demo that cover the case you mentioned, but i have to check if all this can get prioritized.

**Closed as completed** 2022-04-11 15:12 UTC
Labels: Bug

**Comment by NiklasBr** [comment] 2022-04-11 15:26
I disagree that this should be closed.

**Comment by dlhck** [comment] 2023-07-25 13:42
@NiklasBr I just experience the exact same problem. No idea why this gets closed as it is a major issue. URL slugs are not usable within localizedfields right now. The uniqueness of slugs should be determined on `slug` + `position` (language). Currently it is only based on the slug which causes problems with the fallback logic of the localizedfields.

**Comment by NiklasBr** [comment] 2023-07-25 14:05
Yes @davidhoeck, thanks for chiming in.

This problem is also made more complex because languages in localizedfields are only loosely connected to the actual front end sites using the slugs. I could have sworn I had written a feature request/RFQ written a few months ago but it has apparently been deleted(!) detailing suggested steps to fix that, would love to know why it was removed!

Another thing which URL Slugs does badly is dealing with object variants which causes some issues. The end result is that we have a set of custom patches to resolve this issue because unfortunately @kingjia90 thinks of this as not a problem.

**Comment by dlhck** [comment] 2023-07-25 14:45
@NiklasBr it is crazy that there is not even a hint of something like that in the docs. @brusch could you maybe take a look at this one. I think it is really important as the basic functionality of URL slugs is great but in practice not really usable with these constraints. 

I think it is necessary to include that locale in the slug, but to me that's nonsense. Especially for applications in headless environments.

**Comment by dpfaffenbauer** [comment] 2023-07-25 15:01
@NiklasBr @davidhoeck I also don't understand your problem here. the term "fallback" is bit misleading here, it is meant for the default site (ID 0). If you want to generate 2 slugs for 2 sites in 2 different languages, you should have Site1 and Site2 added and add the slugs there in the corresponding Site Slug.

**Comment by dlhck** [comment] 2023-07-25 15:04
@dpfaffenbauer what if I am in headless environment? Routing and i18n is done in the frontend apps. Maybe the URL slugs are the wrong choice for this use case after all?

**Comment by dpfaffenbauer** [comment] 2023-07-25 15:07
@davidhoeck you can still use sites for this right? I mean, in frontend you would still have site1 and site2 right?

And still in these envs: The same slug for 2 objects is just simply wrong from a concept point of view. You should than rather use simple text fields if you map locales to domains.

**Comment by dlhck** [comment] 2023-07-25 15:15
@dpfaffenbauer you're getting that wrong. The problem exists with one object and multiple languages. For example, I have a name in EN and the FR value is blank, so it falls back to EN. That would mean I have an English slug for FR. So it is the same slug for two languages but one object.

**Comment by dpfaffenbauer** [comment] 2023-07-26 06:10
@davidhoeck you mean cause of language fallbacks?

**Comment by dlhck** [comment] 2023-07-26 06:55
@dpfaffenbauer exactly.

**Comment by dpfaffenbauer** [comment] 2023-07-26 06:56
@davidhoeck I see. But its still not a Pimcore bug, a Slug has to be unique. You have to handle that in your slug generation.

**Comment by dlhck** [comment] 2023-07-26 07:37
@dpfaffenbauer well I think it is wrong to set the slug column as unique. The uniqueness should be assessed via an overwriteable service in my eyes.

**Comment by dpfaffenbauer** [comment] 2023-07-26 07:40
@davidhoeck and how should the router than select which slug to use if there 2 of them?

**Comment by brusch** [comment] 2023-07-26 07:41
@NiklasBr we normally do not delete any issues/PRs/comments (only if they would contain offensive content or so - which didn't happen so far afaik 😉 ) - I have no idea why your RFQ is not there anymore 🤷

**Comment by NiklasBr** [comment] 2023-07-26 08:04
>  how should the router than select which slug to use if there 2 of them?

By also knowing which site and/or locale it belongs to. And object published on both SiteA and SiteB should be able to have the same URL Slug and/or fallback on both sites. And two different objects on SiteA and SiteB should be able to have the same URL Slug because the domain will keep them apart. As it is right now in 10.5 none of the above is possible without custom patches.

**Comment by dlhck** [comment] 2023-07-26 08:06
@NiklasBr thank you - I was just writing the same. 😄

**Comment by NiklasBr** [comment] 2023-07-26 08:07
@brusch Found it. Apparently it was moved to https://github.com/pimcore/pimcore/issues/15627 two months ago. I do not agree that it should have been moved, but I can see why it was moved.

**Comment by dpfaffenbauer** [comment] 2023-07-26 08:07
the router doesn't know any locale when visiting `/fallback`, the locale get's set by the request itself. it only knows the site, and for sites it is working as intendent.

**Comment by brusch** [comment] 2023-07-26 09:41
@NiklasBr moved it back https://github.com/pimcore/pimcore/issues/15627 - thanks 😊 - Sorry, that was my fault 🤗
