### ISSUE TITLE
Pimcore backend search not working for newly created Objects

### ISSUE THREAD

**Issue by manasaR507** [pimcore/pimcore#12870] opened 2022-08-11 06:10 UTC
### Expected behavior

When user filter the particular class data from search panel. It should return all data.

### Actual behavior

If user search the data from search objects panel. Data is not getting properly. It's showing only old data. Not for new one.  Have a look below attached screenshots. 

![Screenshot (213)](https://user-images.githubusercontent.com/64125570/184072811-1b354c75-9a63-42ba-8d2b-1347668fd544.png)
![Screenshot (214)](https://user-images.githubusercontent.com/64125570/184072816-d400f696-39d7-45e7-8220-5e057192dd8f.png)

### Steps to reproduce

Currently, we are using pimcore 10.0. I had tried with bin/console pimcore:search-backend-reindex. But still the issue is same.

**Comment by kingjia90** [comment] 2022-08-11 07:05
Could it be related and fixed by this 
https://github.com/pimcore/pimcore/pull/10641?

How does the `search_backend_data` table look like after running the command? Are you able find the element in this table?

**Comment by brusch** [comment] 2022-08-11 07:51
Do you have the `messenger:consume` command running?

**Comment by yamenalahlas** [comment] 2022-08-16 07:47
I have the same Problem, 
```
[program:messenger-consume]
command=bash -c 'sleep 5m && /var/www/html/bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize portal-engine-async pimcore_index_queues --time-limit=300'
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/var/www/html/var/log/supervisor.err.log
stdout_logfile=/var/www/html/var/log/supervisor.out.log
user=www-data
```

**Comment by yamenalahlas** [comment] 2022-08-18 22:16
I think in my case the problem ist that  the supervisor program cannot access to  env varriables from the Container.
I must to export the .env File in the supervisord Programm to get this variables
```
[program:messenger-consume]
command=bash -c 'export $(cat /pathto/.env | egrep -v "(^#.*|^$)" | xargs) &&  /var/www/html/bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize --time-limit=300 -vvv'
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/var/www/html/var/log/supervisor.err.log
stdout_logfile=/var/www/html/var/log/supervisor.out.log
user=www-data
```
it works so.

**Comment by mcop1** [comment] 2022-08-22 06:29
I tried to reproduce the problem, but everything seems to be working fine in my environment. 

@manasaR507 maybe @yamenalahlas´s solution works for you too?

**Comment by yamenalahlas** [comment] 2022-08-22 06:54
I fixed the problem, the problem was that supervisord doesn't see the env from the container. I had to export the env variables from the container to shell from the supervisor then it worked.
```
[program:messenger-consume]
command=bash -c 'export $(cat /path_to_your/.env | egrep -v "(^#.*|^$)" | xargs) &&  /var/www/html/bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize --time-limit=300 -vvv >> /var/www/html/var/log/sp-messenger-consume.log'
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/var/www/html/var/log/supervisor.err.log
stdout_logfile=/var/www/html/var/log/supervisor.out.log
user=www-data
```
it is **important** to be sure that www-data have permissions for the "/var/www/html/var" before supervisor started
I hope it helps @manasaR507

**Comment by manasaR507** [comment] 2022-08-24 05:26
> Do you have the `messenger:consume` command running?

@brusch I had run the command. It's working, But, throwing errors like unable to load image. Attached screenshot below. Please check.

![Screenshot (226)](https://user-images.githubusercontent.com/64125570/186335959-9b9bc9bc-d3fd-40b5-81f4-4cbea0a44336.png)

**Comment by manasaR507** [comment] 2022-08-24 06:25
> you able find the element in this

Yes data is present in the search_backend_data table. It's having only old data. Not updated with the new records. New records not present in this table.

**Comment by manasaR507** [comment] 2022-08-24 06:27
> I fixed the problem, the problem was that supervisord doesn't see the env from the container. I had to export the env variables from the container to shell from the supervisor then it worked.
> 
> ```
> [program:messenger-consume]
> command=bash -c 'export $(cat /path_to_your/.env | egrep -v "(^#.*|^$)" | xargs) &&  /var/www/html/bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize --time-limit=300 -vvv >> /var/www/html/var/log/sp-messenger-consume.log'
> autostart=true
> autorestart=true
> redirect_stderr=true
> stderr_logfile=/var/www/html/var/log/supervisor.err.log
> stdout_logfile=/var/www/html/var/log/supervisor.out.log
> user=www-data
> ```
> 
> it is **important** to be sure that www-data have permissions for the "/var/www/html/var" before supervisor started I hope it helps @manasaR507

Folder permissions are fine. No issue with that. Can you please tell me the path of above program:messenger-consume configurations. Needs to check in my end.

**Comment by brusch** [comment] 2022-08-24 08:38
Seems to be an Imagick problem of your setup, just see the error messages 😉 

![image](https://user-images.githubusercontent.com/142037/186371797-0e08958c-5dc0-4f06-87d5-2d00bc68b3d1.png)

**Closed as completed by brusch** 2022-08-24 08:38 UTC
Labels: Bug

**Comment by manasaR507** [comment] 2022-08-24 17:02
@brusch  If imagick library is not configured properly. Then it will be impact on search backend table or data objects. Imagick library will have impact on assets only right? So, that's not the issue for the search backend data.
