### ISSUE TITLE
[Bug]: Cannot enable Not Editable on URL Slug anymore

### ISSUE THREAD

**Issue by dvelguru** [pimcore/pimcore#13629] opened 2022-11-21 05:17 UTC
### Expected behavior

URL Slug input field should be disabled and uneditable when Not Editable is checked.
<img width="612" alt="Bildschirm­foto 2022-11-21 um 06 10 28" src="https://user-images.githubusercontent.com/3622712/202970361-4682d068-6d4e-492f-9783-b534d5c55394.png">

### Actual behavior

Input field is editable and I am able to change the value.
<img width="734" alt="Bildschirm­foto 2022-11-21 um 06 10 11" src="https://user-images.githubusercontent.com/3622712/202970535-0f99562f-7f7e-4ce4-8237-bac186af07de.png">

### Steps to reproduce

Create a new data object test class, add a new data component of data type "URL Slug".

Check the "Not Editable" field and then save the newly created data object test class.

Add a new data object and the input field will be editable.

**Comment by SamyMP** [comment] 2022-11-21 07:26
Possible duplicate of #13555

The "not editable" and "invisible" config were both not working since 10.5.10 I think

**Comment by dvelguru** [comment] 2022-11-21 07:53
> Possible duplicate of #13555
> 
> The "not editable" and "invisible" config were both not working since 10.5.10 I think

It is in fact the same problem.

**Comment by robertSt7** [comment] 2022-11-21 08:31
duplicate of https://github.com/pimcore/pimcore/issues/13555

**Closed as completed by robertSt7** 2022-11-21 08:31 UTC
Labels: Bug
