### ISSUE TITLE
[Improvement]: Delete temp files from image optimisation on error

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#11522] opened 2022-02-24 06:25 UTC
### Improvement description

We found a problem with the image optimisation algorithm.
I one project we had 330G images in the folder "var/tmp" witch are from the image optimisation.
The problem is that there was an huge tiff file. For that file there was a thumbnail with ~10M.
The optimizer "pngout" run very long for that image an run into a timeout (witch is 60s default from the symfony process component).
We also found many temp files in many other projects, with much smaller thumbnails.

I think there could be 2 things to avoid such a huge amount of temp files.

First in the `Pimcore\Image\Optimizer\AbstractCommandOptimizer` the [symfony process](https://github.com/pimcore/pimcore/blob/b6d4a89e88d5ae761a4311e8594e004c6fcf38a5/lib/Image/Optimizer/AbstractCommandOptimizer.php#L35) should be initialized with an configurable timeout value which defaults to 60s.

The second thing is that there is a random file generated for the optimisation process. 
When an exception occurs like symfony process timeout the whole process stops an the ramdon file is still there.
I think there should be a try catch arround of the [complete optimisation](https://github.com/pimcore/pimcore/blob/b6d4a89e88d5ae761a4311e8594e004c6fcf38a5/lib/Image/Optimizer.php#L41-L54) for example in `Pimcore\Image\Optimizer::optimizeImage`.
When an Error or an Exception occurs, the temp file should be deleted.

**Comment by GALCF** [comment] 2022-03-02 09:38
I would describe this as a bug, because it fills our tmp folder in production as well, to the point where the server crashes when no more space is available

**Comment by brusch** [comment] 2022-03-02 09:40
@GALCF yep - can you maybe provide a PR fixing the issue? Today would be the release of `10.3.2` so if you're quick, we can include the fix 😉

**Comment by GALCF** [comment] 2022-03-02 09:41
> @GALCF yep - can you maybe provide a PR fixing the issue? Today would be the release of `10.3.2` so if you're quick, we can include the fix 😉

I'll try to reproduce it right now

**Comment by GALCF** [comment] 2022-03-02 10:03
@brusch Fast enough?

**Comment by brusch** [comment] 2022-03-02 10:04
Yep, that was really quick 👍😁

**Comment by aweichler** [comment] 2022-03-02 10:38
What do you think about increasing the timeout value for Symfony Process in `Pimcore\Image\Optimizer\AbstractCommandOptimizer`? Maybe configurable? That is also a point, because big images maybe take longer than 60s so there are no optimisations.

**Comment by brusch** [comment] 2022-03-02 15:14
Fixed by #11566

**Comment by brusch** [comment] 2022-03-02 15:14
@aweichler since optimization is only done for thumbnails I'd assume that the images shouldn't be too big, right?

**Closed as completed by brusch** 2022-03-02 15:14 UTC
Labels: Bug

**Comment by aweichler** [comment] 2022-03-15 05:15
@brusch you are right. Thanks anyway for the quick fix.
