### ISSUE TITLE
[BUG][Translations] %count% parameter doesn't work since 6.7.2

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#7382] opened 2020-10-22 17:35 UTC
This change broke use cases like:

```twig
{{ '{0} list.product-count.zero|{1} list.product-count.one|]1,Inf[ list.product-count.plural'|trans({'%count%': totalCount}) }}
```

Now it just returns the key:
![image](https://user-images.githubusercontent.com/279826/96721666-c0824e80-13ac-11eb-9229-863783046125.png)

_Originally posted by @NiklasBr in https://github.com/pimcore/pimcore/pull/7071#issuecomment-713545650_

**Comment by brusch** [comment] 2020-10-28 11:54
Fixed by #7387

**Closed by brusch** 2020-10-28 11:54 UTC
Labels: Bug

**Comment by solverat** [comment] 2020-11-02 18:31
@dvesh3, @brusch: Now the symfony validation messages are broken (formbuilder failing tests: https://travis-ci.com/github/dachcom-digital/pimcore-formbuilder/jobs/424146687#L1531).

Validation template like `This value should be between {{ min }} and {{ max }}` does not get translated anymore.

I guess it's because of this early return but I'm not sure:

https://github.com/pimcore/pimcore/pull/7387/files#diff-348ef94471940979eacfda402822c86f98fc9fdf4abc5c08afb74211d3898898R302-R303

I particularly don't like this if/elseif loop in general. It's hard to read and not very well written (for exampe: `elseif ($comparisonId != $translated && $translated)`).:

https://github.com/pimcore/pimcore/blob/e2d8837a46ce0a99711be8cc5927418bb221286b/lib/Translation/Translator.php#L297-L308

**Comment by dvesh3** [comment] 2020-11-05 11:05
@solverat Sorry, unable to reproduce! Maybe you can share reproducible case on v.6.8.4. thanks!

**Comment by solverat** [comment] 2020-11-05 11:50
- Use locale "en"
- Create a form with one input type
- add constraint "range" with option "min", "max"
- submit form
-> checkout error
