### ISSUE TITLE
[Bug]: Environment variable processor not applied

### ISSUE THREAD

**Issue by simonkey** [pimcore/pimcore#15980] opened 2023-09-20 12:20 UTC
### Pimcore version

10.6.9

### Steps to reproduce

Usecase turn off e.g. the full page cache via env-variable.

Add the following to the config/config.yaml:

```
parameters:
    env(PIMCORE_ENABLE_FULL_PAGE_CACHE): 'true'

pimcore:
    full_page_cache:
        enabled: '%env(bool:PIMCORE_ENABLE_FULL_PAGE_CACHE)%'
```

### Actual Behavior

Variables are not processed before building the configuration tree. So the validation e.g. for boolean or integer fails because the value is always a string.

Causes the following error for the used example:
```
 Symfony\Component\Config\Definition\Exception\InvalidTypeException {#1704                                                                                                        
    #message: "Invalid type for path "pimcore.full_page_cache.enabled". Expected "bool", but got "string"."                                                                        
    #code: 0                                                                                                                                                                       
    #file: "./vendor/symfony/config/Definition/BooleanNode.php"  
```

### Expected Behavior

Variables should be processed as in all other configuration files as described in https://symfony.com/doc/current/configuration/env_var_processors.html.

**Comment by dpfaffenbauer** [comment] 2023-10-11 07:43
Happens in 11 too right? I think this is the reason: https://github.com/pimcore/pimcore/pull/14263

Pimcore is processing configurations before symfony does its parts.

**Comment by simonkey** [comment] 2023-10-12 06:35
@dpfaffenbauer Yes, the issue happens in 11 too.

**Comment by dpfaffenbauer** [comment] 2023-10-12 08:04
@brusch maybe you can investigate? I feel Pimcore does something wrong

**Comment by cancan101** [comment] 2024-08-07 21:38
Is this still an issue (with v11.3)? I tried this:
```yaml
  config_location:
      object_custom_layouts:
        write_target:
          type: "%env(PIMCORE_WRITE_TARGET_OBJECT_CUSTOM_LAYOUTS)%"
```
and am getting this error:
```
PHP Fatal error:  Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: The value "" is not allowed for path "pimcore.config_location.object_custom_layouts.write_target.type". Permissible values: "symfony-config", "settings-store", "disabled" in /var/www/pimcore11/vendor/symfony/config/Definition/EnumNode.php:88
```
CC @kingjia90

**Comment by kingjia90** [comment] 2024-08-08 08:40
Confirming the issue
i will investigate a little more

**Comment by kingjia90** [comment] 2024-11-04 16:33
This seems related to https://github.com/symfony/symfony/issues/57958 

So the EnumNode 
https://github.com/pimcore/pimcore/blob/3ffaeac8d9f07f877ea4f469015be1774de447b9/bundles/CoreBundle/src/DependencyInjection/ConfigurationHelper.php#L58-L60
and the canBeDisabled (validating `true/false`?) https://github.com/pimcore/pimcore/blob/0a3bd0dfbd44c407f932cb5395c814f95f3fb77b/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L1234
might have the same runtime vs buildtime "discrepancy" under the hood.

@brusch could you please have a second look on this? TIA

**Comment by brusch** [comment] 2024-11-06 15:12
@kingjia90 is right, this is not a Pimcore issue, it's by design how Symfony Config works. 
See also: https://github.com/symfony/symfony/issues/57210#issuecomment-2136844261 (about `enabled:`) and https://github.com/symfony/symfony/issues/57958#issuecomment-2294904662 (about `type` enum). 

Yes, we can think / discuss about changing to runtime validation for certain use cases, but this is a different topic imho (not a bug). 
Looking at the config tree definition I'm afraid that there are quite some more config options are affected by this, so this is more a general question how Pimcore deals with that in future. 

To be honest, for the configs mentioned here, I'd prefer to keep the current behavior and use env specific configs during build time instead,  I don't see the point of changing the type of a storage or the full page cache at runtime  and this would need to get rid of all the Symfony best-practice of using things like `canBeEnabled()` for the config tree 🤔 Nonetheless I understand why this topic came up, see also the Symfony tickets above... 

Feel free to continue the discussion here, but I'll close this ticket at this point (see Symfony).

**Closed as completed by brusch** 2024-11-06 15:12 UTC
Labels: Bug, Pimcore:Priority

**Comment by cancan101** [comment] 2024-11-06 16:28
Is there any suggested workaround to accomplish something like:
```yaml
  config_location:
      object_custom_layouts:
        write_target:
          type: "%env(PIMCORE_WRITE_TARGET_OBJECT_CUSTOM_LAYOUTS)%"
```
Perhaps the ability to add specific Pimcore specific settings like: `PIMCORE_WRITE_TARGET_CUSTOM_LAYOUTS` akin to the existing `PIMCORE_CLASS_DEFINITION_WRITABLE`.
