### ISSUE TITLE
Mark the last key not dirty?! 

### ISSUE THREAD

**Issue by mike4git** [pimcore/pimcore#4999] opened 2019-09-20 10:16 UTC
In the ObjectBricks loading mechanism there is an error we were stumbling over.

In line 
https://github.com/pimcore/pimcore/blob/f57c214c2b53e56d420a09f1a4b8efd7bbe6cdd2/models/DataObject/Objectbrick/Dao.php#L111
the last key will be marked as NOT dirty but we are sure it should have been propably the object itself:
`$brick->markFieldDirty('_self', false);`

**Comment by weisswurstkanone** [comment] 2019-09-23 09:02
please provide the build number. thx!

**Comment by mike4git** [comment] 2019-09-23 09:40
Build number: v5.8.4 (which I have used for fixing)
But we guess that the following commit
https://github.com/pimcore/pimcore/commit/a0518623c639f27ec0a6ae195a3c4c8a8e6d19af#diff-30cd79ff8a376b104bc4bd82d778d0f7L99
has introduced this bug.

**Comment by weisswurstkanone** [comment] 2019-09-23 09:42
I would say already fixed via
https://github.com/pimcore/pimcore/issues/4677

**Comment by mike4git** [comment] 2019-09-23 10:47
In Issue #4677 you have corrected the saving of objects but not the loading.
And during the loading there should be no field marked as dirty, as well as the object itself.
But the markFieldDirty('_self') would not be deleted, if you would not use my change.
And the current code in the loading method is marking always the LAST $key as not dirty.
I would say this is development by accident, isn't it?!

1. The change should not happen in the save BUT in the load method.
2. The wrong line of code uses $key outside of the foreach block where it has been defined. (s. line 111 above)

**Comment by weisswurstkanone** [comment] 2019-09-23 10:56
still ... could you please try to reproduce this with at least the latest pimcore 5 build. please note that 5.8.4 is kind of outdated :-)

**Comment by mike4git** [comment] 2019-09-23 11:33
Nice try...but this didn't work ;-)

In the current version (master and 6.2.1 - https://github.com/pimcore/pimcore/blob/master/models/DataObject/Objectbrick/Dao.php) you can see the following code block (for convenience reason I've extracted it here):

```
public function load(DataObject\Concrete $object, $params = [])
{
        $fieldDef = $object->getClass()->getFieldDefinition($this->model->getFieldname());
        $values = [];
        ...
                foreach ($fieldDefinitions as $key => $fd) {
                    ...
                } // end of foreach, where $key has been defined


                $setter = 'set' . ucfirst($type);
                if ($brick instanceof DataObject\DirtyIndicatorInterface) {

                    // here $key is used again OUTSIDE of foreach
                    $brick->markFieldDirty($key, false);
                }
       
        ...
}
```
And because of that block our "last" object brick relation to our products have been deleted and not inserted again.

Please read the code, get an idea of what has gone wrong and take one of my two fixes.

**Comment by weisswurstkanone** [comment] 2019-09-23 11:49
ok, could you please create a PR for pimcore 6 ? thanks a lot!

**Comment by weisswurstkanone** [comment] 2019-09-23 12:18
as well as steps to reproduce on the pimcore demo instance please ;-)

**Comment by mike4git** [comment] 2019-09-23 13:04
I did it: https://github.com/pimcore/pimcore/pull/5001
But reproducing steps are NOT easily possible.

**Comment by weisswurstkanone** [comment] 2019-09-23 14:48
Also not able to reproduce it. However, you may have a valid point - which IMHO does not explain what you are describing here. BTW, I think we should replace it with resetDirtyMap because after loading the brick should be clean anyway.

Please don't forget to sign the CLA.

**Closed** 2019-10-24 06:50 UTC
