### ISSUE TITLE
Get wrong value in localizedfields when saving multiple localizedfields within a fieldcollection

### ISSUE THREAD

**Issue by ollegz** [pimcore/pimcore#2508] opened 2018-01-25 10:50 UTC
# Bug Report
The method "getDataFromObjectParam" (in pimcore/models/DataObject/ClassDefinition/Data.php) checks if there are any indexes when you do a get, but you don't do a get on save & publish so if you create multiple field collections on an object and save the backend doesn't know about the order and can override the old field collection with the newly created one.

### Expected behavior 
Get correct data in correct field collection.

### Actual behavior  
Get overruled data in wrong field collection. 
  
### Steps to reproduce  
1. Create a new FieldCollection with a localizedfields in it, and add a textfield.
2. Create a new Class with a fieldcollection field linking to the one created in step 1.
3. Create a new Object from class created in step 2.
4. Add a new fieldcollection and write a "1" in the localized text field.
5. Save and publish.
6. Refresh.
7. Add a new fieldcollection and move it above the first one. Write a "2" in the localized text field.
8. Save and publish, no refresh!
9. Add a new fieldcollection under the "2" and write a "3" in the localized text field.
10. Save and publish.
11. Refresh.

Result: The "1" fieldcollection now has a "2" in its localized text field. Taking the data from the first fieldcollection.

**Comment by weisswurstkanone** [comment] 2018-01-25 11:33
Can this reproduced on the pimcore demo instance ?

Please provide the build number we are talking about. thx!

**Comment by ollegz** [comment] 2018-01-25 11:37
Both 5.1.1 (build 185) and 4.6.2 as well as the pimcore demo instance. The steps to reproduce are from the demo 🕹

**Comment by weisswurstkanone** [comment] 2018-01-25 11:48
The order I see after performing all these steps is 2-3-1 which is what I would expect. Am I missing something here? Can you provide a video footage?

**Comment by ollegz** [comment] 2018-01-25 12:17
Of course, here is a video tutorial https://youtu.be/VkD3MTUa0oI 

Sorry about the video quality, just made a quick youtube.

**Comment by weisswurstkanone** [comment] 2018-01-25 12:28
Wait,  the video doesn't show the sequence you described above, right ? What about those deletions ?

**Comment by ollegz** [comment] 2018-01-25 12:40
I just wanted to show it twice (hence the deletions), because in the first sequence you couldn't see all fields in one page.

**Comment by weisswurstkanone** [comment] 2018-01-25 14:48
ok, got the point :-) the root cause is moving existing items around combined with saving the object without reloading it. the consequence is that the indices in the database don't match anymore with the ones in the UI.

fixed in build 188

**Comment by ollegz** [comment] 2018-01-25 14:57
Wooo! Yeah, that (root cause) is what I was trying to show in the video 😄

**Closed** 2018-01-26 09:07 UTC
Labels: Bug
