### ISSUE TITLE
[Improvement] Check possibilities of usage of symfony/flex

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#14355] opened 2023-02-16 09:06 UTC
### Improvement description

- are there changes need in Pimcore core to support symfony/flex? 
- create one/two blueprint bundles (public/private) to showcase how it can be used

**Comment by mattamon** [comment] 2023-03-03 10:16
# Symfony flex

## Require symfony/flex via composer
I tried to simply require `symfony/flex`.
Here are my findings so far to get a better feeling for the estimation:

### Composer questions
During the installation you will get asked the following questions. I used the `default` answers

```bash
symfony/flex (installed globally) contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "symfony/flex" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]
```

####  doctrine/doctrine-bundle
This one is causing problems later on
```bash
-  WARNING  doctrine/doctrine-bundle (>=2.8): From github.com/symfony/recipes:main
    The recipe for this package contains some Docker configuration.

    This may create/update docker-compose.yml or update Dockerfile (if it exists).

    Do you want to include Docker configuration from recipes?
    [y] Yes
    [n] No
    [p] Yes permanently, never ask again for this project
    [x] No permanently, never ask again for this project
    (defaults to y):
```

####  friendsofsymfony/jsrouting-bundle
Can also cause problems.
```bash
 -  WARNING  friendsofsymfony/jsrouting-bundle (>=2.3): From github.com/symfony/recipes-contrib:main
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/main/friendsofsymfony/jsrouting-bundle/2.3

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n):
```

####  google/apiclient
No problems experienced  while testing
```bash
  -  WARNING  google/apiclient (>=2.10): From github.com/symfony/recipes-contrib:main
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/main/google/apiclient/2.10

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n):
```
####  php-http/httplug-bundle
No problems experienced while testing, but will install a different version.
```bash
 -  WARNING  php-http/httplug-bundle (>=1.6): From github.com/symfony/recipes-contrib:main
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/main/php-http/httplug-bundle/1.6

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n):
```
### Many config files get added
Files do not get removed when uninstalling `symfony/flex`

```
        config/packages/ansi_to_html.yaml
        config/packages/cache.yaml
        config/packages/debug.yaml
        config/packages/doctrine.yaml
        config/packages/doctrine_migrations.yaml
        config/packages/flysystem.yaml
        config/packages/framework.yaml
        config/packages/lock.yaml
        config/packages/mailer.yaml
        config/packages/messenger.yaml
        config/packages/monolog.yaml
        config/packages/scheb_2fa.yaml
        config/packages/translation.yaml
        config/packages/twig.yaml
        config/packages/uid.yaml
        config/packages/validator.yaml
        config/packages/web_profiler.yaml
        config/packages/webpack_encore.yaml
        config/packages/workflow.yaml
        config/routes/framework.yaml
        config/routes/scheb_2fa.yaml
        config/routes/web_profiler.yaml

```

### Problems while composer install/update
The following error was showing while trying to clear the cache.
Root cause was the new `mailer.yaml` file that was created with symfony/flex
Deleting the file at least helped to get rid of the error.
```bash
 An error occurred when executing the "/usr/local/bin/php bin/console --ansi cache:clear --no-warmup --ignore-mainte
  nance-mode" command:

  Exit code: 255

  Symfony\Component\Config\Definition\Exception\InvalidConfigurationException {#5371
    #message: "Invalid configuration for path "framework.mailer": "dsn" and "transports" cannot be used together."
    #code: 0
    #file: "./vendor/symfony/config/Definition/BaseNode.php"
    #line: 408
    -previous: InvalidArgumentException {#5350
      #message: ""dsn" and "transports" cannot be used together."
      #code: 0
      #file: "./vendor/symfony/config/Definition/Builder/ExprBuilder.php"
      #line: 199
      trace: {
        ./vendor/symfony/config/Definition/Builder/ExprBuilder.php:199 { …}
        ./vendor/symfony/config/Definition/Builder/ExprBuilder.php:246 { …}
        ./vendor/symfony/config/Definition/BaseNode.php:400 { …}
        ./vendor/symfony/config/Definition/ArrayNode.php:232 { …}
        ./vendor/symfony/config/Definition/BaseNode.php:394 { …}
        ./vendor/symfony/config/Definition/Processor.php:36 { …}
        ./vendor/symfony/config/Definition/Processor.php:46 { …}
        ./vendor/symfony/dependency-injection/Extension/Extension.php:100 { …}
        ./vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:307 { …}
        ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:73 { …}
        ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42 { …}
        ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
        ./vendor/symfony/dependency-injection/ContainerBuilder.php:721 { …}
        ./vendor/symfony/http-kernel/Kernel.php:487 { …}
        ./vendor/pimcore/pimcore/lib/Kernel.php:258 { …}
        ./vendor/symfony/http-kernel/Kernel.php:709 { …}
        ./vendor/symfony/http-kernel/Kernel.php:122 { …}
        ./vendor/pimcore/pimcore/lib/Kernel.php:237 { …}
        ./vendor/pimcore/pimcore/lib/Bootstrap.php:248 { …}
        ./vendor/pimcore/pimcore/lib/Bootstrap.php:58 { …}
        ./bin/console:46 {
          › /** @var \Pimcore\Kernel $kernel */
          › $kernel = \Pimcore\Bootstrap::startupCli();
          › $application = new \Pimcore\Console\Application($kernel);
        }
      }
    }
    -path: null
    -containsHints: false
    trace: {
      ./vendor/symfony/config/Definition/BaseNode.php:408 { …}
      ./vendor/symfony/config/Definition/ArrayNode.php:232 { …}
      ./vendor/symfony/config/Definition/BaseNode.php:394 { …}
      ./vendor/symfony/config/Definition/Processor.php:36 { …}
      ./vendor/symfony/config/Definition/Processor.php:46 { …}
      ./vendor/symfony/dependency-injection/Extension/Extension.php:100 { …}
      ./vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:307 { …}
      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:73 { …}
      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42 { …}
      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
      ./vendor/symfony/dependency-injection/ContainerBuilder.php:721 { …}
      ./vendor/symfony/http-kernel/Kernel.php:487 { …}
      ./vendor/pimcore/pimcore/lib/Kernel.php:258 { …}
      ./vendor/symfony/http-kernel/Kernel.php:709 { …}
      ./vendor/symfony/http-kernel/Kernel.php:122 { …}
      ./vendor/pimcore/pimcore/lib/Kernel.php:237 { …}
      ./vendor/pimcore/pimcore/lib/Bootstrap.php:248 { …}
      ./vendor/pimcore/pimcore/lib/Bootstrap.php:58 { …}
      ./bin/console:46 {
        › /** @var \Pimcore\Kernel $kernel */
        › $kernel = \Pimcore\Bootstrap::startupCli();
        › $application = new \Pimcore\Console\Application($kernel);
      }
    }
  }


  2023-03-03T07:42:48+00:00 [critical] Uncaught Exception: Invalid configuration for path "framework.mailer": "dsn" a
  nd "transports" cannot be used together.
```

Another error with doctrine/orm occurred. The package was not installed automatically although the configs were set in the `doctrine.yaml` file.

```bash
  An error occurred when executing the "/usr/local/bin/php bin/console --ansi cache:clear --no-warmup --ignore-mainte
  nance-mode" command:

  Exit code: 255

  Symfony\Component\DependencyInjection\Exception\LogicException {#1932
    #message: "The doctrine/orm package is required when the doctrine.orm config is set."
    #code: 0
    #file: "./vendor/doctrine/doctrine-bundle/DependencyInjection/Configuration.php"
    #line: 376
    trace: {
      ./vendor/doctrine/doctrine-bundle/DependencyInjection/Configuration.php:376 { …}
      ./vendor/symfony/config/Definition/Builder/ExprBuilder.php:246 { …}
      ./vendor/symfony/config/Definition/BaseNode.php:330 { …}
      ./vendor/symfony/config/Definition/ArrayNode.php:269 { …}
      ./vendor/symfony/config/Definition/BaseNode.php:358 { …}
      ./vendor/symfony/config/Definition/Processor.php:32 { …}
      ./vendor/symfony/config/Definition/Processor.php:46 { …}
      ./vendor/symfony/dependency-injection/Extension/Extension.php:100 { …}
      ./vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php:81 { …}
      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:73 { …}
      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42 { …}
      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
      ./vendor/symfony/dependency-injection/ContainerBuilder.php:721 { …}
      ./vendor/symfony/http-kernel/Kernel.php:487 { …}
      ./vendor/pimcore/pimcore/lib/Kernel.php:258 { …}
      ./vendor/symfony/http-kernel/Kernel.php:709 { …}
      ./vendor/symfony/http-kernel/Kernel.php:122 { …}
      ./vendor/pimcore/pimcore/lib/Kernel.php:237 { …}
      ./vendor/pimcore/pimcore/lib/Bootstrap.php:248 { …}
      ./vendor/pimcore/pimcore/lib/Bootstrap.php:58 { …}
      ./bin/console:46 {
        › /** @var \Pimcore\Kernel $kernel */
        › $kernel = \Pimcore\Bootstrap::startupCli();
        › $application = new \Pimcore\Console\Application($kernel);
      }
    }
  }


  2023-03-03T08:02:08+00:00 [critical] Uncaught Exception: The doctrine/orm package is required when the doctrine.orm
   config is set.
```

`APP_SECRET` needed to be added to `.env` -> there is more to this in the next step


Docker compose down did not work anymore due to a new file `docker-compose.override.yml`. Deleting this file + removing some lines from the docker-compose.yaml solved this problem. Maybe this can be solved to choose `no` for first composer question.


### Problems after installing when trying to access localhost
After installing, the following error occurs if you try to open localhost or localhost/admin after login.

```console
An exception has been thrown during the rendering of a template ("Asset manifest file "/var/www/html/public/build/manifest.json" does not exist. Did you forget to build the assets with npm or yarn?").

After adding the manifest.json to public/build/manifest.json you can open the backend and the following errors appear in the console
GEThttp://localhost/js/routing?callback=fos.Router.setData
[HTTP/1.1 500 Internal Server Error 546ms]

Loading failed for the <script> with source “http://localhost/js/routing?callback=fos.Router.setData”. admin:95:1
unreachable code after return statement
ext-all.js:1568:12
Uncaught Error: The route "pimcore_admin_gdpr_dataobject_searchdataobjects" does not exist.
    getRoute http://localhost/bundles/fosjsrouting/js/router.js:133
    generate http://localhost/bundles/fosjsrouting/js/router.js:139
    <anonymous> http://localhost/admin/misc/script-proxy?storageFile=minified_javascript_core_b575bf299f4774f1cc0ca6b4cd82ffd9.js&_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:20664
router.js:133:15
Cannot create class with null properties! A possible case for this error is using the class pimcore.plugin.admin class.js:48:25
Uncaught Error: The route "pimcore_bundle_personalization_targeting_targetgrouplist" does not exist.
    getRoute http://localhost/bundles/fosjsrouting/js/router.js:133
    generate http://localhost/bundles/fosjsrouting/js/router.js:139
    initialize http://localhost/admin/misc/script-proxy?storageFile=minified_javascript_core_b586f323a2bad117782110d8c6afb446.js&_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:5904
    klass http://localhost/bundles/pimcoreadmin/js/lib/class.js?_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:33
    <anonymous> http://localhost/admin/misc/script-proxy?storageFile=minified_javascript_core_b586f323a2bad117782110d8c6afb446.js&_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:6030
router.js:133:15
Uncaught ReferenceError: L is not defined
    <anonymous> http://localhost/bundles/pimcoreadmin/js/pimcore/startup.js?_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:962
startup.js:962:1
When rendering the <html> element, the used values of CSS properties “writing-mode”, “direction”, and “text-orientation” on the <html> element are taken from the computed values of the <body> element, not from the <html> element’s own values. Consider setting these properties on the :root CSS pseudo-class. For more information see “The Principal Writing Mode” in https://www.w3.org/TR/css-writing-modes-3/#principal-flow ext-all.js:4033:259
Uncaught TypeError: pimcore.helpers.colorpicker is undefined
    <anonymous> http://localhost/bundles/pimcoreadmin/js/pimcore/startup.js?_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:76
    ExtJS 15
startup.js:76:5
Uncaught TypeError: pimcore.notification is undefined
    checkNewNotification http://localhost/bundles/pimcoreadmin/js/pimcore/startup.js?_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:943
    setInterval handler* http://localhost/bundles/pimcoreadmin/js/pimcore/startup.js?_dc=5e04da4bebed1c9365dbce12fd854e6e5c186710:942
```


APP_SECRET must be at least 256 bits long. If it is not, this will cause a problem with the PersonalizationBundle for the JWT Token.
```html
http://localhost/js/routing?callback=fos.Router.setData is failing because the provided key is too short in PersonalizationBundle
Key provided is shorter than 256 bits, only 24 bits provided
```

After all this steps, at least I was able to access localhost and localhost/admin again. 

There were still some errors in the console, but these are maybe unrelated to `symfony/flex`

### Trying to install bundles with flex
No errors so far, but I only installed a few bundles.
The configs could always cause errors with existing configs, though.

## Conclusion
Even by just requiring `symfony/flex` it takes some effort to make it work. 
Some configs must be set and changed to make the installation less challenging. 

It will also take some time to reconfigure the configs altogether and check if there are problems in other areas too.

**Comment by brusch** [comment] 2023-03-07 10:56
@mattamon thanks for sharing your findings 😊 
I guess most of the issues are caused by the fact that those bundles deliver recipes for creating a Symfony project from scratch. In our case we have most of the bundles already pre-configured by either our bundles or skeleton/demo ... 
Maybe there's a config flag to stop running recipes for certain bundles? 🤔

**Comment by dkarlovi** [comment] 2023-03-07 15:30
> In our case we have most of the bundles already pre-configured by either our bundles or skeleton/demo ...

That makes Pimcore mostly incompatible with the goals of Flex, the aim for it was to deprecate [Symfony's equivalent of skeleton/demo](https://github.com/symfony/symfony-standard).

**Comment by jdreesen** [comment] 2023-03-07 15:40
Can/should we also get rid of skeleton/demo and migrate to flex?

**Comment by dkarlovi** [comment] 2023-03-07 15:56
IMO that would probably be best long term since it aligns with what the underlying platform wants to do, also goes hand in hand with how Pimcore is trying to align itself with Symfony more and more, but it's obviously a big decision. :smile:

**Comment by dkarlovi** [comment] 2023-03-07 16:00
Ah, right: there exists an option **as an in-between step, where skeleton/demo ships `symfony.lock`**, thereby telling Flex to not run recipes for those bundles. It doesn't provide the greatest UX long term since, when the recipes update, Flex will hint to the user to rerun the recipes (which blows everything up), but the initial interaction will not be as broken as seen here.

**Comment by mattamon** [comment] 2023-03-07 16:03
> Ah, right: there exists an option **as an in-between step, where skeleton/demo ships `symfony.lock`**, thereby telling Flex to not run recipes for those bundles. It doesn't provide the greatest UX long term since, when the recipes update, Flex will hint to the user to rerun the recipes (which blows everything up), but the initial interaction will not be as broken as seen here.

Well at least it is good to know that something like that exists, but we would only shift the problem to another place as you mentioned yourself. 
So yes, this is a bigger decision, hence why we invest some time into this. :)

**Comment by dkarlovi** [comment] 2023-03-07 16:14
@mattamon if `symfony.lock` mentions the package being installed, Flex will not rerun the recipe so yeah, that's built in since day one, otherwise it wouldn't work and it would always overwrite your local changes instead of allowing the developer to do anything they want, which is one of the design goals of Flex.

We could pretend skeleton/demo did "whatever they wanted" and brought the app into the desired state, with a note saying recipe updates are currently not supported.

**Comment by dvesh3** [comment] 2023-03-27 13:13
We decided to move this 11.1 and still keep it optional on Pimcore 11.

**Comment by hirakch** [comment] 2023-12-26 08:00
do you have plan to take this up in 11.2.0 and what is the estimated timeline for 11.2.0?

**Comment by fashxp** [comment] 2024-01-08 09:01
there is no timeline defined yet for that topic

**Comment by kingjia90** [comment] 2024-08-05 07:59
I've tried to create a [skeleton flex project](https://github.com/kingjia90/flexskeleton) and [recipe](https://github.com/kingjia90/recipes) and it seem working fine but we have to align to their best practice.

The only cons that i have noticed so far is that IF a recipe of `bundle A` adds a line to "bundle.php" (eg. [statistic explorer](https://github.com/kingjia90/recipes/blob/fa619d4059e1ff265cada08c1d242afaeaaafef7/pimcore/statistics-explorer/2.1/manifest.json#L3)) and we install a `bundle X`(eg. portal engine) that requires `bundle A`, it would ask you to run the recipe of `bundle A` and there is no way to tell to skip as it would taken care by the `bundle X` tacitly via `registerDependentBundles()`.

Other than that, everything seem working fine, I've tried to install `bundle A` before `bundle X`(which also requires `bundle A`) and by removing `bundle X`, it leaves `bundle A` recipe changes unaffected as expected.

All the env variables will be [wrapped](https://github.com/kingjia90/recipes/blob/fa619d4059e1ff265cada08c1d242afaeaaafef7/pimcore/pimcore/11.3/manifest.json#L11-L12) by this [tag](https://github.com/kingjia90/flexskeleton/blob/f6b9e487b2dbcd0d766499c9e77328ffae127265/.env#L1-L3)
`###> pimcore/something ###` to allow symfony flex adding/removing lines.
![image](https://github.com/user-attachments/assets/de1fd3fa-2308-4ece-91d5-4997c27b2db9)

and we probably need to do a similar markup tags or placeholders for configs, when adding lines to a specific place that can be found by a text search eg.
https://github.com/kingjia90/recipes/blob/fa619d4059e1ff265cada08c1d242afaeaaafef7/pimcore/portal-engine/4.1/manifest.json#L5-L12

For [docker compose](https://github.com/kingjia90/recipes/blob/main/pimcore/pimcore/11.3/manifest.json#L14) and [git ignore](https://github.com/kingjia90/recipes/blob/fa619d4059e1ff265cada08c1d242afaeaaafef7/pimcore/pimcore/11.3/manifest.json#L110) it needs to be an array where each item is a line, which is not that readable/editable but maybe we can keep it as text and let a workflow convert it.


### Misc 
> Many config files get added

It seems that the best practice is to keep the configs in different files eg. `config/packages/bundlename.yaml` to easily manage them by the recipe script (eg. remove the yaml file when uninstalling a bundle)

and 
> Files do not get removed when uninstalling symfony/flex

seems also intended, uninstalling flex doesn't trigger any recipe unconfiguration, maybe to allow freely unrequire this bundle when in production.

**Comment by kingjia90** [comment] 2024-08-14 08:05
Closing the current issue for paperwork purposes (as the described task about feasibility check and a PoC to showcase are reached within the iteration).

Moving the actual implementation planning to https://github.com/pimcore/pimcore/issues/17496, please join/move the discussion there 😉

**Closed as completed by kingjia90** 2024-08-14 08:05 UTC
Labels: Improvement, PM, Pimcore:Backlog
