### ISSUE TITLE
[Bug]: Multisite Link

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#17473] opened 2024-08-09 08:53 UTC
### Pimcore version

11.x

### Steps to reproduce

Add 2 sites
- Site 1
- Site 2

Create in a wysiwyg on Site 1 a link to Site 2.

### Actual Behavior

The link is rendered as https://site2.comhttps//site2.com/link/to/path

### Expected Behavior

The link should be rendered as https://site2.com/link/to/path
or just /link/to/path (if it's on the same site).

I suspect it has something todo with #16892, because if I delete this change everything works as expected.
=> This PR was created because of #16595, but I can't reproduce this problem (it only shows the sitename in the wysiwyg link editor, what I think is correct).

**Comment by hethehe** [comment] 2024-08-09 09:09
Maybe the Problem from #16595 was that they used for example $pimcoreWysiwygObject->getData() instead of $pimcoreWysiwygObject->frontend().
with ->getData() you get the data which is stored in the database (that's correctly /site2/link/to/path)
with ->frontend() you get the data which can be used in the frontend (with some pimcore magic, like replacing of the href)

@kingjia90, @cadeyrn & @GALPR can you please re-check?

**Comment by kingjia90** [comment] 2024-08-09 09:18
Thank you for reporting and digging into it, just wondering, what's the `getRootPath()` and `$path` in your local instance (could you please put a breakpoint there or var dump the values)? 
Could it be that the regex replace is not working right or the rootpath is not configured as intended?

**Comment by hethehe** [comment] 2024-08-09 09:30
getRootPath() from site (Pimcore\Model\Site) is /site1
$path is the correct path (e.g. /link/to/path)

**Comment by kingjia90** [comment] 2024-08-09 09:52
did you mean `/site1/link/to/path`?

**Comment by hethehe** [comment] 2024-08-09 10:03
no $path it's already correct without /site1 in it.

**Comment by hethehe** [comment] 2024-08-09 11:33
update: 
if you're on site1 and the link is to site1 then the path is `/link/to/path`
if you're on site1 and the link is to site2 then the path is `https://url-from-site2.com/link/to/path`

If I'm not wrong then (Document) [`$element->getFullPath();`](https://github.com/pimcore/pimcore/blob/11.x/models/Document.php#L695) already consider the sites.

**Comment by hethehe** [comment] 2024-08-16 05:58
@kingjia90 could you already check this? Sorry for my impatience, but if I'm not wrong this is a breaking change.

**Comment by kingjia90** [comment] 2024-08-16 07:12
Had a deeper look and it could be that the link is already in the right domain and then `$site->getMainDomain()`would be accidentally prepend to an already valid multisite url

Please have a look and try out
https://github.com/pimcore/pimcore/pull/17501

Thank you in advance

**Comment by hethehe** [comment] 2024-08-16 08:23
It works for me, but I think it is still a breaking change, let me try to explain:

Before #16892 multisite links were stored in the database as `href="/siteX/link/to/path"` but in the frontend pimcore replaced it with the correct URL:  (`href="/link/to/path"` for same site or `href="https://url_of_site2/link/to/path"` for another site)
-> There was only a "problem" if you e.g. used `$pimcoreWysiwygEditable->getData()` instead of `->frontend()`, because:
- `getData()` method gets the original database value 
- `frontend()` method also gets the database value, but optimized for the frontend.

#16892 and #17501 change the behavior how the links are stored in the database. Now the full path incl. domain is stored in the database (e.g. `href="https://url_of_site1/link/to/path` for same site or `href="https://url_of_site2/link/to/path` for another site).

@kingjia90 WDYT

**Comment by kingjia90** [comment] 2024-08-16 09:26
Mhh, i see, but would that be a problem? 

The "href" is not a reliable value to work with, if you move/rename the linked document, it would stay hardcoded with a wrong href in the database until next load&save of the element referring to it, that's why should use the referenced element by id (custom html attributes in the tag) to get the latest path.

**Comment by hethehe** [comment] 2024-08-16 09:38
That's true, but then #16892 isn't necessary either (unless I've overlooked something).
But let's not complicate things unnecessarily, the PR works and fixes my issue, so for me it's OK.

**Comment by kingjia90** [comment] 2024-08-16 10:00
Fixed by https://github.com/pimcore/pimcore/pull/17501

Thank you again for your inputs and insight, it's now merged.

I believe that's necessary for sites to work properly,  at least in `frontend()` as there are no any other places where it consider the sites from this wysiwyg text parser. 
I can partly agree that it might be unnecessary in editmode eg. when calling [getDataEditMode()](https://github.com/pimcore/pimcore/blob/72958f53d0137b19ddb0ff5911a787861d5e7dbf/models/Document/Editable/Wysiwyg.php#L62) because the wysiwyg raw/soruce html and edit link popup(gui) would display the final absolute url instead of the internal relative path(which the latter would may make more sense from edit mode perspective), but to make such distinction may need to refactor a little more and may not fit in a bug fix (but minor/major).

If there's anything else popping up, feel free to open a new issue.

**Closed as completed by kingjia90** 2024-08-16 10:00 UTC
Labels: Bug
