### ISSUE TITLE
[Bug]: backend search update fails in high concurrency situations

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#13507] opened 2022-11-03 10:46 UTC
### Expected behavior

Search backend updates work.

### Actual behavior

We're seeing hundreds of deadlock messages and our workers constantly crashing.

### Steps to reproduce

Have a high rate of update (say, import 30k objects) and multiple workers (we use 4). The rate of deadlocks is very high which ends up crashing our workers (which rely on DBAL based messenger).

Looking at the code which saves, I can see it's doing a lot of weird work, catching deadlock and then trying to do it at random (?).

The issue is the query doing it is doing
```sql
INSERT ... ON DUPLICATE KEY UPDATE
```

which is [acquiring different types of locks](https://medium.com/@mingwho/mysql-deadlock-caused-by-insert-on-duplicate-key-update-893ef30993a8) than just a plain `INSERT`.

The solution might be to do it yourself by trying an INSERT and, if it fails, do an UPDATE. This wouldn't acquire [a gap lock](https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html#innodb-gap-locks) and should reduce the number of deadlocks significantly, probably making all the current deadlock-avoidance related code in the search DAO obsolete.

**Comment by dpfaffenbauer** [comment] 2022-11-18 09:47
Similar issue with UrlSlugs when running multiple workers handling the messages:

```
09:46:44 WARNING   [pimcore] Unable to finish transaction (1. run) because of the following reason 'An exception occurred while executing 'INSERT INTO object_url_slugs (`objectId`, `classId`, `fieldname`, `slug`, `siteId`, `ownertype`, `ownername`, `position`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [765236, "as_standard", "slug", "\/en\/nichtaktive-chirurgische-implantate-weichteilgewebeimplantate-besondere-anforderungen", 0, "localizedfield", "localizedfield", "en"]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction'. --> Retrying in 200000 microseconds ... (2 of 5)
```

**Comment by brusch** [comment] 2022-11-21 13:29
once https://github.com/pimcore/pimcore/pull/13613 is done, we should make a task list or individual tickets for changing this in all relevant places.

**Comment by dkarlovi** [comment] 2022-11-30 09:05
I can confirm the approach done in #13613 fixes the issue for us, we're no longer seeing worker crashes caused by deadlocks.

**Comment by dpfaffenbauer** [comment] 2022-11-30 09:08
@brusch The updateOrInsert is not used in the case for relations... so not sure what a good solution there is

**Comment by brusch** [comment] 2022-12-01 09:35
@dpfaffenbauer since @dkarlovi confirmed that #13613 fixes the issues, I'd implement that as it should be quite easy to change, right?

#13613 is merged now, anyone wants to provide us a PR with actual implementations?

**Comment by dpfaffenbauer** [comment] 2022-12-01 09:53
@brusch you mean for slugs?

**Comment by mcop1** [comment] 2023-02-15 15:09
So if I got everything right we want to replace all of the `insertOrUpdate` calls with `upsert` call? 

- [ ] Deprecate `insertOrUpdate` in 10.6
- [ ] Replace all ~40 occurences of `insertOrUpdate` with `upsert` and remove `insertOrUpdate` helper function
- [ ] Check https://github.com/pimcore/pimcore/blob/bbcc422de55bba2a4f83e4c07cfbd6ca5f6a2b5e/lib/Targeting/Storage/DbStorage.php#L140 & https://github.com/pimcore/pimcore/blob/bbcc422de55bba2a4f83e4c07cfbd6ca5f6a2b5e/lib/Targeting/Storage/DbStorage.php#L340
- [ ] Check https://github.com/pimcore/pimcore/blob/bbcc422de55bba2a4f83e4c07cfbd6ca5f6a2b5e/bundles/EcommerceFrameworkBundle/src/IndexService/Worker/DefaultFindologic.php#L288
- [ ] Check https://github.com/pimcore/pimcore/blob/3da90d1bbec8cbf2d45a4704428559212e56df0a/bundles/EcommerceFrameworkBundle/src/VoucherService/TokenManager/Single.php#L134

- [ ] Check all bundles, e.g. data-importer, simple-rest, webhooks

~~Check if we still need the deadlock detection and retry function~~ - we will keep the retry functionality

**Comment by dkarlovi** [comment] 2023-02-15 15:12
@mcop1 the deadlocks can still happen, they should just happen much less often.

**Closed as completed** 2023-02-28 07:47 UTC
Labels: Bug
