### ISSUE TITLE
TypeError in Website Settings if no language provided

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#5998] opened 2020-03-06 13:44 UTC
# Bug Report

Key collisions in *Website Settings* cause silent errors and the admin interface must be reloaded.

### Expected behavior

Similar to *Properties* on objects, if the same setting is added a second time with the first setting missing a Language, the admin interface should prevent this. Or just allow it without the "hidden" JS error.

### Actual behavior

The entire tab dies and the admin interface must be reloaded.

### Steps to reproduce

1. Open Website Settings
2. Add a setting, for example key: "testSetting" of type *Text*
3. Add a value to the setting.
4. Add a second new setting with the same key
5. Add a third new setting with the same key
6. Set a Language to the first setting
7. Try to set a Language to the second setting.

(You can also try this with the JS console open to see the ExtJS error: `TypeError: k.el is null`)

**Comment by weisswurstkanone** [comment] 2020-03-06 14:21
Unable to reproduce this on demo.pimcore.fun

**Comment by NiklasBr** [comment] 2020-03-06 14:55
I can't try this on demo.pimcore.fun because the regular user does not have permissions. Please try again with Chrome 80 or Firefox 73, but with these steps to reproduce:

1. Open the browser JS console
2. Open the Website Settings
3. Create three empty text settings with the same key, e.g. "testSetting"
4. Set the first one to any language,
5. Set the Value of that setting to any string
6. Press *tab* to move focus away.

The error should show up again.

**Comment by dvesh3** [comment] 2020-03-06 15:23
@NiklasBr can you please try on demo instance? it should be possible to create web settings https://demo.pimcore.fun/admin/?perspective=default we are not able to reproduce it.

**Comment by NiklasBr** [comment] 2020-03-06 15:33
Thanks @dvesh3 I can reproduce two types of errors :

1. Deleting settings with the same name will throw a delete on null error
2. The error described above

![Uploading Screenshot (4).png…]()
![Screenshot (5)](https://user-images.githubusercontent.com/279826/76097408-ef87b380-5fc7-11ea-9028-c4233464b4de.png)

**Comment by NiklasBr** [comment] 2020-04-10 21:45
Any news on this?

**Comment by dvesh3** [comment] 2020-04-16 10:14
Hey @NiklasBr we are not able to reproduce this issue. Can you please provide a fix? thanks!

**Comment by NiklasBr** [comment] 2020-04-16 10:27
Just make sure you follow my instructions to reproduce it, it's not hard :)

**Comment by NiklasBr** [comment] 2020-04-17 07:10
Here's a ten second video demonstrating it again:

[demo.pimcore.fun-js-error.zip](https://github.com/pimcore/pimcore/files/4491464/demo.pimcore.fun-js-error.zip)

**Comment by dvesh3** [comment] 2020-04-17 08:45
Thanks @NiklasBr for your efforts and time on reporting the issue. 
I can only reproduce the issue with **Tab key**  combination and moreover it looks like this is ExtJS cell editing bug and might be fixed in 6.5.1 version (please see https://forum.sencha.com/forum/showthread.php?330959-ExtJs-6-2-CellEditing-plugin-editor-el-dom-is-null)

**Comment by NiklasBr** [comment] 2020-04-17 09:35
Any plans on updating ExtJs? I see it is still at 6.0.0 with quite a lot of fixes in the 6.x version.

**Comment by brusch** [comment] 2020-04-17 09:37
Unfortunately 6.2.0 has some major bugs and is therefore not usable.

**Comment by NiklasBr** [comment] 2020-04-17 09:39
Those bugs are still in 6.7.0?

**Comment by brusch** [comment] 2020-04-17 09:41
No, but last GPLv3 release is 6.2.0 😉

**Comment by NiklasBr** [comment] 2020-04-17 18:29
> GPLv3

Seems version 7 is also available and is GPLv3-friendly, no?

**Comment by dvesh3** [comment] 2020-04-21 09:37
Should be fixed in ExtJS https://forum.sencha.com/forum/showthread.php?330959-ExtJs-6-2-CellEditing-plugin-editor-el-dom-is-null

**Comment by brusch** [comment] 2020-11-05 15:36
see #6362

**Closed by brusch** 2020-11-05 15:36 UTC
Labels: Bug, Third Party Bug
