### ISSUE TITLE
[Bug]: Method call not properly checked on DAO Listing

### ISSUE THREAD

**Issue by GAL-GC** [pimcore/pimcore#12152] opened 2022-05-18 14:49 UTC
### Expected behavior

If I use editables or dataobjects and edit them, there should be no uncaught exception.

### Actual behavior

I got this error:

```
Status: 500 | Internal Server Error
URL: /admin/object/tree-get-childs-by-id?_dc=1652881790330
Method: GET
Message: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Service.php:1727
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Service.php(1727): method_exists(NULL, 'getFieldDefinit...')
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Service.php(1759): Pimcore\Model\DataObject\Service::doResetDirtyMap(Object(Pimcore\Model\DataObject\Categorysort), NULL)
#2 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(356): Pimcore\Model\DataObject\Service::recursiveResetDirtyMap(Object(Pimcore\Model\DataObject\Categorysort))
#3 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(73): Pimcore\Model\DataObject\AbstractObject::getById(24)
#4 [internal function]: Pimcore\Model\DataObject\Listing\Dao->load()
#5 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(246): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(145): Pimcore\Model\AbstractModel->__call('load', Array)
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->treeGetChildsByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 {main}
```

### Steps to reproduce

Unfortunately I couldn't find out, when this happend, but when this happens, the only way to get rid of it, is to restore the database.

**Comment by fashxp** [comment] 2022-05-23 12:13
can you please share a bit more information to reproduce it? 
like what classes, what attributes? etc.?

**Comment by brusch** [comment] 2022-05-31 09:05
Very interesting case ... as `doResetDirtyMap´()` is only used in 2 places and in both cases it's not intendet to be `null` ... 

See: 
https://github.com/pimcore/pimcore/blob/1f11981d5ac17ec19dfff77025ca465f1bc12966/models/DataObject/Service.php#L1759
https://github.com/pimcore/pimcore/blob/1f11981d5ac17ec19dfff77025ca465f1bc12966/models/DataObject/Service.php#L1743

A quick fix would be to add a null check, but I think it would be better to find the root cause for your issue first ...

**Comment by GAL-GC** [comment] 2022-05-31 09:10
Unfortunately I haven't found out yet, how I can reproduce this behavior. I had this issue once and a few other colleges had this too some while ago.

Of course, once I have more information, I'll let you know

**Comment by kingjia90** [comment] 2022-06-07 15:44
~The Class definition seems it can be `null`, when it doesn't find the definition file.
It actually "became" nullable to fix phpstan errors, but it shouldn't be the norm as it would lead to further problems, right?
https://github.com/pimcore/pimcore/blob/ea64c5efc36d4504206c7c530eba4be62694e4a5/models/DataObject/ClassDefinition.php#L272~
~That's something that could be affecting/important to know for  #12212 / #12280~



@GAL-GC  I was unable to reproduce the problem ,but If this happens again, please check if `id` (24) and `name` in `var/classes/definition_Categorysort.php` matches with the values in the db table `classes` and the name appearing in the filename. 
Since it is fixed by restoring the database, i guess it could be related to something in the `classes` table, eg. someone renamed the classes name.

If it's file related, by removing the `@` that suppress any warning/errors, it should provide a better feedback about the problem.
https://github.com/pimcore/pimcore/blob/ea64c5efc36d4504206c7c530eba4be62694e4a5/models/DataObject/ClassDefinition.php#L293

**Comment by kingjia90** [comment] 2022-06-22 06:07
I am closing for the moment, the class definition returning `null` is fine because the `getById` could be used to check wheter the class exists or not, but reaching to that point `doResetDirtyMap` and still returning `null` may indicate some other underlying problem. We would need more information to be able to reproduce it, if you have any, please re-open this issue or open a new one citing this one

**Closed as not planned by kingjia90** 2022-06-22 06:07 UTC
Labels: Bug
