### ISSUE TITLE
[Classification Store] Inheritance not working for PHP API

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#14367] opened 2023-02-16 17:03 UTC
### Expected behavior

`getGroups()`, `getItems()` and other methods of `Pimcore\Model\DataObject\ClassificationStore` should support inheritance.

### Actual behavior

Only if a data field is filled a record in `object_classificationstore_groups_<class id>` gets added. If the classification store is completely inherited it gets shown correctly in the backend. But when using PHP API function `getGroups()` returns an emtpy array.

### Steps to reproduce

1. Create classification store with some groups and fields
2. Create class `Abc`, enable inheritance, add classification store field `classificationStore`.
3. Create object `/parent`, add classification store group and set some field values
4. Create object `/parent/child`

In backend you see the inherited fields.

With PHP script:
```php
$object = \Pimcore\Model\DataObject\Abc::getByPath('/parent/child');
var_dump($object->getClassificationStore()->getGroups()); // returns []
```

Similar issue like #6447 - there it was referenced to use `getLocalizedKeyValue()` which supports inheritance. This is correct but how to get all assigned groups of an object including the inherited ones?

**Comment by fashxp** [comment] 2023-02-17 07:57
related to https://github.com/pimcore/pimcore/issues/3569
and wasn't that fixed with https://github.com/pimcore/pimcore/issues/5129?

**Comment by robertSt7** [comment] 2023-02-23 10:23
https://github.com/pimcore/pimcore/blob/e72eb19f3332c6a1e2cfbfe236b14dfb5018fe0e/models/DataObject/Classificationstore.php#L507 
The problem is that we only get the active groups and the inherited object hasn't no active groups until you change them.  It's the same with the GroupCollections

**Closed as completed** 2023-03-14 07:53 UTC
Labels: Bug
