### ISSUE TITLE
[Bug]: URL Slug fields disappeard since 10.3.2

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11693] opened 2022-03-17 10:34 UTC
### Expected behavior

All URL Slug fields in a localizedfield should be visible and possible to edit.

### Actual behavior

In 10.3.2 and 10.3.3 the value field is gone. Only the fallback is visible where there should be two fields:
![image](https://user-images.githubusercontent.com/279826/158791629-a8d0b4d3-6704-4529-ae6f-72597e1f876e.png)
![image](https://user-images.githubusercontent.com/279826/158792346-be4143cb-a561-4b5d-aa2a-dc7682d2059f.png)

Data is still sent to the frontend, but not rendered:
![image](https://user-images.githubusercontent.com/279826/158805087-e8b7b482-7038-4c4d-8a4f-3b23670327f9.png)

### Steps to reproduce

Add a URL Slug to a Localized field.

Selecting all Sites in the Class Definition does not help.

**Comment by NiklasBr** [comment] 2022-03-17 10:35
(cannot reproduce since demo.pimcore.fun is down)

**Comment by NiklasBr** [comment] 2022-03-17 10:36
Possibly the same as #10604

**Comment by dvesh3** [comment] 2022-03-17 12:12
duplicate of #10604

**Closed as completed by dvesh3** 2022-03-17 12:12 UTC
Labels: Bug
