### ISSUE TITLE
"owner missing" error after upgrading from 6.0.x/6.6.9 to current 6.7.2

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#7226] opened 2020-10-02 13:08 UTC
# Bug-Report

We updated 2 pimcore instances (one from 6.0.x and one from 6.6.9) to the current version of pimcore.
After this update the "owner missing" error appears, when opening an object with blocks.
After a "cache clear" the error disappears for a random time, but then comes back again.

Maybe a regression of #6280 ?

**Comment by dvesh3** [comment] 2020-10-06 12:05
@dpfahlbusch Unable to reproduce. Could you please try on latest version 6.8.0?

**Comment by dpfahlbusch** [comment] 2020-10-06 12:37
I will try it with the latest version

**Comment by tom0815** [comment] 2020-10-12 14:10
We had the same problem. After bin/console pimcore:cache:clear i could load the object once. It seems with "lazy loading" for the block no data for the block field is stored in table "cache". Disabling lazy loading fixed the problem for now.

**Comment by dpfahlbusch** [comment] 2020-10-12 17:44
I will try that workaround.

**Comment by dpfahlbusch** [comment] 2020-10-14 09:51
Disabling lazy loading "fixed" the problem with the "owner missing" error, but in one instance we cant disable lazy loading for blocks, because without it, the hole instance is really slow.
Maybe there IS a problem/bug with owneraware blocks?

**Comment by Ben-WD** [comment] 2020-10-16 15:18
I'm seeing exactly the same issue. With lazy loading enabled, the object cannot be loaded because of the "owner missing" error.

**Comment by brusch** [comment] 2020-10-23 07:55
Fixed by #7360

**Closed by brusch** 2020-10-23 07:55 UTC
Labels: Bug
