### ISSUE TITLE
New messenger queue for recalculating dependencies on save/update of elements

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore#15378] opened 2023-06-14 15:04 UTC
### Improvement description

Please see https://github.com/pimcore/pimcore/issues/15426#issuecomment-2089991720 and https://github.com/pimcore/pimcore/pull/15280#discussion_r1211346600

**Comment by brusch** [comment] 2023-06-14 15:09
We need to check if this could have some negative side-effects in terms of data consistency (cleanups, ...)

**Comment by fashxp** [comment] 2024-06-03 09:36
duplicate of https://github.com/pimcore/pimcore/issues/15426

**Closed as completed by fashxp** 2024-06-03 09:36 UTC
Labels: Pimcore:Backlog
