### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abdelrhmanyosry** [pimcore/pimcore#16014] opened 2023-09-27 11:57 UTC
### Pimcore version

11

### Steps to reproduce

go any folders and create some objects then go grid option -> add a new Grid option -> save 

![image](https://github.com/pimcore/pimcore/assets/121692656/295cc0a0-87d6-4f8a-8522-fe57d8986279)
![image](https://github.com/pimcore/pimcore/assets/121692656/478cf45e-459a-4969-a44d-3320146747ee)

### Actual Behavior

doesn't create new gridoption

### Expected Behavior

it should create new grid option to display the objects and save it

**Comment by aryaantony92** [comment] 2023-10-05 09:21
@abdelrhmanyosry I am not able to reproduce the issue. Could you please check again with the latest version of pimcore (11.0.11) ?

**Comment by dvesh3** [comment] 2023-10-05 09:23
Seems related to https://github.com/pimcore/pimcore/issues/15359

**Comment by aryaantony92** [comment] 2023-10-06 08:54
@abdelrhmanyosry Could you please check if your database table 'gridconfigs' contains the column 'setAsFavourite'. If not, could you please check whether this migration https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20211016084043.php is  executed ?

**Comment by aryaantony92** [comment] 2023-10-11 08:51
Closed as not reproducible.

**Closed as not planned by aryaantony92** 2023-10-11 08:51 UTC
Labels: Bug
