### ISSUE TITLE
[Bug]: Public share - doesn't work with more than 1 item

### ISSUE THREAD

**Issue by axessandro** [pimcore/pimcore#16206] opened 2023-11-06 13:20 UTC
### Pimcore version

11.0.5

### Steps to reproduce

Add more than one item in collection and then create a public share from this collection. 

![Screenshot 2023-11-06 alle 14 16 21](https://github.com/pimcore/pimcore/assets/104524529/d15a375c-32bc-4fdf-9216-f97c64436462)

### Actual Behavior

Warning message `portal-engine.public-share.is-empty`

### Expected Behavior

Listing page of all element shared

**Comment by kingjia90** [comment] 2023-11-06 14:36
Closing as it is in the wrong repository, duplicate of https://github.com/pimcore/portal-engine/issues/455

**Closed as not planned by kingjia90** 2023-11-06 14:36 UTC
Labels: Bug

**Comment by axessandro** [comment] 2023-11-06 15:25
@kingjia90 I'm sorry. I can't see repository and repository's issues
![Screenshot 2023-11-06 alle 16 23 46](https://github.com/pimcore/pimcore/assets/104524529/8b82593c-fecb-4a24-b266-1cee3a179c7b)

**Comment by kingjia90** [comment] 2023-11-06 15:32
Are you working for a Pimcore Partner that has Enterprise Edition?

**Comment by axessandro** [comment] 2023-11-06 15:34
@kingjia90 yes, I work for Jakala who has customers with enterprise license. Is there a way to have access to that repository, in order to track issue fixing progression?

**Comment by kingjia90** [comment] 2023-11-06 15:43
Please contact [enterprise-support@pimcore.com](mailto:enterprise-support@pimcore.com) then.
Unfortunately, I don't have right to grant access to that private repository, but just to let you know, we are already checking on the same exact issue you have reported here (or maybe it was a your co-worker from Jakala Spain or so).
