### ISSUE TITLE
[DOC] Add setHideUnpublished purpose in the doc and that it is setted by default to true for admin plugin

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2158] opened 2017-10-24 15:00 UTC
Using getObjects method, on an objectList, contains unpublished object, but using foreach on the objectList prevent unpublished object as intended.

To reproduce:

```
$myobjectList = new Pimcore\Model\Object\Myobject\Listing();
$myobjectList->load();

var_dump($myobjectList->getObjects()); // display unpublished object: NOK, it should not display unpublished object

foreach ($myobjectList as $myobject) var_dump($myobject); // don't display unpublished object: OK
```

Environment: Pimcore 4 Stable (Version: 4.3., Build: 3961).
I don't know if same problem is on Pimcore 5 too.

**Comment by jbq** [comment] 2017-10-24 15:25
Did you call this method in your code? `Object\AbstractObject::setHideUnpublished(true);`  This should be the standard setting.

**Comment by Yivan** [comment] 2017-10-24 15:25
I found why it acted like that. this is because it is an action extending the admin controller. I think it allow by default the unpublished default.
By adding \Pimcore\Model\Object\AbstractObject::setHideUnpublished(true); it works well.

**Comment by Yivan** [comment] 2017-10-24 15:26
Thanks @jbq i just found the solution as you said it!

**Comment by Yivan** [comment] 2017-10-24 15:29
**For the pimcore team: maybe `setHideUnpublished` should be mentionned in the documentation**
(i searched for it on pimcore 4&5 doc, but 0 result).
It should be added too that by extending admin controller (when developping a plugin in my case), this flag is set to false (at the pre-dispatch i think...).

**Comment by fashxp** [comment] 2017-10-25 04:38
hi, pull requests are always welcome ;-)
https://pimcore.com/docs/5.0.x/Objects/Working_with_PHP_API.html would be a good place?

**Comment by jbq** [comment] 2017-10-25 16:11
@Yivan glad to hear the problem is resolved.  You can submit doc updates, see the source code at https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md

**Comment by Yivan** [comment] 2017-10-27 15:28
Thanks @jbq @maff 
PR is submited here https://github.com/pimcore/pimcore/pull/2173

**Comment by weisswurstkanone** [comment] 2017-10-30 10:51
PR merged

**Closed by weisswurstkanone** 2017-10-30 10:51 UTC
