### ISSUE TITLE
Image thumbnails disappears from asset listing 

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5306] opened 2019-11-21 11:51 UTC
### Expected behavior
The image thumbnails must not disappear from asset preview listing(Preview Tab)
### Actual behavior
Image thumbnails disappears from asset listing if we hover again on the assets in the asset tree
### Steps to reproduce

- Open asset folder.
- Now expand that folder in tree and quickly hover some of the assets.
- Those assets  disappears from the asset listing.

![asset](https://user-images.githubusercontent.com/21308144/69335512-21784280-0c83-11ea-9514-31aafd7ef77a.png)

![asset-list-2](https://user-images.githubusercontent.com/21308144/69335517-263cf680-0c83-11ea-85cd-35c658442f46.png)

**Comment by dvesh3** [comment] 2019-11-21 14:29
cannot reproduce!..do you see any error on console?

**Comment by neha04** [comment] 2019-11-22 07:12
No,There was no error in console.You may also try opening a folder.Then open a few images from the tree(open those that are visible in the preview list).Now open folder using tab panel.

**Comment by neha04** [comment] 2019-11-22 07:19
[image.zip](https://github.com/pimcore/pimcore/files/3878347/image.zip)

**Comment by thgross** [comment] 2019-11-22 09:25
This happens to me, too. Only in Chrome.

**Comment by dvesh3** [comment] 2019-11-22 13:00
Please share Chrome version.

**Comment by thgross** [comment] 2019-11-22 20:35
My current Chrome Version is 78.0.3904.108. It happened for at least 3 major Chrome releases, so this problem is not bound to a specific version of Chrome.

It might happen only on Chrome / Windows 10, though.

**Comment by neha04** [comment] 2019-11-25 06:38
My current Chrome Version is Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by AlternateIf** [comment] 2019-12-04 13:45
can also reproduce this on the pimcore demo. oddly this is only reproducible if the chrome console is not opened upon site load

@dvesh3

**Comment by dvesh3** [comment] 2019-12-05 09:06
@AlternateIf thanks for reporting. Yes, I can **only** reproduce this on pimcore.demo and very random.

**Comment by dvesh3** [comment] 2019-12-05 13:00
Resolved by b8001f3e63e35e82a9e0ba6dd2fb2c70d124d513

root cause: same url `/admin/asset/get-image-thumbnail?id={assetId}&treepreview=true` used for both `grid preivew` & `tree preview`. so when you move quickly over tree grid which then calls the same image url and moves out then it cancels the request which leads to corrupted image in grid preview.
![image](https://user-images.githubusercontent.com/5137917/70237144-c48e8900-1766-11ea-9d42-0ed89d02a74e.png)

Fix: Added extra param to grid preview image url

**Closed by dvesh3** 2019-12-05 13:00 UTC
Labels: Bug
