### ISSUE TITLE
[Bug]: Exception on execute ClassesDefinitionsBuildCommand

### ISSUE THREAD

**Issue by nsd0sneumann** [pimcore/pimcore#16157] opened 2023-10-27 08:19 UTC
### Pimcore version

11.1

### Steps to reproduce

- update from v11.0.12 to v11.1 

- call the command

`pimcore/bin/console pimcore:build:classes`

### Actual Behavior

![exception](https://github.com/pimcore/pimcore/assets/95299884/4c7cf9f7-e0a3-4acc-b29f-65235b986012)

### Expected Behavior

update to v11.1 and call of the command possible without error

**Comment by jdreesen** [comment] 2023-10-27 12:41
I think we need some sort of regression/smoke test for this command, as it's not the first time it broke.

**Comment by dpfaffenbauer** [comment] 2023-10-27 14:42
But is it really broken or is something with your configuration broken? It looks like the database server cannot be resolved or not reached?

**Comment by jdreesen** [comment] 2023-10-27 15:38
But this command shouldn't need the database! It should just regenerate the source code of the classes.

**Comment by dpfaffenbauer** [comment] 2023-10-27 16:58
@jdreesen right. I should know, I created that :D

**Comment by alessandrofilira** [comment] 2023-11-07 13:48
Hi @dpfaffenbauer, do you have any news about this issue? Thanks for your support and your work

**Comment by jdreesen** [comment] 2023-11-16 10:33
@dvesh3, etc. could you please consider this for the next release? It breaks deployments with version `11.1`.

**Comment by dpfaffenbauer** [comment] 2023-11-21 17:35
@dvesh3 This is the reason:

```
line 49:
                                                                                                                                                   
  [Doctrine\DBAL\Exception\TableNotFoundException (1146)]                                                                                          
  An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.settings_store' doesn't exist  
                                                                                                                                                   

Exception trace:
  at /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:49
 Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:1938
 Doctrine\DBAL\Connection->handleDriverException() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:1880
 Doctrine\DBAL\Connection->convertExceptionDuringQuery() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:1105
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:952
 Doctrine\DBAL\Connection->fetchFirstColumn() at /var/www/html/vendor/pimcore/pimcore/models/Tool/SettingsStore/Dao.php:76
 Pimcore\Model\Tool\SettingsStore\Dao->getIdsByScope() at /var/www/html/vendor/pimcore/pimcore/models/Tool/SettingsStore.php:131
 Pimcore\Model\Tool\SettingsStore::getIdsByScope() at /var/www/html/vendor/pimcore/pimcore/lib/Config/LocationAwareConfigRepository.php:262
 Pimcore\Config\LocationAwareConfigRepository->fetchAllKeys() at /var/www/html/vendor/pimcore/pimcore/lib/Model/Dao/PimcoreLocationAwareConfigDao.php:76
 Pimcore\Model\Dao\PimcoreLocationAwareConfigDao->loadIdList() at /var/www/html/vendor/pimcore/pimcore/models/DataObject/SelectOptions/Config/Listing/Dao.php:31
 Pimcore\Model\DataObject\SelectOptions\Config\Listing\Dao->loadList() at /var/www/html/vendor/pimcore/pimcore/models/DataObject/SelectOptions/Config/Listing.php:39
 Pimcore\Model\DataObject\SelectOptions\Config\Listing->getSelectOptions() at /var/www/html/vendor/pimcore/pimcore/models/DataObject/SelectOptions/Config/Listing.php:72
 Pimcore\Model\DataObject\SelectOptions\Config\Listing->getIterator() at /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php:82
 Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1081
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:91
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:320
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:174
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:51

In Exception.php line 28:
                                                                                                    
  [Doctrine\DBAL\Driver\PDO\Exception (1146)]                                                       
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.settings_store' doesn't exist  
```

**Comment by dpfaffenbauer** [comment] 2023-11-21 17:49
@dvesh3 The new Select Options feature in combination with the SettingsStore is the problem here (https://github.com/pimcore/pimcore/pull/14454). It tries to create the PHP Enums with configurations from the database. That can never work in reality. How can we solve that as fast as possible?

**Comment by dvesh3** [comment] 2023-11-22 09:12
Thanks @dpfaffenbauer for your findings. This also concerns other data types like `language` with which tries to load valid languages from db (when system settings are stored on settingsStore) so we need a generic fix (please see https://github.com/pimcore/pimcore/pull/16281) and also adding notices to the docs that using settings store requires db service in deployment setup.

The quick workaround is to use `system-config` on source instances and consider the config files for deployment scenarios:
```yaml
pimcore:
    config_location:
        select_options:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/var/www/html/var/config/select_options'
```

**Comment by dpfaffenbauer** [comment] 2023-11-22 09:30
@dvesh3 Yes. That sounds about right. is it possible then to not trying to connect to the DB at all when symfony-config is configured?

**Comment by dvesh3** [comment] 2023-11-22 10:12
@dpfaffenbauer yes, this shouldn't happen now with this fix https://github.com/pimcore/pimcore/pull/16281/files#diff-aea6f63bf38b8863f731103a59f9a169a7ebd704dd223cb40a3813b1f94b737b

Could you please give it try? thanks!

**Comment by dpfaffenbauer** [comment] 2023-11-22 10:15
The Try/Catch doesn't feel right. It is sort of an expectation thing. With the try/catch you expect in some situations to work and in some not. so it behaves differently. We don't want differently, we want the same behaviour. Hope you know what I mean

**Comment by dvesh3** [comment] 2023-11-23 11:02
@dpfaffenbauer got your point :+1:  We'll come up with a proper fix then to handle it on using `symfony-config` so it doesn't break.

**Comment by brusch** [comment] 2023-12-06 16:16
Ok, found a possible non-breaking fix. 
What we need to do is enabling the `read_target` option for the `select_options` node in `config_location`, here: 
https://github.com/pimcore/pimcore/blob/bcedd91f80c321b748e0024e8c2c65190bba793b/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L142

Then we can make a default config like this: 
```yaml
pimcore: 
    config_location:
        select_options:
            read_target:
                type: 'symfony-config'
```

If you'd like to use `settings-store` or the fallback mechanism, you'd need to change the default config.

**Comment by brusch** [comment] 2023-12-06 16:28
Created a PR with the approach shared above: https://github.com/pimcore/ee-pimcore/pull/19

**Comment by dpfaffenbauer** [comment] 2023-12-06 20:05
@brusch how should someone (besides pimcore) now review that?

**Comment by dpfaffenbauer** [comment] 2023-12-14 14:09
@brusch any eta? this is quite blocking

**Comment by kingjia90** [comment] 2023-12-21 13:32
Fixed by https://github.com/pimcore/pimcore/commit/7a5aaf31e4f48a08b1656a6133a23b90cef32656 in https://github.com/pimcore/pimcore/pull/16380 (`v11.1.4`)

**Comment by dpfaffenbauer** [comment] 2023-12-21 13:47
@kingjia90 nope, still not working

```

In ExceptionConverter.php line 101:
                                                                                                                                                                    
  [Doctrine\DBAL\Exception\ConnectionException (2002)]                                                                                                              
  An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known  
                                                                                                                                                                    

Exception trace:
  at vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101
 Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at vendor/doctrine/dbal/src/Connection.php:1938
 Doctrine\DBAL\Connection->handleDriverException() at vendor/doctrine/dbal/src/Connection.php:1886
 Doctrine\DBAL\Connection->convertException() at vendor/doctrine/dbal/src/Connection.php:379
 Doctrine\DBAL\Connection->connect() at vendor/doctrine/dbal/src/Connection.php:1654
 Doctrine\DBAL\Connection->getWrappedConnection() at vendor/doctrine/dbal/src/Connection.php:1081
 Doctrine\DBAL\Connection->executeQuery() at vendor/doctrine/dbal/src/Connection.php:952
 Doctrine\DBAL\Connection->fetchFirstColumn() at vendor/pimcore/pimcore/models/Tool/SettingsStore/Dao.php:76
 Pimcore\Model\Tool\SettingsStore\Dao->getIdsByScope() at vendor/pimcore/pimcore/models/Tool/SettingsStore.php:131
 Pimcore\Model\Tool\SettingsStore::getIdsByScope() at vendor/pimcore/pimcore/lib/Config/LocationAwareConfigRepository.php:262
 Pimcore\Config\LocationAwareConfigRepository->fetchAllKeys() at vendor/pimcore/pimcore/lib/Model/Dao/PimcoreLocationAwareConfigDao.php:76
 Pimcore\Model\Dao\PimcoreLocationAwareConfigDao->loadIdList() at vendor/pimcore/pimcore/models/DataObject/SelectOptions/Config/Listing/Dao.php:31
 Pimcore\Model\DataObject\SelectOptions\Config\Listing\Dao->loadList() at vendor/pimcore/pimcore/models/DataObject/SelectOptions/Config/Listing.php:39
 Pimcore\Model\DataObject\SelectOptions\Config\Listing->getSelectOptions() at vendor/pimcore/pimcore/models/DataObject/SelectOptions/Config/Listing.php:72
 Pimcore\Model\DataObject\SelectOptions\Config\Listing->getIterator() at vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php:81
 Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand->execute() at vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/framework-bundle/Console/Application.php:126
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at bin/console:51

```

**Comment by kingjia90** [comment] 2024-01-11 09:18
@dpfaffenbauer does https://github.com/pimcore/pimcore/pull/16446 help fixing that?

**Comment by kingjia90** [comment] 2024-01-15 10:39
Closing as https://github.com/pimcore/pimcore/issues/16157#issuecomment-1866278445 seem fixed by https://github.com/pimcore/pimcore/pull/16446

**Closed as completed by kingjia90** 2024-01-15 10:39 UTC
Labels: Bug
