### ISSUE TITLE
Error on Successfully Completing Data Import

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5061] opened 2019-10-07 12:04 UTC
On completing the data import error is displayed in popup.
Following are the resolver settings used along with the screenshot of errors

![resolver settings used](https://user-images.githubusercontent.com/21308144/66309966-99371b80-e928-11e9-8dda-538e682d1027.png)

![error2](https://user-images.githubusercontent.com/21308144/66309969-99371b80-e928-11e9-9354-6f707c3fdaa5.png)

![error1](https://user-images.githubusercontent.com/21308144/66309971-99371b80-e928-11e9-8a5a-2a41e8ab5d10.png)

**Comment by weisswurstkanone** [comment] 2019-10-07 12:13
Unable to reproduce. Seems to be specific to your data.
Is the CSV preview displayed correctly. Maybe there is something wrong with the CSV Settings (e.g. delimiter)

**Comment by neha04** [comment] 2019-10-07 13:11
This is the test csv file that i have used.Always getting this error irrespective of file.I have tried with multiple files.I have tested this on demo basic instance.
[test.zip](https://github.com/pimcore/pimcore/files/3697488/test.zip)

**Comment by weisswurstkanone** [comment] 2019-10-07 14:05
Changed so that the only the last __empty__ row in your sample is marked as error.

![image](https://user-images.githubusercontent.com/6142086/66318765-38094b00-e91c-11e9-9cae-73c65d1f723b.png)

**Closed by weisswurstkanone** 2019-10-07 14:05 UTC
