### ISSUE TITLE
[Bug]: var/tmp is filled up with endless copies of video files

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#9696] opened 2021-07-07 09:15 UTC
### Expected behavior

pimcore does not create many temporary files of the same video-asset.

### Actual behavior

whenever you open a page that contains a pimcore_video editable, pimcore creates a new temporary file for the video in var/tmp, for example:
var/tmp/temp-file-60e56b46a6bbd-c033b2f0298a96fd7174e8279d88e0.mp4
another file with another name gets created on every reload.

### Steps to reproduce

- open https://demo.pimcore.fun/en/Magazine/Pick%20of%20the%20Day or open the page in pimcore: https://demo.pimcore.fun/admin/login/deeplink?document_104_page. The name of the video is Volkswagen-Van.mp4.
- take a look at var/tmp. A seperate file is created on each reload.

**Comment by brusch** [comment] 2021-07-07 09:17
Duplicate of #9583

**Comment by brusch** [comment] 2021-07-07 09:18
Would be nice if you could debug this and provide a fix as a PR 😊

**Closed as completed by brusch** 2021-07-07 09:17 UTC
Labels: Bug

**Comment by thgross** [comment] 2021-07-07 09:20
I'm sorry, I was searching the issues for this, but unfortunately didn't find #9583.
