### ISSUE TITLE
Object UI breaks if checkbox or Calculated field is added under field container

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2919] opened 2018-06-11 10:08 UTC
### Expected behavior 
  Object UI must not break , if checkbox or Calculated field is added under field container
### Actual behavior  
  Object UI breaks if checkbox or Calculated field is added under field container
### Steps to reproduce  
 Just add a checkbox under field container.The ui of  field container breaks.

![add checkbox in class](https://user-images.githubusercontent.com/21308144/41225574-b48a8a16-6d8c-11e8-9304-2f887e83b8c4.png)

![ui of object breaks](https://user-images.githubusercontent.com/21308144/41225575-b83c903c-6d8c-11e8-9f98-15be25aadac5.png)
After Adding checkbox in field container all the data fields inside that field container becomes invisible.

Same is the case with Calculated field.
Add Calculated field under field container. 
![calculated field in class](https://user-images.githubusercontent.com/21308144/41225769-37ecae70-6d8d-11e8-9ee8-522767161e30.png)

![calculated field breaked ui](https://user-images.githubusercontent.com/21308144/41225773-3c77ab52-6d8d-11e8-9bf1-82214f5d16cd.png)

**Comment by sdserban** [comment] 2019-04-05 14:59
The bug is still present at version 5.7, at least for checkbox. For calculated field I have not tested yet. 
I have been solved for me using custom CSS, but will be nice if somebody from Pimcore will take care of this bug or at least offer some work around to it.

**Comment by butlersupply** [comment] 2020-07-31 14:22
This is still a bug in 6.6.10  Is this ever going to be fixed?  Does anyone have a workaround?

**Comment by fashxp** [comment] 2020-07-31 14:25
it's not on our priority list, we happy to merge PRs to fix it though

**Comment by weisswurstkanone** [comment] 2020-08-04 11:53
I was not able to reproduce it with a checkbox but found a fix for the calculated value. See #6894

**Comment by neha04** [comment] 2020-08-04 13:00
Yes,Its working fine with checkbox now.I created this issue two years back.Seems it get resolved with some changes done for checkbox in earlier releases.

**Comment by weisswurstkanone** [comment] 2020-08-04 13:04
Ok, I guess the checkbox was fixed by this commit (May 2019) 
https://github.com/pimcore/pimcore/commit/9a2e2241275efeef98e1e64d39f10e680f4954d7
I didn't have a default width before.

Thanks for testing

**Closed by weisswurstkanone** 2020-08-04 13:04 UTC
Labels: Bug

**Comment by butlersupply** [comment] 2020-08-05 13:41
Awesome!  Thanks for fixing!

**Comment by weisswurstkanone** [comment] 2020-08-05 13:42
Thanks a lot for checking again 👍
