### ISSUE TITLE
[Bug]: Versions created prior to v11 upgrade render incorrectly

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#15931] opened 2023-09-12 19:47 UTC
### Pimcore version

11.0.8

### Steps to reproduce

With the upgrade from v10 to v11, the `o_` prefix was removed from some data object properties and database columns.

Data object versions created before the upgrade are serialized objects with an old version of the class and contain fields like `o_published` (instead of `published`), so if you view a version created prior to the upgrade, Pimcore will show you an incorrect version because there's no mapping from the old to new version of the class properties.

![image](https://github.com/pimcore/pimcore/assets/533798/1ad34231-44dd-4eaa-bdb8-1a3b45524fe3)
In the screenshot above, the version actually _was_ published but it was created before the upgrade to v11.

Something like this could map the properties to their new version:
```php
    public function __unserialize(array $data): void
    {
        foreach ($data as $prop => $value) {
            $prop = trim($prop, "\0*"); // protected properties are prefixed with a null byte and an asterisk
            $prop = str_replace('o_', '', $prop); // PCv10 prefixed some properties with o_
            if (property_exists($this, $prop)) {
                $this->$prop = $value;
            }
        }
    }
```

At the very least mention should be made in the upgrade guide that version data will be inaccurate after the upgrade.

### Actual Behavior

Object version data is inaccurate after a v11 upgrade from v10.

### Expected Behavior

Object version data is accurate after a v11 upgrade from v10.

**Comment by kingjia90** [comment] 2023-09-19 11:53
Potential duplicate of https://github.com/pimcore/pimcore/issues/15839

**Comment by dvesh3** [comment] 2023-10-04 11:50
We need to provide scripts to migrate these properties in serialized data e.g. `versions, re-cyclebin ..`

**Comment by dvesh3** [comment] 2023-10-09 12:19
@tmannherz could you please try these [scripts](https://gist.github.com/dvesh3/96e68c1fe0e9d03996e09857105813c3) to migrate `o_` prefixes on v11 serialized data? thanks!

**Comment by tmannherz** [comment] 2023-10-10 14:25
@dvesh3 I ran the data object version migration script on a local development DB, but it looks to have corrupted the version data when PC attempts to unserialize it:

![image](https://github.com/pimcore/pimcore/assets/533798/3687c6e5-a7dd-4b4c-8308-8fbc429d05a9)

Additionally the `o_published` field is missing from the property mappings in that script.

I'll let you know if I can figure out why PHP can't unserialize the version.

I didn't run the recyclebin migration since the local DB didn't have any items in the recycle bin.

**Comment by tmannherz** [comment] 2023-10-10 16:10
I did a little more investigation, but parsing a serialized string is not easy. Here's the beginning of the version shown in the error above that complains about offset 435 if you want to debug it yourself:

```
O:30:"Pimcore\Model\DataObject\Event":111:{s:15:" * dependencies";N;s:25:" * __dataVersionTimestamp";i:1690987027;s:7:" * path";s:12:"/Products/G/";s:13:" * properties";a:0:{}s:5:" * id";i:497;s:15:" * creationDate";i:1635367340;s:19:" * modificationDate";i:1690987224;s:15:" * versionCount";i:218;s:12:" * userOwner";i:0;s:9:" * locked";N;s:19:" * userModification";i:25;s:11:" * parentId";i:38;s:12:" * _fulldump";b:1;s:5:" * id";R:6;s:11:" * parentId";R:13;s:9:" * o_type";s:6:"object";s:8:" * o_key";s:40:"Global Culinary Ice Cream Tour (150-496)";s:7:" * path";R:4;s:10:" * o_index";i:21;s:15:" * creationDate";R:7;s:19:" * modificationDate";R:8;s:12:" * userOwner";R:10;s:19:" * userModification";R:12;s:13:" * o_siblings";a:0:{}s:16:" * o_hasSiblings";a:0:{}s:13:" * o_children";a:0:{}s:9:" * locked";R:11;s:19:" * o_childrenSortBy";N;s:22:" * o_childrenSortOrder";N;s:15:" * versionCount";R:9;s:13:" * properties";R:5;s:20:" * __rawRelationData";a:10:{i:0;a:9:{s:2:"id";i:79607;s:6:"src_id";i:497;s:7:"dest_id";i:250;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:1;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:1;a:9:{s:2:"id";i:79608;s:6:"src_id";i:497;s:7:"dest_id";i:271;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:2;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:2;a:9:{s:2:"id";i:79609;s:6:"src_id";i:497;s:7:"dest_id";i:1086;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:3;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:3;a:9:{s:2:"id";i:79610;s:6:"src_id";i:497;s:7:"dest_id";i:1657;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:4;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:4;a:9:{s:2:"id";i:79611;s:6:"src_id";i:497;s:7:"dest_id";i:1658;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:5;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:5;a:9:{s:2:"id";i:79612;s:6:"src_id";i:497;s:7:"dest_id";i:1659;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:6;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:6;a:9:{s:2:"id";i:79613;s:6:"src_id";i:497;s:7:"dest_id";i:1660;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:7;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:7;a:9:{s:2:"id";i:79614;s:6:"src_id";i:497;s:7:"dest_id";i:1832;s:4:"type";s:6:"object";s:9:"fieldname";s:10:"Categories";s:5:"index";i:8;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:8;a:9:{s:2:"id";i:79615;s:6:"src_id";i:497;s:7:"dest_id";i:271;s:4:"type";s:6:"object";s:9:"fieldname";s:15:"PrimaryCategory";s:5:"index";i:0;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}i:9;a:9:{s:2:"id";i:79616;s:6:"src_id";i:497;s:7:"dest_id";i:203;s:4:"type";s:6:"object";s:9:"fieldname";s:4:"Host";s:5:"index";i:0;s:9:"ownertype";s:6:"object";s:9:"ownername";s:0:"";s:8:"position";s:1:"0";}}s:19:"__objectAwareFields";a:3:{s:17:"EventPresenceType";b:1;s:6:"Themes";b:1;s:4:"FAQs";b:1;}s:14:" * o_published";b:1;s:12:" * o_classId";s:5:"event";s:14:" * o_className";s:5:"Event";s:28:" * allLazyKeysMarkedAsLoaded";b:1;s:17:" *
```

Unfortunately I don't have a copy of the serialized data _before_ running the script, making a diff even more difficult.

I think there are some other fields missing from the mapping like `o_type`, `o_key`, `o_children`, etc.

I personally think string manipulation on serialized data is risky and problematic, so I wouldn't be running these script on production data.

**Comment by dvesh3** [comment] 2023-10-11 08:17
Yes, I understand the script is not well tested (not easy as every data model is different and special in its own way) so might need some validation and testing after migrating the data. This is why we added instructions to [migrate this data already on 10.6](https://github.com/pimcore/pimcore/blob/11.0/doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md#migrate-o_-prefix-properties-in-the-stored-data) as there you just need to re-save it and [references](https://github.com/pimcore/pimcore/blob/10.6/models/DataObject/AbstractObject.php#L1464) will take care of the rest. 

Also, we can't add `__unserialize` on v11 to AbstractObject as this can have side effects with advanced data types e.g. localizedfields, fieldcollections and so on.

The scripts for v11 is just to help with migrating the data if the instance is already upgraded to v11 and it needs to be adapted according to your data model.

Thanks for testing. I'll update the script with missing system properties.

**Comment by tmannherz** [comment] 2023-10-11 12:38
@dvesh3 I'll leave our `__unserialize` method in place until all of our pre-v11 versions expire -- thanks for looking into this.

~Though, unless I'm missing something, there is/was no way to migrate serialized version data prior to the upgrade since the serialized data is a representation of the class in its current state.~ Also those scripts now in the docs were only created last week.

Nvm I see the code reference you linked to, but it wasn't clear to me when going through the upgrade notes a couple months back what exactly had to happen to preserve our version data.

**Comment by dvesh3** [comment] 2023-10-11 13:34
Correct, it was missing until last week. I think we can close this issue now?

**Closed as completed** 2023-10-12 08:29 UTC
Labels: Bug
