### ISSUE TITLE
Admininer don't work with no output_buffer

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2472] opened 2018-01-19 19:10 UTC
It seems adminer don't work without output_buffer (there is not this problem on Pimcore 4 on another server with the same PHP config, so probably a Pimcore 5/Symfony session problem).

Please see the following screenshots, lastest stable Pimcore (Version: 5.1.1 Build: 179)

![adminer](https://user-images.githubusercontent.com/9025839/35166985-11782a84-fd54-11e7-85c0-8c9dc06be673.png)

![php](https://user-images.githubusercontent.com/9025839/35167045-47bd8896-fd54-11e7-86a9-a577378aa360.png)

**By the way i noticed that /vendor/vrana/jush has a .git folder, is it normal ? This is the only package which has a .git directory indise.... From the zip from the last stable download from Pimcore website.**

**Comment by maff** [comment] 2018-01-22 10:58
Duplicate of #2444

**Closed by maff** 2018-01-22 10:58 UTC

**Comment by Yivan** [comment] 2018-01-24 13:08
@maff Thanks for the fix https://github.com/pimcore/pimcore/commit/d0fb7bd91416be313f1f59e4be22b2a446688529, i confirm that adminer work great with it.

I know it has nothing to do with this issue, but i noticed on the same instance when i tried vrana adminer that that /vendor/vrana/jush has a .git folder, is it normal ? This is the only package in `/vendor` which has a .git directory inside.... Instance is from the zip from the last stable download from Pimcore website.
I don't know if this is related but when doing a pimcore update and git reinit the directory /vendor/vrana/jush has been emptied.

**Comment by maff** [comment] 2018-01-24 13:35
This is on purpose - the adminer composer package is broken as it does not include its syntax highlighter (`vrana/jush`) and there is no proper package for that dependency, so Pimcore's composer.json is configured to clone/update `vrana/jush` directly from its git directory.

See https://sourceforge.net/p/adminer/bugs-and-features/468/

**Comment by Yivan** [comment] 2018-01-24 13:49
Ok i understand now, thanks!
