### ISSUE TITLE
[Bug]: Video Editable open link

### ISSUE THREAD

**Issue by bheApik** [pimcore/pimcore#17933] opened 2024-12-16 15:48 UTC
### Pimcore version

2024.4

### Steps to reproduce

1. Create a Pimcore Video Editable on the view
2. Click on the video edit icon in the editmode

### Actual Behavior

When clicking on the pencil icon (edit) of the Editable Video, the edit modal does not appear, and I get the following error message in the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at pimcore.helpers.editmode.openVideoEditPanel (script-proxy?storageFile=minified_javascript_core_5914b25d43ef4112199e4bbb18353e2b.js&_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:5408:22)
    at klass.openEditor (script-proxy?storageFile=minified_javascript_core_2239aa9910d3b4896a4f531fd0702aa2.js&_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:10206:48)
    at Object.callback (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:1827:134)
    at constructor.fireHandler (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:8936:359)
    at constructor.onClick (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:8936:55)
    at constructor.fire (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:2407:19)
    at constructor.fire (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:3087:49)
    at constructor.publish (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:3085:125)
    at constructor.publishDelegatedDomEvent (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:3086:92)
    at constructor.doDelegatedEvent (ext-all.js?_dc=b8f7406927e3ca36ad9022b3154bb09f9d3a1af1:3087:421)

```

![Image](https://github.com/user-attachments/assets/2b5c68f6-f399-47a3-b3c7-e484951bf18d)

### Expected Behavior

When using the Video Editable in Pimcore’s edit mode, the modal to link a video should appear.

**Comment by muratbinerbay** [comment] 2024-12-16 16:57
Duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/784 I believe :)

**Closed as completed** 2024-12-16 18:09 UTC
Labels: Bug
