### ISSUE TITLE
Random labels aligned to the right

### ISSUE THREAD

**Issue by palazzetti** [pimcore/pimcore#7359] opened 2020-10-20 09:31 UTC
### Expected behavior
Labels text-align left
### Actual behavior
Labels text-align right
### Steps to reproduce
Update from 6.7.2 to 6.8.3
### Code example
<img src="https://user-images.githubusercontent.com/49283657/96567643-517efa00-12c7-11eb-83e8-bfa99121525d.png" width="100" height="200">

<img src="https://user-images.githubusercontent.com/49283657/96567797-7ffcd500-12c7-11eb-82da-b5cd0c3ab637.png" width="200" height="200">

<img src="https://user-images.githubusercontent.com/49283657/96567867-97d45900-12c7-11eb-8295-a653caeb8903.png" width="200" height="200">

<img src="https://user-images.githubusercontent.com/49283657/96567880-9c990d00-12c7-11eb-9a12-da84ecf8ff23.png" width="200" height="200">

This "bug" is applied randomly, there is no logical link between the text-align right and the selected labels.

**Comment by weisswurstkanone** [comment] 2020-10-20 10:11
duplicate of https://github.com/pimcore/pimcore/pull/7293 ?

**Comment by palazzetti** [comment] 2020-10-20 10:19
> duplicate of #7293 ?

Its a duplicate of https://github.com/pimcore/pimcore/issues/7292 yes

**Closed** 2020-10-20 11:34 UTC
