### ISSUE TITLE
[Bug][TinyMCE]: Wrong document editables defaultEditorConfig node

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#15535] opened 2023-07-14 13:59 UTC
### Pimcore version

11.x

### Steps to reproduce

- Add a `custom.js` like described [here](https://github.com/pimcore/pimcore/tree/bdc9a2dcd6d75403a3a1750c4c117fc8e1ea541e/bundles/TinymceBundle#custom-configuration-for-tinymce)
- Open a document with a wysiwyg editable on it
- The config will not be applied.

It's a little confusing and I'm not 100% sure, but if i remove the `parent.` from here,

https://github.com/pimcore/pimcore/blob/bdc9a2dcd6d75403a3a1750c4c117fc8e1ea541e/bundles/TinymceBundle/public/js/editor.js#L74C1-L75

...everything works fine

**Comment by dvesh3** [comment] 2023-07-14 14:21
duplicate of https://github.com/pimcore/pimcore/issues/15700. thanks for the fix suggestion 😊

**Closed as completed by dvesh3** 2023-07-14 14:21 UTC
Labels: Bug
