### ISSUE TITLE
Making a folder locked is hiding "Delete" menu on that locked folder tree but not on grid rows

### ISSUE THREAD

**Issue by faiyazalam** [pimcore/pimcore#4300] opened 2019-04-30 10:45 UTC
# Bug Report

### Expected behavior
After clicking on "Lock" under Advance menu on tree, it should not hide the menu of "Delete" on tree as "Lock" is used to avoid changing of parent of the locked folder, as per documentation. Lock is not for hiding Delete menu.

### Actual behavior
After clicking on "Lock" under Advance menu on tree,  the "Delete" menu is visible on tree but not on grid rows.

### Steps to reproduce
1)Right click on a folder under tree and go to Adavace>>Lock
2)Click on Lock
3)Right click on the locked folder, the Delete button is invisible. Cool.
4)Click on the locked folder, Grid will be visible
5)Right click on any row of the grid, Delete button is visible. Not Cool.

**Comment by dvesh3** [comment] 2019-04-30 10:47
duplicate of #4281

**Closed by dvesh3** 2019-04-30 10:47 UTC
