### ISSUE TITLE
Localized fields at a glance (side-by-side)

### ISSUE THREAD

**Issue by msenkpiel** [pimcore/pimcore#1279] opened 2017-02-13 14:38 UTC
Add a new option to localizedfields data object definition. So you can view mutliple language fields at a glance side by side. That's helpful to translate text.

**Comment by brusch** [comment] 2017-02-14 12:08
A generic approach would be to let the user choose the languages and save it somewhere in the local storage.

**Comment by frithjof** [comment] 2017-03-23 09:12
An overlay as long as you are in the field showing the other language values could be nice

**Comment by brusch** [comment] 2019-01-31 13:21
Duplicate of #3054

**Closed by brusch** 2019-01-31 13:21 UTC
