### ISSUE TITLE
Dataloss in localized fields and maps

### ISSUE THREAD

**Issue by TheMorgner** [pimcore/pimcore#6509] opened 2020-06-03 09:44 UTC
Class loses all input of localized fields and points on the maps. Using 26 languages.

[bulk_export (2).json.txt](https://github.com/pimcore/pimcore/files/4722362/bulk_export.2.json.txt)

**Comment by fashxp** [comment] 2020-06-03 09:58
Hi, can you please give a bit more information about how to reproduce?

**Comment by TheMorgner** [comment] 2020-06-03 10:06
Actually i tried to repoduce this error but i was not able to test it on the deme as i could not add languages to it. 

Workflow:
-> Add new class
-> Fill out all fields (set points on the maps and add text to localized fields)
-> Save and publish
-> reopen/reload
-> all gone (but still in the version history)

**Comment by TheMorgner** [comment] 2020-06-03 10:36
If it would help i can give you an acces to the actuall project where this error appears. Started with the demo project car shop.

**Comment by fashxp** [comment] 2020-06-03 13:00
so what you are saying is, with only 3 languages it works fine, but with 26 languages it doesn't? 
any specific languages?

**Comment by TheMorgner** [comment] 2020-06-03 13:12
en, de, pl, ru, sr, hr, af, bs, bg, da, fi, fr, it, kk, nl, nb, nn, pt, ro, sv, es, th, cs, tr, uk, hu

**Comment by TheMorgner** [comment] 2020-06-03 13:12
These are the languages we use

**Comment by dvesh3** [comment] 2020-06-03 13:14
@TheMorgner please share affected Pimcore version. thanks!

**Comment by TheMorgner** [comment] 2020-06-03 13:23
I can't tell excactly where the problem is as localized fields work in another component. 

To avoid issues with the old files(Car Shop Demo) i exported this one and renamed it and gave it another id and then reuploaded it -> same issue 

V6.4.2 @dvesh3

**Comment by fashxp** [comment] 2020-06-03 13:43
cannot be reproduced. 

steps I did: 
- installed pimcore demo application with lastest pimcore version
- imported your class definition
- added all mentioned languages
- created new object & entered data to localized fields (to first 6 languages)
- save & publish
- reload --> all data is here

**Comment by solverat** [comment] 2020-06-04 17:18
We just encountered the same issue. We used two languages with one as a fallback. Used a localized textfield with the **unique** flag.

After creating one object, save and creating another one, the data in object_localized_data_XX gets replaced instead of appended. 

We removed the unique flag and it worked again as expected.

**Comment by brusch** [comment] 2020-06-04 18:51
@solverat thanks for sharing your findings, we'll try to reproduce the issue again on our end.

**Comment by weisswurstkanone** [comment] 2020-06-05 07:45
@solverat unable to reproduce on latest version. could you share even more details?

**Comment by TheMorgner** [comment] 2020-06-05 08:49
So for us the solution is to go to another server and start with a new project as i want to start with a clean and fresh installation of the newest pimcore version. But for finding the bug i'll give you the credentials for an admin account on the old server if you want as this one will be my test server for new features and modifications in the future.

**Comment by weisswurstkanone** [comment] 2020-06-05 09:08
@TheMorgner please try with the latest version. If the problem still exists I will happy to investigate this directly on your "old" server.

**Comment by brusch** [comment] 2020-06-08 09:43
@TheMorgner Any feedback? Thanks! 😊

**Comment by TheMorgner** [comment] 2020-06-08 11:17
Did not run the update yet as i got important work in other projects. I'll give feedback asap

**Comment by blankse** [comment] 2020-06-16 10:10
We have also this issue. I tested it in the demo.

1. I created a FieldCollection with localized many-to-one relation to image assets for News

2. Save the news with 2 filled and 1 empty field collection item

3. Reload

4. Save the news with all 3 filled field collection items

5. Reload

-> The first 2 filled items are empty now

![demo_pimcore_fun_Pimcore](https://user-images.githubusercontent.com/998558/84761867-5acf2180-afca-11ea-9de7-342bb232cc55.gif)

**Comment by weisswurstkanone** [comment] 2020-06-16 12:18
Thx @blankse for bringing light into this!

**Comment by blankse** [comment] 2020-06-18 16:35
With Pimcore 6.6.7 and #6612 my issue is gone. 👍

**Comment by brusch** [comment] 2020-06-19 09:51
Fixed by #6612

**Closed** 2020-06-19 09:51 UTC
Labels: Bug
