### ISSUE TITLE
[Bug] [Backend UI]: Object/Tab reload -> console error 

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#10975] opened 2021-12-07 14:34 UTC
### Expected behavior

The object must be reloaded correctly.

### Actual behavior

The object is reloaded, but with an error in the browser console.

### Steps to reproduce

1. Create the simple plugin, that reloads an Product object, after object was updated:

```javascript
pimcore.registerNS('pimcore.test.admin.plugin');

pimcore.test.admin.plugin = Class.create(pimcore.plugin.admin, {
    getClassName: function () {
        return 'pimcore.test.admin.plugin';
    },

    initialize: function () {
        pimcore.plugin.broker.registerPlugin(this);
    },

    postSaveObject: function (object) {
        if (object.data.general.o_className === 'Product') {
        
            object.reload();
            
            // Also console error
            // let tabpanel = Ext.getCmp("pimcore_panel_tabs");
            // let activeTab = tabpanel.getActiveTab();
            // if (activeTab) {
            //     if (activeTab.initialConfig.object) {
            //         activeTab.initialConfig.object.reload();
            //     }
            // }
        }
    },
});

let PimcoreTestAdminPlugin = new pimcore.test.admin.plugin();
```

2. Save the object.
3. Reload works, but we'll get an error in browser console:

<img width="831" alt="Bildschirmfoto 2021-12-07 um 15 31 59" src="https://user-images.githubusercontent.com/12817320/145047949-337f5954-9bd2-4682-8176-6046878e5402.png">

**Comment by SamyMP** [comment] 2021-12-08 12:50
As a workaround solution, I found out that putting the reload in a setTimeout of 1 sec seems to prevent this message in the console :

```js
pimcore.registerNS('pimcore.test.admin.plugin');

pimcore.test.admin.plugin = Class.create(pimcore.plugin.admin, {
    getClassName: function () {
        return 'pimcore.test.admin.plugin';
    },

    initialize: function () {
        pimcore.plugin.broker.registerPlugin(this);
    },

    postSaveObject: function (object) {
        if (object.data.general.o_className === 'Product') {
        
            setTimeout(() => object.reload(), 1000) // <- This should work
            
            // Also console error
            // let tabpanel = Ext.getCmp("pimcore_panel_tabs");
            // let activeTab = tabpanel.getActiveTab();
            // if (activeTab) {
            //     if (activeTab.initialConfig.object) {
            //         setTimeout(() => activeTab.initialConfig.object.reload() ,1000); // Same here
            //     }
            // }
        }
    },
});

let PimcoreTestAdminPlugin = new pimcore.test.admin.plugin();
```

But I think the issue should be adressed properly in the source code

**Comment by MyZik** [comment] 2021-12-10 09:08
Thank you @SamyMP, the workaround works :)

**Comment by brusch** [comment] 2022-02-02 09:09
Fixed by #11318

**Comment by MarcW09** [comment] 2022-02-09 14:00
This related PR leads to "Object.reload" not working anymore for me. When removing the PR Commit it works again, but with the maskEl error.
![Screenshot_09_02_22__14_58](https://user-images.githubusercontent.com/91049331/153215843-79b71c58-c389-4e9e-ba20-ab68af5ef3e4.png)

**Comment by MarcW09** [comment] 2022-02-09 14:47
Can this maybe be fixed in the unmask function? just set maskEl to null, when data is null. Then the changes in the Commit of the PR #11318 is not necessary.

![Screenshot_09_02_22__15_46](https://user-images.githubusercontent.com/91049331/153225264-22d62c77-3671-478c-b251-65870dfefe92.png)

**Comment by kingjia90** [comment] 2022-02-09 15:03
> This related PR resolves in Object.reload not working anymore for me. When removing the PR Commit it works again, but with the maskEl error. ![Screenshot_09_02_22__14_58](https://user-images.githubusercontent.com/91049331/153215843-79b71c58-c389-4e9e-ba20-ab68af5ef3e4.png)

i cannot reproduce it, @MarcW09 could you please open an new issue (by referencing this one) with more details on how to reproduce it? 
It could be related but not the same topic, as it mentions about toolbar register(), not the tabbar.

**Closed as completed by kingjia90** 2022-02-09 15:03 UTC
Labels: Bug
