### ISSUE TITLE
localizedfields don't display correctly in admin when you create an object

### ISSUE THREAD

**Issue by MaguyB** [pimcore/pimcore#1040] opened 2016-11-15 15:40 UTC
### Expected behavior 
Form fields should look the same in every language like the first one displayed  

### Actual behavior  
Alternate language like german on the demo site (for blog for instance) : fields appear at the bottom : you need to scroll down to see the fields...
  
### Steps to reproduce  
 Open blog objects in demo.pimcore admin and look  at german tab

**Comment by MaguyB** [comment] 2016-11-15 15:41
I have expérienced the same problem on my sites, what ever I use for layout (accordion, region...)

**Comment by brusch** [comment] 2016-11-16 07:08
I'm not able to reproduce this problem on demo.pimcore.org. 
Which browser are you using? Zoom enabled? Any other special setting? Screenshot, ... 
Some more information would be really helpful, otherwise I have to close this issue.

**Comment by MaguyB** [comment] 2016-11-16 07:50
Hello
Under Internet Explorer Edge (Microsoft Edge 38.14393.0.0),   (Resolution display : 1366 * 768) - Zoom 100% on browser. I don't see any field nor any scrolling bars for German. Please see below 
![pimcore demo local en](https://cloud.githubusercontent.com/assets/23481029/20338668/b1c836b0-abd8-11e6-8606-844e3aa1fba2.JPG)
![pimcore demo local german](https://cloud.githubusercontent.com/assets/23481029/20338667/b1c37418-abd8-11e6-9f14-4b70dd5e0fcb.JPG)
With Chrome, which I use most of the time, at least I can see a scrolling bar, but the alternative language always hide deeper, you need to use the scrollbar to access it as the first top part is completely blank. Not even obvious at first that you need to scroll down to view. 
Here are the screens on Chrome 
![pimcore demo local en with chrome](https://cloud.githubusercontent.com/assets/23481029/20338775/601663fe-abd9-11e6-9cbd-a3b71da8c187.JPG)
![pimcore demo local german with chrome](https://cloud.githubusercontent.com/assets/23481029/20338776/601ba0d0-abd9-11e6-8437-276ec9fd5712.JPG)

This behaviour also occurs on my website. I have noticed that for a while, but it worked fine with previous versions before (I am not sure when this even occured exactly but I am pretty sure it was fine with most if not all versions 3)

**Comment by brusch** [comment] 2016-11-16 07:54
Hmmm, just tested it on BrowserStack, also without any problems in both browsers ... strange. 
Anything else that is different from a typical system on your PC? Can you reproduce the problem also on a different PC?

**Comment by MaguyB** [comment] 2016-11-16 08:01
I have tried many times indeed, and on many PCs. 
My PCs are not noticably different from others ; I even tested this on a brand new one I bought a few days ago. One thing that is nevertheless important to notive : I am French and my computer is configured for French... who knows...  Anything else you would like me to try ?

**Comment by brusch** [comment] 2016-11-16 08:56
Well, it would be good to have it reproducible :) 
Anyone else experiencing the same issues? Maybe you can try to further debug it (enable dev-mode). 
Thanks!

**Comment by MaguyB** [comment] 2016-11-16 10:31
I tried to change language and resolur
tion : that did not fix the problem. I installed and tried on Firefox : it works well on this platform ! So the problem is on Chrome and even worse witb IE edge. I don't know how to debug this fuether, I don't see any errors on the screen, not even sure the error is caught... I just hope some other people will try ! I refuse to think that I am the only person having this problem !

**Comment by Yivan** [comment] 2016-11-16 11:44
Hello MaguyB,

I tried on Windows 7/Chrome, no problem (no blanck area on german tab).
(i don't have edge so cannot try).
You say "I have tried many times indeed, and on many PCs. ". Did this work on some of them ? If yes you should check what is the difference between those working and those not. Maybe some fancy extension or antivirus or any windows software/malicious program could alter the navigator view.

Hope it helps.

**Comment by MaguyB** [comment] 2016-11-17 09:51
Hello
I have disabled all my plugins on Chrome, (still Chromecast remained) : it still does not work. 
I tried on my brand new pc which no plugin installed and no Chromecast yet, so Chromecast could not be the cause. I also have the same problem with Edge...
Well, at least I am glad it works with Firefox ! 
I hope somebody else will find the problem and help further... Thanks

**Comment by MaguyB** [comment] 2016-11-17 13:18
I tried on an old Dell with Windows 7 and an external big screen : it works on IE and Chrome. My computer which don't work work under Windows 10 and use a quite small resolution (or at least fonts are enlarged) because I am working in remote locations and don't have a screen to plug to. Windows 10 ? Resolution problem ? I will try to connect my new surface pro (on which it does not work) with an external screen when I get the chance...

**Comment by cleggypdc** [comment] 2016-11-17 13:35
Hi, I can also reproduce this in Chrome 54, it's fine in Firefox

**Comment by MaguyB** [comment] 2016-11-17 13:39
Thank you so much Cleggypdc, now I feel less lonely :)

**Comment by cleggypdc** [comment] 2016-11-17 14:31
@brusch it appears to be the autoScroll causing the issue here:
https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/object/tags/localizedfields.js#L206

**Comment by brusch** [comment] 2016-11-18 10:19
@cleggypdc thanks! Removed this config, still looks good in browser without this issue.

**Closed** 2016-11-18 10:19 UTC
Labels: Bug

**Comment by MaguyB** [comment] 2016-11-18 10:47
If you already configured the demo site with your change, I am sorry to say that this did not solve my issue neither on IE Edge, nor on Chrome... If you did not yet, and if the change really solves the problem, could you please let me know exactly what I should change ? Thanks

**Comment by brusch** [comment] 2016-11-21 08:09
@MaguyB demo.pimcore.org is now up-to-date , can you please check it again? Thanks!

**Comment by MaguyB** [comment] 2016-11-21 08:33
Hello Bernard. Yes, I can confirm it completely works now ! Nice to finally see it working well even on smaller screens ! 
Now I need to update my existing projects. To update my sites made with Pimcore, should I just update the file localizedfields.js ?
Thanks !

**Comment by brusch** [comment] 2016-11-21 08:43
@MaguyB Thanks for your quick reply. You can either update to the latest build of pimcore (recommended)  or you can patch `localizedfields.js` manually.

**Comment by MaguyB** [comment] 2016-11-21 08:44
Ok thanks, will do !
