### ISSUE TITLE
Document editables: max name length = 750 only ASCII -> warning if not

### ISSUE THREAD

**Issue by etwasch** [pimcore/pimcore#421] opened 2016-01-30 20:32 UTC
lets say we have two areas, one called 'nested' and one called 'text'.

this is view.php for text:
```
<div>
    <?php echo $this->wysiwyg("content_wysiwyg"); ?>
</div>
```

this is view.php for 'nested':
```
<div>
    <?php while($this->block('index')->loop()) { ?>
        <div>
            <?php echo $this->areablock('index_block'); ?>
        </div>
    <?php } ?>
</div>
```

i create a page, and insert the areas like this:
>nested 1
>text 1
>nested 2
>>text 1.1

when i preview the page everything is fine. but when i view the same page without pimcore_preview=true text 1.1 is not displayed. the divs are there so the template gets included, but the content is missing.

i tried to trace the bug and landed deep inside the framework but couldn't find out what's going on.

**Comment by brusch** [comment] 2016-02-03 20:57
Unfortunately I'm not able to reproduce this problem. Please provide us an example (files, bricks, ...) + a detailed step by step guide how to reproduce this problem. Thanks

**Comment by etwasch** [comment] 2016-02-03 23:22
thank you so much for looking into this!
here are all the necessary example files and three screenshots for clarification:
[nested.zip](https://github.com/pimcore/pimcore/files/116583/nested.zip)

**Comment by etwasch** [comment] 2016-02-03 23:32
btw. the bug isn't in the wysiwyg. no data is included in the nested areablock, no matter what brick is used as content. as i said, the template get's included but not the data.

**Comment by brusch** [comment] 2016-02-04 11:56
This really seems to be related to your project. 
I've just done the following: 

Created a new view with the following content: 
`<div style="margin-left: 200px">
    <?= $this->areablock("test") ?>
</div>
`

I created a new document that uses this view (empty action) and added three "Nested" blocks, Inside this nested blocks I've added some text blocks.(used the areas out of your zip file): 
![image](https://cloud.githubusercontent.com/assets/142037/12814283/291aa030-cb3e-11e5-9f71-22d8a10390fd.png)



Then in the frontend (not preview), everything just works as expected: 

![image](https://cloud.githubusercontent.com/assets/142037/12814293/4256441e-cb3e-11e5-9fa7-cea4f911b3cc.png)


Next steps: 
- Please download our demo package
- Try to reproduce the problem there (like I did above)
- if you're able to do so, please send me your demo instance including a db dump and all files + additional information (in which document, ...)

**Comment by etwasch** [comment] 2016-02-04 18:23
thanks for the answer! you're almost there…
the bug occurs in a nested view _inside_ a nested view. you have them all at the same level. that's why i have called them nested. i've added a margin for clarification:
![nested](https://cloud.githubusercontent.com/assets/15729562/12825017/7eb0c9b2-cb74-11e5-817b-7ea3226625b1.png)

**Comment by brusch** [comment] 2016-02-05 15:04
Unfortunately it is not, I have not exactly the same brick constellation, right? 

Editmode: 
![image](https://cloud.githubusercontent.com/assets/142037/12849696/4e1abd14-cc21-11e5-8476-4cabb894d7ee.png)

Frontend: 
![image](https://cloud.githubusercontent.com/assets/142037/12849709/58c311d0-cc21-11e5-8590-09e050cfe03f.png)

Works exactly as it should... or I'm doing anything wrong again? 
If not, ... see my answer above - I think the only way that makes sense now is, that you download our demo package, create exactly the problem as described above, dump the database and share the files with us. Alternatively please provide us a guide where we definitely can reproduce this problem, and verify it first on your side before sharing it with us. If not we'd have to close this issue as it isn't reproducible.

**Comment by etwasch** [comment] 2016-02-05 23:27
no, you did everything exactly as intended and i can replicate your success. but…
after very confusing hours of testing i found the bug. this will probably be hard to fix!

> Created a new view with the following content: 
> `<div style="margin-left: 200px"> <?= $this->areablock("test") ?> </div>` 

now put this instead:
`<div style="margin-left: 200px"> <?= $this->areablock("test_with_more_chars") ?> </div>` 

a look into $this->areablock('index_block')->getElement('text') of "nested" shows what's going on. some indices of the (totaly hardcore) array exceed 255 chars:
```
[content_wysiwygtest_with_more_chars_indextest_with_more_chars1_index_blocktest_with_more_chars_indextest_with_more_chars11_1_indextest_with_more_chars_indextest_with_more_chars1_index_blocktest_with_more_chars_indextest_with_more_chars11_11_1_1_index_bloc] => Pimcore\Model\Document\Tag\Wysiwyg Object ( [text] =>
this text is not displayed in frontend
```

whereas with test the indices are just under the limit and not truncated:
```
[content_wysiwygtest_with_more_chars_indextest_with_more_chars1_index_blocktest_with_more_chars_indextest_with_more_chars11_1_indextest_with_more_chars_indextest_with_more_chars1_index_blocktest_with_more_chars_indextest_with_more_chars11_11_1_1_index_bloc] => Pimcore\Model\Document\Tag\Wysiwyg Object ( [text] =>
this text is displayed in frontend
```

and these indices are stored in the db as varchar(255) of course…

**Comment by etwasch** [comment] 2016-02-05 23:56
no i have a question:
i'm working on several existing, huge pimcore projects. what could be the best, safest way for a quickfix? i have two ideas:

- change all identifiers of blocks and areablocks to 2-chars and do a search and replace in the database. how big is the chance that char255 is exceeded, given that the nesting level is never more than two (as in our examples), but the number of bricks in a nested areablock can be huge? as i see it, this shouldn't be a problem because the bricks are stored in an array (?).

- change the definition of the fields of the db to varchar. this would be a clean solution but i have no idea what files i have to change so that pimcore will adopt this change.

any help or other ideas how to quickfix this are very, very appreciated!
thanks for all you are doing for pimcore bernhard! coding, bug fixing, documentation…
btw. i'm from switzerland, and if you're willing to help me with a quickfix maybe we can do this in german on private channels. i'm willing to contribute and test as much as i can if you can guide me to the right direction.

**Comment by brusch** [comment] 2016-02-06 07:47
Alright, now everything is clear :-) Thanks for further investigating this! 
That's a known problem but unfortunately we don't have a fix yet, as it's not that easy as it sounds (backward compatibility, ...). I'll think about it again.

**Comment by etwasch** [comment] 2016-02-08 07:57
that's a known problem? i'm a bit shocked. i asked some veteran pimcore developers and they have no clue how i'm supposed to meet my requirements as long as this bug exists. i mean, do i have to tell my client "pimcore is just broken, i can't do that"?

so, i'm sorry to bother you, but do you have an answer to my question about the quick hack without a primary key on an existing installation. as far as i can see, there are no negative consequences, but i would really like to hear your opinion. and i still have no clue where the function is that writes the data to the table "documents_elements" if i would want to add a hash as primary.

**Comment by brusch** [comment] 2016-02-08 08:10
Yes, that's a known problem - systems have have limitations, so it is with MySQL indices, where the maximum length is at 767 bytes. Be shocked or not, we do our best to deliver an exceptional product, it's open source and free of charge - do it better, solve the problem and create a pull request to fix the problem. Thanks!

**Comment by etwasch** [comment] 2016-02-08 10:04
wow, i certainly didn't want to start an argument about the quality of pimcore or your hard work.

i don't see any possibility to rewrite the buildTagName function without breaking absolutely everything.

then there's the possibility to forget about storing and reading tag names altogether when within blocks and calculate them on the fly every time. no thanks, i don't want that, even if i see it as the only way to assure compatibility and fix the bug.

since you insist that altering the database structure is a no go (which totally makes sense regarding compatibility), it doesn't make sense for me to contribute a patch and a database converter that would fix the problem with a few lines of code, since it would never get accepted.

therefore i would like to make a patch and database conversion scheme for all who want to apply it at their own risk, knowing why it exists, what it does and what the drawbacks are.

and therefore i would be really glad if you could guide me to the right direction where to look to insert a hashing function for a primary for documents_elements.

**Closed** 2016-02-08 12:42 UTC

**Comment by brusch** [comment] 2016-02-08 16:11
The above patch should alleviate the effects of the problem, since this allows much longer names for editables and gives a meaningful error if a the length of a name hits the given limit. 
So i guess this should also fix your particular case.

**Comment by brusch** [comment] 2016-02-09 19:50
@etwasch did this solved your problem?

**Comment by etwasch** [comment] 2016-02-10 15:07
yes, sorry i was very busy. this works for me and is of course much better than my approach. 

unfortunately it's only backward compatible and compatible to existing projects when only ascii characters are used already. if not, it can be quite dangerous, and it could be really hard to repair a project after an update. i hope nobody breaks an installation with this, i would feel guilty a little bit.

thanks very much for your responsive help!
i hope i can contribute something sometime to pimcore when i have more time at hand and find another undocumented bug.

best wishes
ueli


renaming partially possible: area, yes,
