### ISSUE TITLE
Chrome's autocomplete unintentionally changes fields in "System Settings"

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#6783] opened 2020-07-14 13:57 UTC
# Bug Report

_(While this seems not to be a Pimcore bug it's an annoyance I hope can be solved easily.)_

Chrome/ Chromium browser seems to struggle with its autocomplete-feature and especially has problems deciding when [fields are not visible](https://bugs.chromium.org/p/chromium/issues/detail?id=448539) (just to name one). We noticed this several times in Pimcore backend "System Settings" that Chrome auto-fills several (even **non-visible fields**) like "Email Settings -> SMTP -> SMTP Username/Password" and "Debug -> Archive database name" with values from (maybe previously saved) backend login screen. If Chrome decides it has data to be filled, it's nearly impossible to edit the "Pimcore Settings" without wreaking havoc -> unintentionally setting some fields to incorrect/guessed values and breaking functionality such as log rotation and emailing.

As browser's autocomplete IMHO doesn't make any sense on the "System Settings" page, we might want **to turn off autocomplete for all fields in "System Settings"?** I may provide a PR if desired.

### Expected behavior

Fields on "System Settings" should never be autofilled.

### Actual behavior

Sometimes Chrome seems to autocomplete some "known" fields, even fields in collapsed panels that aren't currently visible.

### Steps to reproduce

One sure way is to save the settings in "System Settings" and tell Chrome to save/update its password. But it seems that there are more ways to make Chrome believe it should fill those fields.

**Comment by brusch** [comment] 2020-07-15 06:19
Yes, I also think that auto-complete doesn't make sense at all for the System Settings form. 
A PR would be really nice! Thanks a lot in advance!

**Comment by spotbot2k** [comment] 2020-07-15 09:42
The problem with this one is - chrome ignores `autocomplete="off"`, because you know, for reasons. Setting it to `autocomplete="chrome-off"` (just tested it) will work, but that is not a solution, just a workaround until they will decide to drop it. All in in all - that is a chrome issue, not a pimcore one, IMHO

Here more about it: https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by podarcis** [comment] 2020-07-16 06:10
@spotbot2k Thanks for your input. Yes, Chrome's behavior is very unfortunate. Earlier I [read something similar](https://www.scotsscripts.com/blog/html-css-trick-how-to-turn-off-auto-complete.html). I agree that there is no solution, but maybe a temporary workaround.

Currently I see those options:

1. Set attribute autocomplete to an invalid value.
2. Rename the fields in question to yet unknown identifiers or even randomize "name" (like this [jQuery plugin does it](https://terrylinooo.github.io/jquery.disableAutoFill/)).
3. Another approach is to set the field read-only. On element focus the read-only-property is removed. ([source: this blog article](https://www.codementor.io/@leonardofaria/disabling-autofill-in-chrome-zec47xcui))

I think ideally the workaround consists of a single function that can be applied to the whole form/panel.

**Comment by spotbot2k** [comment] 2020-07-17 13:00
This should do for a single field:

``` js
listeners: {
    afterrender: function (item) {
        item.inputEl.set({
            autocomplete: (Ext.isChrome) ? "chrome-off" : "off"
        });
    }
}
```

**Comment by podarcis** [comment] 2020-07-30 10:28
Unfortunately I'm not able to reproduce this behavior anymore. Maybe a recent change in Chrome..? Without the ability to reproduce the issue I'm not able to implement a workaround.

If not anyone else is interested in digging into this for me the ticket might be closed.

**Comment by brusch** [comment] 2020-08-03 08:00
I'm also not able to reproduce this anymore. I'll close this for now 😊

**Closed by brusch** 2020-08-03 08:00 UTC
