### ISSUE TITLE
Multihref Advanced datatype field send NULL instead an empty array()

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2672] opened 2018-03-08 18:00 UTC
For objects, when getting values with the object API, the `Multihref Advanced` datatype field send `null ` instead an empty `array()` when no object is associated in this field.

Step to reproduce:
- create an new class "MyTest"
- create a Multihref Advanced field "multiLinkMeta"
- create an object instance of the class
- call with the object API the value of the field
```
$obj = \Pimcore\Model\DataObject\MyTest::getById(46);
var_dump($obj->getMultiLinkMeta());
```
It will print null. It should print an empty array.
Having null is problem when using foreach loop for instance and it is not consistent with other relation fields (Objects, Objects with Metadata and Multi-Href) which send an empty array(), which is ok.

Thanks.

**Comment by weisswurstkanone** [comment] 2018-03-09 07:17
Unable to reproduce. Am I missing something here ? Is the field lazy loaded ?

**Comment by weisswurstkanone** [comment] 2018-03-09 07:21
Your mhref is probably NOT lazy-loaded. Fixed in build 218.

**Closed by weisswurstkanone** 2018-03-09 07:21 UTC
