### ISSUE TITLE
[Bug]: scheduled task errors in backend search

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#9687] opened 2021-07-06 09:17 UTC
### Expected behavior

Scheduled tasks for documents which include snippets should work.

### Actual behavior

Scheduled tasks for documents which include snippets result in the following error.

>  LogicException: Rendering a fragment can only be done when handling a request. in /home/gabor/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php:82

![image](https://user-images.githubusercontent.com/9052094/124575946-2257eb00-de4c-11eb-95c3-df58199d039a.png)

### Steps to reproduce

1. Create a document and include a snippet 
2. Schedule a task to publish a new version of the document
3. Run `pimcore:maintenance` command
4. The error will be shown during the `scheduledtasks` job

Tested in 6.6.2

**Comment by dvesh3** [comment] 2021-07-07 11:59
@jremmurd sorry, cannot reproduce on 10.0.6. If this is really specific to 6.x, then please close it as 6.x reached it EOL.

**Comment by jremmurd** [comment] 2021-07-08 06:18
Do you have any idea how it got fixed, so we can maybe patch it on project level for now?

**Comment by dvesh3** [comment] 2021-07-08 07:03
i'm not really sure...could be this https://github.com/pimcore/pimcore/pull/8966

**Closed as completed** 2021-07-08 08:56 UTC
Labels: Bug
