### ISSUE TITLE
[Bug]: uploading a large number of files kills Pimcore UI / makes browser unresponsive

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#14107] opened 2023-01-19 15:28 UTC
### Expected behavior

When you drag & drop 3000 files, they can still all be processed one at a time by Pimcore.

### Actual behavior

Pimcore UI tries to draw a progress bar for each file immediately, making the browser unresponsive.

This UI element should be adjusted to not try to draw the progress bar for **all dropped files**, it could create a progress bar for the "next few to upload" or have one one overall progressbar + one progressbar for the **currently** uploading file. The idea is to never create N UI elements for N files, but to have an upper limit.

![Pimcore](https://user-images.githubusercontent.com/209225/213482641-108075c9-bace-4cac-902c-070317d6b5bb.png)

### Steps to reproduce

Open Pimcore Admin UI, drag & drop a folder with several thousand files to upload. The admin UI becomes unresponsive.

**Comment by fashxp** [comment] 2023-01-19 15:44
any suggestions to improve that are welcome ...

**Comment by dkarlovi** [comment] 2023-01-19 15:55
@fashxp is this not enough of a suggestion?

> This UI element should be adjusted to not try to draw the progress bar for **all dropped files**, it could create a progress bar for the "next few to upload" or have one one overall progressbar + one progressbar for the currently uploading file.

Basically:
1. if I drop one file, the current solution is OK, the "single file upload progress bar" (SFUPB)
2. if I drop multiple files, we can have SFUPB for the **currently uploading file** (multiple, if multiple files are uploaded at the same time) and another, overall progress bar (either bytes or count, whichever is easiest).

This approach would mean we never draw more than 2-3 progress bars, even with thousands of files being uploaded.

**Comment by brusch** [comment] 2023-01-30 08:50
Duplicate of #6682

**Closed as completed by brusch** 2023-01-30 08:50 UTC
Labels: Bug, PR Welcome
