### ISSUE TITLE
[Bug] Grid sorting by Date & Time incorrect since 6.9.0

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8971] opened 2021-04-30 13:57 UTC
### Expected behavior

Sorting should be in the correct order.

### Actual behavior

It is slightly jumbled in the incorrect order.

### Steps to reproduce

Pimcore 6.9.3

Data model example:
![image](https://user-images.githubusercontent.com/279826/116705099-7bc71800-a9cc-11eb-8ab5-d56626357e8c.png)

Result:
![image](https://user-images.githubusercontent.com/279826/116705036-6651ee00-a9cc-11eb-8b6e-f712c3939b7c.png)

Looking at the history of the model something happened in the 6.9 upgrade at #8200 which is suspect:

![image](https://user-images.githubusercontent.com/279826/116706211-abc2eb00-a9cd-11eb-8114-eb769dfbf50d.png)

**Comment by dvesh3** [comment] 2021-05-03 08:47
@NiklasBr not able to reproduce with new objects. could you please share sample data? thanks!

**Comment by NiklasBr** [comment] 2021-05-03 14:02
Make sure your objects were created with integers, unix timestamps, prior to the 6.9 upgrade, then after the upgrade to 6.9 this happens:

![image](https://user-images.githubusercontent.com/279826/116885844-a1505d80-ac28-11eb-81d4-273ba1fda6b6.png)

It's as if the model is not properly saving `datetimes` because the table column is still registered as `bigint(20)`.

**Comment by NiklasBr** [comment] 2021-05-05 11:54
@dvesh3 Since 6.9 why does not `fieldtype` change and persist on the class when switching between `BIGINT` and `DATETIME`?

**Comment by NiklasBr** [comment] 2021-05-05 12:01
Update, the issue can be recreated on demo.pimcore.fun as well:

1. Open the News class:
![Screenshot_2021-05-05 demo pimcore fun Pimcore(1)](https://user-images.githubusercontent.com/279826/117137570-2e6ef000-adaa-11eb-85ee-3bb53bb55906.png)

2. Change *Spaltentyp* on the *Date* field from `BIGINT` to `DATETIME`
3. Save.
4. Close the class.
5. Open the class and check if the setting is remaining at `DATETIME` or has been reverted.

**Comment by dvesh3** [comment] 2021-05-05 12:20
@niklas this is changed on 6.9 to support column type changes from core rather than using generated files. However, date fields should still use generated files as there is a possibility to change column types in class config. Could you please check if https://github.com/pimcore/pimcore/pull/9021 (you need to resave your class) fixes your issue? thanks!

**Comment by NiklasBr** [comment] 2021-05-05 12:26
Will test soon, thanks!

**Comment by brusch** [comment] 2021-05-05 12:51
I can confirm it fixed it for me.

**Comment by brusch** [comment] 2021-05-05 12:51
But I'm not 100% sure if this is really the final fix for this issue 🤔

**Comment by NiklasBr** [comment] 2021-05-05 12:58
Works here as well, 

But any object which was created, updated, or edited after 6.9 have dates in the database which looks like `20210318093748` which is neither a timestamp, nor a datetime. Maybe need a fix for that as well. Looks like it could be split into `2021-03-18 09:37:48`.

**Closed** 2021-05-05 13:11 UTC
Labels: Bug
