### ISSUE TITLE
Backend: When a class field is set to "not editable" you cannot see whether a field value is inherited or not.

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#1036] opened 2016-11-14 11:48 UTC
# Bug Report
In a 3-level product hierarchy, some values are derived from the parent (e.g. a md5 hash or a price).
If the field is defined as "not editable" in the data model, then the backend user cannot recognize if the field value has been derived or not. 
  
### Expected behavior 
Mark lock fields as derived, analogeously to unlocked fields.

**Comment by brusch** [comment] 2019-01-31 13:48
I'm not able to reproduce this behavior anymore (tested with Input and Select data-types). 
Maybe it was fixed by #3693 ? 😊

**Closed by brusch** 2019-01-31 13:48 UTC
