### ISSUE TITLE
[Bug][Assets] Open version preview is blocking other requests

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11094] opened 2021-12-27 14:09 UTC
### Expected behavior

requests are not blocking each other

### Actual behavior

requests of version preview block each other which results in bad responding backend UI

might also be the case for other requests that calculate thumbnails. 

### Steps to reproduce

- Upload big image as asset and save multiple times
- open preview of different versions (and don't wait for them to finish loading)
- try opening another asset --> will wait until asset preview is loaded

![image](https://user-images.githubusercontent.com/8792145/147479269-8c90a401-5aa0-4517-820c-b6c246567b9c.png)

**Comment by brusch** [comment] 2021-12-29 14:28
See also: https://github.com/Imagick/imagick/issues/524

**Comment by brusch** [comment] 2022-01-11 10:19
Unable to reproduce anymore ... closing for now.

**Closed as completed by brusch** 2022-01-11 10:19 UTC
Labels: Bug
