### ISSUE TITLE
[Bug]: Every field is editable as admin

### ISSUE THREAD

**Issue by simonkey** [pimcore/pimcore#14280] opened 2023-02-09 14:06 UTC
### Expected behavior

Invisible and not editable fields in data object should be marked as them, even if you are logged in as admin.

### Actual behavior

After https://github.com/pimcore/pimcore/pull/14160 the `getSuperLayoutDefinition` is called and everything is editable.

### Steps to reproduce

Use Pimcore 10.5.16:

* Login as admin
* Create a data object with a field which is either not editable or invisible
* Every e.g. input field looks the same, even it shouldn't be edited because it's eg handled by an import.

Field with the settings:
![Screenshot from 2023-02-09 15-03-10](https://user-images.githubusercontent.com/1583145/217834384-f67a01d4-28f8-4c27-a9cd-38b8fe65c97e.png)

Logged in as admin:
![Screenshot from 2023-02-09 15-02-55](https://user-images.githubusercontent.com/1583145/217834409-7cb7c90e-a5b0-44d8-9fc3-466351b54cca.png)

Logged in as user:
![Screenshot from 2023-02-09 15-04-04](https://user-images.githubusercontent.com/1583145/217834434-44933138-50db-4b1e-b984-b32a6c167e72.png)

**Comment by mattamon** [comment] 2023-02-09 14:36
@simonkey https://github.com/pimcore/pimcore/issues/14241 we are aware of this issue :) 
Thank you for reporting.

**Comment by mcop1** [comment] 2023-02-13 10:25
Closed, because it is a duplicate of https://github.com/pimcore/pimcore/issues/14241

**Closed as completed by mcop1** 2023-02-13 10:25 UTC
Labels: Bug
