### ISSUE TITLE
[Tags] Search: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by GitHubUserDev12345** [pimcore/pimcore#4797] opened 2019-08-01 13:35 UTC
When filtering of 490 tags in PimCore Backend (found in version 5.7.3 and still there in version 6.0.5) you get an Javascript "Uncaught RangeError".

**How to reproduce**

- Open PimCore Backend
- Settings ->Tag Configuration
- Add 490 different tags
- Search for your word
- Look at the JS Error in the Developer Console in your browser ()

**Uncaught RangeError: Maximum call stack size exceeded**
at RegExp.exec ()
at RegExp.[Symbol.replace] ()
at String.replace ()
at Object.encodeString (ext-all.js?_dc=d2acc6e0bbf363175975fce77af0557b017739cb:22)
at Object.doEncode [as encodeValue] (ext-all.js?_dc=d2acc6e0bbf363175975fce77af0557b017739cb:22)
at encodeObject (ext-all.js?_dc=d2acc6e0bbf363175975fce77af0557b017739cb:22)
at Object.doEncode [as encodeValue] (ext-all.js?_dc=d2acc6e0bbf363175975fce77af0557b017739cb:22)
at encodeObject (ext-all.js?_dc=d2acc6e0bbf363175975fce77af0557b017739cb:22)
at Object.doEncode [as encodeValue] (ext-all.js?_dc=d2acc6e0bbf363175975fce77af0557b017739cb:22)
Show 170 more frames

**Comment by jones1008** [comment] 2019-08-13 07:57
this seems to be the same issue as #4725.
This is probably only tested with Chrome which gives a different error message

**Comment by stephan-herold** [comment] 2019-11-19 09:32
Same issue here for v5.8.7.
The tag list get filtered though. But the _Loading..._ overlay  does not disappear.

**Comment by knoepfchen23** [comment] 2020-01-08 13:42
I also experienced this error. Is there any solution?
I only have 100 tags.

**Comment by brusch** [comment] 2020-01-08 13:50
Duplicate of  #4725 - closed.

**Closed by brusch** 2020-01-08 13:50 UTC
