### ISSUE TITLE
[Bug]: definitionModificationDate expected by Version20230412105530 but only added by Version20230615103905

### ISSUE THREAD

**Issue by HageMaster3108** [pimcore/pimcore#17264] opened 2024-07-03 10:57 UTC
### Pimcore version

11.3.0

### Steps to reproduce

* Spin up a pimcore web <11.3.0-RC1 and create at least one data-object class definition
* Update to 11.3.0-RC1 or later (i updated to 11.3.0)
* Run core migrations

### Actual Behavior

Migrations give me the error
```
[notice] Saving class: Ansprechpartner
[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20230412105530 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'definitionModificationDate' in 'field list'"

In ExceptionConverter.php line 67:
                                                                                                                                                      
  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'definitionModificationDate' in 'field list'  
                                                                                                                                                      

In Exception.php line 28:
                                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'definitionModificationDate' in 'field list'  
                                                                                                       

In Statement.php line 130:
                                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'definitionModificationDate' in 'field list'  
```
This is because PR #15383 has introduced the field `definitionModificationDate` and added a migration [`Version20230615103905` (`pimcore/pimcore/bundles/CoreBundle/src/Migrations/Version20230615103905.php`) ](https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20230615103905.php) to create the column.
However because there is a migration which auto-regenerates all classes [`Version20230412105530` (`pimcore/pimcore/bundles/CoreBundle/src/Migrations/Version20230412105530.php`)](https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20230412105530.php) which is executed BEFORE `Version20230615103905`, that migration fails because it is missing `definitionModificationDate`.

### Expected Behavior

* The migration which re-generates the classes should run AFTER `Version20230615103905` (which adds `definitionModificationDate`).
* Hence core migrations should not fail in this scenario

**Comment by HageMaster3108** [comment] 2024-07-03 11:01
I decided to skip the one migration
` bin/console doctrine:migrations:version Pimcore\\Bundle\\CoreBundle\\Migrations\\Version20230412105530 --add` and run classes-rebuild manually after that...

**Comment by HageMaster3108** [comment] 2024-07-03 13:23
More migrations which basically regenerate the classes and may fail because of the missing field:
Version20211117173000 Version20230508121105 Version20230516161000
I guess this is mostly relevant when updating old webs.

**Comment by blankse** [comment] 2024-07-08 06:51
@HageMaster3108 Should be fixed by #17281

**Comment by toxyy** [comment] 2024-07-10 16:34
> I guess this is mostly relevant when updating old webs.

Of which there are a lot of... I wish things like this were tested before they're deployed.

**Comment by kingjia90** [comment] 2024-07-10 19:09
Maybe these class regeneration should not be executed in any migrations (also cannot be undone and has no `down()` anyways), as a rule of thumb. 
In future, what about a migration that just displays as a [message/warning at the end](https://www.doctrine-project.org/projects/doctrine-migrations/en/3.8/reference/events.html#migrations-events:~:text=onMigrationsMigrated%3A%20dispatched%20when%20all%20versions%20have%20been%20executed.) to remind to manually call the command?

Update: mhh, but sometimes we may need to do these regeneration before other migrations, so maybe it's not a fully viable solution yet

**Comment by brusch** [comment] 2024-07-12 08:14
@HageMaster3108 I'm wondering why migrations from 2023 are getting executed when updating from 11.3.0-RC1 to 11.3.0 ... 🤔 
Older migrations should be marked as done on install and therefore they shouldn't be executed anymore, see: 
https://github.com/pimcore/pimcore/blob/a96a60244d7d9bb26a0d69500a7075efc6fac686/bundles/InstallBundle/src/Installer.php#L550 

So I'd assume something went wrong during your installation. 
Can you confirm that?

**Comment by brusch** [comment] 2024-07-12 08:42
However, should be fixed by https://github.com/pimcore/pimcore/issues/17264

**Closed as completed by brusch** 2024-07-12 08:42 UTC
Labels: Bug, Pimcore:ToDo, Pimcore:Priority

**Comment by HageMaster3108** [comment] 2024-07-12 14:09
I did not update from the 11.3 release candidate, I updated from pimcore 10.
What I intended to say above ist that I noticed that the issue was caused by a change in the RC (but i updated to the final version).

**Comment by brusch** [comment] 2024-07-15 07:45
@HageMaster3108 thanks for clarifying. 
I assumed you were upgrading from `<11.3.0-RC1` because in the step to reproduce you were writing: 
> Spin up a pimcore web <11.3.0-RC1 and create at least one data-object class definition

Anyway, thanks a lot 👍😉

**Comment by dpfaffenbauer** [comment] 2024-07-15 07:47
FYI: I ran into the same issue upgrading from Pimcore 10. Will check if https://github.com/pimcore/pimcore/issues/17281 fixes it.
