### ISSUE TITLE
[Bug]: Chrome Headless Web2Print omits backgrounds even when explicitly told to keep them

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#12666] opened 2022-07-15 14:06 UTC
### Expected behavior

Background colours and images should be visible with these settings:
```json
{
  "displayHeaderFooter": false,
  "format": "A4",
  "height": "297mm",
  "landscape": false,
  "margin": {
    "top": "0mm",
    "bottom": "0mm"
  },
  "omitBackground": false,
  "preferCSSPageSize": true,
  "printBackground": true,
  "width": "210mm"
}
```

With this preview:
![image](https://user-images.githubusercontent.com/279826/179234421-4c1937ee-1aec-4553-94af-ec8c9f80223c.png)

### Actual behavior

Positioning works, but no backgrounds visible, not `background-color` nor `background-image`, nor `fill` in SVG:s:

![image](https://user-images.githubusercontent.com/279826/179234688-36fc4f9b-b44a-4893-acea-afa7ef6c0881.png)

### Steps to reproduce

Example HTML to send in a `printpage`:
```html
<!DOCTYPE html>
<html lang="nb">

<head>
	<meta charset="UTF-8">
	<title>Print</title>
	<link rel="stylesheet" type="text/css" media="all" href="https://localhost/static/ateles.1fcac.css"> </head>

<body class="pdf">
	<main class="page grid-wrapper custom-background">
		<div class="decoration grid-item-3-4-5-2 fill-primary"></div>
		<div class="decoration grid-item-1-4-7-2 fill-primary"></div>
		<div class="decoration grid-item-1-2-9-2 fill-primary"></div>
		<div class="decoration grid-item-3-6-1-4 fill-secondary"></div>
		<div class="logo grid-item-1-2-1-4 fill-primary logo-color">
			<svg viewBox="0 0 339.03 357.51" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet">
				<path d="M0,.14H10.46l21,47.78L52.11.14H62.63V73.48H51.51V27.75h-.25L35.92,63H26.66L11.32,27.75h-.2V73.48H0Z" />
				<path d="M148.58,0h46.83V10.5H159.69V31.43H190.2v9.86H159.69V62.82h35.72V73.33H148.58Z" />
				<path d="M292.2,0h11.12V62.82h35.71V73.33H292.2Z" />
				<path d="M7.51,142.68H35.93q10.81.09,16.24,5.43t5.49,14.23A16.915,16.915,0,0,1,55.49,171a13.991,13.991,0,0,1-3.29,3.72,23.793,23.793,0,0,1-5.33,3.37v.2a14.8,14.8,0,0,1,9.06,6.29,20.579,20.579,0,0,1,2.87,10.61q-.1,9.51-5.94,15A19.59,19.59,0,0,1,38.39,216H7.51Zm11.11,9.91v21h16q6.09,0,9-3.17a9.918,9.918,0,0,0,2.92-7.34,10.468,10.468,0,0,0-2.92-7.5q-2.86-2.87-9-3Zm0,30.88v22H35.73q6.18-.09,9-3.37a11.1,11.1,0,0,0,2.87-7.64,11.268,11.268,0,0,0-2.87-7.75q-2.86-3.169-9-3.27Z" />
				<path d="M166.75,185.84l-22.09-43.16h11.77l15.55,32.54,15.54-32.54h11.77L177.2,185.84V216H166.75Z" />
				<path d="M6.77,284.21H53.6v10.52H17.88v20.92H48.37v9.86H17.88V347H53.6v10.51H6.77Z" /> </svg>
		</div>
		<h1 class="heading text-color grid-item-4-5-2-1 grid-align-end">Frontpage 1</h1>
		<h2 class="subheading text-color grid-item-4-5-3-1">A subheader here</h2>
		<div class="version grid-item-8-9-12-13 fill-tertiary"> V1
			<br> </div>
		<div class="bu grid-item-1-2-5-2 bu-background-color bu-text-color">
			<svg viewBox="0 0 28 28" xmlns="http://www.w3.org/2000/svg">
				<path d="M27.15,11.77a.57.57,0,0,0-.64-.44.55.55,0,0,0-.44.64,12.57,12.57,0,0,1,.19,2.2A12.28,12.28,0,1,1,14,1.89h0A12.74,12.74,0,0,1,15.72,2a.57.57,0,0,0,.63-.47.55.55,0,0,0-.47-.62h0A13.36,13.36,0,1,0,27.23,16.05,13.66,13.66,0,0,0,27.15,11.77Z" />
				<path d="M19.4,10.71,11.1,19a.53.53,0,0,0,0,.75l0,0a.53.53,0,0,0,.76,0h0l11-11-6.78,1.56L25,1.42a.54.54,0,0,0,0-.76v0a.53.53,0,0,0-.75,0l0,0L12.65,12.27Z" /> </svg>
			<h3>Energi</h3> </div>
		<div class="bu-label grid-item-4-1-1-1 grid-align-end bu-background-color">
			<h5 class="bu-text-color">Energi</h5> </div>
	</main>
	<style media="all">
	.fill-primary {
		background-color: #6abe8a;
	}
	
	.fill-secondary {
		background-color: #388053;
	}
	
	.fill-tertiary {
		background-color: #fff28c;
	}
	
	.text-color {
		color: #f6f1ec;
	}
	
	.logo-color,
	.logo-color svg {
		color: #ffffff;
		fill: currentcolor;
	}
	
	.bu-background-color {
		background-color: #f6f1ec;
	}
	
	.bu-text-color,
	.bu-text-color svg {
		color: #003e20;
		fill: currentcolor;
	}
	
	.pdf .page.custom-background {
		background-color: #ffffff;
		background-image: url("http://localhost/30231/image-thumb__30231__large_print/hspennfjell.jpg");
	}
	</style>
</body>

</html>
```

**Comment by kingjia90** [comment] 2022-07-15 19:06
Can you give it a try with square brackets instead curly?

It feels like none of the options are actually set, including the `margin top` and `bottom` as `0`.
```
[
  "displayHeaderFooter": false,
  "format": "A4",
  "height": "297mm",
  "landscape": false,
  "margin": [
    "top": "0mm",
    "bottom": "0mm"
  ],
  "omitBackground": false,
  "preferCSSPageSize": true,
  "printBackground": true,
  "width": "210mm"
]
```
It's the main difference i see from the official documentation
https://github.com/spiritix/php-chrome-html2pdf/blob/master/README.md#usage

**Comment by NiklasBr** [comment] 2022-07-15 19:18
The settings *must* be a JSON dict, otherwise it throws an error. See here: https://github.com/pimcore/pimcore/blob/ce622b63335ef1cd262f94e3be4de36a17668751/lib/Web2Print/Processor/HeadlessChrome.php#L40

**Comment by kingjia90** [comment] 2022-07-15 19:31
Yes, my bad, i've just realized that i missed that and deleted that comment. 
But the other input that the margin top and bottom are also wrong might be valid, i guess the entire configuration is ignored or not properly loaded, not just background. What we see may be the results of the default options:
https://github.com/pimcore/pimcore/blob/75bbc5bbacbd57383ccb20e52bbb151397b81a78/lib/Web2Print/Processor/HeadlessChrome.php#L120-L134
If you change to `landscape` to `true`, is it still in portrait mode?

**Comment by NiklasBr** [comment] 2022-07-16 13:06
Settings are as expected here:
![image](https://user-images.githubusercontent.com/279826/179354563-8db4a70b-34df-4ddc-af88-f06f2b07ea67.png)


And testing by changing the web2print setting `landscape`to `true` is also reflected here:
![image](https://user-images.githubusercontent.com/279826/179356011-a0de9a5d-1c7c-426d-8528-eb1ff45c2d5d.png)


And as expected here:
![image](https://user-images.githubusercontent.com/279826/179356087-aad25ab4-2983-48fe-bc09-7a828534fb94.png)


But the end result is unchanged:
![image](https://user-images.githubusercontent.com/279826/179356148-beaea6fa-aa59-4c85-b82d-39a155f75143.png)

**Comment by NiklasBr** [comment] 2022-07-19 10:47
@kingjia90 I notice that even the Test page does not properly adhere to landscape and background settings. e.g. this does not affect the end result at all

```json
{
  "displayHeaderFooter": false,
  "format": "A4",
  "landscape": true,
  "margin": {
    "top": "0 mm",
    "bottom": "0 mm",
    "left": "0 mm",
    "right": "0 mm"
  },
  "omitBackground": true,
  "preferCSSPageSize": true,
  "printBackground": false,
}
```

It is still in portrait and shows backgrounds.

**Comment by kingjia90** [comment] 2022-07-19 10:54
> @kingjia90 I notice that even the Test page does not properly adhere to landscape and background settings. e.g. this does not affect the end result at all
> 
> ```json
> {
>   "displayHeaderFooter": false,
>   "format": "A4",
>   "landscape": true,
>   "margin": {
>     "top": "0 mm",
>     "bottom": "0 mm",
>     "left": "0 mm",
>     "right": "0 mm"
>   },
>   "omitBackground": true,
>   "preferCSSPageSize": true,
>   "printBackground": false,
> }
> ```
> 
> It is still in portrait and shows backgrounds.

Test page doesn't currently load the configs
https://github.com/pimcore/pimcore/blob/ce622b63335ef1cd262f94e3be4de36a17668751/bundles/AdminBundle/Controller/Admin/SettingsController.php#L1810-L1827
it uses the default if `$params` is empty
https://github.com/pimcore/pimcore/blob/ce622b63335ef1cd262f94e3be4de36a17668751/lib/Web2Print/Processor/HeadlessChrome.php#L91-L93

**Comment by kingjia90** [comment] 2022-07-19 11:01
Was trying to debug, but I got stuck here
https://github.com/pimcore/pimcore/blob/ce622b63335ef1cd262f94e3be4de36a17668751/lib/Web2Print/Processor/HeadlessChrome.php#L44 Have you also encoutered problems there with the DocumentRenderer?
IMHO if the `params` are correctly passed, it going to be a third party bug because after 

```
$converter->setOptions($params);
$output = $converter->convert();
``` 
would be all in the hands of the Spiritix bundle

**Comment by NiklasBr** [comment] 2022-07-19 11:23
> Test page doesn't currently load the configs

Aha, maybe it should?

**Comment by NiklasBr** [comment] 2022-07-19 12:04
I wonder if this code is fully correct, especially the `$params = ['document' => $document]; ` line.

https://github.com/pimcore/pimcore/blob/ce622b63335ef1cd262f94e3be4de36a17668751/lib/Web2Print/Processor/HeadlessChrome.php#L36-L46

Because `$this` is already used here:

https://github.com/pimcore/pimcore/blob/f9527b064dee119bbe75002d014d154a4414d9d6/models/Document/PrintAbstract.php#L126-L131

So maybe `$web2printConfig` should be where `$params` are?

**Comment by kingjia90** [comment] 2022-07-25 08:48
> Was trying to debug, but I got stuck here
> 
> https://github.com/pimcore/pimcore/blob/ce622b63335ef1cd262f94e3be4de36a17668751/lib/Web2Print/Processor/HeadlessChrome.php#L44
> 
> Have you also encoutered problems there with the DocumentRenderer?

The problem i have encountered got fixed here https://github.com/pimcore/pimcore/pull/12745 and i was able to proceed, but i cannot reproduce the problems of background and configuration settings. Test page is also working fine with the settings.

Which version Pimcore and Spiritix are you on?

**Comment by kingjia90** [comment] 2022-07-29 10:54
> I wonder if this code is fully correct, especially the `$params = ['document' => $document]; ` line.
> Because `$this` is already used here:
> So maybe `$web2printConfig` should be where `$params` are?

@NiklasBr I don't know exactly, but as far as i understood, the `$params` renderer is just for the html rendering, while `$web2printConfig` is basically the stuff in the print dialog that we see in Chrome
![image](https://user-images.githubusercontent.com/6014195/181742930-737b2560-c1d6-4250-a2bc-e2fce159cc39.png)
so it shouldn't be replacing `$params` and it's used only by the Spiritix `$converter`

One thing is that `$config` parameter is never used here, but so far it works for me, so just wondering if there's any further details or feedback to reproduce the problem. Did the test page with colored background work for you?

**Comment by kingjia90** [comment] 2022-08-01 11:14
Closing for the moment as it's not reproducible. Please reopen with further details, if it's still occuring.

**Closed as not planned by kingjia90** 2022-08-01 11:14 UTC
Labels: Bug
