### ISSUE TITLE
[Bug]: 11.x "Redirect additional domains to main domain" doesn't work

### ISSUE THREAD

**Issue by Daniel-Ateles** [pimcore/pimcore#16705] opened 2024-02-29 12:59 UTC
### Pimcore version

11.1.5

### Steps to reproduce

Set an additional domain in site settings.
Turn on "Redirect additional domains to main domain".
Go to the additional domain.

This results in "There is currently no session available".

### Actual Behavior

Symfony Exception  "There is currently no session available"

### Expected Behavior

Url redirected to main domain and normal load of site.

**Comment by DzemalBecirevic** [comment] 2024-03-01 07:28
Yes, this is causing a lot of problems for us where we have internal domains as additional domains that do not work anymore.

**Comment by Daniel-Ateles** [comment] 2024-03-01 13:51
I now noticed this error is for *all* redirects, including the auto-redirects made when moving documents.

**Comment by kingjia90** [comment] 2024-03-04 17:03
Couldn't reproduce so far, any tips?

**Comment by Daniel-Ateles** [comment] 2024-03-05 15:08
Hi @kingjia90 I think I've found out the culprit of the problem: If you have the SeoBundle activated it will send a GoogleTagManagerEvents::CODE_HEAD event on onKernelResponse that the ecom bundle's TrackingCodeSubscriber listens for and executes $this->trackingManager->getActiveTrackers() that in turn tries to getCurrentAssortmentTenant that in turn tries to do a SesssionEnvironment->load() that finally will throw a SessionNotFoundException.
Simple as that.
Where should I file a bug-report?

**Comment by kingjia90** [comment] 2024-03-05 15:15
Ahhh, thank you, reporting here it's fine for SeoBundle as it is under [/bundles](https://github.com/pimcore/pimcore/tree/11.x/bundles/SeoBundle) , maybe just change the issue title a little bit

> Simple as that

😄 Would you also be able to provide a PR to fix that? I still have to reproduce it (and anyways for the eventual review later) and if you already into it and have a possible solution, that would save some time.

**Comment by Daniel-Ateles** [comment] 2024-03-06 07:07
@kingjia90 I will try now :) Not sure I will do the correct architecturally choices so you will have to examine the PR very carefully.

**Comment by Daniel-Ateles** [comment] 2024-03-06 14:34
@kingjia90 here is the PR. It got quite small and is easy to understand: https://github.com/pimcore/google-marketing-bundle/pull/45

**Comment by kingjia90** [comment] 2024-03-06 14:52
Nice, thank you very much for it! 
Will have a look asap, just quickly rebased the PR from `1.x` to `1.0` in the meanwhile,

**Comment by kingjia90** [comment] 2024-07-03 13:38
Fixed by https://github.com/pimcore/google-marketing-bundle/pull/45

**Closed as completed by kingjia90** 2024-07-03 13:38 UTC
Labels: Bug, Pimcore:ToDo
