### ISSUE TITLE
editableRenderer is null (Bricks, Pimcore 6.8.1)

### ISSUE THREAD

**Issue by nspacex** [pimcore/pimcore#7267] opened 2020-10-08 11:41 UTC
# Bug Report

### Expected behavior

Calling getDocumentEditable should return the Editable Object. 

### Actual behavior

Calling this method, throws an error ("Call to a member function getEditable() on null") cause $editableRenderer (\lib\Extension\Document\Areabrick\AbstractAreabrick.php) is null / is "not set" in the constructor

### Steps to reproduce

Try to call the method inside the brick's action() method 

### Code example
```php
public function action(Info $info) {
    $this->getDocumentEditable( $info->getDocument(), 'input', 'someInputName' );
}
```

**Comment by brusch** [comment] 2020-10-08 12:29
@nspacex Hmm, I'm unfortunately not able to reproduce the problem. 
`$this->editableRenderer` can't be null, it's set set in the constructur and not nullable: 
https://github.com/pimcore/pimcore/blob/6.8/lib/Extension/Document/Areabrick/AbstractAreabrick.php#L39

So how should that work?

**Comment by nspacex** [comment] 2020-10-08 13:56
@brusch Unfortunately I do not know at the moment. I have the problem in an instance updated from 6.7.2 to 6.8.1. I will have a closer look at it again.

**Comment by nspacex** [comment] 2020-10-08 14:08
For completeness [trace.txt](https://github.com/pimcore/pimcore/files/5348431/trace.txt)

**Comment by nspacex** [comment] 2020-10-08 16:54
@brusch I tried it again with a clean installation (6.8.0 -> 6.8.1). There it works with a very simple brick and the auto registration. But as soon as you define the service yourself (like described in the docs) and inject some others services, this error occurs.

```
AppBundle\Document\Areabrick\Test:
    arguments: ['@logger', '@translator' ...]
    tags:
         - { name: pimcore.area.brick, id: test }
```

If I change that to the following:

```
AppBundle\Document\Areabrick\Test:
    arguments: ['@Pimcore\Templating\Renderer\EditableRenderer', '@logger', ...]
    tags:
        - { name: pimcore.area.brick, id: test }
```

AND call the parent constructor (__construct from AbstractAreabrick.php with the EditableRenderer as argument) in the bricks own constructor , it works. 

The initial error message was unfortunately something missleading. In a clean installation you get the "right" one or one that is a bit clearer, namely that the order or types of arguments does not fit

**Comment by jdreesen** [comment] 2020-10-08 17:34
You're right, this is a breaking change resulting from the refactoring in #6921. 
`Pimcore\Extension\Document\Areabrick\AbstractAreabrick` now has a constructor (with one parameter) which must be called from custom classes that also have a constructor and extend the abstract one. There should be a note in the changelog.

**Comment by brusch** [comment] 2020-10-08 18:24
I thin we can fix that with an `@required` annotation instead of injecting the editable renderer to the constructor - that should work as a fix right?

**Comment by dpfaffenbauer** [comment] 2020-10-09 06:44
@brusch Only if the bricks are autowired. You could create a CompilerPass that adds the 'call' param automatically

**Comment by brusch** [comment] 2020-10-09 08:58
Fixed by c5646276fd80a3c818bb47fbd39d626f34bd636e

**Closed by brusch** 2020-10-09 08:58 UTC
Labels: Bug

**Comment by blankse** [comment] 2020-10-12 06:14
> Fixed by [c564627](https://github.com/pimcore/pimcore/commit/c5646276fd80a3c818bb47fbd39d626f34bd636e)

@brusch The fix should be in 6.8 branch (is in master branch), right?

**Comment by brusch** [comment] 2020-10-12 06:49
@blankse  No, it is in `6.8` 😉
But GitHub now says already `master` because `6.8` was already merged into `master` 😉
But thanks anyway for having an eye on it 😊

**Comment by blankse** [comment] 2020-10-12 07:00
@brusch OK, then it's good 👍🏼😊
