### ISSUE TITLE
[Bug] Renaming unpublished object is no more possible.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5016] opened 2019-09-25 16:46 UTC
Hello,

On the online demo Pimcore website, if you do on the backend :
- create a new "News" object at the root of the object tree and call it "test"
- save it (not published)
- rename it in the tree

You will get an error with message: `You can't relocate if there's a newer not published version`

Actually we cannot rename in the tree unpublished object. I think it is a pretty new bug because we haven't this one on older Pimcore.

**Comment by dvesh3** [comment] 2019-10-25 08:18
this is the case if there is "a newer not published version", please see https://github.com/pimcore/pimcore/issues/4905 and also https://github.com/pimcore/pimcore/blob/ce2138fb35fe84ab3fa22ba7cf0a882c6cb9341f/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L997-L1004

**Comment by Yivan** [comment] 2019-10-25 11:33
You mean it is intended ?
Now we must publish object to be able to rename the key ?
I mean the 3 step actions i done (see first post), are pretty common and many users can fall in this message.

I think we really must be able to rename the key not depending the published state, like it was before.
Content/data managers need this to be able to prepare datas without publishing objects (same for documents).

I link it to this issue, maybe related or at least in the same scope:
https://github.com/pimcore/pimcore/issues/5136

Thanks.

**Comment by jms-gsulcer** [comment] 2020-03-26 20:05
Not just objects, this also affects documents as well.  This is a new behavior, somewhere between 6.2.1 and 6.5.3 (we have both versions running).

This is a big issue with documents because it is common that documents are created with "placeholder" values while SEO strategies are developed, but the document remains unpublished until all information is final, including the document key.

Currently, we are forced to first publish the document, then rename it.  It's not catastrophic, but it does mean the document is "live" on the site for a brief period, which is unexpected behavior

**Comment by fashxp** [comment] 2023-12-19 13:59
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed by fashxp** 2023-12-19 13:59 UTC
Labels: PR Welcome
