### ISSUE TITLE
[Bug][QuickSearch] Searching/previewing asset documents results in error message

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#15474] opened 2023-07-04 08:21 UTC
### Pimcore version

11

### Steps to reproduce

- open quicksearch
- search for document asset (e.g. csv or json file)
- hover with mouse over asset 

![image](https://github.com/pimcore/pimcore/assets/8792145/38ca336f-3fe5-449d-bca9-e672da82cd3c)

![image](https://github.com/pimcore/pimcore/assets/8792145/20728d95-35c1-4cce-ae0c-ca8c62aa447f)

### Expected / actual behavior

no error message

**Comment by dvesh3** [comment] 2023-07-04 09:14
duplicate of pimcore/demo-enterprise#202

**Closed as completed by dvesh3** 2023-07-04 09:14 UTC
Labels: Bug
