### ISSUE TITLE
Pagination disappears when saving an object

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6530] opened 2020-06-04 15:01 UTC
I have an object that has more than 30 direct children. I get a pagination in the tree. 

<img width="907" alt="Bildschirmfoto 2020-06-04 um 16 54 51" src="https://user-images.githubusercontent.com/8749138/83773199-87a73e80-a684-11ea-80d5-8419c4b97716.png">

Now I open the parent element and at the same time I open the list of child elements via the plus icon in the tree. When I save the parent element, the pagination of the open parent element disappears in the tree.

<img width="915" alt="Bildschirmfoto 2020-06-04 um 16 54 59" src="https://user-images.githubusercontent.com/8749138/83773197-85dd7b00-a684-11ea-84eb-5bc49827002c.png">

----
General Information:
Detected in Pimcore Version: v6.5.3 (also in latest release, see demo.pimcore.fun)

**Comment by weisswurstkanone** [comment] 2020-06-09 11:05
Unable to reproduce. Can you share a short video demonstrating the problem please?

**Comment by BlackbitNeueMedien** [comment] 2020-06-09 11:33
I have attached a zip file with a short one minute log video which demonstrate the issue. 

[Bildschirmvideo aufnehmen 2020-06-09 um 13.28.17-720p.mov.zip](https://github.com/pimcore/pimcore/files/4751867/Bildschirmvideo.aufnehmen.2020-06-09.um.13.28.17-720p.mov.zip)

**Comment by weisswurstkanone** [comment] 2020-06-09 12:53
Thx, seems to be a nasty side effect of this line:

https://github.com/pimcore/pimcore/blob/a9f787995202fa4729ab26405c940464ae7f35f4/bundles/AdminBundle/Resources/public/js/pimcore/helpers.js#L229

**Comment by brusch** [comment] 2020-06-09 15:16
@BlackbitNeueMedien can you confirm that?

**Comment by brusch** [comment] 2020-06-19 09:41
Fixed by #6577

**Closed by brusch** 2020-06-19 09:41 UTC
Labels: Bug

**Comment by patrickbitzer** [comment] 2020-07-15 08:03
> @BlackbitNeueMedien please check if #6577 solves your problem & if you notice any side effects

Sorry for this late response. But at the moment we have many work :D.

This fix does not has any effects. I build in this changes in our clients code, but the problem i described has already been there. Any other solutions?

**Comment by patrickbitzer** [comment] 2020-07-15 09:14
Sorry. The adjustment does work. I got the line wrong. It's all fixed and working fine now.
Thanks again. I delete the Pull Request again ;-)
