### ISSUE TITLE
"Show In Tree" not working

### ISSUE THREAD

**Issue by pradeeppimcore** [pimcore/pimcore#17897] opened 2024-12-05 10:03 UTC
### Pimcore version

11.4.3 OR v2024.3 (pimcore demo site)

### Steps to reproduce

1. Open any data object or asset.
2. Use "Show in tree" button.
3. Observe that Pimcore is not locating object/asset in tree.

I have tried this on the pimcore demo site (https://demo.pimcore.com/admin/) as well and it is not working there also.

### Actual Behavior

Show in tree is not locating the element in tree.

### Expected Behavior

Show in tree should locate the element in tree.

**Comment by blankse** [comment] 2024-12-05 11:16
@pradeeppimcore Duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/778

**Closed as not planned** 2024-12-07 20:30 UTC
Labels: Bug
