### ISSUE TITLE
[Bug]: Documents are not copied completely

### ISSUE THREAD

**Issue by manuelkleinert** [pimcore/pimcore#17455] opened 2024-08-07 06:34 UTC
### Pimcore version

11.3.1

### Steps to reproduce

After copying a document, the title, name and attributes are missing:

<img width="1422" alt="Bildschirmfoto 2024-08-07 um 08 27 34" src="https://github.com/user-attachments/assets/4300fbb9-7300-4898-964c-f20922a70469">

<img width="1429" alt="Bildschirmfoto 2024-08-07 um 08 30 28" src="https://github.com/user-attachments/assets/cf0ac00a-22f9-4ffb-b645-ca9d86c7ea80">

### Actual Behavior

If I want to copy several or individual documents, several contents are missing afterwards. Title, name or attributes...

### Expected Behavior

The content (title, name or attributes) of the documents should also be copied

**Comment by hadl** [comment] 2024-10-01 11:03
Any updates on this?

Copying documents to create new language trees and loosing the data is a huge issue.

Or did anyone find a "workaround"?

**Comment by manuelkleinert** [comment] 2024-10-07 08:33
@fashxp Why hasn't this bug been fixed?

**Comment by fashxp** [comment] 2024-10-07 08:39
Because we didn't had the time yet and no one provided a PR for it yet ...

**Comment by cadeyrn** [comment] 2024-10-25 07:27
This is a serious regression of a core feature that complicates the workflow for the content people and increases the risk of missing data and it's known since 2 1/2 months. Can this please be prioritized? This bug is no longer even assigned to a milestone.

**Comment by hadl** [comment] 2024-11-07 07:32
Another info for this issue: 

If you paste via "Paste as new language variant" or "Paste as new language variant (recursive)" the properties are kept 👍  
**BUT** the `language` property is not _inherited_ anymore &rarr; it will be written for every document in the properties table 👎 

This behavior should be fixed as well. Thx

**Comment by blankse** [comment] 2024-11-07 09:15
I created a PR: https://github.com/pimcore/pimcore/pull/17805

**Comment by martineiber** [comment] 2024-11-15 11:14
Fixed by https://github.com/pimcore/pimcore/pull/17805

**Closed as completed by martineiber** 2024-11-15 11:14 UTC
Labels: Bug, Pimcore:ToDo

**Comment by jdreesen** [comment] 2024-11-15 11:16
No milestone? Also in the PR?
