### ISSUE TITLE
[Feature]: multiple selection of assets in search assets popup (gallery field)

### ISSUE THREAD

**Issue by coes-devs-jakala** [pimcore/pimcore#17175] opened 2024-06-13 13:07 UTC
### Feature description

Is there a way to select multiple assets in "Search Assets" popup that shows up when you are adding new images into a gallery field?

![Schermata 2024-06-13 alle 15 00 03](https://github.com/pimcore/pimcore/assets/151197252/54d1b9ab-1576-4139-95ec-76a64ca1d46e)

**Comment by ghost** [comment] 2024-06-19 10:53
Duplicate of [https://github.com/pimcore/pimcore/issues/17176](https://github.com/pimcore/pimcore/issues/17176), so closing.

**Closed as not planned by ghost** 2024-06-19 10:53 UTC
Labels: New Feature
