### ISSUE TITLE
[Bug]: Translated keys are not working in the search mechanism

### ISSUE THREAD

**Issue by kamilawiercinska** [pimcore/pimcore#12903] opened 2022-08-17 09:29 UTC
### Expected behavior

A key from Classification Store named "extra features" in English shows up on the screen and you can add it to grid.

### Actual behavior

No results from search. You have to type "Cechy dodatkowe" (which is a key for this feature and appears in shared translations) to be able to see the search results.
Right now, foreigners cannot work with the app.

![image](https://user-images.githubusercontent.com/49391646/185084739-07829fc6-5179-477a-93e1-2088d9ff625c.png)
![image](https://user-images.githubusercontent.com/49391646/185084891-816e16b7-1cd2-4601-a108-3b01da0b7bfe.png)
![image](https://user-images.githubusercontent.com/49391646/185084982-1e30519e-4192-47bc-9cf6-b12f5d6a8248.png)

### Steps to reproduce

1. Set application settings for the selected language as "English"
2. Open objects grid
3. Open Grid Options
4. Select Product Features from Classification Store
5. Look for a feature via search engine. Type "extra features"

**Comment by dvesh3** [comment] 2022-08-24 10:23
@kamilawiercinska It seems you are using older version of Pimcore (by looking at your screenshot). Now `admin` & `shared` translations are merged into single UI with lot of fixes. could you please try to reproduce the issue on latest version 10.5.3? thanks!

**Comment by kamilawiercinska** [comment] 2022-08-24 10:57
@dvesh3 
Sure, I did it on 10.5.2

1. add translations 
![image](https://user-images.githubusercontent.com/49391646/186401051-974a7bbd-b9b4-494a-a509-9a7fd19d7919.png)
![image](https://user-images.githubusercontent.com/49391646/186401407-0e27aac1-349a-4d70-8056-71dd564bd858.png)
2. go to grid
3. select language EN (this language is also my app language)
4. observe
![image](https://user-images.githubusercontent.com/49391646/186401563-4134b12f-a88d-41dd-b89a-e600e4f67589.png)
5. search with translation
![image](https://user-images.githubusercontent.com/49391646/186401623-bb3c1573-619b-4c66-b58b-ed53a5aaddfd.png)
No results.
6. search with key
![image](https://user-images.githubusercontent.com/49391646/186401720-cd615200-25f5-4bd9-ad83-c14efa6d8593.png)
It works

**Comment by dvesh3** [comment] 2022-08-24 11:49
Sorry, I was looking at the wrong place. The actual issue is on CS store key selection grid on Grid options.

**Comment by kamilawiercinska** [comment] 2022-09-02 10:03
Hello, any updates?

**Comment by robertSt7** [comment] 2022-09-02 11:48
@kamilawiercinska I was able to reproduce the bug and estimate the time it will take to fix. We will consider it next week in the planning.

**Comment by robertSt7** [comment] 2022-09-22 11:19
Since we are using an index search and we are only indexing the key, the search is limited to the key and indexing all languages of a key would make the index extremely large. As alternative you could use the filter for the translated values.

**Comment by kamilawiercinska** [comment] 2022-09-22 13:45
Please advise then, does your last comment mean that you are not going to fix that behaviour?
And can you please explain more about the filter for the translated values?

**Comment by brusch** [comment] 2022-09-22 14:18
Yes, we not gonna work on that anytime soon. 
The search uses the search index, which only includes the values and not the translated labels.

**Closed as completed by brusch** 2022-09-22 14:18 UTC
Labels: Bug

**Comment by kamilawiercinska** [comment] 2022-09-27 09:51
@robertSt7 
You wrote "As alternative you could use the filter for the translated values." - the filter mechanism does not work with the translated labels either. Should it work?

**Comment by robertSt7** [comment] 2022-09-28 09:20
@kamilawiercinska Yes, it should work. Could you please provide more details?

**Comment by kamilawiercinska** [comment] 2022-09-28 09:49
@robertSt7 
1. i am logged as a french user
2. opening car grid
3. choosing CS
4. filtering by french name

https://user-images.githubusercontent.com/49391646/192748169-8c5ec469-489c-4ef4-ace0-1dfc40e2c7e6.mp4


only english (key) name works in the filter mechanism, same as the search one. even though, the french name is visible on UI, which causes user's confusion.

**Comment by brusch** [comment] 2022-10-06 08:22
@kamilawiercinska thanks again for sharing the details. 
Unfortunately that's quite a tricky thing, I guess it would be best to just remove the filters to avoid confusion. 
Can you provide a PR for that? 

Thanks in advance!
