### ISSUE TITLE
[Bug]: >>Invalid domain name ""<< exception on Pimcore admin load

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#17697] opened 2024-10-08 11:56 UTC
### Pimcore version

11.4.1

### Steps to reproduce

- We have a multi site setup with multiple domains for document root folders. But I don't know if this makes a difference for the error.
- Update Pimcore from v11.3.2 to v11.4.0 or v11.4.1
- Log in into the Pimcore admin
- Open the frontend

### Actual Behavior

When opeing the frontend URL the exception _Invalid domain name ""_is thrown.

In the Pimcore admin while loading the documents tree multiple errors pop up with the exception:
`Message: Invalid domain name "" Trace:  in /var/www/html/vendor/pimcore/pimcore/models/Site.php:236`

Here some screenshots of the debugging info. "setDomains" is called with empty data and this results in the error. I first thaught the bug may be resvolved with https://github.com/pimcore/pimcore/pull/17685 but this error seems to be sth. different...

Currently I tried the Pimcore update on localhost only.

![grafik](https://github.com/user-attachments/assets/d771f620-cc68-4032-87fd-38f486dbbcd4)

![grafik](https://github.com/user-attachments/assets/e08ac769-fca1-4038-898f-f8e333da2bea)

![grafik](https://github.com/user-attachments/assets/ef98bb8d-b81d-48a7-a5bc-62ca02ccbe8a)

![grafik](https://github.com/user-attachments/assets/02a4c959-7f9e-49a5-9abb-6a640dae11ff)

![grafik](https://github.com/user-attachments/assets/5f236414-d85a-43c3-8a98-eb01ccaddee7)

### Expected Behavior

The frontend and pimcore admin document tree loads without errors.

**Comment by akno77** [comment] 2024-10-08 12:07
Maybe the error has sth. to do with doing "Remove site" for a "site"? I had some strange behaviors with this in the past...

**Comment by akno77** [comment] 2024-10-08 12:25
The Ajax URLs producing an error are:
- http://localhost/admin/document/tree-get-root?_dc=1728390260709&id=1&view=&elementType=document
- http://localhost/admin/settings/get-available-sites?_dc=1728390260964&page=1&start=0&limit=25

**Comment by kingjia90** [comment] 2024-10-08 12:28
Thank you for reporting!

The error is simply reproduce-able if you have an empty new line on `Additional Domains(one domain per line)`
![image](https://github.com/user-attachments/assets/adf474b6-0a20-4af8-ac06-aadd39814f99)
If that's the case, you should be removing the empty line manually, so that the line cursor looks like
![image](https://github.com/user-attachments/assets/22b4cc57-7c67-4f48-8705-70d3400c4657)

In the next bug fix release, i think i will exclude the empty line from being checked and will provide a PR for it

**Comment by akno77** [comment] 2024-10-08 12:28
And this is how my sites look in the db:

![grafik](https://github.com/user-attachments/assets/b07de509-4ed1-49a6-8c2f-bc994f9f18e2)

**Comment by akno77** [comment] 2024-10-08 12:30
@kingjia90 thank you for the feedback. But in my case I don't have any additional domains defined...

**Comment by kingjia90** [comment] 2024-10-08 12:33
Ah, can you replace the values of `domains` to `a:0:{}`? The unserialized value is still a string and thus is causing issues

**Comment by kingjia90** [comment] 2024-10-08 12:44
May be fixed by https://github.com/pimcore/pimcore/pull/17698 in `11.4.2`, could you please give it a try and help review? Thank you in advance

**Comment by akno77** [comment] 2024-10-08 12:47
Yes, changing the db values for "domains" solves the problem! But how did the wrong values come into the db?
Before I deploy a Pimcore Update to a production system I'd have to check if there are such values in the db anotherwise the whole frontend of the site would crash with the exception...

I also tested to set a additional domain. It was not saved in the db. If I added a return in the field it was saved but produces the same "Invalid domain name" error...

**Comment by akno77** [comment] 2024-10-08 12:51
> I also tested to set a additional domain. It was not saved in the db. If I added a return in the field it was saved but produces the same "Invalid domain name" error...

This was wrong...my fault....the debugger prevented from saving.

**Comment by akno77** [comment] 2024-10-08 13:06
@kingjia90 https://github.com/pimcore/pimcore/pull/17698 seems to work

**Comment by kingjia90** [comment] 2024-10-08 15:03
Thank you for the confirmation, the PR is merged and i am closing this issue as resolved

**Closed as completed** 2024-10-08 15:03 UTC
Labels: Bug

**Comment by NiklasBr** [comment] 2024-10-15 12:11
Same problem in 11.4.1, the fix in #17698 appears to fix it.

**Comment by jdreesen** [comment] 2024-10-15 12:14
But only for non-IDN domains: #17724
