### ISSUE TITLE
Mod_pagespeed incompatibility with latest version 4.2 breaks admin interface

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#762] opened 2016-07-22 07:54 UTC
# Possible Bug Report
After upgrading two pimcore installations on two different servers, I got errors in the Pimcore backend.
I updated from 4.1.3 to 4.2.0 (stable branch) without errors.

The frontend keeps working fine but the backend will show the loading image for one second and after that a completely white page. There are no entries in debug or php error log.
Firebug shows this:
![pimcore error](https://cloud.githubusercontent.com/assets/2771909/17093338/f366591a-5248-11e6-923d-b29fc10ea1d5.png)

I thought it'd be a damaged file somewhere and replaced all files with new ones from the pimcore release without success. I guess the update itself has been tested so it might be the configuration of our servers - but the two servers are configured slightly different and both - independent - pimcore installations had the same issue so this might be a bug.

File permissions are correct, database is okay as far as I can see. Frontend is working.

**Comment by brusch** [comment] 2016-07-22 09:33
No, doesn't seem to be a bug in general. 
We have the update also an many different environments and we didn't see any issue. 

Please further debug this and if it is a bug in pimcore, please let me know. 
A good starting point would be to look at the contents of script in question (first error in console) and then here https://github.com/pimcore/pimcore/blob/e27a93ce3683cd730d046ba04f1ac9b69ed3e128/pimcore/modules/admin/controllers/MiscController.php#L70-L70 why you have so many strange characters in your scripts.

**Comment by Cruiser13** [comment] 2016-07-22 10:09
Thank you for the reply @brusch 
I've been able to debug this further. Calling /admin/misc/script-proxy?scriptPath=%2Fwebsite%2Fvar%2Fsystem%2F&scripts=minified_javascript_core_23d18d0e622710fad0ce21c4da5a0e5f.js&_dc=3858 from my browser does correctly output the JS file. replacing dc=3858 by dc=3900 (pimcore default for ACP) does cause the strange characters in the JS file. Since I reuploaded all JS files of pimcore (I replaced the whole installation with a newly downloaded zip from pimcore.org) I'm not sure where to go from here.
If I download the minified_javascript_core_23d18d0e622710fad0ce21c4da5a0e5f.js from my website/var/system via FTP everything is fine, the JS looks properly - just like the JS looks if I use the query param dc=3858 in the browser.

**Comment by brusch** [comment] 2016-07-22 10:15
As I said, ... this must be something on your side. 
The _dc parameter has absolutely no functionality, it's just there as a cache buster. It's not reproducible, so there's nothing further we can do about that. Please solve this on your system, if there's anything we have to fix in the core, let us know, or even better, create a PR for us. 

Thanks!

**Comment by brusch** [comment] 2016-07-22 10:17
check also: 
https://github.com/pimcore/pimcore/blob/e27a93ce3683cd730d046ba04f1ac9b69ed3e128/pimcore/modules/admin/controllers/MiscController.php#L98-L98 

It's not that complex what happens in this script proxy, so it should be quite easy to debug.

**Comment by Cruiser13** [comment] 2016-07-22 11:15
I'll continue posting our findings here just in case anybody else has similar issues.
Switching from PHP-FPM to FastCGI does solve the issue - but is no real option.

Since Pimcore 4.1.3 worked fine, we tracked the issue down to the new PHP-DI solution. It had issues with caching in the past ( https://github.com/PHP-DI/PHP-DI/issues/266 ) and it seems to me that it does now cause issues for our environment with PHP-FPM.

**Comment by brusch** [comment] 2016-07-22 11:41
You mean from FCGI to FastCGI?

**Comment by Cruiser13** [comment] 2016-07-22 11:57
@brusch we're usually running Pimcore using PHP-FPM: http://php-fpm.org/ as FastCGI implementation instead of the usual FastCGI implementation. 
But it looks like PHP-DI has some issues with it, this is from the official homepage: http://php-di.org/doc/container-configuration.html

> There has been reports that PHP-FPM might choke on such errors ...

Since errors appeared with 4.2 and the main change was PHP-DI, I guess that's our issue with PHP-FPM. Running the site in FastCGI directly now, works properly. PHP-FPM is faster though so I'd really like a solution for this issue. It's also interesting that the frontend is working properly. And it looks like the MiscController is not even executed if we have these strange chars. It's like served from cache but opcache and apc are disabled, aswell as mod_pagespeed and all others. And since it works with a different PHP implementation I'm pretty sure that's the error. We have no issues anywhere else on that server.

**Comment by brusch** [comment] 2016-07-22 12:33
We are running also PHP-FPM using mod-fastcgi on apache ... no problems. 

But still, we'd need some more info on that...

**Comment by brusch** [comment] 2016-07-25 06:57
Any updates on this issue?
Thanks!

**Comment by psuhane** [comment] 2016-07-25 07:24
I have the same issue, see the attached screen. But no special chars in console.

![pim4](https://cloud.githubusercontent.com/assets/12061880/17093444/f7f0e0ae-5266-11e6-83f6-6e3f072c93b9.png)

**Comment by psuhane** [comment] 2016-07-25 07:26
I was updating from 3.1.1 to 4.2.

**Comment by brusch** [comment] 2016-07-25 07:29
Can you share your phpinfo() with us? 
Thanks!

**Comment by psuhane** [comment] 2016-07-25 07:35
![phpinfo](https://cloud.githubusercontent.com/assets/12061880/17093677/51c5456a-5268-11e6-8e21-f70d9225c532.png)

**Comment by brusch** [comment] 2016-07-25 07:40
Interesting, ... you're using modphp and not FPM, so i guess it's a different problem. 

Can you try to track this down and find a fix for it?Would be perfect - Thanks!

**Comment by psuhane** [comment] 2016-07-25 07:43
Okay.. thanks @brusch for prompt reply :)

**Comment by Cruiser13** [comment] 2016-07-25 07:56
@brusch we're still investigating at our system, sadly there is nothing in the logs which would be helpful at all.
This is the PHP Config we're using at the moment. Works with 4.1.3, does not work with 4.2.0. OPCache disabled for debugging, usually activated. I'm happy to provide further information if needed.

![phpinfo](https://cloud.githubusercontent.com/assets/2771909/17094183/f18095de-524d-11e6-8c1d-45c9927db6b7.png)

**Comment by bbak** [comment] 2016-07-25 08:04
@Cruiser13 you've got XCache and OpCache configured?! They both have the same purpose. Even though you've OpCache disabled, I'd give it a try without even loading either of those as a Module.

**Comment by Cruiser13** [comment] 2016-07-25 08:21
@bbak even if I don't load both extensions the problem does persist. It's not an issue with OPCache or XCache.

**Comment by bbak** [comment] 2016-07-25 08:42
Hm, ok. Either way, I'd advise to load either/or as a module, since these caching modules attach themselves quite close to the PHP Core. 

Next try. Do you really need the [ionCube Loader](http://www.ioncube.com/loaders.php)? Such encryption modules basically attach to the same routines as Bytecode Caches like OpCache and XCache. Sorry for not mentioning it in my first post - I had not seen it.

**Comment by Cruiser13** [comment] 2016-07-25 08:47
@bbak in production we'll need all these modules, yes. Our servers handle other software beside pimcore - shopware for example - which does relay on ionCube Loader. I already deactivated the module for debugging on this server but it had no effect - and I'd not see any reason it should have any.

I can confirm the issue on a similiar configured server running PHP 5.5.37 (PHP-FPM aswell).

**Comment by brusch** [comment] 2016-07-25 08:52
Very very strange. Hopefully you find a solution soon. Thanks again!

**Comment by Cruiser13** [comment] 2016-07-25 10:04
I saved the correctly generated minified_javascript_core_23d18d0e622710fad0ce21c4da5a0e5f.js to my.js at the domain level and changed the pimcore/lib/Pimcore/Tool/Admin.php line 78:

`
    public static function getMinimizedScriptPath($scriptContent)
    {
		return "/my.js";
`

This works fine, I can access pimcore and the my.js loads fine - even if I reload it several times.
So the error must be inside the scriptProxyAction or during the creation but the generated file itself is fine.

**Comment by Cruiser13** [comment] 2016-07-25 10:56
Okay, I think we finally found the issue. There have been two problems. The first one is an incompatibility of PHP-FPM in recent PHP versions with Imagick and the MySQL free call as described here: https://forum.owncloud.org/viewtopic.php?t=30672#p97670
Has been solved on our server by a different version of PHP and Imagick, recompiled.

The main issue now is indeed - as you said @brusch - inside the Misc ScriptProxy, specifically in the headers.

In 4.1.3 they looked like this:

`
        header("Cache-Control: max-age=86400");
        header("Pragma: ");
`
This works fine in our environment.

In 4.2.0 they do look like this:

`
        $this->getResponse()->setHeader("Cache-Control", "max-age=" . $lifetime, true);
        $this->getResponse()->setHeader("Expires", gmdate("D, d M Y H:i:s", time() + $lifetime) . " GMT", true);
        $this->getResponse()->setHeader("Content-Type", $contentType, true);
        /*$this->getResponse()->setHeader("Pragma", "", true);*/
`

The outcommented last line does cause our strange characters. Removing this line does solve the issue on our environment.

**Comment by brusch** [comment] 2016-07-26 04:26
@psuhane does the solution described by @Cruiser13 also works for you? 
Thanks for a short feedback!

**Comment by brusch** [comment] 2016-07-26 05:18
@Cruiser13 this seems to be somehow releated to the gzip compression here: 
https://github.com/pimcore/pimcore/blob/54377c1a556e141bd7d87d087456bec64575d716/pimcore/lib/Pimcore.php#L976-L976 
Maybe in combination with other Apache modules? 
Even if removing the header fixes the problem we should find the root cause of this issue. 

I can imagine that the problem has something to do with the content encoding... 
What happens if you remove the `Content-Type` header instead of `Pragma`? Does this work as well? 
If so, please replace the existing `Content-Type` line with the following: 
`$this->getResponse()->setHeader("Content-Type", $contentType . ";charset=", true);` 

Does this fix the problem? 

Thanks for your feedback!

**Comment by Cruiser13** [comment] 2016-07-26 09:28
Hello @brusch removing the Content-Type line instead of the Pragma line does work as well.
Replacing the Content-Type line with your code does cause the same issues.

I think you are on the right track with the gzip compression. If I add a 
`
$gzipIt = false;
`
on line 973 before the if clause, and do not touch the MiscController (4.2.0 default) it'll work. On the second run, it'll minify the JS but it does not cause strange chars.

I removed the IfModule mod_deflate.c from .htaccess but it does not seem to be the source of issues.

**Comment by brusch** [comment] 2016-07-26 09:37
@Cruiser13 ok, it seems we're on the right track :) 

Please try to add the following line at the beginning of your `.htaccess`
`SetEnvIfNoCase Request_URI "\.(php)$" no-gzip dont-vary`

**Comment by brusch** [comment] 2016-07-26 09:42
@Cruiser13 @psuhane 
What is the output of: 
`apache2ctl -M`
and
`apache2 -v`

What happens if you disable mod_deflate? `a2dismod deflate` ?

**Comment by Cruiser13** [comment] 2016-07-26 09:49
@brusch adding the line to .htaccess does not solve the issue.

Disabling apache mod_deflate does not solve the issue.

Output apache2ctl -M

>  core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 auth_digest_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 dav_module (shared)
 dav_fs_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 fastcgi_module (shared)
 fcgid_module (shared)
 filter_module (shared)
 include_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 pagespeed_module (shared)
 passenger_module (shared)
 php5_module (shared)
 python_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 suexec_module (shared)
 xsendfile_module (shared)

Apache version:

> Server version: Apache/2.4.10 (Debian)
Server built:   Nov 28 2015 14:05:48

**Comment by brusch** [comment] 2016-07-26 09:55
@Cruiser13 can you also share your anonymized vhost? 
We'll try to build an environment where we can reproduce the behavior.

**Comment by brusch** [comment] 2016-07-26 09:57
@Cruiser13 one more try :) 
Is Pagespeed enabled? If so, please try to disable it :) (.htaccess)

**Comment by brusch** [comment] 2016-07-26 10:01
@Cruiser13 your're using Debian 8 or a derivate?

**Comment by Cruiser13** [comment] 2016-07-26 10:04
@brusch disabling mod_pagespeed at apache level (a2dismod pagespeed) does solve the issue. Interesting since it should be automatically deactivated (debug-mode on, we're calling /admin).

Using Debian 8.5.

**Comment by brusch** [comment] 2016-07-26 12:52
Ok, very interesting, ... anyway, I'll try to reproduce this on our dev environment and maybe I can find an elegant way how to solve this.

**Comment by Cruiser13** [comment] 2016-07-26 12:57
@brusch I can also give you access to our system in question if that's helpful. I sent you a message on gitter and I can also send you our vhost or similar configs there if needed.

Thanks a lot for looking into this!

**Comment by brusch** [comment] 2016-07-26 12:59
Thanks, but I have already a test-environment up and running where I can reproduce the error :)

**Comment by brusch** [comment] 2016-07-26 13:30
This seems to be related to https://github.com/pagespeed/mod_pagespeed/issues/1044

**Comment by Cruiser13** [comment] 2016-07-26 13:45
You are right, if I download the strange chars as a .gz file, I'll have a file without extension inside which is a properly formatted .js file. So it doubles the gzip which does explain why it's not happening if I remove the gzipping here: https://github.com/pimcore/pimcore/blob/54377c1a556e141bd7d87d087456bec64575d716/pimcore/lib/Pimcore.php#L976-L976

**Comment by brusch** [comment] 2016-07-26 14:23
Again, same problem reported here: https://github.com/mrclay/minify/issues/526

**Comment by Cruiser13** [comment] 2016-07-26 15:43
This might be a problem with the latest pagespeed version but I'm not sure why Pimcore 4.1.3 would still work fine in this case: https://groups.google.com/forum/#!topic/mod-pagespeed-discuss/Mgm6ZbAeJms
https://github.com/pagespeed/mod_pagespeed/issues/1362

Adding ModPagespeedHttpCacheCompressionLevel 0 as suggested did not fix the issue for me though.

**Comment by crowell** [comment] 2016-07-26 18:34
Is this reproducible regularly? If so this would be a great testcase for us in pagespeed.

**Comment by brusch** [comment] 2016-07-26 19:26
@crowell yes, i can prepare a test-case tomorrow

**Comment by crowell** [comment] 2016-07-26 19:28
@brusch perfect, thanks!

**Comment by brusch** [comment] 2016-07-26 19:31
@Cruiser13 the answer to your question is pretty easy :-) before version 4.2 pimcore didn't gzipped the scripts on the fly ;)

**Comment by brusch** [comment] 2016-07-27 05:16
See also: https://github.com/pagespeed/mod_pagespeed/issues/1362#issuecomment-235487689

**Comment by Cruiser13** [comment] 2016-07-27 07:12
@brusch I see. Thanks for looking into this and setting up a reproducable test case.

**Comment by brusch** [comment] 2016-08-09 14:18
Seems to be fixed by Pagespeed: 
https://github.com/pagespeed/mod_pagespeed/issues/1371

**Closed by brusch** 2016-08-09 14:18 UTC
Labels: Bug

**Comment by crowell** [comment] 2016-08-12 15:24
Thanks so much for the repro case. The latest pagespeed release with this bug fixed should be going out very soon.
