### ISSUE TITLE
[Improvement]: locales check should be depending on the OS it is running on

### ISSUE THREAD

**Issue by agdrs** [pimcore/pimcore#15561] opened 2023-07-19 07:16 UTC
### Improvement description

Hi there,

you have a test for setlocale() in your Requirements.php:
`setlocale(LC_ALL, [['en.utf8', 'en_US.utf8', 'en_GB.utf8']) === false ? Check::STATE_ERROR : Check::STATE_OK,`
that will work on linux based systems. It does not work on macOS, because locales here have a different name.
If i change the check to
`setlocale(LC_ALL, ['en.UTF-8', 'en_US.UTF-8', 'en_GB.UTF-8']) === false ? Check::STATE_ERROR : Check::STATE_OK,`
the check will not fail and Pimcore11 will be installed.
Many developers are working with macOS and not using docker, it would be nice to make this check depending on the OS it will be run on.
What do you think?

BR
Andreas

**Comment by gfriloux** [comment] 2023-07-24 09:17
Hello, i can confirm the issue (on `Debian`, not `macos` but the same check is faulty, this is why i did not create a new issue).
Configuring locales with `fr_FR.UTF-8` (while already having `C.UTF-8`...) will not solve.

The error is pretty misleading as it is:
```
* It is recommended to install UTF-8 locale, otherwise all CLI calls which use escapeshellarg() will strip multibyte characters (see https://packages.debian.org/en/stable/locales-all)
```

While **only** `en_US.UTF-8` or `en.GB.UTF-8` seems to be accepted.

I have no idea on **why** it has been done this way, but it is a pretty good time waster!

**Comment by gfriloux** [comment] 2023-07-24 09:22
A good fix would be to accept any `UTF-8` locale.
An almost acceptable fix would be to clearly state that only `en_US.UTF-8` is accepted in both:
- https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Requirements:
```
Operating System
Please ensure you have installed all required packages to ensure proper locale support by PHP. On Debian based systems, you can use the following command to install all required packages: apt-get install locales-all (on some systems there may be a reboot required).
```
It should say that on `debian` installing `locales-all` will solve, but that whatever the configuration, you **must** have `en_US.UTF-8` (+ your desired locale).
- `pimcore_install` script should clearly state you need to have `en_US.UTF-8` enabled.

**Comment by dvesh3** [comment] 2023-07-25 07:17
Duplicate of https://github.com/pimcore/pimcore/issues/15505

**Closed as completed by dvesh3** 2023-07-25 07:17 UTC
Labels: Improvement
