### ISSUE TITLE
object grid - inherited values are not shown as soon as custom sql-filter is active

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#964] opened 2016-10-19 18:14 UTC
fields[] param is not sent any more...

**Comment by mrudnicki** [comment] 2016-10-21 12:11
![image](https://cloud.githubusercontent.com/assets/20395719/19597985/4ae5b8e0-9798-11e6-888b-e4a6a2342cb5.png)

I can't reproduce it.

**Comment by mrudnicki** [comment] 2016-11-07 12:57
@fashxp could you check it again or give me more specific information?

**Comment by weisswurstkanone** [comment] 2016-11-09 08:54
Unable to reproduce. Please provide specific steps ...

**Comment by fashxp** [comment] 2016-11-09 09:52
it happens with localized fields. 

1) use pimcore demo
2) make use class inheritable
3) add a news object below the first entry in news folder and save it (without any modifications)
4) open object grid in news folder
5) add additional columns (like title, shortText, ...) 
6) add custom filter like "title LIKE '%in%'"
7) see following result

![image](https://cloud.githubusercontent.com/assets/8792145/20134140/92888b6a-a66a-11e6-8e4e-ff4dbad09076.png)

**Comment by weisswurstkanone** [comment] 2016-11-09 10:45
fixed in build 3999

**Closed by weisswurstkanone** 2016-11-09 10:45 UTC
Labels: Bug
