### ISSUE TITLE
[Bug]: Performance Data Object Grid

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#9727] opened 2021-07-12 13:37 UTC
### Expected behavior

 DB Queries should not take 10+ seconds inside Pimcore. Pimcore optimizes queries inside admin interface to the fullest.

### Actual behavior

Opening any data object grid in Pimcore executes 2 main queries:

```
SELECT COUNT(*) AS `totalCount`
FROM `object_customer`
WHERE ((o_path = '/XXX/XXX/XXX' OR o_path LIKE '/XXX/XXX/XXX/%') AND object_customer.o_type IN ('object', 'folder'))
```

and

```
SELECT object_customer.o_id as o_id, `object_customer`.`o_type`
FROM `object_customer`
WHERE ((o_path = '/XXX/XXX/XXX' OR o_path LIKE '/XXX/XXX/XXX/%') AND object_customer.o_type IN ('object', 'folder'))
ORDER BY `o_id` ASC
LIMIT 25
```

which both may take several seconds, or even result in a visible error to the user if a request exceeds the js-defined 30 seconds limit.

Explain statement for 700+ rows:
![image](https://user-images.githubusercontent.com/9052094/125296314-74a27b80-e326-11eb-98c3-7bbf38657dc8.png)

### Steps to reproduce

Open data object grid with several hundred thousand children.

**Comment by andreas-gruenwald** [comment] 2021-07-12 13:58
This query is triggered in the children grid of the Pimcore object tree.

**Comment by markus-moser** [comment] 2021-07-15 11:34
Now as Pimcore dropped the MySql < 8 Support it is possible to use CTE https://dev.mysql.com/doc/refman/8.0/en/with.html. In theory it should be possible to replace the like with hierarchical queries which should be much faster.

**Comment by markus-moser** [comment] 2021-09-01 18:46
This is a big problem in projects with massive amounts if objects. I tried to use CTE but in my first tests the performance was not better then the like. This is a problem which is very hard to be solved (without something like elasticsearch in the background...) but it's a major topic when Pimcore wants to be ready for PIM systems with hundrets of thousands or even millions of products. At the moment its not really practicle. #6383 is even much a bigger topic but also this issue really limits Pimcore here.

**Comment by markus-moser** [comment] 2021-09-01 19:33
Just as a reference the CTE I tried:

```sql
WITH recursive cte (o_id, o_classid, o_parentid) AS
(
       SELECT o_id,
              o_classid,
              o_parentid
       FROM   objects
       WHERE  o_parentid = 539285
       UNION ALL
       SELECT     p.o_id,
                  p.o_classid,
                  p.o_parentid
       FROM       objects p
       INNER JOIN cte
       ON         p.o_parentid = cte.o_id )
SELECT DISTINCT o_classid
FROM            cte;
```

Unfortunately it slower then the like pendant on the same folder:

```sql
select distinct o_classId from objects where o_path like '/products%';
```

The "distinct o_classId" is just one example. I tried several other constallations too but the like always was faster then the CTE.

**Comment by andreas-gruenwald** [comment] 2021-09-01 20:46
I also did some analysis based on the original query:


```SQL
select SQL_NO_CACHE object_customer.o_id as o_id, object_customer.o_type from object_customer 
where ((o_path = '/Kunden/' or o_path like '/Kunden/%') 
and object_customer.o_type in ('object', 'folder')
) 
order by o_id asc
 limit 25
```

-> 7.9 seconds for 661.000 data objects



Without ``order by o_id`` it's just 0.266 sec:

```SQL
select SQL_NO_CACHE object_customer.o_id as o_id, object_customer.o_type from object_customer 
where ((o_path = '/Kunden/' or o_path like '/Kunden/%') 
and object_customer.o_type in ('object', 'folder')
) 
 limit 25
```

Is it an option to ignore the default order by clause and get rid of it? 
However, the ``count`` query is still slow...

**Comment by markus-moser** [comment] 2021-09-02 15:52
Maybe Pimcore should introduce some kind of closure table where all parent IDs are stored in a normalized way.

**Comment by RuudvdvNB** [comment] 2021-11-25 14:51
@brusch for us this is not the only query that is causing performance issues in Pimcore. I started a discussion here on Github, might be able to look into that as well? 

https://github.com/pimcore/pimcore/discussions/10907

**Comment by brusch** [comment] 2022-04-07 09:32
See https://github.com/pimcore/pimcore/pull/11856 which fixes at least one part of the problem.

**Comment by jdreesen** [comment] 2022-04-07 09:45
So, no more PR's welcome, stale bot?

**Comment by AditiV-P-HM** [comment] 2023-04-25 10:58
We are PIM 6.9.6 and the below query from PIMcore core takes more than 10 minutes to execute. We have around 2,00,000+ items and while loading folder grid for the items below query gets executed which takes more than 10 minutes and causes high CPU utilization. Is there any update regarding this query - 

SELECT COUNT(*) FROM object_1 WHERE (o_path = '/' OR o_path LIKE '/%') AND  (
                                                    (select list from users_workspaces_object where userId in (3,129) and LOCATE(CONCAT(o_path,o_key),cpath)=1  ORDER BY LENGTH(cpath) DESC LIMIT 1)=1
                                                    OR
                                                    (select list from users_workspaces_object where userId in (3,129) and LOCATE(cpath,CONCAT(o_path,o_key))=1  ORDER BY LENGTH(cpath) DESC LIMIT 1)=1
                                                 ) AND  object_1.o_type IN ('object','folder')

**Comment by nobears** [comment] 2023-05-10 07:33
One of our clients is still having issues opening grids with products, they have 8.6 million products in Pimcore now and this amount is still growing... Opening folders / grids with +/- 1 million products is already failing 7 out of 10 times. 

The only issue that is causing this is the `getTotalCount` method in the Listing class.

Looking at the totalCount class the following query is executed for admin users and takes up more than 18 seconds.

```
SELECT COUNT(*) FROM object_PRODUCT WHERE (o_path = '/products' OR o_path LIKE '/products/%') AND  object_PRODUCT.o_type IN ('object','folder');
```

When i change this query to do the count on the objects table instead of the object VIEW the query is executed in 4 seconds!

```
SELECT COUNT(*) FROM objects WHERE (o_path = '/products' OR o_path LIKE '/products/%') AND  objects.o_type IN ('object','folder');
```

For this specific client we are now using a custom `getTotalCount` which changes the view to the objects table resulting in faster loading grids. 

I'm wondering why Pimcore is doing a count by default on the object view instead of the objects table?

**Comment by brusch** [comment] 2023-06-05 08:50
Related to #12653

**Comment by dkarlovi** [comment] 2023-06-05 09:51
@markus-moser 

> Unfortunately it slower then the like pendant on the same folder:

Sorry to bring this up after two years, but could you provide more info here? For example, we've noticed MySQL got a significant boost to specific CTE queries around version 8.0.18 roughly, while on 8.0.15 or lower they were still somewhat problematic.

Could you share some info about your findings?

**Comment by dkarlovi** [comment] 2023-06-05 10:03
@andreas-gruenwald 

> Is it an option to ignore the default order by clause and get rid of it?

No, this can cause pagination to fail since same items can appear on multiple pages. Unless you define an order by, it's undefined and [any order is correct](https://github.com/w-vision/DataDefinitions/pull/282), including the one which you don't expect.

**Comment by elements-team** [comment] 2023-06-12 07:40
> @markus-moser
> 
> > Unfortunately it slower then the like pendant on the same folder:
> 
> Sorry to bring this up after two years, but could you provide more info here? For example, we've noticed MySQL got a significant boost to specific CTE queries around version 8.0.18 roughly, while on 8.0.15 or lower they were still somewhat problematic.
> 
> Could you share some info about your findings?

I tested it again in a project with approx. 430k data objects. We have a multi level tree structure with about 10-15 levels. In the tree structure there are no nodes with massive amounts of children but it is structured more like in smaller folders (most folders with 1-20 direct children). The CTE query mentionend above runs ~1 sec when executed on a top level folder. A like on the same folder ~0.5 sec. 

In nested levels when there are only a few children left the CTE is much faster but on top levels when it needs to iterate over a lot of nested sub items the CTE gets at some point slower then the like. We are using MariaDB 10.5.19 on this server.

**Comment by markus-moser** [comment] 2023-06-12 07:41
> @markus-moser
> 
> > Unfortunately it slower then the like pendant on the same folder:
> 
> Sorry to bring this up after two years, but could you provide more info here? For example, we've noticed MySQL got a significant boost to specific CTE queries around version 8.0.18 roughly, while on 8.0.15 or lower they were still somewhat problematic.
> 
> Could you share some info about your findings?

@dkarlovi 

I tested it again in a project with approx. 430k data objects. We have a multi level tree structure with about 10-15 levels. In the tree structure there are no nodes with massive amounts of children but it is structured more like in smaller folders (most folders with 1-20 direct children). The CTE query mentionend above runs ~1 sec when executed on a top level folder. A like on the same folder ~0.5 sec.

In nested levels when there are only a few children left the CTE is much faster but on top levels when it needs to iterate over a lot of nested sub items the CTE gets at some point slower then the like. We are using MariaDB 10.5.19 on this server.

**Comment by dkarlovi** [comment] 2023-06-12 07:48
@markus-moser 

could you provide the exact LIKE and CTE queries you're testing with, and their EXPLAIN plan?

**Comment by markus-moser** [comment] 2023-06-12 07:55
@dkarlovi 

The queries are exactly the same like in the initial post:

```sql
WITH recursive cte (o_id, o_classid, o_parentid) AS
(
       SELECT o_id,
              o_classId,
              o_parentId
       FROM   objects
       WHERE  o_parentId = 5
       UNION ALL
       SELECT     p.o_id,
                  p.o_classId,
                  p.o_parentId
       FROM       objects p
       INNER JOIN cte
       ON         p.o_parentId = cte.o_id )
SELECT DISTINCT o_classId
FROM            cte;
```

Like on the same folder:

```sql
select distinct o_classId from objects where o_path like '/products%';
```
The explain for the CTE looks like this:

![image](https://github.com/pimcore/pimcore/assets/4639428/3fb39512-381f-40d3-91a3-bf73a526d6e9)

And for the like:

![image](https://github.com/pimcore/pimcore/assets/4639428/021f1faf-d1c8-48ff-8235-0d6b5dad994e)

**Comment by dkarlovi** [comment] 2023-06-12 14:11
## Note: this was done on MySQL 8.0.31

@markus-moser @brusch testing the above query with my dataset, I can confirm that with 150k objects in a folder, the CTE query is about 50% slower (300ms vs 200ms) here in queries as described.

But, I've tried to drill down into the tree a bit further (`/Products/Example/Valves`) with about 35k objects and the difference got much more narrow (110ms vs 90ms). One further level (`/Products/Example/Valves/Ball Valves`) with about 5k objects, CTE now wins for me (45ms vs 65ms).

This also ignores the fact CTE understands about relations between rows and can provide additional features free of charge, for example

```sql
WITH RECURSIVE `cte` (
                      o_id,
                      o_parentId,
                      o_path,
                      depth
    ) AS (
    SELECT
        o_id,
        o_parentId,
        CONCAT(o_path, o_key) AS o_path,
        1 AS `depth`
    FROM `objects`
    WHERE `o_id` = 45509
    UNION ALL
    SELECT
        o.o_id,
        o.o_parentId,
        CONCAT(o.o_path, o.o_key) AS o_path,
        `depth` + 1
    FROM `objects` o
             INNER JOIN cte
                        ON o.`o_id` = cte.`o_parentId`
)
SELECT o_path FROM cte ORDER BY `depth` ASC;
```

provides breadcrumbs for the said folder in 20ms, I don't know how you do that without CTE. Overall, while there's may be a few places where CTE might not be the fastest solution, it should be fast enough in general and those places can then be special cased if desired.

**Comment by markus-moser** [comment] 2023-06-12 15:11
@dkarlovi Yes, this is exactly the same which I noticed. The sad thing is, that I hoped that CTE could solve our problem with children grids for millions of data objects but it seems that they make these constellations even worse.

**Comment by brusch** [comment] 2023-06-12 15:25
@markus-moser @dkarlovi thank you very much for sharing the details! 
So actually CTEs are not the solution for the described performance issues in this ticket, but they could be a good option for other purposes.

**Comment by GeorgII-web** [comment] 2023-06-15 11:19
Will it help to use Elasticsearch in the Advanced search bundle?
Will the Grid use it for getting a list of objects?
If not, is it possible in general to override this behavior and use ES instead of SQL optionally?

**Comment by dkarlovi** [comment] 2023-08-17 07:34
@GeorgII-web how you'd do it in ES for perf is you'd denormalize the data and make every member of the tree have all their parents (the entire breadcrumb path), this was already suggested https://github.com/pimcore/pimcore/issues/9727#issuecomment-911828576

That's probably the most performant solution since each object knows if it should be part of the result or not. We can use a JSON type to allow an array of IDs which can then be indexed: https://planetscale.com/blog/indexing-json-in-mysql

**Comment by fashxp** [comment] 2024-10-02 08:18
won't fix that in admin UI classic anymore. in studio, we will use generic data index for improved performance.

**Closed as not planned by fashxp** 2024-10-02 08:18 UTC
Labels: Bug, Pimcore:Backlog
