### ISSUE TITLE
[Bug]: Migration from 10.6 to 11.x does not work. 

### ISSUE THREAD

**Issue by martineiber** [pimcore/pimcore#15134] opened 2023-05-08 10:03 UTC
### Pimcore version

11.0

### Steps to reproduce

Try to run `./bin/console doctrine:migrations:migrate` while updating to Pimcore 11 according to the Upgrade Guide. https://github.com/pimcore/pimcore/pull/15130

### Expected / actual behavior

classes, objectBricks, fieldCollections and customLayouts: can not be migrated because some datatypes are wrong or not set in the definition files. 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/11687066/236793672-f5f04e27-e928-4ed9-af0f-6286cf6a6a3c.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/11687066/236796013-20a6cb5a-17e7-4742-b621-7886fa150bf3.png">

https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20230412105530.php
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20220809154926.php

**Comment by fashxp** [comment] 2023-05-08 11:08
Duplicate of https://github.com/pimcore/pimcore/issues/14980

**Closed as completed** 2023-05-09 06:08 UTC
Labels: Bug
