### ISSUE TITLE
[Bug]: extJs deleteElementFromServer 

### ISSUE THREAD

**Issue by SQRR** [pimcore/pimcore#11457] opened 2022-02-15 15:20 UTC
### Expected behavior

Should delete the DataObject

### Actual behavior

Some Objects can not be deleted because nodelEl is null. 
This throws an exception which ends up cancelling the DELETE request.

### Steps to reproduce

Unfortunately I was not able to find out why this erros sometimes occures.
It might depend on the DataObject Folder tree.

Quick'n'Dirty Fix:
https://github.com/pimcore/pimcore/blob/e57752751ecda8aa40190344ee4d85850ebc0ea6/bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js#L133

if(nodeEl) {
    nodeEl.addCls("pimcore_delete");
}

**Comment by brusch** [comment] 2022-02-21 09:56
@SQRR Unfortunately we can't reproduce that on our end. Please share a reproducible scenario (best on demo.pimcore.org) or even better a PR that fixes the issue. Thanks a lot (we'll of course reopen this issue if necessary).

**Comment by luabui** [comment] 2022-04-19 07:34
Can you please reopen this bug? Step to reproduce on pimcore demo site (I tested on [pimcore ](https://demo.pimcore.com/admin) 10.3.5)
- Open an object
- Close the parent node in the object tree (DataObject tree - the News folder)
- Press "Delete" button on the opened object
- Javascript exception: Uncaught TypeError: Cannot read properties of null (reading 'addCls')
    at pimcore.elementservice.deleteElementFromServer
![image](https://user-images.githubusercontent.com/4123658/163950045-efac2c56-388a-4629-aa24-6508a41467a8.png)

**Comment by aryaantony92** [comment] 2022-04-21 08:43
Fixed by #11933

**Closed as completed by aryaantony92** 2022-04-21 08:43 UTC
Labels: Bug
