### ISSUE TITLE
Objects: Tooltip on a non-editable field isn't displayed on hover

### ISSUE THREAD

**Issue by georgkoch** [pimcore/pimcore#738] opened 2016-07-13 08:13 UTC
### Expected behavior

Tooltip should be displayed on a mouseover event
### Actual behavior

For non editable fields the tooltip doesn't appear. 
### Steps to reproduce

Enter a Tooltip-> activate the not editable checkbox ->  do a mouse over in the object on that field
### Version/ Build

Bug seen in:
Version: 4.1.1
Build: 3821

**Comment by weisswurstkanone** [comment] 2016-07-18 08:21
see
https://www.sencha.com/forum/showthread.php?302961-Tooltips-not-working-when-button-is-disabled.-Intended

and

https://www.sencha.com/forum/showthread.php?310184

**Comment by brusch** [comment] 2016-10-27 05:54
Will be fixed by ExtJS

**Comment by weisswurstkanone** [comment] 2016-12-13 11:05
confirmed fix in ExtJS 6.2

**Comment by ckogler-elements** [comment] 2018-02-02 13:04
Maybe the fields should be set to "readonly" instead of disabled, because currently you can't copy values from disabled fields. If it would be set to "readonly" you could copy the values + the tooltips would work :-). 

The readonly fields would have to be styled...

**Closed** 2018-07-19 06:46 UTC
Labels: Approved, Bug
