### ISSUE TITLE
[Bug]: .m4a files are not handled as audio files

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#12838] opened 2022-08-08 08:03 UTC
### Expected behavior

Handle as audio file
- show audio player in preview
- don't break the worker (messenger) process

### Actual behavior

It looks like it is trying to handle the file as a video file:
`Pimcore\Model\Asset\Video\ImageThumbnail::__toString(): Return value must be of type string, null returned`

It also create an infinite loop in the worker process:
`[pimcore] Image thumbnail not yet available, processing is done asynchronously.`

### Steps to reproduce

Upload a .m4a file to Pimcore Assets.

**Comment by kingjia90** [comment] 2022-08-08 12:08
Which version of Pimcore are you using?
The error looks like the same as https://github.com/pimcore/pimcore/issues/12740 fixed in `10.4.6`, but i would check if there's any problems with audio files as well.

**Comment by blankse** [comment] 2022-08-08 13:06
I created a PR, which shows the right icon and show the audio player with .m4a files. The part with the worker process can't I reproduce.

**Comment by kingjia90** [comment] 2022-08-08 13:16
Thank you very much @blankse !

**Comment by hethehe** [comment] 2022-08-09 05:35
Great! Thank you @blankse 
Because of the part with worker process, it was a 10.4.4 Project, so the bug should already be fixed.

**Comment by kingjia90** [comment] 2022-08-09 07:03
Fixed by #12697 and #12841

**Closed as completed by kingjia90** 2022-08-09 07:03 UTC
Labels: Bug
