### ISSUE TITLE
[Pimcore4] Object grid column configuration: localized fields are not showing for non admin users.

### ISSUE THREAD

**Issue by elavarasann** [pimcore/pimcore#270] opened 2015-10-16 10:42 UTC
I have a issue with Object grid column configuration. I have 2 localized field sets in my class

![pim1](https://cloud.githubusercontent.com/assets/5245575/10539429/24bdfa50-741d-11e5-8be1-7d6203c3e189.png)

When I open column configuration option in admin, in right hand I'm not able to see the localized fields. Attached image.
![pim2](https://cloud.githubusercontent.com/assets/5245575/10539540/ca23a4ea-741d-11e5-8c77-af0c68dcec9f.png)

I can see only the field sets not the fields. And I noticed for the first localized field, all the fields are populated but if we have more localized fields, then the fields are not populated. I tried with interchanging that 2 localized fields but still the second localized fields not not showing in the grid.

And most importantly for admin users not facing this issue only non admin users are facing this issue.

Then I analysed the code. I found one strange thing.

The function  private static function doFilterCustomGridFieldDefinitions(&$layout, $fieldDefinitions) {} from pimcore/models/Object/Service.php  is returning false for some localized fields.

So I dig more,
the function  public static function getCustomGridFieldDefinitions($classId, $objectId) {} 
from pimcore/models/Object/Service.php

Here we get the class field definition 
 $class = ClassDefinition::getById($classId);
        $masterFieldDefinition = $class->getFieldDefinitions(); 

Here the  $masterFieldDefinition  variable contains all the (definitions) localized fields.

But after this function,
$mergedFieldDefinition = unserialize(serialize($masterFieldDefinition));

the second localized fields are gone. So I think the problem is in this function (serializing). Please check it.

Note:

Admin user not facing this issue only non admin users are facing this issue.

Thanks,
Elavarasan N
.

**Comment by fashxp** [comment] 2016-05-11 12:27
is this still reproducible in the latest build?

**Comment by zieglerh** [comment] 2016-11-21 17:13
Hi,
we experienced the same issue after we updated from v4.1.2 to v4.3.1.
Somehow the change from psf to php definition files is causing the described behavior.

1) To reproduce this make a simple class with 2 localized field definitions
![screen shot 2016-11-21 at 17 46 16](https://cloud.githubusercontent.com/assets/18331614/20491950/4b80f696-b013-11e6-9895-28303bd49672.png)
2) Create a user with following rights
![screen shot 2016-11-21 at 17 56 32](https://cloud.githubusercontent.com/assets/18331614/20492138/ed5ff0f2-b013-11e6-8e83-aae5454d5f7f.png)
![screen shot 2016-11-21 at 17 56 43](https://cloud.githubusercontent.com/assets/18331614/20492146/f511f55c-b013-11e6-90aa-eddaa245b9f2.png)
![screen shot 2016-11-21 at 17 56 49](https://cloud.githubusercontent.com/assets/18331614/20492149/f79a8816-b013-11e6-872d-7ba6b45872b2.png)
3) Open column configuration
You can only see the localized columns from the first definition. The second definition is empty.
![screen shot 2016-11-21 at 17 45 30](https://cloud.githubusercontent.com/assets/18331614/20492275/62d640e8-b014-11e6-8065-fd61ab974436.png)
4) Go to pimcore/models/Object/Service.php
Change $mergedFieldDefinition = unserialize(serialize($masterFieldDefinition));
to $mergedFieldDefinition = $masterFieldDefinition;
5) Reopen the column definition and now you can see all columns
![screen shot 2016-11-21 at 17 45 42](https://cloud.githubusercontent.com/assets/18331614/20492322/97930d02-b014-11e6-9748-2d4b1650c2d3.png)

I tried to debug this part and found out, that setChild($childs) in pimcore/models/Object/ClassDefinition/Data/Localizedfields.php is called multiple times from Pimcore\Model\Object\ClassDefinition\Data\Localizedfields::__set_state() in the class definition file 
![screen shot 2016-11-21 at 18 06 56](https://cloud.githubusercontent.com/assets/18331614/20492518/547a179e-b015-11e6-93c5-999fbe2a2706.png)

The __sleep() function is unsetting the referencedFields
```php
     * @return array
     */
    public function __sleep()
    {
        $vars = get_object_vars($this);
        unset($vars['fieldDefinitionsCache']);
        unset($vars['referencedFields']);

        return array_keys($vars);
    }
```
which has all the data for getFieldDefinitions() and causing to get the data from $childs which has the overwritten children.

Hope this helps and you can reproduce and fix this.
Thanks

**Comment by zieglerh** [comment] 2016-11-21 19:36
Forget about the update part. This bug exists since a long time ago. 
We updated an existing class and that was the beginning of the problem.

**Comment by fashxp** [comment] 2016-11-24 10:26
thx for your detailed information, we'll have a look at it.

**Comment by christophluehr** [comment] 2017-10-04 14:50
We can reproduce the same issue with the 4.6.0 & 4.6.2 version. 

I tried to back-port the fix(?) for 5.0 from #1919 :
https://github.com/pimcore/pimcore/commit/a8a4b7eccac3ade8a4705f63021e2d8d0a9700a7

but to no avail.

When i remove the unserialize/serialize combo as @zieglerh suggests, the coulmns appear in the grid and in the column configuration, but i do not really understand if/what undesired effects this is going to have ...: 

> 4. Go to pimcore/models/Object/Service.php
> Change $mergedFieldDefinition = unserialize(serialize($masterFieldDefinition));
> to $mergedFieldDefinition = $masterFieldDefinition;

Anybody?

**Comment by fashxp** [comment] 2017-10-04 15:19
also happens in latest Pimcore 5

**Comment by weisswurstkanone** [comment] 2017-10-05 08:22
build 4104

**Closed by weisswurstkanone** 2017-10-05 08:22 UTC
Labels: Approved, Bug

**Comment by christophluehr** [comment] 2017-10-05 12:24
Seems to work, thanks for the swift fix!
