### ISSUE TITLE
Tree nodes are not properly updated after certain actions

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#323] opened 2015-12-04 12:21 UTC
To reproduce: Unpublish a document/asset/object and move it -> the strike through line disappears after moving. Or publish an unpublished document -> the strike through line does not disappear. See animation below:

![animation](https://cloud.githubusercontent.com/assets/2148902/11589494/5b17c800-9a89-11e5-9db8-cc159bb579b8.gif)

**Comment by weisswurstkanone** [comment] 2015-12-04 12:34
fixed in build 3580

**Comment by chix** [comment] 2015-12-04 12:37
wow, that was really quick :+1:  thanks

**Comment by chix** [comment] 2015-12-04 12:46
Tested it just now, the second use-case (publishing) is fixed, but the first one (moving published/unpublished document) is still buggy.

**Comment by weisswurstkanone** [comment] 2015-12-04 13:11
ok, this seems to be a different case. I pushed a second change

**Comment by chix** [comment] 2015-12-04 13:25
Great, thank you :). Moving an unpublished document works fine now. Just one last thing - moving a published document adds the strike-through line again, see animation:

![animatin](https://cloud.githubusercontent.com/assets/2148902/11590697/33ae003c-9a92-11e5-8020-57459d2699f9.gif)

**Comment by weisswurstkanone** [comment] 2015-12-04 13:30
Hmm, I am not able to reproduce it that way ... I'll play around a little bit ...

**Comment by solverat** [comment] 2016-01-23 09:07
if your in a custom view, the tree is still not updating the current state of the docment, like publishing, deleting

![](http://g.recordit.co/Pq6F3vUVJu.gif)

**Comment by chix** [comment] 2016-02-12 10:25
for the customviews, there is a PR #251

**Comment by solverat** [comment] 2016-02-12 10:30
:+1:

**Comment by brusch** [comment] 2016-02-15 20:48
@chix is the last issue you have posted above still reproducible for you? If so, can you please provide us a step by step guide how to reproduce this on demo.pimcore.org/admin ? 
Thanks in advance!

**Comment by chix** [comment] 2016-02-16 10:51
@brush hi, yes, it is. I can't log in to the demo right now (admin:demo does not work), but on my local copy it is still buggy.

To reproduce:
- unpublish a document
- refresh its parent node
- publish the document and move it

![animation](https://cloud.githubusercontent.com/assets/2148902/13073940/c39bbcf4-d4a1-11e5-8648-818f34b557ef.gif)

On documents, only moving a published document is buggy (moving an unpublished document it already fixed). On objects, moving both published or unpublished object is still buggy.

**Comment by weisswurstkanone** [comment] 2016-02-16 11:21
confirmed

**Comment by weisswurstkanone** [comment] 2016-02-16 13:02
there is a similar issue in the object tree:
- unpublish object
- reload parent
- publish object
- move to a different folder

**Comment by weisswurstkanone** [comment] 2016-02-16 13:02
fixed in build 3664

**Closed by weisswurstkanone** 2016-02-16 13:02 UTC
Labels: Bug
