### ISSUE TITLE
Clearing filters in grid view is not working for number column

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6874] opened 2020-07-31 19:34 UTC
Hi,

As the title is saying the clear filters function is not working for the number column when you have filtered here on number (greater than, less than etc).

We noticed this issue in PimCore 6.6.10.

**Comment by dvesh3** [comment] 2020-08-03 08:24
@Hbitvof Sorry, unable to reproduce. could please verify on https://demo.pimcore.fun/admin?

**Comment by Hbitvof** [comment] 2020-08-05 11:57
I was able to reproduce it on the PimCore Demo.

Please add the column Number of doors to the grid view and change the number of doors for one car to 0. When you filter on greater than 0 you should get one 2 doors as results. When you clear the filter you still don't see the car with 0 doors. When you look at the filter still 0 is filled in at the filter but the filter has no mark:

![image](https://user-images.githubusercontent.com/41229269/89410172-87c6c780-d723-11ea-8b19-3a3c39bacbde.png)

When you manually delete the 0 in the filter you see the car with 0 doors again.

**Comment by dvesh3** [comment] 2020-08-11 16:00
seems ExtJS bug with 0 value filter. https://fiddle.sencha.com/#fiddle/384j&view/editor

**Comment by weisswurstkanone** [comment] 2020-08-17 12:17
Already fixed in ExtJS 7.0 so probably not worth finding a workaround.

**Comment by Hbitvof** [comment] 2020-08-17 12:21
@weisswurstkanone in what PimCore version the new extJS 7.0 is implemented? the bug is still in PimCore 6.7.

**Comment by weisswurstkanone** [comment] 2020-08-17 12:22
It will be in Pimcore 7 and I think this is fine since this is not a critical issue.

**Comment by dvesh3** [comment] 2021-03-23 08:54
Resolved by #6922

**Closed by dvesh3** 2021-03-23 08:54 UTC
Labels: Bug, Third Party Bug
