### ISSUE TITLE
Call to a member function supportsInheritance() on null

### ISSUE THREAD

**Issue by Dinesh2703** [pimcore/pimcore#6854] opened 2020-07-29 16:37 UTC
Whenever I click on search button to select object from list as shown in image below.

![searchtoselect](https://user-images.githubusercontent.com/41935464/88827435-9410c900-d1e7-11ea-94bf-7021a2b89050.PNG)

I get the error Call to a member function supportsInheritance() on null. It was working but today its started showing this error. Image showing error is below

![SearchError](https://user-images.githubusercontent.com/41935464/88827530-b0146a80-d1e7-11ea-8550-2dba92763962.PNG)
This issue can be same as this https://github.com/pimcore/pimcore/issues/2809
But reason why its happening can be different.

Full exception details are in below image

![Details](https://user-images.githubusercontent.com/41935464/89044612-d3662380-d367-11ea-8c1e-f5078deb5f3e.PNG)

I already have lists to select by searching and it was working today. I have created fields inside bricks and using bricks inside classes. Any solution will be appreciated. My pimcore version is 6.6
Thanks in advance

**Comment by dvesh3** [comment] 2020-07-30 07:31
I'm not able to reproduce. Could you please try on latest version 6.6.10? thanks!

**Comment by Dinesh2703** [comment] 2020-07-30 12:23
@dvesh3  ok Thanks. I will try on latest version

**Comment by Dinesh2703** [comment] 2020-07-31 14:26
Hi @dvesh3  I have included Details of the error also.

**Comment by brusch** [comment] 2020-08-03 08:02
@Dinesh2703 any updates, same error with a fresh install of the latest version?

**Comment by Dinesh2703** [comment] 2020-08-06 05:12
@brusch No issue till now in latest version. will ping if face that issue again. Thanks

**Comment by dvesh3** [comment] 2020-08-25 07:40
@Dinesh2703 thanks for confirmation! I'm closing the issue, since it is not reproducible on latest version.

**Closed by dvesh3** 2020-08-25 07:40 UTC
