### ISSUE TITLE
[Bug]: unable to delete graphql configuration 

### ISSUE THREAD

**Issue by Abdelrhman02** [pimcore/pimcore#16849] opened 2024-03-26 03:22 UTC
### Pimcore version

11

### Steps to reproduce

I don't know how can reproduce it 

### Actual Behavior

should able to delete data-hub configuration 
![image](https://github.com/pimcore/pimcore/assets/53811899/6a9b4d0e-a46a-430d-a59c-3c9456226fb4)

I deleted it from var/config/data_hub folder but it still here 

I can't save or delete or clone the configuration.
![image](https://github.com/pimcore/pimcore/assets/53811899/8c082ec9-bd65-4259-a1f5-3e9dcf5e6f67)

### Expected Behavior

should be able to delete configuration from pimcore UI or by deleting the config file from var/config/data_hub

**Comment by podarcis** [comment] 2024-03-26 07:33
Seems that you're in an environment that uses config write-target `symfony-config` for your Data-Hub configs and your environment is cached (probably `prod`). This is the expected behavior, see https://pimcore.com/docs/platform/next/Pimcore/Deployment/Configuration_Environments/#production-environment-with-symfony-config

You can either clear the Symfony caches (ideally integrated in deployment) or change the write-target to `settings-store` and have your configs in the DB and thus editable in `prod`, however not under version control.

**Comment by fashxp** [comment] 2024-04-15 08:08
I'll close this, as the reason is explained by @podarcis. Thx very much!

**Closed as completed by fashxp** 2024-04-15 08:08 UTC
Labels: Bug, PR Welcome
