### ISSUE TITLE
[Data Objects] modificationDate of object unchanged when only fieldcollection is modified

### ISSUE THREAD

**Issue by TheCodyKnight** [pimcore/pimcore#6494] opened 2020-06-02 09:03 UTC
verified on pimcore v6.6.4

### Expected behavior
When I modify a fieldcollection within an object, I expect the modificationDate of the object to change.

### Actual behavior

When I modify a fieldcollection within an object, the modificationDate of the object is unchanged.

### Steps to reproduce

- Create an object containing a fieldcollection
- Modify a data field within the fieldcollection
- Save the object
- Find the modificationDate in the Version history of the respective version unchanged

**Comment by dvesh3** [comment] 2020-06-02 09:34
sorry, cannot reproduce it on demo.pimcore.fun
![image](https://user-images.githubusercontent.com/5137917/83504405-c2627880-a4c4-11ea-957f-e4b01871c13f.png)

**Comment by TheCodyKnight** [comment] 2020-06-02 14:01
Sorry for causing you an inconvenience - the issue with the unchanged modificationDate actually only happens when saving the field collection programmatically.

**Comment by fashxp** [comment] 2023-12-19 15:48
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed by fashxp** 2023-12-19 15:48 UTC
Labels: PR Welcome
