### ISSUE TITLE
[Bug]: Pimcore installation fails with mysql SSL 

### ISSUE THREAD

**Issue by khusseini** [pimcore/pimcore#14494] opened 2023-02-28 20:16 UTC
### Expected behavior

Installation succeeds

### Actual behavior
pimcore-install --ignore-existing-config --admin-username=admin --admin-password=admin -n --mysql-ssl-cert-path=/etc/mysql-ca/cert.crt

Insallation fails.

### Steps to reproduce

Install pimcore X and mysql with SSL.
run

```
pimcore-install --ignore-existing-config --admin-username=admin --admin-password=admin -n --mysql-ssl-cert-path=/etc/mysql-ca/cert.crt

[WARNING] Using sensitive options (--admin-username) on the command line interface can be insecure.
Consider using the interactive prompt or the PIMCORE_INSTALL_ADMIN_USERNAME environment variable instead.

[WARNING] Using sensitive options (--admin-password) on the command line interface can be insecure.
Consider using the interactive prompt or the PIMCORE_INSTALL_ADMIN_PASSWORD environment variable instead.


Running installation. You can find a detailed install log in var/log/integration.log

Starting the install process...

  0/11 [>---------------------------]   0%


                                                                                                                        
 [ERROR] The following errors were encountered during installation                                                      
                                                                                                                        

 * Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited while --require_secure_transport=ON.
```

```bash
composer show | grep pimcore
asioso/pimcore-quicktranslate-module                v3.0.3    With this Bundle you can automatically translate your content via DeepL Interface.
pimcore/data-hub                                    v1.2.0    Pimcore Datahub
pimcore/data-importer                               v1.6.3   
pimcore/number-sequence-generator                   v1.0.7   
pimcore/output-data-config-toolkit-bundle           v4.1.9   
pimcore/pimcore                                     v10.5.14  Content & Product Management Framework (CMS/PIM/E-Commerce)
```

**Comment by mattamon** [comment] 2023-03-01 06:56
Duplicate of https://github.com/pimcore/pimcore/issues/14135#issuecomment-1449446207
Please see my last comment. It is not a pimcore specific issue. 

We can transfer it to the discussion if you want to.

**Closed as completed by mattamon** 2023-03-01 06:56 UTC
