### ISSUE TITLE
[Bug] Error loading files using Turkish language in backend

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#4476] opened 2019-06-03 06:14 UTC
# Bug Report

When setting Turkish language as Document language editables starting with letter i (input, image) generate error.

Error is related with how in Turkish language uppercase i becomes İ (with dot). When using `$this-input()` Pimcore tries to load `İnput.php` instead of 'Input.php' which generates an error. Same for image and other cases when file is auto loaded by making first letter uppercase.

There are also other related errors, like Monolog throws error 'info' severity is not supported, etc.

Even if you don't set Turkish as Document language but just use Pimcore user language as Turkish, there are errors because of the same reason. In this case no error is thrown but when you save a Document content of all editables starting with i is erased.

### Expected behavior

When auto loading files when first letter is capitalized, capitalization should be done in English, no matter which language is set in backend.

### Actual behavior

If Turkish language is set in backend, Turkish is also used for capitalizing first letter for cammel case file name, which results in errors.

### Steps to reproduce
Add Turkish language in System Settings. Select Turkish as Document language and add some editables starting with letter i (image, input). Also Turkish system language should be present on server else the problem doesn't occur.

### Code example
```php
$this->image('image')
```

**Comment by ckemptner** [comment] 2020-01-10 08:30
Just for reference - Community forum post about the same issue
https://talk.pimcore.org/t/error-using-turkish-languages-as-document-language/2077

**Comment by PimLab** [comment] 2020-01-13 12:05
Hey @brusch and @ckemptner 
i've worked on this problem at the weekend to locate the problem source. In case of this, i wondered because the problem is on our staging system and on some developer environments, but now in my. First it was a little mysterious but maybe i found the source of this evil. To found, i take a look beneath pimcore and symfony on the PHP and OS Level.

I use an macOS 10.15 with self complied PHP an has no problem with the TR locale. Colleagues uses Ubuntu 18.04 with Ubuntu PHP Packages (FPM with nginx and Apache with PHP-Mod, both in use on different evns.) and they has the Problem like the staging system. So take a look on staging system, it is also a Ubuntu 18.04 with Ubuntu PHP Package FPM with nginx but as server-system; the local envs. using desktop version in VM. So we tried the Project on Debian with PHP Debian Packages and it works fine. Same testes with FreeBSD and RedHat on the weekend, also no Problem with it. On one of the colleagues systems where problem exists, the reinstall of TR local/lang package solves the error. On Ubuntu Server the TR local was installed already with system setup, we don't has reinstalled it now.
All tests are done with PHP 7.2 and 7.3.

Hope that helps

Best wishes
Felix

**Comment by brusch** [comment] 2020-02-19 10:43
I'm wondering if this is really related to Pimcore or if this is an issue of Composer's autoloading.

**Comment by brusch** [comment] 2020-02-19 10:44
Hmm, that seems to be fixed already: https://github.com/composer/composer/pull/7303

**Comment by beheist** [comment] 2020-02-25 07:47
We encounter the same issue on a CentOS server with pimcore v.6.2.3. Any news on this one?

**Comment by Ascathor** [comment] 2020-03-16 13:01
@beheist Could you try updating to current composer version and validate if that fixes your issue ? We no longer encounter this issue (At least I got no more feedback on this), so it seems related to what @brusch mentioned.

**Comment by brusch** [comment] 2020-11-05 15:33
Seems to be fixed by Composer - closed.

**Closed by brusch** 2020-11-05 15:33 UTC
Labels: Bug

**Comment by ramundomario** [comment] 2021-02-26 14:13
Unfortunately we are experiencing the same behavior with Pimcore docker image (pimcore/pimcore:PHP7.4-apache).
With PHP layout we have errors with Image & Input editables, so seems related with the capitalization of letter "i" in turkish
![Screenshot from 2021-02-26 15-04-47](https://user-images.githubusercontent.com/16133208/109309762-0318d380-7844-11eb-90ec-aca3996a8bf9.png)
![Screenshot from 2021-02-26 15-05-41](https://user-images.githubusercontent.com/16133208/109309896-29d70a00-7844-11eb-8323-ba3d9bc1dec7.png)

With TWIG layout (Reproduced on latest demo changing the language to turkish in _/de/shared/includes/footer_) there are errors with blocks:
![Screenshot from 2021-02-26 15-11-43](https://user-images.githubusercontent.com/16133208/109310568-fea0ea80-7844-11eb-9cbc-b59c3c49256d.png)
