### ISSUE TITLE
[Bug]: Backend search not working in Pimcore v11.1.3

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#16399] opened 2023-12-28 19:47 UTC
### Pimcore version

11.1.3

### Steps to reproduce

Click Search icon and the Documents (or any other type), then enter any search term and click Search button.

### Actual Behavior

Instead of showing search results an error moral pops up (in dev mode with debug enabled) with error description:

> Server threw exception - could not perform action. Please reload the admin interface and try again.

Following is detailed stack trace:

```
	
Timestamp: Thu Dec 28 2023 22:45:36 GMT+0300 (GMT+03:00)
Status: 500 | 
URL: /admin/bundle/search/search/find?_dc=1703792736640
Method: GET
Message: Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data::setModificationDate(): Argument #1 ($modificationDate) must be of type int, string given, called in /home/tp/public_html/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Listing/Dao.php on line 59
Trace: 
in /home/tp/public_html/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data.php:225
#0 /home/tp/public_html/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Listing/Dao.php(59): Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data->setModificationDate()
#1 [internal function]: Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data\Listing\Dao->load()
#2 /home/tp/public_html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array()
#3 /home/tp/public_html/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php(324): Pimcore\Model\AbstractModel->__call()
#4 /home/tp/public_html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\SimpleBackendSearchBundle\Controller\SearchController->findAction()
#5 /home/tp/public_html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#6 /home/tp/public_html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#7 /home/tp/public_html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#8 /home/tp/public_html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#9 /home/tp/public_html/public/index.php(19): require_once('/home/tp/public...')
#10 {main}
```

### Expected Behavior

Matching documents are shown in grid.

**Comment by kovinet** [comment] 2023-12-28 19:49
In general I have plenty of similar error related to incorrect types passed to functions in latest version. I am using PHP 8.2 and all requirements are met on server.

**Comment by ghost** [comment] 2024-01-08 08:56
@kovinet Thanks for reporting this issue. We will have a look at the descibed search bug. But could you please provide us more information on the other "plenty of similar errors" as we need them for investigating? Maybe raise other issues or even provide pull requests? thanks!

**Comment by kingjia90** [comment] 2024-01-09 16:22
Couldn't reproduce it
https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Listing/Dao.php#L37-L66 in there we directly fetch from the db and assign the value we get there.

Please check if in the table `search_backend_data` , the column `modificationDate` is a `nullable int`. I've tried to change the value to an empty string or any string, and cannot do that.

To fix, should add a type cast to `int` similarly on https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Listing/Dao.php#L52 but i am pretty sure the DBAL detects the right type, see screenshot of the debugger of fetchAllAssociative
![image](https://github.com/pimcore/pimcore/assets/6014195/14f40f82-cba8-41a4-92d6-817810028796)

**Comment by kovinet** [comment] 2024-01-09 22:02
I have now made fresh installation on CPanel server using Softaculous Apps Installer and I was able to reproduce the issue again.

As mentioned earlier, there are few type related errors and I have already fixed some and then opened a bug for one of the errors received. After fresh install and running cron and then searching in backend error is following:

```
Message: Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data::setUserOwner(): Argument #1 ($userOwner) must be of type int, string given, called in /home/pim/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Listing/Dao.php on line 56
```

Here is whole trace:
```
in /home/pim/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data.php:255
#0 /home/pim/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Listing/Dao.php(56): Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data->setUserOwner()
#1 [internal function]: Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data\Listing\Dao->load()
#2 /home/pim/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array()
#3 /home/pim/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php(324): Pimcore\Model\AbstractModel->__call()
#4 /home/pim/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\SimpleBackendSearchBundle\Controller\SearchController->findAction()
#5 /home/pim/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#6 /home/pim/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#7 /home/pim/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#8 /home/pim/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#9 /home/pim/public/index.php(19): require_once('/home/transport...')
#10 {main}
```

I have fixed this temporarily (by casting string to int or removing type from function argument), but then other errors appear, finally the one originally posted, so then I gave up with quick fixes and posted a bug. It seems to be related to wrong types returned from DBAL, which are strings instead of int as mentioned by @kingjia90 

And, yes, table `search_backend_data` has correct types, see below:

![image](https://github.com/pimcore/pimcore/assets/707846/264a38ac-0c4c-4d50-bf79-51e0699d9ddd)


MySql version on the server: 10.6.16-MariaDB-log

**Comment by kingjia90** [comment] 2024-01-09 23:48
Thank you for all the details. 

Reading the dbal docs, it states it doesn't type cast, it is depending on [database driver and php version](https://www.doctrine-project.org/projects/doctrine-dbal/en/3.7/reference/data-retrieval-and-manipulation.html#:~:text=do%20not%20perform%20any%20type%20conversion.%20So%20the%20result%20php%20type%20for%20a%20database%20column%20can%20vary%20between%20database%20drivers%20and%20php%20versions.) probably could explain why it happens as you mentioned: 
> I have plenty of similar error related to incorrect types 

I'd suggest to check the `doctrine/dbal` version to see if there's a regression and try to upgrade the `MariaDB`, so far, works on `10.11` https://github.com/pimcore/demo/blob/11.x/docker-compose.yaml#L7C16-L7C29 for me, it could be that we need to raise the minimum supported version or define incompatible "combination" (MariaDb/Php). So far these [combinations](https://github.com/pimcore/pimcore/blob/2b3bb4d10f4c32270589bb37557b932ca38d2a7e/.github/workflows/codeception.yaml#L43-L46)used in the tests seem covered and fully working.

**Comment by kovinet** [comment] 2024-01-10 08:39
You mean it is fully working on MariaDb versions 10.5 and and 10.7, but not working on 10.6 (my version)?  That seems weird. 

![image](https://github.com/pimcore/pimcore/assets/707846/53734b43-b861-4e03-85a2-54c75fc41e9a)

Since this is on managed server getting an upgrade won't be easy.  I will look into it, debug and report when I manage.

**Comment by kovinet** [comment] 2024-01-10 08:51
BTW another type related error is with thumbnail generation using `{{ pimcore_image() }}'. Thumbnails don't generate on page load resulting on broken image on the website. When refreshing the page image is then shown. This bug is also related to type related warning.  So I had a feeling that Pimcore 11 release is very buggy, since I had no such issues with version 10.

**Comment by kingjia90** [comment] 2024-01-10 08:56
yes, it's the only clue/possibility at the moment, because it seem working fine on my end, public demos and safely assuming in others project and instances (this kind of problems would be surely promptly reported by the community). 
There is also nothing in between `fetchAllAssociative` and the array being passed to setters that we could deal without major refactoring (eg. by adding all the typecasts, which doesn't look the solution).

It is quite weird indeed, could be also a sublte difference things like in the driver used https://www.doctrine-project.org/projects/doctrine-dbal/en/3.7/reference/configuration.html#pdo-mysql / https://www.doctrine-project.org/projects/doctrine-dbal/en/3.7/reference/configuration.html#mysqli or a database global setting.

**Comment by kingjia90** [comment] 2024-01-10 09:00
> BTW another type related error is with thumbnail generation using `{{ pimcore_image() }}'. Thumbnails don't generate on page load resulting on broken image on the website. When refreshing the page image is then shown. This bug is also related to type related warning. So I had a feeling that Pimcore 11 release is very buggy, since I had no such issues with version 10.

weird, i'd recommend to open a new and separate issue with the details on how to reproduce it.

**Comment by kingjia90** [comment] 2024-01-10 09:17
Closing this issue for the moment as `can't repro`, please feel free to re-open (or a new one linking this thread) if you have new feedback and if you have to share your potential findings/fixes about the issue that may help the others too.

Thank you again for reporting

**Comment by MosiiAUT** [comment] 2024-08-07 07:20
@kovinet @kingjia90 i have the same problem and can reproduce it -> Pimcore 11.2.3.

I guess our customer has deleted a pimcore-user and after you restart the reindex-command the entry in userModification will be null

To repoduce:
- create a dummy user
- save a document/asset/object
- delete the user
- start the reindex command
- try to search for the said document/asset/object

Version-Table entry "userId" for example is also null

**Comment by kingjia90** [comment] 2024-09-05 08:22
The bot brought my attention back to this, but i believe it can be closed again.

@MosiiAUT the described issue will get resolved by https://github.com/pimcore/pimcore/pull/17020 , could you please try to apply the patch and join the conversation there?

**Closed as not planned by kingjia90** 2024-09-05 08:22 UTC
Labels: Bug, PR Welcome, Backlog

**Comment by MosiiAUT** [comment] 2024-12-11 15:17
I made a clean install of Pimcore 11.2.3 and Pimcore 11.5 but this time i couldn't reproduce it unfortunately and on the system where i could reproduce it, the problem is already fixed... 
Maybe @kovinet could test it?

**Comment by kovinet** [comment] 2024-12-11 15:22
Last time I had this issue I fixed it by switching the PHP to version to
8.3, even though 8.2 was officially supported by the affected instance. I
will test it and let you know.
