### ISSUE TITLE
Image upload is broken in Safari 12

### ISSUE THREAD

**Issue by swissdev** [pimcore/pimcore#3132] opened 2018-07-25 07:39 UTC
# Bug Report
Image upload in Safari 11 does not work when using the upload button on an image or image field. It shows this JSON Parse Error in the attachment. After that the admin panel needs a reload. It only works when using the direkt upload function in the assets pane.

### Expected behavior 
Image uploads correctly.

### Actual behavior  
JSON Parse Error - Unrecognized Token '?'

### Steps to reproduce  
Upload an image on Safari 11 directly on an Image editable field or replace an existing image with the upload button on the image toolbar. (See Screenshots)

  
<img width="1115" alt="json_error" src="https://user-images.githubusercontent.com/546931/43186323-9e16d2a6-8fee-11e8-8224-8caf1fca5e1e.png">

<img width="1116" alt="upload_button" src="https://user-images.githubusercontent.com/546931/43186337-a598d59c-8fee-11e8-975c-eecaac5ca4d7.png">

**Comment by brusch** [comment] 2018-07-26 06:04
Unable to reproduce, tested with latest Safari 11, see [26-07-_2018_08-03-34.zip](https://github.com/pimcore/pimcore/files/2230614/26-07-_2018_08-03-34.zip)

**Comment by swissdev** [comment] 2018-07-27 10:15
I'm sorry it's Safari version 12.0 on OS X Mojave. I've found this issue earlier on Safari 11 too but this is fixed now.

**Comment by brusch** [comment] 2018-07-27 10:17
Hmmm I don't have Mojave yet, so probably you can help out an further debug this? 
Would be great!

**Comment by swissdev** [comment] 2018-07-27 10:18
Ok, yes.

**Comment by brusch** [comment] 2018-07-27 11:04
Great, thanks!

**Comment by brusch** [comment] 2018-09-07 09:32
Any updates on that? 
Still broken?

**Comment by swissdev** [comment] 2018-09-07 09:56
Sorry, I forgot it. 
Yes, still broken. I am currently looking in the logs but haven't found something.
Maybe it has to do with get-image-thumbnail. The debugger on Safari is very slow.

**Comment by brusch** [comment] 2018-09-13 08:35
I've tried it on Safari 12.1 - no problems ... so I guess that's gonna be fixed by Apple. 
![image](https://user-images.githubusercontent.com/142037/45476981-b1963000-b740-11e8-86f7-9546fbc3835d.png)


But maybe you can share a more detailed error message, the one from above doesn't really say anything (stack trace, readable error message, ...) 

Thanks

**Comment by brusch** [comment] 2018-09-13 11:44
Also tried it on the latest beta of Mojave, with Safari version `12.0` (`14060.1.36.1.9`) - still everything ok.

**Closed by brusch** 2018-09-13 11:44 UTC

**Comment by swissdev** [comment] 2018-09-13 11:49
How did you upload the image? If we want to try to upload an image directly on an image areabrick it does not work. It only works when the image is directly uploaded in the assets.

**Comment by brusch** [comment] 2018-09-13 12:01
Tried it as described by you above (screenshot) - so directly on the asset.
