### ISSUE TITLE
[Improvement]: Lazy load Objectbrick attributes in grid options

### ISSUE THREAD

**Issue by paulverdu** [pimcore/pimcore#12465] opened 2022-06-22 07:08 UTC
### Improvement description

In our project loading the Class Attributes in the Grid Options window takes very long.
Class Attributes are loading Object columns (attributes), System columns (attributes) and all columns (attributes) of all objectbricks. Since we have about 135 objectbricks, this loading takes very long (about 50 seconds).

It might be an idea to load in the objectbricks in a separate accordion item 'Objectbrick columns' that lazy loads in after everything else is done loading.

![Screen Shot 2022-06-22 at 09 08 27](https://user-images.githubusercontent.com/13202286/174966009-6975f981-2c22-4a5c-b0fa-452e11282527.png)

**Comment by dev-pim** [comment] 2023-04-24 23:23
I had the same problem, managed to fix it by changing the value of **bufferedRenderer** to **_true_** when creating the Ext.tree.TreePanel object
**`in vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree**
`
I don't know why this value is explicitly false in pimcore, because I did not notice any side effects, but the speed increased many times on ext js 6

It also works in pimcore 10 on ext js 7, but not as efficiently, due to changes in ext js 7 itself
My results:
ext js 6 from 30 seconds to 1 second
ext js 7 from 30 seconds to 5 seconds

You can cheat on ext js 7 and return performance by removing unnecessary new features or replacing them with functions from ext-js 6, but this is at your own peril and risk

**Comment by eciosk** [comment] 2023-07-27 11:27
Same here, pimcore 10.6.3.

**Comment by skoch98** [comment] 2023-11-12 00:03
Hi @paulverdu / @eciosk - Are you able to reproduce the problem in the latest version of Pimcore?

I found a fix for this behavior: See https://github.com/pimcore/pimcore/pull/16007 / https://github.com/pimcore/admin-ui-classic-bundle/pull/293#issue-1913221698

**Comment by fashxp** [comment] 2023-12-21 09:32
fixed with https://github.com/pimcore/admin-ui-classic-bundle/pull/293#issue-1913221698

**Closed as completed by fashxp** 2023-12-21 09:32 UTC
Labels: Improvement, PR Welcome
