### ISSUE TITLE
[Grid View] Error when ordering & filtering object brick fields

### ISSUE THREAD

**Issue by AlexPalmi** [pimcore/pimcore#6609] opened 2020-06-16 09:07 UTC
# Bug Report

### Expected behavior
Using Pimcore v6.6.6
Opening a folder in data object with some childs or an object with variants. In grid view, adding an attribute of type "picker" (through the grid options) and order the field with "sort Ascending/Sort descending" options. The grid must bu ordered by the picker value.

### Actual behavior
When I try to order by the picker attribute, I get an error (more specifically a "Database error").

### Steps to reproduce
In grid view, if you try to order a column of type "picker", you get a "Database error".

**Comment by dvesh3** [comment] 2020-06-16 16:36
@AlexPalmi can you please share the **DataType** of attribute?

**Comment by AlexPalmi** [comment] 2020-06-17 07:16
@dvesh3 sorry, DataType it's "color".

**Comment by dvesh3** [comment] 2020-06-17 07:41
Unable to reproduce on demo.pimcore.fun

**Comment by AlexPalmi** [comment] 2020-06-17 07:59
@dvesh3 Sorry again, but I forgot to specify that the "color Picker" must be inside a ObjectBrick available in the objects listed in the grid view.

**Comment by dvesh3** [comment] 2020-06-17 10:10
general problem, when using multiple bricks in a class: 

An exception occurred while executing 'SELECT object_localized_CAR_en.o_id as o_id, `object_localized_CAR_en`.`o_type` FROM `object_localized_CAR_en` LEFT JOIN `object_brick_query_Engine_CAR` AS `Engine` ON 1 AND `Engine`.o_id = `object_localized_CAR_en`.o_id LEFT JOIN `object_brick_query_SaleInformation_CAR` ....... DESC LIMIT 25': SQLSTATE[23000]: **Integrity constraint violation: 1052 Column 'fieldname' in where clause is ambiguous**

**Comment by dvesh3** [comment] 2020-06-18 14:14
resolved by #6622

**Closed by dvesh3** 2020-06-18 14:14 UTC
Labels: Bug
