### ISSUE TITLE
Remove all composer warnings, vrana/adminer.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9123] opened 2021-05-14 16:20 UTC
Hello,

Pimcore 10 is really great because we can use composer v2 without nearly no warnings ! : ))
I noticed just vrana/adminer make the output of composer v2 less clean returning:

```
Warning: Ambiguous class resolution, "Min_DB" was found in both "/var/www/html/vendor/vrana/adminer/plugins/drivers/clickhouse.php" and "/var/www/html/vendor/vrana/adminer/plugins/drivers/simpledb.php", the first will be used.
Warning: Ambiguous class resolution, "Min_Result" was found in both "/var/www/html/vendor/vrana/adminer/plugins/drivers/clickhouse.php" and "/var/www/html/vendor/vrana/adminer/plugins/drivers/simpledb.php", the first will be used.
Warning: Ambiguous class resolution, "Min_Driver" was found in both "/var/www/html/vendor/vrana/adminer/plugins/drivers/clickhouse.php" and "/var/www/html/vendor/vrana/adminer/plugins/drivers/simpledb.php", the first will be used.
Warning: Ambiguous class resolution, "Min_DB" was found in both "/var/www/html/vendor/vrana/adminer/plugins/drivers/clickhouse.php" and "/var/www/html/vendor/vrana/adminer/plugins/drivers/firebird.php", the first will be used.
Warning: Ambiguous class resolution, "Min_Result" was found in both "/var/www/html/vendor/vrana/adminer/plugins/drivers/clickhouse.php" and "/var/www/html/vendor/vrana/adminer/plugins/drivers/firebird.php", the first will be used.
Warning: Ambiguous class resolution, "Min_Driver" was found in both "/var/www/html/vendor/vrana/adminer/plugins/drivers/clickhouse.php" and "/var/www/html/vendor/vrana/adminer/plugins/drivers/firebird.php", the first will be used.
```

I open this issue so people can check this issue about this subject.
And I just posted this issue vrana ticketing system as I think this is on their side (we want to keep adminer in Pimcore, it is a really great program ; )): https://sourceforge.net/p/adminer/bugs-and-features/798/

When adminer will be resolved, this issue can be closed/updated.
If you think this ticket should not be here/concerning Pimcore, you can close it, but it can be a good thing to track it here.

Best regards.

**Comment by Yivan** [comment] 2021-05-14 16:26
Maybe could be solved on Pimcore side using https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps ?

**Comment by dvesh3** [comment] 2021-05-17 08:08
Hi @Yivan, let's keep it open until the issue is fixed on vrana 😉

**Comment by Yivan** [comment] 2021-05-17 18:27
Just I confirm for now for those wanting to get rid of those adminer messages waiting for the fix on adminer side, you can add `"exclude-from-classmap": ["/vendor/vrana/adminer/plugins/drivers/"]` in the section `autoload` of your project composer.json which will be (pimcore skeleton composer.json):

```
  "autoload": {
    "psr-4": {
      "App\\": "src/",
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
      "Pimcore\\Model\\Object\\": "var/classes/Object",
      "Website\\": "legacy/website/lib"
    },
    "exclude-from-classmap": ["/vendor/vrana/adminer/plugins/drivers/"]
  },
```

This way composer output is clean:

![image](https://user-images.githubusercontent.com/9025839/118538059-fe323480-b74d-11eb-9beb-261b7c32fb90.png)

And adminer works well! : )

**Comment by dpfaffenbauer** [comment] 2021-05-18 06:23
@Yivan but that is not a fix pimcore can make, that would be a project side fix..

**Comment by Yivan** [comment] 2021-05-18 17:19
Yes, I was just meaning developers can hide it by updating their composer.json file. Pimcore could hide it by updating the composer.json of pimcore/skeleton. But the better is vrana to fix it for sure : )

**Comment by brusch** [comment] 2021-05-19 09:50
I'll close that here for now.

**Closed as completed by brusch** 2021-05-19 09:50 UTC
Labels: Third Party Bug

**Comment by NiklasBr** [comment] 2021-12-15 08:53
Can we revisit this issue (maybe for Pimcore 11)? Because it has been no single commit to the Vrana repository for seven months now:
https://sourceforge.net/p/adminer/git/ci/1f173e18bdf0be29182e0d67989df56eadea4754/log/?path=
