### ISSUE TITLE
[Bug]: calculated field breaks many to many relation

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#13489] opened 2022-10-31 13:38 UTC
### Expected behavior

When using a calculated value as visible field in a(n advanced) many to many object relation it should display.

### Actual behavior

The grid is cut off at the calculated value column, also removing any columns in advanced many to many object relations and all row edit options.

### Steps to reproduce

Reproduced on the [demo environment](https://demo.pimcore.com/admin/) (10.5.9). This issue didn't occur in version 10.5.6.

- Create a basic Test class containing a calculated field ([class_Test_export.json.zip](https://github.com/pimcore/pimcore/files/9901482/class_Test_export.json.zip)).
  - Expression used: object.getId() ~ ' ' ~ object.getName()
- Create a basic ManyToMany class containing a many to many object relation ([class_ManyToMany_export.json.zip](https://github.com/pimcore/pimcore/files/9901492/class_ManyToMany_export.json.zip)).
- Create some Test objects and set a name.
- Create a many to many object and add the test objects.

![Test_example](https://user-images.githubusercontent.com/24292941/199020907-b7b654d8-c464-4eef-9ccb-296861e366aa.png)
![many_to_many_object_relation](https://user-images.githubusercontent.com/24292941/199020923-67f28f91-1b91-4a19-9c60-82e9ba0a21d4.png)

**Comment by mcop1** [comment] 2022-10-31 14:02
@kjkooistra-youwe This may be a duplicate of https://github.com/pimcore/pimcore/issues/13439 ?

**Comment by kjkooistra-youwe** [comment] 2022-10-31 14:14
> @kjkooistra-youwe This may be a duplicate of #13439 ?

@mcop1 Looks very similar indeed. I searched for calculated value, but if that issue report is correct it might even break other fields types.

**Comment by mcop1** [comment] 2022-11-04 11:43
Thanks, we will follow the issue through #13439

**Closed as completed by mcop1** 2022-11-04 11:43 UTC
Labels: Bug
