### ISSUE TITLE
[Bug]: VsitorInfo variable blocks does not exists

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#13824] opened 2022-12-16 14:22 UTC
### Expected behavior

When implementing [the code in the 10.5 documentation for frontend javascript](https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Targeting_and_Personalization/Frontend_Javascript.html#page_Change-extend-the-code-snippet-injected-into-the-Response) is should work without issues.

### Actual behavior

```
Twig\Error\RuntimeError:
Variable "blocks" does not exist.

  at vendor/pimcore/pimcore/bundles/CoreBundle/Resources/views/Targeting/targetingCode.html.twig:1
  at __TwigTemplate_017311d87d370705819275458c9785e0->{closure}()
     (var/cache/dev/twig/2b/2bb11ad1cbae30cc0114963b58132af0.php:97)
  at __TwigTemplate_017311d87d370705819275458c9785e0->block_beforeScriptTag(array('document' => object(Page), 'title' => 'Forside', 'site' => ', 'areaConfigs' => array('snippets')), 'preview' => false, 'pathInfo' => '/', 'mobileNavigation' => object(Container), 'pageNavigation' => object(Container), 'bannerSnippet' => null, 'app' => object(AppVariable), 'container' => object(App_KernelDevDebugContainer), 'pimcore_csrf' => object(CsrfProtectionHandler), 'pimcore_csp' => object(ContentSecurityPolicyHandler), 'editmode' => false), array('beforeScriptTag' => array(object(__TwigTemplate_97e988d614bc1b3970315566cfac8cab), 'block_beforeScriptTag'), 'beforeScript' => array(object(__TwigTemplate_017311d87d370705819275458c9785e0), 'block_beforeScript'), 'script' => array(object(__TwigTemplate_017311d87d370705819275458c9785e0), 'block_script'), 'afterScript' => array(object(__TwigTemplate_017311d87d370705819275458c9785e0), 'block_afterScript'), 'afterScriptTag' => array(object(__TwigTemplate_017311d87d370705819275458c9785e0), 'block_afterScriptTag'), 'targetingScript' => array(object(__TwigTemplate_017311d87d370705819275458c9785e0), 'block_targetingScript')))
     (vendor/twig/twig/src/Template.php:171)
```

### Steps to reproduce

Pimcore 10.5.12 and Twig 3.4.3

1. Add Event Listener according to the docs
2. Add JS according to the docs
3. Reload frontend

**Comment by mattamon** [comment] 2022-12-22 15:18
Hey @NiklasBr,

I can't reproduce the error on my local machine. 
Seems like there is a typo in your code "blocks" instead of "block"?

**Comment by mattamon** [comment] 2022-12-22 15:31
Hey @NiklasBr 

I could not reproduce this error on my local machine.

I dumped the blocks and this is the result

````php
array:4 [
  "beforeScriptTag" => [Pimcore\Analytics\Code\CodeBlock](http://localhost/_profiler/open?file=dev/pimcore/pimcore/lib/Analytics/Code/CodeBlock.php&line=24#line24) {#9301
    -parts: []
  }
  "beforeScript" => [Pimcore\Analytics\Code\CodeBlock](http://localhost/_profiler/open?file=dev/pimcore/pimcore/lib/Analytics/Code/CodeBlock.php&line=24#line24) {#9300
    -parts: array:1 [
      0 => "console.log("Custom targeting code");"
    ]
  }
  "afterScript" => [Pimcore\Analytics\Code\CodeBlock](http://localhost/_profiler/open?file=dev/pimcore/pimcore/lib/Analytics/Code/CodeBlock.php&line=24#line24) {#9299
    -parts: []
  }
  "afterScriptTag" => [Pimcore\Analytics\Code\CodeBlock](http://localhost/_profiler/open?file=dev/pimcore/pimcore/lib/Analytics/Code/CodeBlock.php&line=24#line24) {#9292
    -parts: []
  }
]```

I also see no recent changes in these files. 
Maybe you could check again and give me another hint on how to preproduce this error.

**Comment by NiklasBr** [comment] 2023-01-02 09:00
I implemented the code verbatim. Can you show your controller @mattamon ?

**Comment by mattamon** [comment] 2023-01-02 09:27
@NiklasBr
I actually only implemented the Listener and the template. No controller was involved here.

```php
<?php

// src/EventListener/TargetingCodeListener.php

namespace App\EventListener;

use Pimcore\Event\Targeting\TargetingCodeEvent;
use Pimcore\Event\TargetingEvents;
use Pimcore\Targeting\Code\TargetingCodeGenerator;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class TargetingCodeListener implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            TargetingEvents::TARGETING_CODE => 'onTargetingCode',
        ];
    }

    public function onTargetingCode(TargetingCodeEvent $event)
    {
        // add code to a code block (see TargetingCodeGenerator and the default
        // template for a list of blocks and their location)
        $event
            ->getBlock(TargetingCodeGenerator::BLOCK_BEFORE_SCRIPT)
            ->append([
                'console.log("Custom targeting code");'
            ]);

        // completely override the rendered template
        $event->setTemplate('@App/Targeting/targetingCode.html.twig');
    }
}
```

```twig
{# templates/Targeting/targetingCode.html.twig #}

{% extends '@PimcoreCore/Targeting/targetingCode.html.twig' %}

{% block beforeScriptTag %}
    {{ parent() }}

    <script type="text/javascript">
        console.log('Custom targeting template');
    </script>
{% endblock %}

{% block targetingScript %}
    <script type="text/javascript">
        window._ptg = window._ptg || {};
        window._ptg.dataProviders = window._ptg.dataProviders || {};

        window._ptg.dataProviders.userAgent = function() {
            console.log('The current user agent is ' + navigator.userAgent);
        };
    </script>
    {{ parent() }}
{% endblock %}
```

**Comment by NiklasBr** [comment] 2023-01-02 11:53
Sure that is the only thing you do?

![image](https://user-images.githubusercontent.com/279826/210227728-70ddde13-8622-42c5-9850-9baa50054ceb.png)

**Comment by mattamon** [comment] 2023-01-02 12:08
Well I also added Eventlistener to the services.yaml
```yaml
    App\EventListener\TargetingCodeListener: ~
```
But other than that I did nothing else.

**Comment by NiklasBr** [comment] 2023-01-02 12:25
We have a catch-all for event listeners:
```yaml
    #
    # EVENT LISTENERS
    #
    App\EventListener\:
        resource: '../src/EventListener'
        public: true
```

But explicitly adding your line did not help either:
```yaml
    #
    # EVENT LISTENERS
    #
    App\EventListener\:
        resource: '../src/EventListener'
        public: true
    App\EventListener\TargetingCodeListener: ~
```

Testing by editing the Pimcore Core file to just dump with Twig results in this:
![image](https://user-images.githubusercontent.com/279826/210230809-39a43c7e-56c9-49a7-9ed0-c92b84d4c1f4.png)

**Comment by dvesh3** [comment] 2023-01-02 12:31
@NiklasBr could you please debug the data passed to the template [here](https://github.com/pimcore/pimcore/blob/83142b53cfd5a791e3c6167470a66336fd03da22/lib/Targeting/Code/TargetingCodeGenerator.php#L77)? As per this line, "blocks" variable should be available in the template.

**Comment by mattamon** [comment] 2023-01-02 12:48
@NiklasBr I did the exact same thing as you and my blocks are set. 
![image](https://user-images.githubusercontent.com/38959016/210233379-2d23af85-f513-4eef-ad7a-6e237b55a636.png)

**Comment by NiklasBr** [comment] 2023-01-02 12:52
@dvesh3 that code never appears to execute, debugger does not stop and it does not appear in the stack trace.

**Comment by dvesh3** [comment] 2023-01-02 14:07
sorry, not able to reproduce
![image](https://user-images.githubusercontent.com/5137917/210241773-8bbc7553-e775-440a-b5e7-00ac5e0e65b8.png)

**Comment by NiklasBr** [comment] 2023-01-02 14:20
Can you show the full stack trace at your breakpoint?

**Comment by dvesh3** [comment] 2023-01-02 15:00
It is called from here https://github.com/pimcore/pimcore/blob/1aed6b7e85ebcb42d494cc892e0e42920c4dc809/lib/Targeting/EventListener/TargetingListener.php#L189

**Comment by dvesh3** [comment] 2023-01-04 11:03
Closed as it is not reproducible.

**Closed as completed by dvesh3** 2023-01-04 11:03 UTC
Labels: Bug
