### ISSUE TITLE
Issue with the admin interface, after migrated successfully to pimcore v 10.6, admin giving error

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#15660] opened 2023-08-01 04:50 UTC
### Pimcore version

pimcore v 10.6

### Steps to reproduce

Hi Team,

I have successfully migrated pimcore 6.9 v to pimcore 10.6, but in the admin getting below error, its not rendering into template
when i hit url/admin/login => gives error

Gives error in this point just in the rendering part, before that im able to print something.
return $this->render('@PimcoreAdmin/Admin/Login/login.html.twig', $params);

![router](https://github.com/pimcore/pimcore/assets/78895325/4dcc052a-b139-4f39-89fd-b337dcb744ed)

Anyone knows the solution for this and how to resolve it?

Please help

### Actual Behavior

Not working

### Expected Behavior

It should redirect into login

**Comment by dvesh3** [comment] 2023-08-01 14:55
Duplicate of https://github.com/pimcore/pimcore/discussions/15620

**Closed as completed by dvesh3** 2023-08-01 14:55 UTC
Labels: Bug
