### ISSUE TITLE
Objects - custom layouts - problem with field selection 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#711] opened 2016-07-02 19:27 UTC
when multiple custom layouts are available: opening and editing first layout, then opening second layout -> selection of fields in second layout not possible anymore: 
TypeError: me.items is null in customLayoutEditor (Zeile 735)

**Comment by weisswurstkanone** [comment] 2016-08-12 11:52
unable to reproduce

**Comment by weisswurstkanone** [comment] 2016-08-16 07:31
fixed in build 3929

**Closed** 2016-08-16 07:32 UTC
Labels: Bug
