### ISSUE TITLE
[Bug]: Master (Admin Mode) set by default

### ISSUE THREAD

**Issue by kamilawiercinska** [pimcore/pimcore#13655] opened 2022-11-22 14:18 UTC
### Expected behavior

user is not able to edit non-editable attributes, because Master mode is set by deafult.

This behavior existed within the past versions of pimcore, but when I test it on 10.5.10, the scenario works differently (described below)

### Actual behavior

user is able to edit non-editable attributes because Master(admin mode) is set by default
![image](https://user-images.githubusercontent.com/49391646/203336695-f37c035d-4ba5-4b24-87fd-2fd714596e2a.png)

### Steps to reproduce

1. log in to pimcore as 'admin'
2. open object with some non-editable attributes

**Comment by SamyMP** [comment] 2022-11-23 07:36
Duplicate of #13555

**Closed as completed** 2022-11-23 07:39 UTC
Labels: Bug
