### ISSUE TITLE
[Bug]: Console command "bin/console doctrine:migrations:migrate" fails with the error "The prefix option does not exist."

### ISSUE THREAD

**Issue by MarkTro** [pimcore/pimcore#16160] opened 2023-10-27 11:46 UTC
### Pimcore version

11.1.0

### Steps to reproduce

Actually I can't say who and why this happend. It's deep in the dependency injection somewhere. I'm glad for every hint where I can modify this befaviour.

The problem is that the command is not loaded as a real DoctrineCommand than as a LazyCommand, which will replaced later to the real DoctrineCommand. For this reason in \Pimcore\Console\Application::add the command is not recognized as DoctrineCommand and therefore the prefix option won't add. That causes the error.

### Actual Behavior

If you execute the console command "doctrine:migration:migrate" the command ends with an error:

>  The "prefix" option does not exist.

### Expected Behavior

The command works as expected.

**Comment by MarkTro** [comment] 2023-10-27 12:13
Pull request for this issue: https://github.com/pimcore/pimcore/pull/16162

**Comment by kingjia90** [comment] 2023-11-15 08:28
Reproduced on automated tests eg. https://github.com/pimcore/demo/actions/runs/6872382520/job/18696815335#step:7:82

**Comment by mtramp-neusta** [comment] 2023-11-15 12:27
We got this error after upgrading doctrine/migrations from 3.6.0 to 3.7.0. After the downgrade back to 3.6.0, the error no longer occurred.

**Comment by kingjia90** [comment] 2023-11-15 12:31
> We got this error after upgrading doctrine/migrations from 3.6.0 to 3.7.0. After the downgrade back to 3.6.0, the error no longer occurred.

Had the same suspicions, because it used to work fine but only got our test failing recently.
The culprit could be this PR https://github.com/doctrine/migrations/pull/1330 which turned them into [lazyloaded commands according symfony docs](https://symfony.com/doc/current/console/commands_as_services.html#lazy-loading)

**Comment by jdreesen** [comment] 2023-11-15 12:54
Should already be broken in [v3.6.1](https://github.com/doctrine/migrations/releases/tag/3.6.1) then (released at the same time as [3.7.0](https://github.com/doctrine/migrations/releases/tag/3.7.0)).

**Comment by mtramp-neusta** [comment] 2023-11-15 13:04
Just tested with 3.6.1 and the error occurred again.

**Comment by coes-devs-jakala** [comment] 2023-11-22 16:23
Updated to Pimcore 11.1.1 and still having the issue

**Comment by kingjia90** [comment] 2023-11-22 16:40
@coes-devs-jakala tomorrow would be tagged a new release containing these fix, sorry for the inconveniences. Please (temporarily) apply the changes manually if it's necessary

**Comment by kingjia90** [comment] 2023-11-22 16:44
Fixed by https://github.com/pimcore/pimcore/pull/16257

**Closed as completed by kingjia90** 2023-11-22 16:44 UTC
Labels: Bug
