### ISSUE TITLE
website settings extjs6 problem

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#440] opened 2016-02-10 22:39 UTC
build 3641-3649

editing first time any cell is ok, but next time cell is not editable and whole plugin is broken and unusable

**Comment by brusch** [comment] 2016-02-11 07:07
Unfortunately I'm not able to reproduce this. Please provide us a guide how we can reproduce the described problem on demo.pimcore.org/admin - Thanks! 

See also: 
[screencapture.zip](https://github.com/pimcore/pimcore/files/126000/screencapture.zip)

**Comment by jansarmir** [comment] 2016-02-11 10:25
srr, any cell was not correct
values are fine
problem is with **Name** cells, after editing and losing focus, panel is dead

tested on firefox and chrome on demo

reopening panel does not helps, result in screen
![website_settings](https://cloud.githubusercontent.com/assets/13581247/12974077/7275afd6-d0b1-11e5-9801-821edf43cee4.jpg)

**Comment by atietje** [comment] 2016-02-11 10:36
For me, both editing names and values doesn't work after leaving a field by hitting the tab key. 

*Reproduce*

* Open Pimcore backend in Chrome, click Settings -> Website
* Enter string "foo" in Add setting key field, select type text, click (+) icon
* Click on newly created value cell in the grid, enter something, hit tab key: entered string disappears.
* Repeat last step, see JS errors in browser console.

Additionally, clicking the close X on the Website tab doesn't remove the tab.

**Comment by weisswurstkanone** [comment] 2016-02-12 08:42
fixed in build 3654

**Closed by weisswurstkanone** 2016-02-12 08:42 UTC
Labels: Bug
