### ISSUE TITLE
Shared translations broken in 6.7.2

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#7184] opened 2020-09-28 13:37 UTC
# Bug Report
### Expected behavior
Translations work as they used to. This will be properly translated if placed in a twig view template:
`{{ "Role"|trans }}`
Works in 6.7.0.

### Actual behavior
Starting from 6.7.2, this will no longer use the proper translated value but the english value only.

### Reason
Must be in this commit:
https://github.com/pimcore/pimcore/pull/7071/commits/3f4e0e3b81f330ccb287716d3a5c46318e08d3b2#diff-35148f8556f54cb705805f95b0f19fed
Reverting it fixes the bug.

**Comment by brusch** [comment] 2020-09-28 13:52
Unable to reproduce ... just tested this on the public demo:

![image](https://user-images.githubusercontent.com/142037/94441071-991bd580-01a2-11eb-9120-2b20e6e8ccc7.png)
![image](https://user-images.githubusercontent.com/142037/94441107-a33dd400-01a2-11eb-865c-d746ba99b09b.png)
![image](https://user-images.githubusercontent.com/142037/94441127-ab960f00-01a2-11eb-8a30-45c8ab16d27b.png)

**Comment by Cruiser13** [comment] 2020-09-28 13:59
Weird, we can reproduce it. Might be settings specific? Here are ours:
![settings locale](https://user-images.githubusercontent.com/2771909/94441846-89e95780-01a3-11eb-92b3-1d848afb2fbf.png)

**Comment by brusch** [comment] 2020-09-28 14:06
Just tried the same (added allback language and set default to `de`) ... works as expected ... 😐

**Comment by dpfaffenbauer** [comment] 2020-09-28 14:11
try clearing the cache, maybe that works.

**Comment by brusch** [comment] 2020-09-28 14:14
Did it twice ... still works

**Comment by Cruiser13** [comment] 2020-09-28 14:25
Clearing the cache was the first thing we did too... no success.

We nailed it down to this line of code. Commenting out 
`$lookForFallback = $comparisonId == $translated;`
makes it work for us. No idea why yet.

**Comment by Cruiser13** [comment] 2020-09-29 08:35
We have a second pimcore instance now which shows the same behaviour at 6.7.2.
I think the issue appears, if the key and one of the translations are the same. In the following setup:

![key replacement shared translations](https://user-images.githubusercontent.com/2771909/94533384-5825ce80-023f-11eb-86c7-e567c3227097.png)

This will be translated properly:
`{{ "ask_for_callback"|trans }}`

This will fail:
`{{ "Rückruf vereinbaren"|trans }}`

**Comment by brusch** [comment] 2020-09-29 08:55
@Cruiser13 yep, that could be the answer to the issue, but I'm not sure if we can solve this that easy 😐

**Comment by Cruiser13** [comment] 2020-10-27 08:28
@brusch this is actually a huge BC break introduced here which does affect a lot of templates in a lot of instances. Any chance to get a 6.8 milestone for this?

**Comment by brusch** [comment] 2020-10-27 09:07
Well, calling this a **huge** BC break is probably a bit of an exaggeration, it's just a normal bug which occurs under certain circumstances which we'll try to fix as soon as possible.

**Comment by NiklasBr** [comment] 2020-10-27 10:26
Also broke #7382

**Comment by podarcis** [comment] 2020-11-11 06:49
We are also affected by this problem and it's effectively locking some of our projects (Pimcore 4 migrated) to Pimcore 6.7.1.

While having "translation key equals translated text" is not best practice in Symfony, it's been often used that way in [ZF projects](https://framework.zend.com/manual/1.12/en/zend.translate.using.html).

Thank you for investigating.

**Comment by ayoob-lfc** [comment] 2020-11-12 21:02
We having the same issue in pimcore 6.8.4 and symfony 4.4.16. 

We tried a simple translation with parameter:

```
{% set name = "You" %}

{% trans %}Hello %name%{% endtrans %}
```

Outputs as:

`Hello %name%`

As in the variable name doesn't get replaced. However when we replaced the following line, from:

https://github.com/pimcore/pimcore/blob/cfe69de2574503f4ce73d7d8708e917e45594290/lib/Translation/Translator.php#L289

to:

```
                if (!empty($parameters)) {
                    return strtr($this->getCatalogue($locale)->get($normalizedId, $domain), $parameters);
                } else {
                    return $this->getCatalogue($locale)->get($normalizedId, $domain);
                }
```

It then works.

**Comment by kathangeorg** [comment] 2020-11-18 10:08
We have a similar problem in pimcore 6.8.4.

If there is no shared translation for a language (e.g. fo a technical value that is only translated in the default language) the key in our case something like **[places__total]:lt:20** is rendered instead of the value for the fallback language in all other languages. Nevertheless `$locale` is set correct.

`$comparisonId == $translated` are equal (value is the key **[places__total]:lt:20**) in this line

https://github.com/pimcore/pimcore/blob/cfe69de2574503f4ce73d7d8708e917e45594290/lib/Translation/Translator.php#L287

and

https://github.com/pimcore/pimcore/blob/cfe69de2574503f4ce73d7d8708e917e45594290/lib/Translation/Translator.php#L289

returns the key instead of the fallback value.

**Comment by brusch** [comment] 2020-11-27 09:20
Fixed by #7588

**Closed by brusch** 2020-11-27 09:20 UTC
Labels: Bug

**Comment by Cruiser13** [comment] 2021-02-06 14:59
@brusch this issue disappeared but is now back in Pimcore 6.8.8.
A translation key "Artikel suchen" with english translation "search article" and german translation "Artikel suchen" will show up in english on a german website.

**Comment by brusch** [comment] 2021-02-08 08:31
@Cruiser13 thanks for reporting. Can you please create a new issue, that references this one? 
Thanks a lot!
