### ISSUE TITLE
[Bug]: Convert to webp with option Cover [center]. 

### ISSUE THREAD

**Issue by mackrais** [pimcore/pimcore#10017] opened 2021-08-12 10:51 UTC
### Expected behavior

If I set format jpeg i got correct image
![image](https://user-images.githubusercontent.com/8103057/129184034-89755001-68c0-48b6-924c-93af62348f41.png)

### Actual behavior

After covert for some images I got transparent image.
![image](https://user-images.githubusercontent.com/8103057/129184079-29689e0b-5ec5-4940-9b91-06bce194e585.png)

### Steps to reproduce
Pimcore version v6.9.6
Use next config to thumbnails. Also i use to store image AWS. 

![image](https://user-images.githubusercontent.com/8103057/129183871-d243c153-aea9-4f21-8c7a-c747af173794.png)

After investigation your code i found some problems in method Pimcore\Image\Adapter\Imagick -> crop -> preModify.

After comment this method 
![image](https://user-images.githubusercontent.com/8103057/129184751-39f9a47b-5db6-495c-bad1-c95b3ac35301.png)

Everything started working fine.

**Comment by brusch** [comment] 2021-08-25 09:53
@mackrais can you reproduce this behavior using latest version of 10 as well? Thanks for your feedback!

**Comment by fashxp** [comment] 2023-12-20 10:29
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed as not planned by fashxp** 2023-12-20 10:29 UTC
Labels: Bug, PR Welcome
