### ISSUE TITLE
CSV import. ObjectBrick setter - Default mode is not set.

### ISSUE THREAD

**Issue by rndfm** [pimcore/pimcore#6642] opened 2020-06-22 12:07 UTC
Having some trouble with CSV import into objects bricks that are not already created.
Seams the default create mode for ObjectBrick Setter i only really working in the UI where the radiobutton is correctly places at "If not empty".
For a successful import I have to edit the ObjectBrick setter "settings" and click on the already chosen "If not empty". Then the mode is working as expected and objectbricks are created.

Expected behavior:
When using default "Create mode": "If not empty".
Object bricks should be created if not existing when CSV importing.

Actual behavior
Error message "brick does not exist". 

Steps to reproduce
Create a class with some objectbrick fields.
Create a data object with that class. Do not add the object brick.
CSV Import to a objectbrick field by using the ObjectBrick Setter.
Open the settings for the ObjectBrick setter. Confirm that create is set to "If not empty". (Do not click it.)
Close out of the settings panel for the ObjectBrick Setter.
(Set some resolver settings if needed)
Click import.
Get error "brick does not exist"
Go back to the Column configuration and edit the ObjectBrick Setter.
Click on the already chosen create mode "if not empty". Click Apply.
Click import again.
Import success!

**Comment by weisswurstkanone** [comment] 2020-06-23 09:06
Unable to reproduce, maybe I am missing an important point here.

Note that there was some activity a couple of days ago. Maybe this already explains what you experience? Please double-check

https://github.com/pimcore/pimcore/pull/6636/files

**Comment by rndfm** [comment] 2020-07-17 08:41
> Unable to reproduce, maybe I am missing an important point here.
> 
> Note that there was some activity a couple of days ago. Maybe this already explains what you experience? Please double-check
> 
> https://github.com/pimcore/pimcore/pull/6636/files

I don't see any direct connection to my problem?

**Comment by braaam** [comment] 2020-08-20 08:47
This happens for me as well. I've just upgraded to 6.7, but the issue persists. I'll try to describe the flow: 

* Created a class which has object bricks mapped to it. 
* Import a CSV to create new objects
* Mapped some of the fields in the CSV to the objectbrick setters
* Each row in the CSV that has data for one of the objectbricks setters will not be imported, and showing the exact error as @rndfm described. 
* The workaround as described by @rndfm works for me as well (thanks!) You have to do this every time you import a CSV.

I've also tested the import when resolving to existing objects that already have the object bricks filled in - here it works perfectly fine - as also stated by @rndfm.

**Comment by weisswurstkanone** [comment] 2020-08-20 10:15
Sorry, still not able to repoduce this. Can you please attach your csv and steps to reproduce on the demo instance please?

**Comment by braaam** [comment] 2020-08-20 12:06
I've tried to reproduce on a demo instance, but I cannot upload a CSV (I think because the cache directory is not writable). 

Attached is the CSV I used (it was exported by pimcore, I just used it to test if it could create new objects/bricks from that)  and a definition export from one of the object bricks.

[objectbrick_workingconditionsRisk_export-2.json.zip](https://github.com/pimcore/pimcore/files/5102822/objectbrick_workingconditionsRisk_export-2.json.zip) 

[export-25.csv.zip](https://github.com/pimcore/pimcore/files/5102812/export-25.csv.zip)

**Comment by weisswurstkanone** [comment] 2020-08-20 13:28
The definitinon refeferences the class "Country" which is not available.  

    "classDefinitions": [
        {
            "classname": "Country",
            "fieldname": "proxies"
        }
    ],

**Comment by braaam** [comment] 2020-08-20 20:30
Not in the demo you mean? I hadn't set up this full example in the demo. 

Attached the class definition for the country object.

[class_Country_export.json.zip](https://github.com/pimcore/pimcore/files/5105306/class_Country_export.json.zip)

**Comment by weisswurstkanone** [comment] 2020-08-24 07:27
"...Close out of the settings panel for the ObjectBrick Setter...." means that you don't "apply" but simply close the condiguration dialog.
Maybe attach a short video showing everyting from the beginning.

**Comment by braaam** [comment] 2020-08-25 20:14
Here's a movie describing the process. Also attached are the import configurations as used in the movie. 
It's actually a one-time fix - once applied in the configuration - it retains. 

[csv-import-configurations.zip](https://github.com/pimcore/pimcore/files/5126042/csv-import-configurations.zip)

https://schuttelaarenpartners-my.sharepoint.com/:v:/g/personal/bu_schuttelaar_nl/EYytRtic38xCqKN_yZkc0z0BwCV-i7ttHuIw0S-5ZMSJYQ?e=0tc8o6

**Comment by weisswurstkanone** [comment] 2020-08-26 08:48
thanks a lot!

**Closed** 2020-08-26 15:08 UTC
Labels: Bug
