### ISSUE TITLE
[Bug]: Users with permissions for specific files don't see them

### ISSUE THREAD

**Issue by PGBrandi** [pimcore/pimcore#11852] opened 2022-04-06 09:16 UTC
### Expected behavior

When given the permission to a certain object within a folder the user is able to see the object.

### Actual behavior

The user is not able to see the object on the initial loading, if the object is within a folder. However, it is possible to show it by reloading the folder.

### Steps to reproduce

https://user-images.githubusercontent.com/24474378/161941102-3ad0f916-8341-4ad0-bce2-55253ad2ffa5.mp4

**Comment by blankse** [comment] 2022-04-06 09:20
@PGBrandi The user must also have the permission to the folder to see it in the tree. But that you can see it with reload is a bug I think.

**Comment by PGBrandi** [comment] 2022-04-06 09:59
In our case we want users to have access to specific files only, not the entire folder. So that would not be a solution for us. However, I expected that when I am able to assign a specific asset/document/object to a user that this would work. Otherwise this possibility to do so would be very confusing.

**Comment by blankse** [comment] 2022-04-06 10:15
I think we need a option to the workspaces: "sub tree" or "node only"
So we can set permission to this folder only, without its content.
But show this folder without permission is not correct I think.
This should also be in object/document trees and there can be sensitive data inside.

**Comment by fashxp** [comment] 2022-04-06 12:56
related? https://github.com/pimcore/pimcore/pull/11714

**Comment by dvesh3** [comment] 2022-04-07 07:11
duplicate of https://github.com/pimcore/pimcore/issues/11603

**Closed as completed by dvesh3** 2022-04-07 07:11 UTC
Labels: Bug
