### ISSUE TITLE
[Bug]: workflow image

### ISSUE THREAD

**Issue by ruccvcs50x** [pimcore/pimcore#12386] opened 2022-06-10 04:02 UTC
### Expected behavior

workflow can render work flow image

### Actual behavior

workflow image is not rendered. 
Empty string was returned.

As was checked, the command place holder was not replaced by its value.
for example:
`D:\xampp\php\php.EXE D:\MyProjects\demomdm/bin/console pimcore:workflow:dump ${WNAME} ${WPLACES} | ${DOT} -Tsvg`

### Steps to reproduce

- config new workflow
-  start workflow.

**Comment by kingjia90** [comment] 2022-06-14 18:12
I've took a look but i couldn't reproduce it.

On the live demo, it also renders the image correctly.
![image](https://user-images.githubusercontent.com/6014195/173640136-24580f8f-478b-4727-aa85-8ccd422bd1b9.png)
So far, i've not encountered any problems here in the code where that command replaces the placeholders. 
https://github.com/pimcore/pimcore/blob/7e3e5df20c2077730164b182a3d3c1f25faa2d0d/bundles/AdminBundle/Controller/Admin/WorkflowController.php#L366-L377
Beyond `$process->run` we are kind of in the hands of a Symfony component, then would be likely a third-party issue.

- What version of Pimcore are you using? It would help so i can check if it's a past known issue that got solved in the meantime.
- Also, please let me know if "symfony/process" is "^5.2.0"

I have some "suspects" on the slashes, because of this difference between Windows and Linux.
`D:\MyProjects\demomdm/bin/console` should be `D:\MyProjects\demomdm\bin\console`, please try to change it
https://github.com/pimcore/pimcore/blob/7e3e5df20c2077730164b182a3d3c1f25faa2d0d/bundles/AdminBundle/Controller/Admin/WorkflowController.php#L366  and/or try to run the command manually in the bash to see if works without any errors.
For demo, this works for me `bin/console pimcore:workflow:dump simple_asset_workflow | dot -Tsvg > test.svg`

**Comment by kingjia90** [comment] 2022-06-22 06:00
Closing for the moment, it seems that the problem might be related to Xampp/Windows and it's not supported.
I'd recommend to use Docker + WSL2 when using Windows, it's also what we mostly use in the core team.

If there are further issues, please reopen it or open a new one with more info.

**Closed as not planned by kingjia90** 2022-06-22 06:00 UTC
Labels: Bug
