### ISSUE TITLE
QuickSearch becomes slow with the time

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#8130] opened 2021-02-10 08:40 UTC
With the time the Quicksearch/Object search becomes very slow so that queries take quite a long time. 
To correct this i had to execute a OPTIMIZE TABLE search_backend_data . 

It would be cool if Pimcore can handle this automatically.
Solution could be:
1) rename search_backend_data  to search_backend_data_tmp
2) create dummy search_backend_data table
3) run optimize table on search_backend_data_tmp
4) insert all data from search_backend_data to search_backend_data_tmp and rename search_backend_data_tmp to search_backend_data

This way it should not lock the table while the optimization is executed because it can take several minutes to optimize large tables.

**Comment by alexthunder3** [comment] 2021-07-15 20:30
The issue is a few months old, so I'm probably late to the party. But it seems there is a search-reindex command available to use which truncates, rebuild the table, then runs optimize table. Even after running it i'm still dealing with timeouts in the search that make it impossible for editors to find anything. Any search ends in a communication failure. The search_backend_data has about 680k rows, which is basically nothing.
In my case, it seems to be throwing the communication failure error and ending with timeouts whenever there is a cron running in the background that is creating new objects. I'm guessing there is some locking of tables or waiting for indexing  that keeps the search query waiting until it times out.

**Comment by fashxp** [comment] 2023-12-20 09:43
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Closed by fashxp** 2023-12-20 09:43 UTC
Labels: PR Welcome
