### ISSUE TITLE
[Bug]: Unable to Login Into 11.x-dev.pimcore.fun

### ISSUE THREAD

**Issue by cancan101** [pimcore/pimcore#17893] opened 2024-12-05 01:33 UTC
### Pimcore version

11.x

### Steps to reproduce

Go to https://11.x-dev.pimcore.fun/admin/  and use admin / demo

### Actual Behavior

I am promoted for 2fa and then told 2fa code is wrong.

I have added the 2fa to google authenticator but have no luck actually logging in.

### Expected Behavior

login without 2fa (for demo site)

**Comment by ghost** [comment] 2024-12-09 11:36
Maybe a duplicate of https://github.com/pimcore/pimcore/issues/17905 and already done?

**Closed as completed** 2024-12-09 15:35 UTC
Labels: Bug
